// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_FW_1SP_H_
#define HSP_FW_1SP_H_

#include <stdbool.h>
#include <stdint.h>
#include "crypto/ecc_hw.h"
#include "crypto/hash.h"
#include "drivers/hsp_aes.h"
#include "firmware/firmware_loader.h"
#include "flash/flash.h"
#include "splibs/inc/spcryptotypes.h"
#include "status/msft_module_id.h"


/**
 * Magic number identifying a 1SP firmware image.
 */
#define	HSP_FW_1SP_MARKER			0x53504657

/**
 * Flag indicating that the image is encrypted with the device firmware key.
 */
#define	HSP_FW_1SP_ENCRYPTED_FLAG	(1U << 7)

/**
 * Length of the build version number in the firmware image header.
 */
#define	HSP_FW_1SP_VERSION_LEN		8


/**
 * Header structure that is prepended to all 1SP images.
 */
struct hsp_fw_1sp_header {
	uint32_t marker;									/**< Marker identifying a 1SP firmware image. */
	uint8_t flags;										/**< Flags indicating properties of the image. */
	uint8_t reserved[3];								/**< Unused. */
	uint8_t iv[16];										/**< IV used to encrypt the image. */
	SP_ECDSA_P384_SIGNATURE signature;					/**< Signature of the signed image header. */
	SP_ECDSA_P384_SIGNATURE secondary_signature;		/**< Secondary signature of the signed image header. */
	struct {
		uint32_t svn;									/**< SVN for the 1SP image. */
		uint8_t build_version[HSP_FW_1SP_VERSION_LEN];	/**< Version identifier for the image. */
		uint32_t load_addr;								/**< Address in SP RAM where the image should be loaded. */
		uint32_t length;								/**< Length of the firmware image data. */
		SP_MSG_384 digest;								/**< SHA2-384 digest of the image data. */
	} header_signed;									/**< Signed firmware image header. */
};


/**
 * Variable context for handling a 1SP firmware image.
 */
struct hsp_fw_1sp_state {
	struct hsp_fw_1sp_header header;	/**< Header for the 1SP image. */
	uintptr_t base_addr;				/**< Base address of the image. */
	bool on_flash;						/**< Flag indicating if the image in on flash. */
};

/**
 * Handler for loading and verifying a 1SP firmware image.
 */
struct hsp_fw_1sp {
	struct hsp_fw_1sp_state *state;			/**< Variable context for the image. */
	const struct firmware_loader *loader;	/**< Handler for loading the 1SP image into memory. */
	const struct flash *flash;				/**< Flash that contains the 1SP image. */
};


/**
 * Initialize a static instance of a 1SP image handler.  This does not initialize the image state.
 * That will need to be initialized separately with hsp_fw_1sp_init_state or
 * hsp_fw_1sp_init_state_from_memory.
 *
 * There is no validation done on the arguments.
 *
 * @param state_ptr Variable context for the 1SP image handler.
 * @param loader_ptr Handler for loading the image into SP memory.  This can be a constant instance.
 * @param flash_ptr The flash device that contains the image.  This can be a constant instance.
 */
#define	hsp_fw_1sp_static_init(state_ptr, loader_ptr, flash_ptr)	{ \
		.state = state_ptr, \
		.loader = loader_ptr, \
		.flash = flash_ptr \
	}

int hsp_fw_1sp_init (struct hsp_fw_1sp *fw, struct hsp_fw_1sp_state *state,
	const struct firmware_loader *loader, const struct flash *flash, uint32_t base_addr);
int hsp_fw_1sp_init_from_memory (struct hsp_fw_1sp *fw, struct hsp_fw_1sp_state *state,
	const struct firmware_loader *loader, const uint8_t *base_addr);

int hsp_fw_1sp_init_api (struct hsp_fw_1sp *fw, struct hsp_fw_1sp_state *state,
	const struct firmware_loader *loader, const struct flash *flash);

int hsp_fw_1sp_init_state (const struct hsp_fw_1sp *fw, const struct flash *flash,
	uint32_t base_addr);
int hsp_fw_1sp_init_state_from_memory (const struct hsp_fw_1sp *fw, const uint8_t *base_addr);

void hsp_fw_1sp_release (const struct hsp_fw_1sp *fw);

size_t hsp_fw_1sp_get_total_length (const struct hsp_fw_1sp *fw);
int hsp_fw_1sp_get_size_on_flash (const struct flash *flash, uint32_t base_addr);

int hsp_fw_1sp_verify_signed_header (const struct hsp_fw_1sp *fw, const struct hash_engine *hash,
	const struct ecc_hw *pka, const struct ecc_point_public_key *fw_key,
	const struct ecc_point_public_key *secondary_key, uint32_t expected_svn);
int hsp_fw_1sp_verify_full_image (const struct hsp_fw_1sp *fw, const struct hash_engine *hash,
	const struct ecc_hw *pka, const struct ecc_point_public_key *fw_key,
	const struct ecc_point_public_key *secondary_key, uint32_t expected_svn);

int hsp_fw_1sp_load_image (const struct hsp_fw_1sp *fw, const struct hash_engine *hash);
int hsp_fw_1sp_encrypt_image (const struct hsp_fw_1sp *fw, const struct hsp_aes *aes, uint8_t key,
	const SP_MSG_128 *iv);

int hsp_fw_1sp_verify_image_in_memory (const struct hsp_fw_1sp *fw, const struct hash_engine *hash);


#define	HSP_FW_1SP_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_FW_1SP, code)

/**
 * Error codes that can be generated by a 1SP firmware image.
 */
enum {
	HSP_FW_1SP_INVALID_ARGUMENT = HSP_FW_1SP_ERROR (0x00),					/**< Input parameter is null or not valid. */
	HSP_FW_1SP_NO_MEMORY = HSP_FW_1SP_ERROR (0x01),							/**< Memory allocation failed. */
	HSP_FW_1SP_BAD_IMAGE_MARKER = HSP_FW_1SP_ERROR (0x02),					/**< The image marker is not the required value. */
	HSP_FW_1SP_SVN_MISMATCH = HSP_FW_1SP_ERROR (0x03),						/**< The image does not have the expected SVN value. */
	HSP_FW_1SP_IMAGE_VERIFY_FAILED = HSP_FW_1SP_ERROR (0x04),				/**< The image is not valid. */
	HSP_FW_1SP_IMAGE_ENCRYPTION_NOT_SUPPORTED = HSP_FW_1SP_ERROR (0x05),	/**< The operation doesn't support encrypted images. */
	HSP_FW_1SP_IMAGE_NOT_BLOCK_ALIGNED = HSP_FW_1SP_ERROR (0x06),			/**< The image size is not aligned to a 16 byte block. */
	HSP_FW_1SP_IMAGE_NO_DATA = HSP_FW_1SP_ERROR (0x07),						/**< The image size is equal to 0. */
	HSP_FW_1SP_LOAD_IMAGE_NOT_SUPPORTED = HSP_FW_1SP_ERROR (0x08),			/**< Loading the image for execution is not supported. */
};


#endif	/* HSP_FW_1SP_H_ */
