// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_FW_UTIL_H_
#define HSP_FW_UTIL_H_

#include <stdint.h>
#include "crypto/ecc_hw.h"
#include "crypto/hash.h"
#include "splibs/inc/spcryptotypes.h"
#include "status/msft_module_id.h"


void hsp_fw_load_public_key (const SP_ECDSA_P384_PUBLIC *pub_in,
	struct ecc_point_public_key *pub_out);
void hsp_fw_load_signature (const SP_ECDSA_P384_SIGNATURE *sig_in,
	struct ecc_ecdsa_signature *sig_out);

int hsp_fw_verify_signed_image (const struct ecc_hw *pka, const struct hash_engine *hash,
	const uint8_t *signed_data, size_t signed_length, const SP_ECDSA_P384_SIGNATURE *signature,
	const struct ecc_point_public_key *key, const uint8_t *hashed_data, size_t hashed_length,
	const uint8_t *expected, int error_code);

int hsp_fw_run_self_test_verify_signed_image (const struct ecc_hw *pka,
	const struct hash_engine *hash);


#define	HSP_FW_UTIL_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_FW_UTIL, code)

/**
 * Error codes that can be generated by the HSP firmware utilities.
 */
enum {
	HSP_FW_UTIL_INVALID_ARGUMENT = HSP_FW_UTIL_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_FW_UTIL_NO_MEMORY = HSP_FW_UTIL_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* HSP_FW_UTIL_H_ */
