// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef IDENTITY_RENEWAL_H_
#define IDENTITY_RENEWAL_H_

#include <stdint.h>
#include "drivers/fuse_controller_interface.h"
#include "status/msft_module_id.h"


/**
 * Interface to hardware-backed state that manages device identity renewal.
 */
struct identity_renewal {
	/**
	 * Get the renewal counter value for the device DME key.
	 *
	 * @param identity The renewal handler to query.
	 * @param dme Output for the current DME renewal counter.
	 *
	 * @return 0 if the query was successful or an error code.
	 */
	int (*get_dme_renewal) (const struct identity_renewal *identity, uint32_t *dme);

	/**
	 * Update the DME renewal counter to revoke previous DME keys.
	 *
	 * @param identity The renewal handler for the DME key.
	 *
	 * @return 0 if the DME renewal was successful or an error code.
	 */
	int (*set_dme_renewal) (const struct identity_renewal *identity, uint32_t dme);

	/**
	 * Get the renewal counter value for the device DICE UDS.
	 *
	 * @param identity The renewal handler to query.
	 * @param dice Output for the current DICE renewal counter.
	 *
	 * @return 0 if the query was successful or an error code.
	 */
	int (*get_dice_renewal) (const struct identity_renewal *identity, uint32_t *dice);

	/**
	 * Update the DICE renewal counter to revoke previous DICE identity keys.
	 *
	 * @param identity The renewal handler for the DICE key.
	 *
	 * @return 0 if the DICE renewal was successful or an error code.
	 */
	int (*set_dice_renewal) (const struct identity_renewal *identity, uint32_t dice);

	const struct fuse_controller_interface *fuses;	/**< Driver for accessing HSP fuses. */
};


int identity_renewal_init (struct identity_renewal *identity,
	const struct fuse_controller_interface *fuses);
void identity_renewal_release (const struct identity_renewal *identity);


#define	IDENTITY_RENEWAL_ERROR(code)		ROT_ERROR (MSFT_MODULE_IDENTITY_RENEWAL, code)

/**
 * Error codes that can be generated by device identity management.
 */
enum {
	IDENTITY_RENEWAL_INVALID_ARGUMENT = IDENTITY_RENEWAL_ERROR (0x00),		/**< Input parameter is null or not valid. */
	IDENTITY_RENEWAL_NO_MEMORY = IDENTITY_RENEWAL_ERROR (0x01),				/**< Memory allocation failed. */
	IDENTITY_RENEWAL_GET_DME_RENEW_FAILED = IDENTITY_RENEWAL_ERROR (0x02),	/**< Failed to get the DME renewal counter. */
	IDENTITY_RENEWAL_GET_DICE_RENEW_FAILED = IDENTITY_RENEWAL_ERROR (0x03),	/**< Failed to get the DICE renewal counter. */
	IDENTITY_RENEWAL_SET_DME_RENEW_FAILED = IDENTITY_RENEWAL_ERROR (0x04),	/**< Failed to update the DME renewal counter. */
	IDENTITY_RENEWAL_SET_DICE_RENEW_FAILED = IDENTITY_RENEWAL_ERROR (0x05),	/**< Failed to update the DICE renewal counter. */
	IDENTITY_RENEWAL_NOT_POSSIBLE = IDENTITY_RENEWAL_ERROR (0x06),			/**< The renewal counter is at the maximum value. */
};


#endif	/* IDENTITY_RENEWAL_H_ */
