# Copyright (c) Microsoft Corporation. All rights reserved.

[package]
name = "mcr-profiler"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
doctest = false

[[test]]
name = "calltree_tests"
path = "tests/calltree_tests.rs"

[[test]]
name = "checkpoint_tests"
path = "tests/checkpoint_tests.rs"
