// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef FORCED_RECOVERY_CPLD_H_
#define FORCED_RECOVERY_CPLD_H_

#include <stdbool.h>
#include <stdint.h>
#include "host_fw/host_irq_handler.h"
#include "i2c/i2c_master_interface.h"
#include "status/msft_module_id.h"
#include "status/rot_status.h"


/**
 * CPLD forced recovery control register.
 */
#define FORCED_RECOVERY_CPLD_CTRL  100


/**
 *  Control instance communicating with the CPLD to implement forced host recovery.
 */
struct forced_recovery_cpld {
	struct host_irq_handler *irq;		/**< Handler for processing a forced recovery request. */
	struct i2c_master_interface *i2c;	/**< I2C device connected to the CPLD. */
	uint8_t slave_addr;					/**< The 7-bit I2C slave address of the CPLD. */
};


int forced_recovery_cpld_init (struct forced_recovery_cpld *recovery, struct host_irq_handler *irq,
	struct i2c_master_interface *i2c, uint8_t slave_addr);
void forced_recovery_cpld_release (struct forced_recovery_cpld *recovery);

int forced_recovery_cpld_process_recovery (const struct forced_recovery_cpld *recovery);


#define	FORCED_RECOVERY_CPLD_ERROR(code)		ROT_ERROR (MSFT_MODULE_FORCED_RECOVERY_CPLD, code)

/**
 * Error codes that can be generated by a forced recovery implementation.
 */
enum {
	FORCED_RECOVERY_CPLD_INVALID_ARGUMENT = FORCED_RECOVERY_CPLD_ERROR (0x00),	/**< Input parameter is null or not valid. */
	FORCED_RECOVERY_CPLD_NO_MEMORY = FORCED_RECOVERY_CPLD_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	// FORCED_RECOVERY_CPLD_H_
