// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HOST_FIRMWARE_H_
#define HOST_FIRMWARE_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "crypto/hash.h"
#include "crypto/rsa.h"
#include "manifest/pfm/pfm.h"
#include "status/module_id.h"


/**
 * Handler for operations on a host firmware image stored on the protected flash device.
 */
struct host_firmware {
	/**
	 * Validate the firmware image on flash.
	 *
	 * @param firmware The firmware image to validate.
	 * @param pfm The PFM to validate the firmware against.
	 * @param good_pfm A PFM known to validate against the flash that can be used to optimize
	 * verification with the target PFM.  Set this to null to bypass verification optimizations.
	 * @param hash The hash engine to use for validation.
	 * @param rsa The RSA engine to use for signature verification.
	 *
	 * @return 0 if the image was successfully validated or an error code
	 */
	int (*validate_flash) (const struct host_firmware *firmware, const struct pfm *pfm,
		const struct pfm *good_pfm, const struct hash_engine *hash, const struct rsa_engine *rsa);

	/**
	 * Recover the firmware image from the backup image.  The backup image is validated prior to
	 * being used.
	 *
	 * @param firmware The firmware image to recover.
	 * @param pfm The PFM to validate backup flash against.
	 * @param hash The hash engine to use for validation.
	 * @param rsa The RSA engine to use for signature verification.
	 *
	 * @return 0 if the image was successfully recovered or an error code.
	 */
	int (*recover_flash) (const struct host_firmware *firmware, const struct pfm *pfm,
		const struct hash_engine *hash, const struct rsa_engine *rsa);

	/**
	 * Ensure the contents of the backup region of flash match the active region.
	 *
	 * @param firmware The firmware image to backup
	 *
	 * @return 0 if the image was successfully backed up or an error code.
	 */
	int (*backup_flash) (const struct host_firmware *firmware);

	/**
	 * Prepare the flash to be updated with a new firmware image.  The write address will be reset
	 * to the start of the image.
	 *
	 * @param manager The firmware image to update.
	 * @param total_length The total expected length of the update image.
	 * @param lock_flash_access Flag indicating that the host will be blocked from getting access to
	 * the flash while the update is active.
	 * @param ctrl_flag Implementation specific flag that can be used to trigger special workflows
	 * during update preparation.
	 *
	 * @return 0 if the flash is ready to be updated or an error code.
	 */
	int (*prepare_image_update) (const struct host_firmware *firmware, size_t total_length,
		bool lock_flash_access, uint8_t ctrl_flag);

	/**
	 * Write firmware image data to the flash.  It must have been erased prior to writing.  Writing
	 * will continue from the last written address.
	 *
	 * @param manager The firmware image to update.
	 * @param data The data to write to flash.
	 * @param length The length of the data to write.
	 *
	 * @return 0 if the data was written successfully or an error code.
	 */
	int (*write_image_update) (const struct host_firmware *firmware, const uint8_t *data,
		size_t length);

	/**
	 * Get the expected number of bytes remaining in the current firmware update.
	 *
	 * @param firmware The firmware image to query.
	 *
	 * @return The number of remaining bytes.  This can be negative if more data was received than
	 * expected.
	 */
	int (*get_remaining_update_bytes) (const struct host_firmware *firmware);

	/**
	 * Get the port identifier for the firmware image.
	 *
	 * @param firmware The firmware image to query.
	 *
	 * @return The firmware port identifier.
	 */
	int (*get_port_id) (const struct host_firmware *firmware);
};

#define	HOST_FIRMWARE_ERROR(code)		ROT_ERROR (ROT_MODULE_HOST_FIRMWARE_IMAGE, code)

/**
 * Error codes that can be generated by host firmware interface.
 */
enum {
	HOST_FIRMWARE_INVALID_ARGUMENT = HOST_FIRMWARE_ERROR (0x00),								/**< Input parameter is null or not valid. */
	HOST_FIRMWARE_NO_MEMORY = HOST_FIRMWARE_ERROR (0x01),										/**< Memory allocation failed. */
	HOST_FIRMWARE_VALIDATE_FAILED = HOST_FIRMWARE_ERROR (0x02),									/**< An error unrelated to validation caused verification to fail. */
	HOST_FIRMWARE_RECOVER_FAILED = HOST_FIRMWARE_ERROR (0x03),									/**< An error unrelated to validation caused recovery to fail. */
	HOST_FIRMWARE_PREPARE_UPDATE_FAILED = HOST_FIRMWARE_ERROR (0x04),							/**< Host flash is not ready to receive an update. */
	HOST_FIRMWARE_WRITE_UPDATE_FAILED = HOST_FIRMWARE_ERROR (0x05),								/**< Host image data was not written to flash. */
	HOST_FIRMWARE_BACKUP_FAILED = HOST_FIRMWARE_ERROR (0x06),									/**< A backup image could not be created. */
	HOST_FIRMWARE_NO_FLASH_ACCESS = HOST_FIRMWARE_ERROR (0x07),									/**< The host currently has access to the flash. */
	HOST_FIRMWARE_UPDATE_NOT_READY = HOST_FIRMWARE_ERROR (0x08),								/**< The system has not been prepared to receive an update. */
	HOST_FIRMWARE_IMAGE_NOT_VALID = HOST_FIRMWARE_ERROR (0x09),									/**< The active image is not known to be valid. */
	HOST_FIRMWARE_UNSUPPORTED = HOST_FIRMWARE_ERROR (0x0A),										/**< Operation not supported */
	HOST_FIRMWARE_BUFFER_TOO_SMALL = HOST_FIRMWARE_ERROR (0x0B),								/**< Output Buffer not large enough. */
	HOST_FIRMWARE_IMAGE_TOO_LARGE = HOST_FIRMWARE_ERROR (0x0C),									/**< Image size is larger than the allocated size. */
	HOST_FIRMWARE_IMAGE_STAGING_REGION_LOCKED = HOST_FIRMWARE_ERROR (0x0D),						/**< Staging memory locked. */
	HOST_FIRMWARE_IMAGE_UPDATE_STATE_FAIL = HOST_FIRMWARE_ERROR (0x0E),							/**< Failure in setting or reading the update state. */
	HOST_FIRMWARE_UPDATE_FAILED_ID_MISMATCH = HOST_FIRMWARE_ERROR (0x0F),						/**< Host ID in the image is not matching with the targeted host ID. */
	HOST_FIRMWARE_UPDATE_FAILED_SECURITY_VER_DOWNGRADE = HOST_FIRMWARE_ERROR (0x10),			/**< Update failed as security version cannot be downgraded . */
	HOST_FIRMWARE_UPDATE_FAILED_STATE_VER_DOWNGRADE = HOST_FIRMWARE_ERROR (0x11),				/**< Update failed as state version cannot be downgraded . */
	HOST_FIRMWARE_UPDATE_FAILED_IMPACT_VER_UPGRADE = HOST_FIRMWARE_ERROR (0x12),				/**< Update failed as impact version cannot be upgraded . */
	HOST_FIRMWARE_UPDATE_FAILED_ACTIVE_IMAGE_HEADER_READ_FAILED = HOST_FIRMWARE_ERROR (0x13),	/**< Failed to read the header of current active image . */
	HOST_FIRMWARE_UPDATE_FAILED_STAGING_IMAGE_HEADER_READ_FAILED = HOST_FIRMWARE_ERROR (0x14),	/**< Failed to read the header of staging image . */
	HOST_FIRMWARE_UPDATE_PLATFORM_READ_FAILURE = HOST_FIRMWARE_ERROR (0x15),					/**< Failed to read the platform information needed for update . */
	HOST_FIRMWARE_DECOMPRESSION_FAILURE = HOST_FIRMWARE_ERROR (0x16),							/**< Failed to decompress incoming firmware */
	HOST_FIRMWARE_IMAGE_STAGING_REGION_IDLE = HOST_FIRMWARE_ERROR (0x17),						/**< Staging memory idle. */
	HOST_FIRMWARE_PL_IMAGE_NOT_PRESENT = HOST_FIRMWARE_ERROR (0x18),							/**< PL image is not present in the staging region. */
	HOST_FIRMWARE_UPDATE_FAILED_OSPI_LAYOUT_HEADER_READ_FAILED = HOST_FIRMWARE_ERROR (0x19),	/**< Failed to read the header of OSPI layout . */
	HOST_FIRMWARE_IMAGE_UPDATE_PREPARE_FAILED_ANOTHER_IN_PROGRESS = HOST_FIRMWARE_ERROR (0x1A),	/**< Update terminated in prepare because another update is in progress. */
	HOST_FIRMWARE_IMAGE_UPDATE_WRITE_FAILED_ANOTHER_IN_PROGRESS = HOST_FIRMWARE_ERROR (0x1B),	/**< Update terminated in write because another update is in progress. */
	HOST_FIRMWARE_IMAGE_UPDATE_FINISH_FAILED_ANOTHER_IN_PROGRESS = HOST_FIRMWARE_ERROR (0x1C),	/**< Update terminated in finish because another update is in progress. */
};


#endif	/* HOST_FIRMWARE_H_ */
