// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HOST_FW_CMD_INTERFACE_H_
#define HOST_FW_CMD_INTERFACE_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "status/msft_module_id.h"
#include "status/rot_status.h"


/**
 * Status codes for host firmware operations.
 */
enum host_fw_cmd_status {
	HOST_FW_CMD_STATUS_SUCCESS = 0,			/**< Successful operation. */
	HOST_FW_CMD_STATUS_STARTING,			/**< The host firmware update process is starting. */
	HOST_FW_CMD_STATUS_REQUEST_BLOCKED,		/**< A request has been made before the previous one finished. */
	HOST_FW_CMD_STATUS_PREPARE,				/**< The host firmware module is being prepared for updating. */
	HOST_FW_CMD_STATUS_PREPARE_FAIL,		/**< There was an error preparing the host firmware for updating. */
	HOST_FW_CMD_STATUS_STORE_DATA,			/**< Host fimware update is storing the image. */
	HOST_FW_CMD_STATUS_STORE_FAIL,			/**< There was an error in storing host firmare image. */
	HOST_FW_CMD_STATUS_INTERNAL_ERROR,		/**< An unspecified, internal error occurred. */
	HOST_FW_CMD_STATUS_NONE_STARTED,		/**< No host firmware update has been attempted since the last reboot. */
	HOST_FW_CMD_STATUS_TASK_NOT_RUNNING,	/**< The task servicing host firmware update operations is not running. */
	HOST_FW_CMD_STATUS_UNKNOWN,				/**< The host firmware update status could not be determined. */
	HOST_FW_CMD_STATUS_START_FAILURE,		/**< Failed to start the host firmware update process. */
};

/**
 * Make a a status value suitable to be returned by get_status.
 *
 * @param status The status per host_fw_cmd_status.
 * @param error The error code for the operation.
 */
#define	HOST_FW_CMD_STATUS(status, error)	(((error & 0xffffff) << 8) | status)


/**
 * Defines the API to handle commands for a single host firmware image.
 */
struct host_fw_cmd_interface {
	/**
	 * Trigger the system to prepare to receive a new firmware image. This will return immediately,
	 * with the status of the operation being reported separately.
	 *
	 * @param cmd The command interface for the firmware to prepare for update.
	 * @param total_size Total size of the firmware update.
	 * @param prioitize_update Flag to indicate that the FW update should take priority over
	 * allowing the host to access flash.
	 * @param ctrl_flag Implementation specific flag that can be used to trigger special workflows
	 * during update preparation.
	 *
	 * @return 0 if the action was successfully triggered or an error code.
	 */
	int (*prepare_update) (const struct host_fw_cmd_interface *cmd, uint32_t total_size,
		bool prioritize_update, uint8_t ctrl_flag);

	/**
	 * Indicate that new image data should be written to host flash. This will return immediately,
	 * with the status of the operation being reported separately.
	 *
	 * @param cmd The command interface for firmware to update.
	 * @param data The image data to store.
	 * @param length The number image data bytes to store.
	 *
	 * @return 0 if the action was successfully triggered or an error code.
	 */
	int (*write_update) (const struct host_fw_cmd_interface *cmd, const uint8_t *data,
		size_t length);

	/**
	 * Get the status of the last firmware operation requested.
	 *
	 * @param cmd The command interface for the firmware to query.
	 *
	 * @return The firmware operation status. The lower 8 bits will be the operation status as per
	 * enum host_fw_cmd_status. The remaining bits will be the return code from the host
	 * firmware operation.
	 */
	int (*get_status) (const struct host_fw_cmd_interface *cmd);

	/**
	 * Get the number of bytes remaining in the expected firmware update.
	 *
	 * @param cmd The command interface for the firmware to query.
	 *
	 * @return The remaining number of update bytes.
	 */
	int (*get_update_remaining) (const struct host_fw_cmd_interface *cmd);
};


#define	HOST_FW_CMD_ERROR(code)		ROT_ERROR (MSFT_MODULE_HOST_FW_CMD, code)

/**
 * Error codes that can be generated by an host firmware command handler.
 */
enum {
	HOST_FW_CMD_INVALID_ARGUMENT = HOST_FW_CMD_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HOST_FW_CMD_NO_MEMORY = HOST_FW_CMD_ERROR (0x01),			/**< Memory allocation failed. */
	HOST_FW_CMD_PREPARE_FAILED = HOST_FW_CMD_ERROR (0x02),		/**< Failure to start update preparation. */
	HOST_FW_CMD_WRITE_FAILED = HOST_FW_CMD_ERROR (0x03),		/**< Failure to start update writing. */
	HOST_FW_CMD_NO_TASK = HOST_FW_CMD_ERROR (0x04),				/**< No command task is running. */
	HOST_FW_CMD_TASK_BUSY = HOST_FW_CMD_ERROR (0x05),			/**< The command task is busy performing an operation. */
	HOST_FW_CMD_UNSUPPORTED_OP = HOST_FW_CMD_ERROR (0x06),		/**< The requested operation is not supported. */
	HOST_FW_CMD_TOO_MUCH_DATA = HOST_FW_CMD_ERROR (0x07),		/**< Too much data was sent in a single request. */
};


#endif	/* HOST_FW_CMD_INTERFACE_H_ */
