// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef OVERLAKE_CONTROL_H_
#define OVERLAKE_CONTROL_H_

#include <stdbool.h>
#include <stdint.h>
#include "status/msft_module_id.h"
#include "status/rot_status.h"


/**
 * Defines the interface for controlling the overlake SoC.
 */
struct overlake_control {
	/**
	 * Enable or disable the signal that will trigger NMI on the SoC.
	 *
	 * @param control The control instance for the SoC.
	 * @param enable true to enable the trigger NMI on the host processor, false to disable.
	 *
	 * @return 0 if successfully able to enable or disable NMI on the SoC or an error code.
	 */
	int (*soc_trigger_nmi) (struct overlake_control *soc_control, bool enable);

	/**
	 * Force the SoC/Cyclone V FPGA to be reset.  This call does not guarantee the SoC/Cyclone V
	 * FPGA will have been reset upon returning.  The reset may be executed within a different context.
	 *
	 * @param soc_control The control instance for the SoC.
	 * @param reset_id The ID indicating whether SoC or Cyclone V FPGA will be reset.
	 *
	 * @return 0 if the SoC/FPGA will be reset or an error code.
	 */
	int (*soc_reset) (struct overlake_control *soc_control, uint8_t reset_id);

	/**
	 * Perform a physical flash reset of the SoC flash.  This restores flash configuration register to default
	 * settings among other changes.
	 *
	 * @param soc_control The control instance for the SoC.
	 *
	 * @return 0 if the flash was reset successfully or an error code.
	 */
	int (*force_flash_reset) (struct overlake_control *soc_control);
};


#define	OVERLAKE_CONTROL_ERROR(code)		ROT_ERROR (MSFT_MODULE_OVERLAKE_CONTROL, code)

/**
 * Error codes that can be generated by the Overlake control driver.
 */
enum {
	OVERLAKE_CONTROL_INVALID_ARGUMENT = OVERLAKE_CONTROL_ERROR (0x00),			/**< Input parameter is null or not valid. */
	OVERLAKE_CONTROL_NO_MEMORY = OVERLAKE_CONTROL_ERROR (0x01),					/**< Memory allocation failed. */
	OVERLAKE_CONTROL_NMI_TRIGGER_FAILED = OVERLAKE_CONTROL_ERROR (0x02),		/**< Failed to trigger NMI on the SoC. */
	OVERLAKE_CONTROL_SOC_RESET_FAILED = OVERLAKE_CONTROL_ERROR (0x03),			/**< Failed to initiate SoC reset. */
	OVERLAKE_CONTROL_FPGA_RESET_FAILED = OVERLAKE_CONTROL_ERROR (0x04),			/**< Failed to initiate FPGA reset. */
	OVERLAKE_CONTROL_FPGA_RESET_UNSUPPORTED = OVERLAKE_CONTROL_ERROR (0x05),	/**< FPGA reset not supported. */
	OVERLAKE_CONTROL_FLASH_RESET_UNSUPPORTED = OVERLAKE_CONTROL_ERROR (0x06),	/**< Flash reset is not supported. */
	OVERLAKE_CONTROL_OPERATION_NOT_SUPPORTED = OVERLAKE_CONTROL_ERROR (0x07),	/**< Requested operation is not supported by this interface. */
	OVERLAKE_CONTROL_NO_TASK = OVERLAKE_CONTROL_ERROR (0x08),					/**< No command task is running. */
	OVERLAKE_CONTROL_TASK_BUSY = OVERLAKE_CONTROL_ERROR (0x09),					/**< The command task is busy performing an operation. */
	OVERLAKE_CONTROL_HOST_RESET_INPROGRESS = OVERLAKE_CONTROL_ERROR (0x0a),		/**< Host reset is already in progress. */
	OVERLAKE_CONTROL_TOO_MUCH_DATA = OVERLAKE_CONTROL_ERROR (0x0a),				/**< Too much data was sent in a single request . */
};


#endif	/* OVERLAKE_CONTROL_H_ */
