// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef GRACEFUL_SHUTDOWN_H_
#define GRACEFUL_SHUTDOWN_H_

#include "cmd_interface/cmd_device.h"
#include "ipc/ipc_channel.h"
#include "status/manticore_module_id.h"


/**
 * The maximum drain time allowed during a graceful shutdown.
 */
#define	GRACEFUL_SHUTDOWN_MAX_ALLOWED_DRAIN_TIME		60000

/**
 * Magic number indicating that a graceful shutdown has been executed.
 */
#define	GRACEFUL_SHUTDOWN_INDICATOR_MAGIC_NUMBER		0x5354574e


/**
 * Control interface to manipulate the behavior of the graceful shutdown process.
 */
struct graceful_shutdown_control {
	/**
	 * Get the current configuration for the amount of time CP and FP cores can take draining the
	 * active operations when shutting down.
	 *
	 * @param handler The shutdown handler to query.
	 * @param drain_time_ms Output for the current drain time configuration, in milliseconds.
	 *
	 * @return 0 if the drain time was retrieved successfully or an error code.
	 */
	int (*get_allowed_drain_time) (const struct graceful_shutdown_control *handler,
		uint32_t *drain_time_ms);

	/**
	 * Change the amount of time CP and FP cores are allowed to take draining the active operations
	 * during shutdown.  The next request to shutdown will use this new drain time value.
	 *
	 * @param handler The shutdown handler to query.
	 * @param drain_time_ms The drain time to configure, in milliseconds.  If this is 0, the default
	 * drain time will be configured.
	 *
	 * @return 0 if the allowed drain time was successfully updated or an error code.
	 */
	int (*set_allowed_drain_time) (const struct graceful_shutdown_control *handler,
		uint32_t drain_time_ms);
};

/**
 * Variable context for the graceful shutdown handler.
 */
struct graceful_shutdown_state {
	uint32_t drain_time_ms;	/**< The amount of time allowed to drain active operations. */
};

/**
 * Handler to be executed during reset after firmware update or in other scenarios when a graceful
 * shutdown of the CP and FP cores is required.
 */
struct graceful_shutdown {
	struct graceful_shutdown_control base_ctrl;	/**< Base interface for controlling the shutdown behavior. */
	struct cmd_device base_device;				/**< Base interface for handling device commands. */
	struct graceful_shutdown_state *state;		/**< Variable context for the handler. */
	const struct cmd_device *device;			/**< Underlying handler for device commands. */
	const struct ipc_channel *ipc;				/**< Channel to use for sending IPC requests to other cores. */
	const struct log_flush_handler *log_flush;	/**< Handler for flushing log data. */
	volatile uint32_t *indicator;				/**< Reset tolerant indicator of a graceful shutdown. */
	uint32_t ipc_timeout;						/**< Timeout to use for shutdown IPC messages. */
	uint32_t default_drain_time;				/**< Default drain time allowed during shutdown. */
};


int graceful_shutdown_init (struct graceful_shutdown *shutdown,
	struct graceful_shutdown_state *state, const struct cmd_device *device,
	const struct ipc_channel *ipc, const struct log_flush_handler *log_flush,
	volatile uint32_t *shutdown_indicator, uint32_t shutdown_timeout_ms, uint32_t drain_time_ms);
int graceful_shutdown_init_state (const struct graceful_shutdown *shutdown);
void graceful_shutdown_release (const struct graceful_shutdown *shutdown);

int graceful_shutdown_resume_normal_operation (const struct graceful_shutdown *shutdown,
	uint32_t resp_timeout_ms);


#define	GRACEFUL_SHUTDOWN_ERROR(code)		ROT_ERROR (MANTICORE_MODULE_GRACEFUL_SHUTDOWN, code)

/**
 * Error codes that can be generated by the graceful shutdown handler.
 */
enum {
	GRACEFUL_SHUTDOWN_INVALID_ARGUMENT = GRACEFUL_SHUTDOWN_ERROR (0x00),	/**< Input parameter is null or not valid. */
	GRACEFUL_SHUTDOWN_NO_MEMORY = GRACEFUL_SHUTDOWN_ERROR (0x01),			/**< Memory allocation failed. */
	GRACEFUL_SHUTDOWN_GET_DRAIN_TIME_FAIL = GRACEFUL_SHUTDOWN_ERROR (0x02),	/**< Failed to get the allowed drain time. */
	GRACEFUL_SHUTDOWN_SET_DRAIN_TIME_FAIL = GRACEFUL_SHUTDOWN_ERROR (0x03),	/**< Failed to set the allowed drain time. */
	GRACEFUL_SHUTDOWN_OUT_OF_RANGE = GRACEFUL_SHUTDOWN_ERROR (0x04),		/**< Specified drain time is too long. */
	GRACEFUL_SHUTDOWN_IPC_ERROR_RESP = GRACEFUL_SHUTDOWN_ERROR (0x05),		/**< An IPC error response was received. */
	GRACEFUL_SHUTDOWN_IPC_TIMEOUT_RESP = GRACEFUL_SHUTDOWN_ERROR (0x06),	/**< An IPC timeout error response was received. */
	GRACEFUL_SHUTDOWN_IPC_FAILURE_RESP = GRACEFUL_SHUTDOWN_ERROR (0x07),	/**< An IPC failure error response was received. */
	GRACEFUL_SHUTDOWN_IPC_RESP_UNKNOWN = GRACEFUL_SHUTDOWN_ERROR (0x08),	/**< An unknown status code was returned in the response. */
};


#endif	/* GRACEFUL_SHUTDOWN_H_ */
