// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef MANTICORE_FIRMWARE_PACKAGE_H_
#define MANTICORE_FIRMWARE_PACKAGE_H_

#include <stdbool.h>
#include <stdint.h>
#include "crypto/hash.h"
#include "crypto/signature_verification.h"
#include "drivers/ccs_ksu_interface.h"
#include "firmware/firmware_header.h"
#include "firmware/firmware_loader.h"
#include "firmware/manticore_firmware_descriptor.h"
#include "flash/flash.h"
#include "status/manticore_module_id.h"


/**
 * Length of each encryption IV in the package IV table.
 */
#define MANTICORE_FIRMWARE_PACKAGE_IV_LENGTH		16


/**
 * Context for handling a complete Manticore Firmware Package.
 */
struct manticore_firmware_package {
	struct firmware_header header;						/**< The firmware header on the package. */
	struct manticore_firmware_descriptor *descriptor;	/**< The firmware descriptor for the package. */
	uint8_t *iv_table;									/**< Table of IV values used to encrypt images. */
	bool encrypted;										/**< Flag indicating if the package is encrypted. */
	const struct flash *flash;							/**< The flash device that contains the package data. */
	uint32_t base_addr;									/**< Base address on flash of the firmware package. */
	uint32_t sp_addr;									/**< Base address of the SPRT images. */
	uint32_t cp_addr;									/**< Base address of the CP images. */
	uint32_t fp0_addr;									/**< Base address of the FP0 images. */
	uint32_t fp1_addr;									/**< Base address of the FP1 images. */
	uint32_t fp2_addr;									/**< Base address of the FP2 images. */
	uint32_t pcie_addr;									/**< Base address of the PCIe images. */
};


int manticore_firmware_package_init (struct manticore_firmware_package *fw,
	struct manticore_firmware_descriptor *descriptor, const struct flash *flash, uint32_t address,
	const struct hash_engine *hash, const struct signature_verification *verification,
	const struct ccs_ksu_interface *ccs);
int manticore_firmware_package_init_require_sp (struct manticore_firmware_package *fw,
	struct manticore_firmware_descriptor *descriptor, const struct flash *flash, uint32_t address,
	const struct hash_engine *hash, const struct signature_verification *verification,
	const struct ccs_ksu_interface *ccs);
void manticore_firmware_package_release (struct manticore_firmware_package *fw);

size_t manticore_firmware_package_get_length (const struct manticore_firmware_package *fw);
const struct firmware_header* manticore_firmware_package_get_firmware_header (
	const struct manticore_firmware_package *fw);


int manticore_firmware_package_verify_package_on_flash (const struct manticore_firmware_package *fw,
	const struct hash_engine *hash, const struct signature_verification *verification);
int manticore_firmware_package_verify_components_on_flash (
	const struct manticore_firmware_package *fw, const struct hash_engine *hash,
	const struct signature_verification *verification);

int manticore_firmware_package_load_sp_components (const struct manticore_firmware_package *fw,
	const struct firmware_loader *loader, const struct hash_engine *hash,
	const struct signature_verification *verification, uint8_t **digests, size_t *img_count);
int manticore_firmware_package_load_cp_components (const struct manticore_firmware_package *fw,
	const struct firmware_loader *loader, const struct hash_engine *hash,
	const struct signature_verification *verification, uint8_t **digests, size_t *img_count);
int manticore_firmware_package_load_fp0_components (const struct manticore_firmware_package *fw,
	const struct firmware_loader *loader, const struct hash_engine *hash,
	const struct signature_verification *verification, uint8_t **digests, size_t *img_count);
int manticore_firmware_package_load_fp1_components (const struct manticore_firmware_package *fw,
	const struct firmware_loader *loader, const struct hash_engine *hash,
	const struct signature_verification *verification, uint8_t **digests, size_t *img_count);
int manticore_firmware_package_load_fp2_components (const struct manticore_firmware_package *fw,
	const struct firmware_loader *loader, const struct hash_engine *hash,
	const struct signature_verification *verification, uint8_t **digests, size_t *img_count);
int manticore_firmware_package_load_pcie_components (const struct manticore_firmware_package *fw,
	const struct firmware_loader *loader, const struct hash_engine *hash,
	const struct signature_verification *verification, uint8_t **digests, size_t *img_count);


#define	MANTICORE_FW_PACKAGE_ERROR(code)        \
	ROT_ERROR (MANTICORE_MODULE_MANTICORE_FW_PACKAGE, code)

/**
 * Error codes that can be generated by a firmware package.
 */
enum {
	MANTICORE_FW_PACKAGE_INVALID_ARGUMENT = MANTICORE_FW_PACKAGE_ERROR (0x00),		/**< Input parameter is null or not valid. */
	MANTICORE_FW_PACKAGE_NO_MEMORY = MANTICORE_FW_PACKAGE_ERROR (0x01),				/**< Memory allocation failed. */
	MANTICORE_FW_PACKAGE_BAD_IV_MARKER = MANTICORE_FW_PACKAGE_ERROR (0x02),			/**< The marker on the IV table is not correct. */
	MANTICORE_FW_PACKAGE_SIG_TOO_LONG = MANTICORE_FW_PACKAGE_ERROR (0x03),			/**< The signature on the image longer than allowed. */
	MANTICORE_FW_PACKAGE_BAD_IV_TABLE = MANTICORE_FW_PACKAGE_ERROR (0x04),			/**< Verification of the IV table failed. */
	MANTICORE_FW_PACKAGE_NO_SP_IMAGES = MANTICORE_FW_PACKAGE_ERROR (0x05),			/**< There are no SPRT images to load. */
	MANTICORE_FW_PACKAGE_NO_CP_IMAGES = MANTICORE_FW_PACKAGE_ERROR (0x06),			/**< There are no CP images to load. */
	MANTICORE_FW_PACKAGE_NO_FP0_IMAGES = MANTICORE_FW_PACKAGE_ERROR (0x07),			/**< There are no FP0 images to load. */
	MANTICORE_FW_PACKAGE_NO_FP1_IMAGES = MANTICORE_FW_PACKAGE_ERROR (0x08),			/**< There are no FP1 images to load. */
	MANTICORE_FW_PACKAGE_NO_FP2_IMAGES = MANTICORE_FW_PACKAGE_ERROR (0x09),			/**< There are no FP2 images to load. */
	MANTICORE_FW_PACKAGE_NO_PCIE_IMAGES = MANTICORE_FW_PACKAGE_ERROR (0x0a),		/**< There are no PCIe PHY images to load. */
	MANTICORE_FW_PACKAGE_IV_TABLE_NOT_BLANK = MANTICORE_FW_PACKAGE_ERROR (0x0b),	/**< The IV table is not empty for an unencrypted image. */
};


#endif	/* MANTICORE_FIRMWARE_PACKAGE_H_ */
