// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef MANTICORE_DEVICE_KEYS_H_
#define MANTICORE_DEVICE_KEYS_H_

#include <stdint.h>
#include "drivers/ccs_ksu_interface.h"
#include "drivers/hsp_aes.h"
#include "rom/device_keys.h"
#include "status/manticore_module_id.h"
#include "system/security_manager_hsp.h"


/**
 * Key Storage Unit slot numbers for device keys available to Manticore run-time firmware.
 */
enum manticore_device_keys {
	/* Keys generated by 1SP.  Keys in slots starting with MANTICORE_DEVICE_KEYS_1SP_KSU_SLOTS will
	 * be wiped before executing SPRT. */
	MANTICORE_DEVICE_KEYS_HSM_FMC_CDI_SEED = 1,										/**< Device-unique seed based on the DICE CDI. */
	MANTICORE_DEVICE_KEYS_FW_IMAGE_AES_KEY = 2,										/**< Device-unique key for encrypting firmware images. */
	MANTICORE_DEVICE_KEYS_SPRT_OWNER_GLOBAL_KEY = 3,								/**< Global key for a specific device owner for SPRT. */
	MANTICORE_DEVICE_KEYS_HASH_STICK_KEY = 4,										/**< Device-unique hash stick key, which depends on device state. */
	MANTICORE_DEVICE_KEYS_SPRT_DEVICE_KEY = 5,										/**< Device-unique key that is independent of device state for SPRT. */
	MANTICORE_DEVICE_KEYS_TENANCY_KEY = 6,											/**< Device-unique key for tenancy transfers. */
	MANTICORE_DEVICE_KEYS_FW_IMAGE_HMAC_KEY = 7,									/**< Device-unique key for authenticating the firmware image IV table. */
	MANTICORE_DEVICE_KEYS_UNLOCK_HMAC_KEY = 8,										/**< Device-unique key for authenticating debug unlock policies. */
	MANTICORE_DEVICE_KEYS_SP_ALIAS_KEY = 9,											/**< DICE Alias key pair for SP firmware. */
	MANTICORE_DEVICE_KEYS_CP_ALIAS_KEY = 10,										/**< DICE Alias key pair for CP firmware. */
	MANTICORE_DEVICE_KEYS_BKS1 = 11,												/**< BKS1 hash stick key for HSM BMK generation. */
	MANTICORE_DEVICE_KEYS_FIPS_BKS = 12,											/**< Key for deriving FIPS isolated BKS values. */
	MANTICORE_DEVICE_KEYS_BKS2 = 12,												/**< BKS2 key for HSM BMK generation. */
	MANTICORE_DEVICE_KEYS_1SP_KSU_SLOTS,											/**< The number of KSU key slots used for keys managed by boot firmware. */
	MANTICORE_DEVICE_KEYS_FIPS_DEVICE_ID_KEY = MANTICORE_DEVICE_KEYS_1SP_KSU_SLOTS,	/**< The FIPS compliant Device ID.  Not available to SPRT. */
	MANTICORE_DEVICE_KEYS_UNLOCK_HMAC_SEED,											/**< Intermediate key used to derive the unlock HMAC key.  Not available to SPRT. */

	/* Keys generated by SPRT.  These keys must be stored in a slot no lower than
	 * MANTICORE_DEVICE_KEYS_1SP_KSU_SLOTS. */
	MANTICORE_DEVICE_KEYS_RSA_KEY_FLASH_KEY = MANTICORE_DEVICE_KEYS_1SP_KSU_SLOTS,	/**< Key slot to use for encrypted storage of firmware-generated RSA keys. */

	/* No key storage.  Used by both 1SP and SPRT. */
	MANTICORE_DEVICE_KEYS_SELF_TEST = 63,											/**< Key slot to use for crypto self-tests. */
};

/**
 * Key slot for the FIPS non-compliant Device ID key that is populated by ROM.  This key is only
 * used to endorse the FIPS compliant Device ID key and then zeroized.
 */
#define	MANTICORE_DEVICE_KEYS_NON_FIPS_DEVICE_ID_KEY	DEVICE_KEYS_DEVICE_ID_KEY


#pragma pack(push, 1)
/**
 * Chained DME endorsement structure for the FIPS approved DICE Device ID public key.
 */
struct manticore_device_keys_dice_endorsement {
	struct {
		struct device_keys_dice_endorsement rom;	/**< DME endorsement structure from ROM. */
		SP_ECDSA_P384_PUBLIC rom_key;				/**< The FIPS unapproved DICE public key. */
		SP_MSG_384 device_id_hash;					/**< Hash of the FIPS approved DICE ID public key. */
	} signed_data;									/**< DME structure signed with the FIPS unapproved DICE key. */
	SP_ECDSA_P384_SIGNATURE signature;				/**< Signature of the structure using the FIPS unapproved DICE key. */
};

/**
 * Container for a single Backup Key Seed (BKS) to be used by the HSM.
 */
struct manticore_device_keys_bks_entry {
	uint8_t valid;		/**< Flag indicating if the entry contains a valid BKS. */
	uint64_t svn;		/**< SVN associated with the provided BKS. */
	uint8_t bks[32];	/**< The Backup Key Seed data. */
};

/**
 * Table of all Backup Key Seeds available for use by the HSM.
 */
struct manticore_device_keys_bks_table {
	struct manticore_device_keys_bks_entry entry[12];	/**< Table of BKS values. */
};

#pragma pack(pop)


int manticore_device_keys_convert_to_approved_key (const struct ccs_ksu_interface *ccs,
	uint8_t unapproved_key, const SP_MSG_384 *kdf_key, const SP_MSG_384 *kdf_context,
	uint8_t approved_key);

int manticore_device_keys_convert_1sp_keys (const struct ccs_ksu_interface *fips_ccs,
	const struct ccs_ksu_interface *hw_ccs, const struct ecc_hw *ecc,
	const struct hash_engine *hash, const SP_MSG_384 *kdf_key, const SP_MSG_384 *kdf_context,
	const struct device_keys_dice_endorsement *rom_dme, SP_ECDSA_P384_PUBLIC *device_id,
	struct manticore_device_keys_dice_endorsement *dme);

/**
 * KDF contexts to use for keys derived during 1SP execution.
 */
struct manticore_device_keys_1sp_kdf {
	const SP_MSG_384 *firmware_hmac;	/**< KDF context for the firmware HMAC key. */
	const SP_MSG_384 *sprt_device_key;	/**< KDF context for the SPRT device-unique seed. */
	const SP_MSG_384 *fips_unlock;		/**< KDF context for deriving the FIPS unlock HMAC key. */
	const SP_MSG_384 *non_fips_unlock;	/**< KDF context for deriving the Non-FIPS unlock HMAC key. */
};


int manticore_device_keys_derive_1sp_keys (const struct ccs_ksu_interface *ccs,
	const struct security_manager_hsp *sec_manager,
	const struct manticore_device_keys_1sp_kdf *context, bool is_fips_certified);
int manticore_device_keys_clear_1sp_keys (const struct ccs_ksu_interface *ccs);

int manticore_device_keys_derive_unlocked_1sp_keys (const struct ccs_ksu_interface *ccs,
	const SP_MSG_384 *context);
int manticore_device_keys_derive_non_fips_sprt_keys (const struct ccs_ksu_interface *ccs,
	const SP_MSG_384 *context, const struct security_manager_hsp *sec_manager);

int manticore_device_keys_derive_bks_keys (const struct ccs_ksu_interface *ccs,
	const SP_MSG_384 *bks_fips_context, const SP_MSG_384 *bks1_context, uint64_t bks1_svn,
	const SP_MSG_384 *bks2_context, const SP_MSG_384 *sprt_context);
int manticore_device_keys_export_bks (const struct hsp_aes *aes, const SP_MSG_256 *bks_context,
	const struct ccs_ksu_interface *ccs, uint64_t svn,
	struct manticore_device_keys_bks_table *bks_table);


#define	MANTICORE_DEVICE_KEYS_ERROR(code)        ROT_ERROR (MANTICORE_MODULE_DEVICE_KEYS, code)

/**
 * Error codes that can be generated during device specific key generation.
 */
enum {
	MANTICORE_DEVICE_KEYS_INVALID_ARGUMENT = MANTICORE_DEVICE_KEYS_ERROR (0x00),	/**< Input parameter is null or not valid. */
	MANTICORE_DEVICE_KEYS_NO_MEMORY = MANTICORE_DEVICE_KEYS_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* MANTICORE_DEVICE_KEYS_H_ */
