// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef MANTICORE_BOOTLOADER_H_
#define MANTICORE_BOOTLOADER_H_

#include <stddef.h>
#include <stdint.h>
#include "asn1/ecc_der_util.h"
#include "crypto/signature_verification_ecc.h"
#include "firmware/hsp_fw_1sp.h"
#include "firmware/key_manifest_hsp_firmware.h"
#include "firmware/key_manifest_hsp_rom.h"
#include "firmware/manticore_firmware_package.h"
#include "flash/flash.h"
#include "status/manticore_module_id.h"
#include "system/security_manager.h"


/**
 * Variable context for a Manticore main firmware bootloader.
 */
struct manticore_bootloader_state {
	struct signature_verification_ecc_state verify_state;	/**< Variable context for signature verification. */
	struct manticore_firmware_package fw_pkg;				/**< Main firmware image. */
};

/**
 * Main bootloader for Manticore firmware, responsible for verifying run-time firmware components
 * and loading them into the necessary target memories.
 */
struct manticore_bootloader {
	struct manticore_bootloader_state *state;		/**< Variable context for the bootloader. */
	const struct flash *flash;						/**< Flash device that contains the firmware. */
	const struct hash_engine *hash;					/**< Hash engine for descriptor loading. */
	const struct security_manager *security;		/**< Manager for the device security policy. */
	const struct firmware_loader *sp_loader;		/**< Handler for loading firmware into SP memory. */
	const struct firmware_loader *cp_loader;		/**< Handler for loading firmware into CP memory. */
	const struct firmware_loader *fp0_loader;		/**< Handler for loading firmware into FP0 memory. */
	const struct firmware_loader *fp1_loader;		/**< Handler for loading firmware into FP1 memory. */
	const struct firmware_loader *fp2_loader;		/**< Handler for loading firmware into FP2 memory. */
	const struct firmware_loader *pcie_loader;		/**< Handler for loading PCIe PHY firmware images. */
	struct key_manifest_hsp_firmware manifest;		/**< Key manifest for the main firmware. */
	struct signature_verification_ecc verification;	/**< Verification wrapper for main firmware. */
};


int manticore_bootloader_init (struct manticore_bootloader *boot,
	struct manticore_bootloader_state *state, const struct flash *flash, uint32_t base_addr,
	struct key_manifest_hsp_firmware_manifest *fw_keys,
	struct manticore_firmware_descriptor *fw_descriptor, const struct hash_engine *hash,
	const struct ecc_engine *ecc, const struct ccs_ksu_interface *ccs, const uint8_t *key_1sp,
	size_t key_length, const struct hw_rot *rot_manifest, const struct security_manager *security,
	const struct firmware_loader *sp_loader, const struct firmware_loader *cp_loader,
	const struct firmware_loader *fp0_loader, const struct firmware_loader *fp1_loader,
	const struct firmware_loader *fp2_loader, const struct firmware_loader *pcie_loader);
int manticore_bootloader_init_state (const struct manticore_bootloader *boot, uint32_t base_addr,
	const struct ccs_ksu_interface *ccs, const struct hw_rot *rot_manifest,
	struct manticore_firmware_descriptor *fw_descriptor);
void manticore_bootloader_release (const struct manticore_bootloader *boot);

int manticore_bootloader_load_sp_only (const struct manticore_bootloader *boot, uint8_t *hash_out,
	size_t length);
int manticore_bootloader_load_all_cores (const struct manticore_bootloader *boot,
	uint8_t *sp_hash_out, size_t sp_hash_length, uint8_t *cp_hash_out, size_t cp_hash_length,
	uint8_t *fp0_hash_out, size_t fp0_hash_length, uint8_t *fp1_hash_out, size_t fp1_hash_length,
	uint8_t *fp2_hash_out, size_t fp2_hash_length);
int manticore_bootloader_load_pcie_phy (const struct manticore_bootloader *boot, uint8_t *hash_out,
	size_t length);


#define	MANTICORE_BOOTLOADER_ERROR(code)        \
	ROT_ERROR (MANTICORE_MODULE_MANTICORE_BOOTLOADER, code)

/**
 * Error codes that can be generated by the bootloader.
 */
enum {
	MANTICORE_BOOTLOADER_INVALID_ARGUMENT = MANTICORE_BOOTLOADER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	MANTICORE_BOOTLOADER_NO_MEMORY = MANTICORE_BOOTLOADER_ERROR (0x01),			/**< Memory allocation failed. */
	MANTICORE_BOOTLOADER_MANIFEST_REVOKED = MANTICORE_BOOTLOADER_ERROR (0x02),	/**< The firmware key manifest has been revoked. */
	MANTICORE_BOOTLOADER_FIRMWARE_REVOKED = MANTICORE_BOOTLOADER_ERROR (0x03),	/**< The firmware package has been revoked. */
};


#endif	/* MANTICORE_BOOTLOADER_H_ */
