# Copyright (c) Microsoft Corporation. All rights reserved.

[package]
name = "mcr-mailbox-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcr-controller.workspace = true
mcr-registers.workspace = true

[lib]
doctest = false
