// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef LOGGING_COLLECTOR_H_
#define LOGGING_COLLECTOR_H_

#include <stdint.h>
#include "platform_api.h"
#include "logging/logging.h"
#include "logging/manticore_logging_record.h"
#include "logging/ring_buffer_state.h"


/**
 * Logging collector states
 */
enum {
	LOGGING_COLLECTOR_INITIALIZED = 0,	/**< Collector has been initialized. */
	LOGGING_COLLECTOR_RUNNING,			/**< Collector is running. */
	LOGGING_COLLECTOR_FAULTED,			/**< Collector has encountered an error. */
};


/**
 * State information for a logging collector.
 */
struct logging_collector_state {
	platform_mutex lock;		/*< Mutex for the collector. */
	uint32_t logged_overflows;	/*< Number of sender overflows that have been already reported. */
	uint32_t current_state;		/*< FSM state of the collector. */
};

/**
 * A log that will collect entries from a ring buffer and store them in the debug log.
 *
 * @note See the testing folder for an example sender implementation.
 */
struct logging_collector {
	struct logging base;					/**< The base logging instance. */
	struct logging_collector_state *state;	/**< Variable context for the log instance. */
	uint64_t mem_region_start;				/*< Start of the region to mapped */
	size_t mem_region_records;				/*< Size of the region in records */
	uint32_t collector_id;					/*< The ID of the collector */
	const struct hsp_dmb *dmb;				/*< Pointer to the DMB */
};


int logging_collector_init (struct logging_collector *collector,
	struct logging_collector_state *state, uint64_t mem_region_start, size_t mem_region_records,
	const struct hsp_dmb *dmb, uint32_t sender_id);
int logging_collector_init_state (const struct logging_collector *collector);
void logging_collector_release (const struct logging_collector *collector);


/**
 * Error code for the logging collector module.
 */
#define	LOGGING_COLLECTOR_ERROR(code) ROT_ERROR (MANTICORE_MODULE_LOGGING_COLLECTOR, code)

/**
 * Error codes that can be generated by the logging collector module.
 */
enum {
	LOGGING_COLLECTOR_INVALID_ARGUMENT = LOGGING_COLLECTOR_ERROR (0x00),				/**< Invalid argument */
	LOGGING_COLLECTOR_NO_MEMORY = LOGGING_COLLECTOR_ERROR (0x01),						/**< Insufficient memory */
	LOGGING_COLLECTOR_INVALID_DESCRIPTOR = LOGGING_COLLECTOR_ERROR (0x02),				/**< Invalid descriptor */
	LOGGING_COLLECTOR_UNEXPECTED_NUMBER_OF_RECORDS = LOGGING_COLLECTOR_ERROR (0x03),	/**< Unexpected number of records */
};


#endif	/* LOGGING_COLLECTOR_H_ */
