// Copyright (c) Microsoft Corporation. All rights reserved.
// This is an autogenerated file using log_tokenizer.py. Do not edit manually.

#ifndef MANTICORE_FP_LOG_TOKENS_H_
#define MANTICORE_FP_LOG_TOKENS_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif


#define MANTICORE_FP_LOG_ARGS_SPLITTER_MAX	8

/**
 * @brief Identifiers for telemetry fp0 log message_str Index
 */
enum {
	FP0_RSVD_ID_00,	// Reserved ID
	FP0_COMMON_01,
	FP0_COMMON_02,
	FP0_COMMON_03,
	FP0_COMMON_04,
	FP0_COMMON_05,
	FP0_COMMON_06,
	FP0_COMMON_07,
	FP0_COMMON_08,
	FP0_COMMON_09,
	FP0_COMMON_0A,
	FP0_COMMON_MAX,
};

/**
 * @brief Identifiers for telemetry fp1 log message_str Index
 */
enum {
	FP1_RSVD_ID_00,	// Reserved ID
	FP1_COMMON_01,
	FP1_COMMON_02,
	FP1_COMMON_03,
	FP1_COMMON_04,
	FP1_COMMON_05,
	FP1_COMMON_06,
	FP1_COMMON_07,
	FP1_COMMON_08,
	FP1_COMMON_09,
	FP1_COMMON_0A,
	FP1_COMMON_0B,
	FP1_COMMON_0C,
	FP1_COMMON_0D,
	FP1_COMMON_0E,
	FP1_COMMON_0F,
	FP1_COMMON_10,
	FP1_COMMON_11,
	FP1_COMMON_12,
	FP1_COMMON_13,
	FP1_COMMON_14,
	FP1_COMMON_15,
	FP1_COMMON_16,
	FP1_COMMON_17,
	FP1_COMMON_18,
	FP1_COMMON_MAX,
};

/**
 * @brief Identifiers for telemetry fp2 log message_str Index
 */
enum {
	FP2_RSVD_ID_00,	// Reserved ID
	FP2_COMMON_01,
	FP2_COMMON_02,
	FP2_COMMON_03,
	FP2_COMMON_04,
	FP2_COMMON_05,
	FP2_COMMON_06,
	FP2_COMMON_07,
	FP2_COMMON_08,
	FP2_COMMON_09,
	FP2_COMMON_0A,
	FP2_COMMON_0B,
	FP2_COMMON_0C,
	FP2_COMMON_0D,
	FP2_COMMON_0E,
	FP2_COMMON_0F,
	FP2_COMMON_10,
	FP2_COMMON_11,
	FP2_COMMON_12,
	FP2_COMMON_13,
	FP2_COMMON_14,
	FP2_COMMON_15,
	FP2_COMMON_16,
	FP2_COMMON_17,
	FP2_COMMON_18,
	FP2_COMMON_19,
	FP2_COMMON_1A,
	FP2_COMMON_MAX,
};

extern const char *telemetry_fp0_logging_component_str[FP0_COMMON_MAX];
extern const char *telemetry_fp1_logging_component_str[FP1_COMMON_MAX];
extern const char *telemetry_fp2_logging_component_str[FP2_COMMON_MAX];

extern uint8_t telemetry_fp0_component_size;
extern uint8_t telemetry_fp1_component_size;
extern uint8_t telemetry_fp2_component_size;

#ifdef __cplusplus
}
#endif


#endif	// MANTICORE_FP_LOG_TOKENS_H_
