// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef SECURITY_POLICY_HSP_H_
#define SECURITY_POLICY_HSP_H_

#include <stdint.h>
#include "system/security_policy.h"


/**
 * Provides security properties of the device, extended to include properties specific to HSP-based
 * implementations.
 */
struct security_policy_hsp {
	struct security_policy base;	/**< Base policy API. */

	/**
	 * Get the list of Access Enablement Bits (AEBs) that should be enabled for the device.
	 *
	 * @param policy The security policy to query.
	 * @param aeb Output for the list of AEBs to enable.  This will be a bitmask, with each AEB
	 * represented by a single bit.  Set bits will be AEBs that should be enabled.
	 * @param word_count Number of AEB words in the output buffer.  This must be large enough to
	 * hold all AEBs supported by the device.
	 *
	 * @param 0 if the AEBs were retrieved successfully or an error code.
	 */
	int (*get_enabled_aebs) (const struct security_policy_hsp *policy, uint32_t *aeb,
		size_t word_count);

	/**
	 * Get the list of Access Enablement Bits (AEBs) that should be disabled for the device.
	 *
	 * @param policy The security policy to query.
	 * @param aeb Output for the list of AEBs to disable.  This will be a bitmask, with each AEB
	 * represented by a single bit.  Set bits will be AEBs that should be disabled.
	 * @param word_count Number of AEB words in the output buffer.  This must be large enough to
	 * hold all AEBs supported by the device.
	 *
	 * @param 0 if the AEBs were retrieved successfully or an error code.
	 */
	int (*get_disabled_aebs) (const struct security_policy_hsp *policy, uint32_t *aeb,
		size_t word_count);

	/**
	 * Get the list of Access Enablement Bits (AEBs) that should be locked for the device.
	 *
	 * @param policy The security policy to query.
	 * @param aeb Output for the list of AEBs to lock.  This will be a bitmask, with each AEB
	 * represented by a single bit.  Set bits will be AEBs that should be locked.
	 * @param word_count Number of AEB words in the output buffer.  This must be large enough to
	 * hold all AEBs supported by the device.
	 *
	 * @param 0 if the AEBs were retrieved successfully or an error code.
	 */
	int (*get_locked_aebs) (const struct security_policy_hsp *policy, uint32_t *aeb,
		size_t word_count);

	/**
	 * Get the list of Access Enablement Bits (AEBs) that should be permanently disabled via fuses.
	 *
	 * AEBs are defined such that disable is a more secure state than enable.  Therefore, while
	 * permanently disabling AEBs may remove flexibility in device management, it will not
	 * compromise the overall security guarantees of the device.
	 *
	 * @param policy The security policy to query.
	 * @param aeb Output for a bit mask for the AEBs that should be permanently disabled through
	 * fuses.  Each bit position that is set represents a single AEB that should be disabled in
	 * fuses.  Only the first 32 AEBs can be backed by fuses.
	 *
	 * @return 0 if the AEBs were retrieved successfully or an error code.
	 */
	int (*get_fuse_disabled_aebs) (const struct security_policy_hsp *policy, uint32_t *aeb);

	/**
	 * Determine if the security policy requires that memory fencing should be enforced by the
	 * device.
	 *
	 * @param policy The security policy to query.
	 *
	 * @return 1 if the policy requires memory fencing, 0 if not, or an error code.
	 */
	int (*enforce_memory_fencing) (const struct security_policy_hsp *policy);
};


/**
 * Error codes that can be generated by an HSP security policy.  These errors are in addition to the
 * base security policy error codes, and start at the reserved value of 0x80.
 */
enum {
	SECURITY_POLICY_HSP_GET_ENABLED_FAILED = SECURITY_POLICY_ERROR (0x80),		/**< Failed to get the list of enabled AEBs. */
	SECURITY_POLICY_HSP_GET_DISABLED_FAILED = SECURITY_POLICY_ERROR (0x81),		/**< Failed to get the list of disabled AEBs. */
	SECURITY_POLICY_HSP_GET_LOCKED_FAILED = SECURITY_POLICY_ERROR (0x82),		/**< Failed to get the list of locked AEBs. */
	SECURITY_POLICY_HSP_GET_FUSED_FAILED = SECURITY_POLICY_ERROR (0x83),		/**< Failed to get the list of fuse disabled AEBs. */
	SECURITY_POLICY_HSP_CHECK_FENCING_FAILED = SECURITY_POLICY_ERROR (0x84),	/**< Failed to determine memory fencing enforcement. */
};


#endif	/* SECURITY_POLICY_HSP_H_ */
