# Copyright (c) Microsoft Corporation. All rights reserved.

[package]
name = "mcr-io-controller"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
bitfield-struct.workspace = true
bitfield.workspace = true
cfg-if.workspace = true
cortex-m.workspace = true
mcr-ddi-types.workspace = true
mcr-error.workspace = true
mcr-registers.workspace = true
mcr-types.workspace = true

[features]
# Feature switches used for optional test hooks and validation
mcr_test_hooks = []
