// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef TELEMETRY_TEMPERATURE_HANDLER_H_
#define TELEMETRY_TEMPERATURE_HANDLER_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "logging/logging.h"
#include "logging/manticore_logging.h"
#include "status/manticore_module_id.h"
#include "system/periodic_task.h"
#include "system/temperature_sensor_tsen.h"

/**
 * The macro defining the window size for the moving average.
 */
#define TELEMETRY_TEMPERATURE_HANDLER_MOVING_AVERAGE_WINDOW_SIZE		3

/**
 * Struct to hold the temperature thresholds. The values shall be in hundredths of degree celsius.
 */
struct telemetry_temperature_handler_thresholds {
	int16_t lower_temperature_threshold;	/**< Lower temperature threshold value of the given sensor. */
	int16_t higher_temperature_threshold;	/**< Higher temperature threshold value of the given sensor. */

	/**
	 * The value defining the maximum delta of the previous temperature and current temperature
	 * after which the debug log entry should be created if the state is abnormal. This helps us reduce
	 * the logging messages while maintaining enough logs to help track the temperature changes.
	 */
	uint16_t max_delta;
};

/**
 * Variable context for the telemetry temperature handler.
 */
struct telemetry_temperature_handler_state {
	platform_clock next;														/**< Time at which the next execution should run. */
	bool next_valid;															/**< Indicate if the next timeout has been initialized. */
	uint32_t current_state;														/**< The FSM state of the temperature monitor */
	int16_t	last_avg_temperature;												/**< Last computed average temperature value */
	int16_t values[TELEMETRY_TEMPERATURE_HANDLER_MOVING_AVERAGE_WINDOW_SIZE];	/**< Array to store the values. */
	uint8_t index;																/**< Index to store the value in array. */
	uint8_t count;																/**< Number of samples collected. */
	int32_t sum;																/**< Cumulative sum for the average. */
};

/**
 * Handler for the telemetry temperature monitor.
 */
struct telemetry_temperature_handler {
	struct periodic_task_handler base;									/**< Base interface for task integration. */
	struct telemetry_temperature_handler_state *state;					/**< Variable context for the handler. */
	const struct temperature_sensor *sensor;							/**< Temperature sensor to be measured. */
	const struct telemetry_temperature_handler_thresholds *threshold;	/**< The pointer to the structure storing the threshold values. */
	uint32_t period;													/**< Required time between temperature monitoring requests. */
};


int telemetry_temperature_handler_init (struct telemetry_temperature_handler *handler,
	struct telemetry_temperature_handler_state *state, const struct temperature_sensor *sensor,
	const struct telemetry_temperature_handler_thresholds *threshold, uint32_t period_ms);
int telemetry_temperature_handler_init_state (const struct telemetry_temperature_handler *handler);
void telemetry_temperature_handler_release (const struct telemetry_temperature_handler *handler);


#define	TELEMETRY_TEMPERATURE_HANDLER_ERROR(code)      \
	ROT_ERROR (MANTICORE_MODULE_TELEMETRY_TEMPERATURE, code)

/**
 * Error codes that can be generated by the Telemetry Temperature Module.
 *
 * Note: Commented error codes have been deprecated.
 */
enum {
	TELEMETRY_TEMPERATURE_HANDLER_INVALID_ARGUMENT = TELEMETRY_TEMPERATURE_HANDLER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	TELEMETRY_TEMPERATURE_HANDLER_NO_MEMORY = TELEMETRY_TEMPERATURE_HANDLER_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* TELEMETRY_TEMPERATURE_HANDLER_H_ */
