// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef TELEMETRY_PCIE_HANDLER_H_
#define TELEMETRY_PCIE_HANDLER_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "drivers/hsp_dmb.h"
#include "logging/logging.h"
#include "logging/manticore_logging.h"
#include "marvell/RegComphy1Soc.h"
#include "marvell/RegPcieEp.h"
#include "status/manticore_module_id.h"
#include "system/periodic_task.h"

/**
 * Structure to hold the values of the PCIe link status and width.
 */
struct telemetry_pcie_link_status {
	uint8_t speed;	/**< PCIe Link Speed value. */
	uint8_t width;	/**< PCIe Link Width value. */
};

/**
 * Variable context for the telemetry PCIe handler.
 */
struct telemetry_pcie_handler_state {
	platform_clock next;								/**< Time at which the next execution should run. */
	bool next_valid;									/**< Indicate if the next timeout has been initialized. */
	uint32_t current_state;								/**< The current state of the PCIe monitor */
	LinkControlLinkStatus_t previous_pcie_link_status;	/**< Previous value for the PCIe Link Status Register  */
};

/**
 * Handler for the telemetry PCIe monitor.
 */
struct telemetry_pcie_handler {
	struct periodic_task_handler base;								/**< Base interface for task integration. */
	struct telemetry_pcie_handler_state *state;						/**< Variable context for the handler. */
	const struct hsp_dmb *dmb;										/**< Pointer to the DMB */
	const struct telemetry_pcie_link_status *expected_link_status;	/**< Expected values for PCIe Link Speed and width */
	uint32_t period;												/**< Required time between temperature monitoring requests. */
};


int telemetry_pcie_handler_init (struct telemetry_pcie_handler *handler,
	struct telemetry_pcie_handler_state *state, const struct hsp_dmb *dmb,
	const struct telemetry_pcie_link_status *expected_link_status, uint32_t period_ms);
int telemetry_pcie_handler_init_state (const struct telemetry_pcie_handler *handler);
void telemetry_pcie_handler_release (const struct telemetry_pcie_handler *handler);


#define	TELEMETRY_PCIE_HANDLER_ERROR(code)      \
	ROT_ERROR (MANTICORE_MODULE_TELEMETRY_PCIE, code)

/**
 * Error codes that can be generated by the Telemetry PCIe Module.
 *
 * Note: Commented error codes have been deprecated.
 */
enum {
	TELEMETRY_PCIE_HANDLER_INVALID_ARGUMENT = TELEMETRY_PCIE_HANDLER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	TELEMETRY_PCIE_HANDLER_NO_MEMORY = TELEMETRY_PCIE_HANDLER_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* TELEMETRY_PCIE_HANDLER_H_ */
