// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef MANTICORE_1SP_H_
#define MANTICORE_1SP_H_

#include <stddef.h>
#include <stdint.h>
#include "platform_api.h"
#include "asn1/ecc_der_util.h"
#include "cmd_interface/cerberus_protocol.h"
#include "crypto/hash.h"
#include "firmware/key_manifest_hsp_firmware.h"
#include "firmware/manticore_firmware_descriptor.h"
#include "firmware/manticore_measurements.h"
#include "riot/dice_oid.h"
#include "system/device_unlock_token.h"
#include "system/security_policy_hsp_manticore.h"


/**
 * Length of the unlock counter used by 1SP for persistent unlock token verification.  The counter
 * will be stored at the beginning of RSVD1 fuses.
 */
#define	MANTICORE_1SP_UNLOCK_COUNTER_LENGTH		32

/**
 * Length of the Manticore OID for use in static initialization scenarios.
 */
#define	MANTICORE_OID_LENGTH				11

/**
 * Length of the device-specific data that will be added to unlock authorization tokens.
 */
#define	MANTICORE_UNLOCK_TOKEN_DATA_LENGTH  \
	DEVICE_UNLOCK_TOKEN_SIZEOF_EXTRA_DATA (MANTICORE_OID_LENGTH, \
		MANTICORE_1SP_UNLOCK_COUNTER_LENGTH)

/**
 * Maximum length of a device unlock token generated by Manticore.
 */
#define	MANTICORE_MAX_UNLOCK_TOKEN_LENGTH	(MANTICORE_UNLOCK_TOKEN_DATA_LENGTH + \
	DEVICE_UNLOCK_TOKEN_NONCE_LENGTH + ECC_DER_P384_ECDSA_MAX_LENGTH)

/**
 * Maximum length of authorized device unlock data for Manticore.
 */
#define	MANTICORE_MAX_UNLOCK_DATA_LENGTH	(2 + MANTICORE_MAX_UNLOCK_TOKEN_LENGTH + 2 + \
	sizeof (struct security_policy_hsp_manticore_data) + ECC_DER_P384_ECDSA_MAX_LENGTH)

/**
 * The buffer space needed for unlock HMAC operations.  This must be large enough to hold the entire
 * authorized unlock data and the HMAC.
 */
#define	MANTICORE_UNLOCK_HMAC_BUFFER_SIZE	(MANTICORE_MAX_UNLOCK_DATA_LENGTH + SHA384_HASH_LENGTH)


/**
 * Maximum length of the Device ID Certificate for the FIPS compliant key.
 */
#define MAX_FIPS_DEVID_CERT_LENGTH				2048

/**
 * Maximum length of the Device ID CSR for the FIPS compliant key.
 */
#define MAX_FIPS_DEVID_CSR_LENGTH				1792

/**
 * Maximum length of the Alias private key.
 */
#define MAX_ALIAS_KEY_LENGTH					ECC_DER_P384_PRIVATE_NO_PUB_LENGTH

/**
 * Maximum length of the Alias Certificate.
 */
#define MAX_ALIAS_CERT_LENGTH					1160

/**
 * Total amount of memory reserved for shared data between 1SP and SPRT.  Changes to this size will
 * break compatibility with existing 1SP builds.
 */
#define	TOTAL_SHARED_DATA_MEMORY				(12 * 1024)

/**
 * Structure for storing information that will be passed from 1SP to the main application.
 */
struct manticore_1sp_shared_data {
	union {
		/**
		 * Container for the data generated by 1SP.  This must not exceed the maximum length
		 * allocated for this data.
		 *
		 * Any fields unsupported by a version of 1SP will be zeroized.  This includes deprecated
		 * fields as 1SP versions drop support for those fields.
		 */
		struct {
			size_t valid_length;									/**< Length of the shared data populated by 1SP. */
			struct key_manifest_hsp_firmware_manifest fw_keys;		/**< Keys that should be used run-time operations. */
			struct manticore_firmware_descriptor fw_descriptor;		/**< Descriptor for the running firmware image. */
			struct security_policy_hsp_manticore_data sec_policy;	/**< Security policy applied to the device. */
			struct manticore_measurements_log pcr_log;				/**< Log of measurements for PCRs 1 and 3. */
			uint32_t boot_properties;								/**< Placeholder for additional boot properties, such as secure boot. */
			char version_1sp[CERBERUS_PROTOCOL_FW_VERSION_LEN];		/**< Version string for the 1SP firmware image. */
			char version_sprt[CERBERUS_PROTOCOL_FW_VERSION_LEN];	/**< Version string for the SPRT firmware image. */
			uint8_t devid_cert_fips[MAX_FIPS_DEVID_CERT_LENGTH];	/**< Storage for the self-signed FIPS Device ID certificate. */
			int devid_cert_fips_length;								/**< Length of the FIPS certificate. */
			uint8_t devid_csr_fips[MAX_FIPS_DEVID_CSR_LENGTH];		/**< Storage for the FIPS Device ID CSR */
			int devid_csr_fips_length;								/**< Length of the FIPS CSR. */
			uint8_t alias_key[MAX_ALIAS_KEY_LENGTH];				/**< Storage for the alias private key. */
			int alias_key_length;									/**< Length of the alias key. */
			uint8_t alias_cert[MAX_ALIAS_CERT_LENGTH];				/**< Storage for the alias certificate signed by the device ID. */
			int alias_cert_length;									/**< Length of the alias certificate. */
			platform_clock start_time_1sp;							/**< Start time of 1SP */
			platform_clock start_time_1sp_load_main_fw;				/**< Start time of 1SP load_main_firmware */
			platform_clock start_time_1sp_gen_dice_key;				/**< Start time of 1SP SPRT & CP dice keys generation */
			platform_clock finish_time_1sp_load_main_fw;			/**< End time of 1SP load_main_firmware */
			platform_clock finish_time_1sp_gen_dice_key;			/**< End time of 1SP SPRT & CP DICE keys generation */
			char service_indicator[9];								/**< String to act as FIPS service indicator. */
			char idfu_version[6];									/**< Version string for the impactless compatibility number. */
			bool fips_certifed_1sp;									/**< Flag to indicate the 1SP that executed is FIPS certified. */

			/* To maintain compatibility with existing 1SP builds, new fields must only be appended
			 * to the end of the existing data fields.  Changing sizes or reordering existing fields
			 * will break compatibility and will likely cause boot-time issues in SPRT when paired
			 * with an incompatible 1SP. */

			/**
			 * End marker of the valid shared data.  DO NOT ADD ANYTHING AFTER THIS FIELD.
			 */
			uint8_t valid_end;
		};

		uint8_t hashed[TOTAL_SHARED_DATA_MEMORY - SHA384_HASH_LENGTH];	/**< Data that is hashed to generate the digest. */
	};

	uint8_t digest[SHA384_HASH_LENGTH];									/**< Hash of the shared data. */
};


/**
 * Length of the valid data in the shared structure from 1SP.
 */
#define	MANTICORE_1SP_SHARED_DATA_VALID_LENGTH      \
	offsetof (struct manticore_1sp_shared_data, valid_end)

_Static_assert ((sizeof (struct manticore_1sp_shared_data) == TOTAL_SHARED_DATA_MEMORY),
	"Shared 1SP data structure not correctly sized.");
_Static_assert ((sizeof (struct manticore_firmware_descriptor) ==
	MANTICORE_FIRMWARE_DESCRIPTOR_STRUCT_SIZE),
	"Firmware descriptor structure not correctly sized.");


/**
 * Flag indicating that SP firmware was booted securely.
 */
#define	MANTICORE_1SP_SECURE_BOOT_FLAG		(1U << 0)

/**
 * Set the secure boot flag for SP firmware.
 */
#define	MANTICORE_1SP_SET_SECURE_BOOT(x)	(x)->boot_properties |= MANTICORE_1SP_SECURE_BOOT_FLAG

/**
 * Clear the secure boot flag for SP firmware.
 */
#define	MANTICORE_1SP_SET_UNSECURE_BOOT(x)	(x)->boot_properties &= ~MANTICORE_1SP_SECURE_BOOT_FLAG

/**
 * Query the shared data from 1SP to determine if the device boot securely.
 */
#define	MANTICORE_1SP_IS_BOOT_SECURE(x)		((x)->boot_properties & MANTICORE_1SP_SECURE_BOOT_FLAG)


#endif	/* MANTICORE_1SP_H_ */
