/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    hsp_fuses.h

Abstract:

    This file was autogenerated using FUSEGEN.EXE.
    Do not modify.

Command Line:

    D:\sources\hsp.devenv\openhsp\build\bin\debug\utils\fusegen.exe
    -f
    D:\sources\hsp.devenv\openhsp\sources\inc\fuselayout.yml
    -fo
    .\sources\inc\port\hsp_fuses.h

--*/

#pragma once

#pragma pack(push,1)

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning( disable: 4201)
#endif

typedef uint32_t HSP_FUSE_LINE;


typedef union _HSP_FUSE_SECURITY_STATE
{
    uint64_t       AsUint64[2];
    HSP_FUSE_LINE  AsUint32[4];

} HSP_FUSE_SECURITY_STATE, *PHSP_FUSE_SECURITY_STATE;


typedef union _HSP_FUSE_AEB_OVERRIDES
{
    HSP_FUSE_LINE  AsUint32[4];

} HSP_FUSE_AEB_OVERRIDES, *PHSP_FUSE_AEB_OVERRIDES;


typedef union _HSP_FUSE_SOC_ID
{
    struct
    {
        uint64_t       Id[2];
        HSP_FUSE_LINE  ReservedEcc;
    };

    HSP_FUSE_LINE  AsUint32[5];

} HSP_FUSE_SOC_ID, *PHSP_FUSE_SOC_ID;


typedef union _HSP_FUSE_ARRAY_KEY_SLOT
{
    struct
    {
        uint64_t  Key[4];
        uint64_t  Attributes   : 24;
        uint64_t  Reserved1    : 40;
        uint64_t  ReservedEcc  : 64;
    };

    HSP_FUSE_LINE  AsUint32[12];

} HSP_FUSE_ARRAY_KEY_SLOT, *PHSP_FUSE_ARRAY_KEY_SLOT;


typedef union _HSP_FUSE_PUB
{
    struct
    {
        uint64_t  Key[4];
        uint64_t  ReservedEcc;
    };

    HSP_FUSE_LINE  AsUint32[10];

} HSP_FUSE_PUB, *PHSP_FUSE_PUB;


typedef union _HSP_FUSE_LINE_AEB_SW_FUSE_OVERRIDE
{
    struct
    {
        HSP_FUSE_LINE  RngHealthCheckEnable   : 2;  // [1:0]
        HSP_FUSE_LINE  RngHealthCheckDisable  : 2;  // [3:2]
        HSP_FUSE_LINE  Reserved4_31           : 28;  // [31:4]
        HSP_FUSE_LINE  Reserved[3];
    };

    struct
    {
        HSP_FUSE_LINE  AebSwFuseOverrides[4];
    };

    HSP_FUSE_LINE  AsUint32[4];

} HSP_FUSE_LINE_AEB_SW_FUSE_OVERRIDE, *PHSP_FUSE_LINE_AEB_SW_FUSE_OVERRIDE;


typedef union _HSP_FUSE_REVOCATION
{
    HSP_FUSE_LINE  Revocation0SP[16];
    uint32_t       AsUint32[16];

} HSP_FUSE_REVOCATION, *PHSP_FUSE_REVOCATION;


typedef union _HSP_FUSES
{
    struct
    {
        HSP_FUSE_SECURITY_STATE             SecurityState;
        HSP_FUSE_AEB_OVERRIDES              AebFuseOverrides;
        HSP_FUSE_SOC_ID                     SocId;
        HSP_FUSE_ARRAY_KEY_SLOT             Key0;
        HSP_FUSE_ARRAY_KEY_SLOT             Key1;
        HSP_FUSE_ARRAY_KEY_SLOT             Key2;
        HSP_FUSE_ARRAY_KEY_SLOT             Key3;
        HSP_FUSE_PUB                        PubX;
        HSP_FUSE_PUB                        PubY;
        HSP_FUSE_LINE_AEB_SW_FUSE_OVERRIDE  SoftwareFuse0;
        HSP_FUSE_LINE_AEB_SW_FUSE_OVERRIDE  SoftwareFuse1;
        HSP_FUSE_REVOCATION                 RevocationFuse;
        HSP_FUSE_LINE                       Reserved[23];
    };

    uint32_t  AsUint32[128];

} HSP_FUSES, *PHSP_FUSES;



static_assert(sizeof(HSP_FUSES) == (128 * 4), "Fuse structure size must not change.");


#define HSP_FUSE_MAJ_DECODE(x, y, z)    (((x) && (y)) || ((x) && (z)) || ((y) && (z)))
#define HSP_FUSE_MAJORITY(x)            HSP_FUSE_MAJ_DECODE((x >> 0) & 1, (x >> 1) & 1, (x >> 2) & 1)


#define HSP_FUSE_LINE_BEGIN(Field) \
    (FIELD_OFFSET(HSP_FUSES, Field) / sizeof(HSP_FUSE_LINE))

#define HSP_FUSE_LINE_END(Field) \
    (RTL_SIZEOF_THROUGH_FIELD(HSP_FUSES, Field) / sizeof(HSP_FUSE_LINE))


//
// Security state deltas.
//

#define HSP_SECURITY_STATE_BLANK_H              0x0000000000000000ULL
#define HSP_SECURITY_STATE_BLANK_L              0x0000000000000000ULL
#define HSP_SECURITY_STATE_TEST_H               0x0341F44300405869ULL
#define HSP_SECURITY_STATE_TEST_L               0x0300A260AC000400ULL
#define HSP_SECURITY_STATE_PRODUCTION_H         0x0341F44300445969ULL
#define HSP_SECURITY_STATE_PRODUCTION_L         0x0300A260AD103400ULL
#define HSP_SECURITY_STATE_SECURE_H             0x4343FC4785747DEBULL
#define HSP_SECURITY_STATE_SECURE_L             0xA310BA61ED1A74A1ULL
#define HSP_SECURITY_STATE_PROTOTYPE_H          0xC7F9F54F80C17F69ULL
#define HSP_SECURITY_STATE_PROTOTYPE_L          0x8394B768BE000CE4ULL
#define HSP_SECURITY_STATE_RETEST_H             0xC7FFFFCF87F57FEFULL
#define HSP_SECURITY_STATE_RETEST_L             0xE396BF79FF9A7CFDULL
#define HSP_SECURITY_STATE_NR_H                 0x3806003070008010ULL
#define HSP_SECURITY_STATE_NR_L                 0x1C69208600658302ULL

#ifdef _MSC_VER
#pragma warning(pop)
#endif

#pragma pack(pop)
