/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Abstract:

    This file was autogenerated using REGGEN.EXE.
    Do not modify.

Command Line:

    D:\sources\athena.hsp\build\bin\debug\utils\reggen.exe
    -r
    D:\sources\athena.hsp\drops\hspregs\hsp_cmd_sw.xml
    -f
    D:\sources\athena.hsp\drops\hspregs\hsp_cmd_sw.yml
    -o
    D:\sources\athena.hsp\sources\inc\hsp_cmd.h

--*/
#pragma once

//
// AES
// Cmd_Code
// Key Length
//
typedef enum _HSP_CMD_AES_CMD_CODE_KEY_LEN
{
    HSP_CMD_AES_CMD_CODE_KEY_LEN_KEY_128 = 1,
    HSP_CMD_AES_CMD_CODE_KEY_LEN_KEY_192 = 2,
    HSP_CMD_AES_CMD_CODE_KEY_LEN_KEY_256 = 3,

} HSP_CMD_AES_CMD_CODE_KEY_LEN;

//
// AES
// Cmd_Code
// Unit size in XTS mode
//
typedef enum _HSP_CMD_AES_CMD_CODE_XTS_SIZE
{
    HSP_CMD_AES_CMD_CODE_XTS_SIZE_LEN_16 = 1,
    HSP_CMD_AES_CMD_CODE_XTS_SIZE_LEN_512 = 2,
    HSP_CMD_AES_CMD_CODE_XTS_SIZE_LEN_1024 = 3,
    HSP_CMD_AES_CMD_CODE_XTS_SIZE_LEN_2048 = 4,
    HSP_CMD_AES_CMD_CODE_XTS_SIZE_LEN_4096 = 5,

} HSP_CMD_AES_CMD_CODE_XTS_SIZE;

//
// AES
// Cmd_Code
// Encrypt/Decript Mode
//
typedef enum _HSP_CMD_AES_CMD_CODE_ED_MODE
{
    HSP_CMD_AES_CMD_CODE_ED_MODE_DECRYPT = 0,
    HSP_CMD_AES_CMD_CODE_ED_MODE_ENCRYPT = 1,

} HSP_CMD_AES_CMD_CODE_ED_MODE;

//
// AES
// Cmd_Code
// Output Message Addressing Mode
//
typedef enum _HSP_CMD_AES_CMD_CODE_MSGOUT_ADDR_MODE
{
    HSP_CMD_AES_CMD_CODE_MSGOUT_ADDR_MODE_INCR = 0,
    HSP_CMD_AES_CMD_CODE_MSGOUT_ADDR_MODE_SG = 1,
    HSP_CMD_AES_CMD_CODE_MSGOUT_ADDR_MODE_FIXED = 2,
    HSP_CMD_AES_CMD_CODE_MSGOUT_ADDR_MODE_RESERVED = 3,

} HSP_CMD_AES_CMD_CODE_MSGOUT_ADDR_MODE;

//
// AES
// Cmd_Code
// Input Message Addressing Mode
//
typedef enum _HSP_CMD_AES_CMD_CODE_MSGIN_ADDR_MODE
{
    HSP_CMD_AES_CMD_CODE_MSGIN_ADDR_MODE_INCR = 0,
    HSP_CMD_AES_CMD_CODE_MSGIN_ADDR_MODE_SG = 1,
    HSP_CMD_AES_CMD_CODE_MSGIN_ADDR_MODE_FIXED = 2,
    HSP_CMD_AES_CMD_CODE_MSGIN_ADDR_MODE_RESERVED = 3,

} HSP_CMD_AES_CMD_CODE_MSGIN_ADDR_MODE;

//
// AES
// Cmd_Code
// Block Cipher Mode
//
typedef enum _HSP_CMD_AES_CMD_CODE_CIPHER_MODE
{
    HSP_CMD_AES_CMD_CODE_CIPHER_MODE_ECB = 1,
    HSP_CMD_AES_CMD_CODE_CIPHER_MODE_CBC = 2,
    HSP_CMD_AES_CMD_CODE_CIPHER_MODE_CTR = 3,
    HSP_CMD_AES_CMD_CODE_CIPHER_MODE_CFB = 4,
    HSP_CMD_AES_CMD_CODE_CIPHER_MODE_OFB = 5,
    HSP_CMD_AES_CMD_CODE_CIPHER_MODE_XTS = 6,

} HSP_CMD_AES_CMD_CODE_CIPHER_MODE;

//
// HSSHA
// Cmd_Code
// Input Message addressing mode. 0: Increment mode, 1-3: Reserved
//
typedef enum _HSP_CMD_HSSHA_CMD_CODE_READ_MESSAGE_MODE
{
    HSP_CMD_HSSHA_CMD_CODE_READ_MESSAGE_MODE_INCR = 0,
    HSP_CMD_HSSHA_CMD_CODE_READ_MESSAGE_MODE_SG = 1,
    HSP_CMD_HSSHA_CMD_CODE_READ_MESSAGE_MODE_FIXED = 2,
    HSP_CMD_HSSHA_CMD_CODE_READ_MESSAGE_MODE_RESERVED = 3,

} HSP_CMD_HSSHA_CMD_CODE_READ_MESSAGE_MODE;

//
// HSSHA
// Cmd_Code
// SHA mode and length
//
typedef enum _HSP_CMD_HSSHA_CMD_CODE_SHA_MODE
{
    HSP_CMD_HSSHA_CMD_CODE_SHA_MODE_SHA_1 = 1,
    HSP_CMD_HSSHA_CMD_CODE_SHA_MODE_SHA_224 = 2,
    HSP_CMD_HSSHA_CMD_CODE_SHA_MODE_SHA_256 = 3,
    HSP_CMD_HSSHA_CMD_CODE_SHA_MODE_SHA_384 = 4,
    HSP_CMD_HSSHA_CMD_CODE_SHA_MODE_SHA_512 = 5,
    HSP_CMD_HSSHA_CMD_CODE_SHA_MODE_SHA_512_224 = 6,
    HSP_CMD_HSSHA_CMD_CODE_SHA_MODE_SHA_512_256 = 7,

} HSP_CMD_HSSHA_CMD_CODE_SHA_MODE;

//
// HSSHA
// Cmd_Code
// Message pass-through addressing mode, determines whether message data is 
// reflected back out, and what addressing mode is used. 0: No pass-through. 
// 1: Increment pass-through. 2-3: Reserved.
//
typedef enum _HSP_CMD_HSSHA_CMD_CODE_PASS_MESSAGE_MODE
{
    HSP_CMD_HSSHA_CMD_CODE_PASS_MESSAGE_MODE_NO_PASS = 0,
    HSP_CMD_HSSHA_CMD_CODE_PASS_MESSAGE_MODE_INCR_PASS = 1,
    HSP_CMD_HSSHA_CMD_CODE_PASS_MESSAGE_MODE_SG_PASS = 2,
    HSP_CMD_HSSHA_CMD_CODE_PASS_MESSAGE_MODE_FIXED_PASS = 3,

} HSP_CMD_HSSHA_CMD_CODE_PASS_MESSAGE_MODE;

//
// PKA
// Cmd_Code_Mod_Mont
// PKA Size Selection
//
typedef enum _HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE
{
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_256 = 0,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_384 = 1,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_1024 = 2,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_2048 = 3,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_3072 = 4,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_4096 = 5,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_192 = 6,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_224 = 7,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE_MOD_MONT_SIZE_521 = 8,

} HSP_CMD_PKA_CMD_CODE_MOD_MONT_SIZE_MODE;

//
// PKA
// Cmd_Code_Mod_Mont
// PKA Operation Selection
//
typedef enum _HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE
{
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_EXP_HL = 0,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_EXP_SMALL_HL = 1,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_EXP = 2,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_EXP_SMALL = 3,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_MUL = 4,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_ADD = 5,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_SUB = 6,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_INV = 7,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_NEG = 8,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MOD_RED = 9,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MONT_REP_OUT = 10,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MONT_REP_IN = 11,
    HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE_MONT_CONST_CALC = 12,

} HSP_CMD_PKA_CMD_CODE_MOD_MONT_OP_MODE;

//
// PKA
// Cmd_Code_Ecc
// PKA Size Selection
//
typedef enum _HSP_CMD_PKA_CMD_CODE_ECC_SIZE_MODE
{
    HSP_CMD_PKA_CMD_CODE_ECC_SIZE_MODE_ECC_SIZE_256 = 0,
    HSP_CMD_PKA_CMD_CODE_ECC_SIZE_MODE_ECC_SIZE_384 = 1,
    HSP_CMD_PKA_CMD_CODE_ECC_SIZE_MODE_ECC_SIZE_192 = 6,
    HSP_CMD_PKA_CMD_CODE_ECC_SIZE_MODE_ECC_SIZE_224 = 7,
    HSP_CMD_PKA_CMD_CODE_ECC_SIZE_MODE_ECC_SIZE_521 = 8,

} HSP_CMD_PKA_CMD_CODE_ECC_SIZE_MODE;

//
// PKA
// Cmd_Code_Ecc
// PKA Operation Selection
//
typedef enum _HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE
{
    HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE_ECC_SIGVER = 0,
    HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE_ECC_SIGGEN = 1,
    HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE_ECC_PT_MULT = 2,
    HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE_ECC_PT_ADD = 3,
    HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE_ECC_PT_NEG = 4,
    HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE_ECC_PT_VAL = 5,
    HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE_ECC_KEY_GEN = 6,

} HSP_CMD_PKA_CMD_CODE_ECC_OP_MODE;

//
// CCS
// Cmd_Code
// Complex command to be run
//
typedef enum _HSP_CMD_CCS_CMD_CODE_CCS_MODE
{
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_SET_KEY = 0,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_GEN_RANDOM_KEY = 1,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_SEND_KEY = 2,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_LOAD_KEY = 3,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_DECRYPT_LEGACY_KEY = 4,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_STORE_KEY = 5,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_SAVE_KEY = 6,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_KDF_KEY = 7,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_KDF_PCR = 8,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_KDF_AS_PCR = 9,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_DERIVE_ECC_PUBLIC = 10,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_ECC_PCR_SIGN = 11,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_ECC_SIGN = 12,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_ECDH_PCR_KEY_EXCHANGE = 13,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_ECDH_KEY_EXCHANGE = 14,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_EXTEND_PCR = 15,
    HSP_CMD_CCS_CMD_CODE_CCS_MODE_BURN_KEY = 16,

} HSP_CMD_CCS_CMD_CODE_CCS_MODE;



//
// HSP AES Command Code and Command Structure format.
//

typedef union _HSP_CMD_AES_CMD_CODE
{
    struct
    {
        volatile uint32_t Key_Len           : 4;
        volatile uint32_t Xts_Size          : 4;
        volatile uint32_t Rsvd_11_8         : 4;
        volatile uint32_t Wiv               : 1;
        volatile uint32_t Rsvd_15_13        : 3;
        volatile uint32_t Ed_Mode           : 1;
        volatile uint32_t Rsvd_19_17        : 3;
        volatile uint32_t Msgout_Addr_Mode  : 2;
        volatile uint32_t Msgin_Addr_Mode   : 2;
        volatile uint32_t Cipher_Mode       : 4;
        volatile uint32_t Id                : 4;
    };

    volatile uint32_t u;

} HSP_CMD_AES_CMD_CODE, *PHSP_CMD_AES_CMD_CODE;
typedef volatile HSP_CMD_AES_CMD_CODE* PVHSP_CMD_AES_CMD_CODE;

typedef union _HSP_CMD_AES_CMD_RSLT
{
    struct
    {
        volatile uint32_t Cmd_Rslt  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_AES_CMD_RSLT, *PHSP_CMD_AES_CMD_RSLT;
typedef volatile HSP_CMD_AES_CMD_RSLT* PVHSP_CMD_AES_CMD_RSLT;

typedef union _HSP_CMD_AES_CMD_BYTE_COUNT
{
    struct
    {
        volatile uint32_t Cmd_Byte_Count  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_AES_CMD_BYTE_COUNT, *PHSP_CMD_AES_CMD_BYTE_COUNT;
typedef volatile HSP_CMD_AES_CMD_BYTE_COUNT* PVHSP_CMD_AES_CMD_BYTE_COUNT;

typedef union _HSP_CMD_AES_CMD_MSG
{
    struct
    {
        volatile uint32_t Cmd_Msg  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_AES_CMD_MSG, *PHSP_CMD_AES_CMD_MSG;
typedef volatile HSP_CMD_AES_CMD_MSG* PVHSP_CMD_AES_CMD_MSG;

typedef union _HSP_CMD_AES_CMD_KEY
{
    struct
    {
        volatile uint32_t Cmd_Key  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_AES_CMD_KEY, *PHSP_CMD_AES_CMD_KEY;
typedef volatile HSP_CMD_AES_CMD_KEY* PVHSP_CMD_AES_CMD_KEY;

typedef union _HSP_CMD_AES_CMD_IV
{
    struct
    {
        volatile uint32_t Cmd_Iv  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_AES_CMD_IV, *PHSP_CMD_AES_CMD_IV;
typedef volatile HSP_CMD_AES_CMD_IV* PVHSP_CMD_AES_CMD_IV;

typedef struct _HSP_CMD_AES
{
    HSP_CMD_AES_CMD_CODE Cmd_Code;
    HSP_CMD_AES_CMD_RSLT Cmd_Rslt;
    HSP_CMD_AES_CMD_BYTE_COUNT Cmd_Byte_Count;
    HSP_CMD_AES_CMD_MSG Cmd_Msg;
    HSP_CMD_AES_CMD_KEY Cmd_Key;
    HSP_CMD_AES_CMD_IV Cmd_Iv;

} HSP_CMD_AES, *PHSP_CMD_AES;
typedef volatile HSP_CMD_AES* PVHSP_CMD_AES;


//
// HSP High Speed SHA Command Code and Command Structure format.
//

typedef union _HSP_CMD_HSSHA_CMD_CODE
{
    struct
    {
        volatile uint32_t Load_Digest        : 1;
        volatile uint32_t Rsvd_7_1           : 7;
        volatile uint32_t Auto_Pad           : 1;
        volatile uint32_t Read_Message_Mode  : 2;
        volatile uint32_t Rsvd_15_11         : 5;
        volatile uint32_t Sha_Mode           : 4;
        volatile uint32_t Endian             : 1;
        volatile uint32_t Check_Digest       : 1;
        volatile uint32_t Pass_Message_Mode  : 2;
        volatile uint32_t Rsvd_27_24         : 4;
        volatile uint32_t Id                 : 4;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_CODE, *PHSP_CMD_HSSHA_CMD_CODE;
typedef volatile HSP_CMD_HSSHA_CMD_CODE* PVHSP_CMD_HSSHA_CMD_CODE;

typedef union _HSP_CMD_HSSHA_CMD_DGST
{
    struct
    {
        volatile uint32_t Cmd_Dgst  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_DGST, *PHSP_CMD_HSSHA_CMD_DGST;
typedef volatile HSP_CMD_HSSHA_CMD_DGST* PVHSP_CMD_HSSHA_CMD_DGST;

typedef union _HSP_CMD_HSSHA_CMD_BYTE_COUNT
{
    struct
    {
        volatile uint32_t Cmd_Byte_Count  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_BYTE_COUNT, *PHSP_CMD_HSSHA_CMD_BYTE_COUNT;
typedef volatile HSP_CMD_HSSHA_CMD_BYTE_COUNT* PVHSP_CMD_HSSHA_CMD_BYTE_COUNT;

typedef union _HSP_CMD_HSSHA_CMD_MSG_BYTES
{
    struct
    {
        volatile uint32_t Cmd_Msg_Bytes  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_MSG_BYTES, *PHSP_CMD_HSSHA_CMD_MSG_BYTES;
typedef volatile HSP_CMD_HSSHA_CMD_MSG_BYTES* PVHSP_CMD_HSSHA_CMD_MSG_BYTES;

typedef union _HSP_CMD_HSSHA_CMD_MSG
{
    struct
    {
        volatile uint32_t Cmd_Msg  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_MSG, *PHSP_CMD_HSSHA_CMD_MSG;
typedef volatile HSP_CMD_HSSHA_CMD_MSG* PVHSP_CMD_HSSHA_CMD_MSG;

typedef union _HSP_CMD_HSSHA_CMD_INIT
{
    struct
    {
        volatile uint32_t Cmd_Init  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_INIT, *PHSP_CMD_HSSHA_CMD_INIT;
typedef volatile HSP_CMD_HSSHA_CMD_INIT* PVHSP_CMD_HSSHA_CMD_INIT;

typedef union _HSP_CMD_HSSHA_CMD_PASS
{
    struct
    {
        volatile uint32_t Cmd_Pass  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_PASS, *PHSP_CMD_HSSHA_CMD_PASS;
typedef volatile HSP_CMD_HSSHA_CMD_PASS* PVHSP_CMD_HSSHA_CMD_PASS;

typedef union _HSP_CMD_HSSHA_CMD_REF
{
    struct
    {
        volatile uint32_t Cmd_Ref  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_HSSHA_CMD_REF, *PHSP_CMD_HSSHA_CMD_REF;
typedef volatile HSP_CMD_HSSHA_CMD_REF* PVHSP_CMD_HSSHA_CMD_REF;

typedef struct _HSP_CMD_HSSHA
{
    HSP_CMD_HSSHA_CMD_CODE Cmd_Code;
    HSP_CMD_HSSHA_CMD_DGST Cmd_Dgst;
    HSP_CMD_HSSHA_CMD_BYTE_COUNT Cmd_Byte_Count;
    HSP_CMD_HSSHA_CMD_MSG_BYTES Cmd_Msg_Bytes;
    HSP_CMD_HSSHA_CMD_MSG Cmd_Msg;
    HSP_CMD_HSSHA_CMD_INIT Cmd_Init;
    HSP_CMD_HSSHA_CMD_PASS Cmd_Pass;
    HSP_CMD_HSSHA_CMD_REF Cmd_Ref;

} HSP_CMD_HSSHA, *PHSP_CMD_HSSHA;
typedef volatile HSP_CMD_HSSHA* PVHSP_CMD_HSSHA;


//
// HSP PKA Command Code and Command Structure format.
//

typedef union _HSP_CMD_PKA_CMD_CODE_MOD_MONT
{
    struct
    {
        volatile uint32_t Size_Mode   : 4;
        volatile uint32_t Rsvd_15_4   : 12;
        volatile uint32_t Op_Mode     : 4;
        volatile uint32_t Rsvd_27_20  : 8;
        volatile uint32_t Id          : 4;
    };

    volatile uint32_t u;

} HSP_CMD_PKA_CMD_CODE_MOD_MONT, *PHSP_CMD_PKA_CMD_CODE_MOD_MONT;
typedef volatile HSP_CMD_PKA_CMD_CODE_MOD_MONT* PVHSP_CMD_PKA_CMD_CODE_MOD_MONT;

typedef union _HSP_CMD_PKA_CMD_CODE_ECC
{
    struct
    {
        volatile uint32_t Size_Mode   : 4;
        volatile uint32_t Rsvd_15_4   : 12;
        volatile uint32_t Op_Mode     : 4;
        volatile uint32_t Rsvd_27_20  : 8;
        volatile uint32_t Id          : 4;
    };

    volatile uint32_t u;

} HSP_CMD_PKA_CMD_CODE_ECC, *PHSP_CMD_PKA_CMD_CODE_ECC;
typedef volatile HSP_CMD_PKA_CMD_CODE_ECC* PVHSP_CMD_PKA_CMD_CODE_ECC;

typedef union _HSP_CMD_PKA_CMD_CODE
{
    HSP_CMD_PKA_CMD_CODE_MOD_MONT Cmd_Code_Mod_Mont;
    HSP_CMD_PKA_CMD_CODE_ECC Cmd_Code_Ecc;

} HSP_CMD_PKA_CMD_CODE, *PHSP_CMD_PKA_CMD_CODE;
typedef volatile HSP_CMD_PKA_CMD_CODE* PVHSP_CMD_PKA_CMD_CODE;

//
// Hspcmd
// PKA
// Pointer to address where PKA will store results of command
//
typedef union _HSP_CMD_PKA_CMD_RSLT
{
    struct
    {
        volatile uint32_t Cmd_Rslt  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_PKA_CMD_RSLT, *PHSP_CMD_PKA_CMD_RSLT;
typedef volatile HSP_CMD_PKA_CMD_RSLT* PVHSP_CMD_PKA_CMD_RSLT;

//
// Hspcmd
// PKA
// arg1 pointer used by PKA command (if applicable)
//
typedef union _HSP_CMD_PKA_CMD_ARG_1
{
    struct
    {
        volatile uint32_t Cmd_Arg_1  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_PKA_CMD_ARG_1, *PHSP_CMD_PKA_CMD_ARG_1;
typedef volatile HSP_CMD_PKA_CMD_ARG_1* PVHSP_CMD_PKA_CMD_ARG_1;

//
// Hspcmd
// PKA
// arg2 pointer used by PKA command (if applicable)
//
typedef union _HSP_CMD_PKA_CMD_ARG_2
{
    struct
    {
        volatile uint32_t Cmd_Arg_2  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_PKA_CMD_ARG_2, *PHSP_CMD_PKA_CMD_ARG_2;
typedef volatile HSP_CMD_PKA_CMD_ARG_2* PVHSP_CMD_PKA_CMD_ARG_2;

//
// Hspcmd
// PKA
// Signature pointer used by PKA command (if applicable)
//
typedef union _HSP_CMD_PKA_CMD_SIG
{
    struct
    {
        volatile uint32_t Cmd_Sig  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_PKA_CMD_SIG, *PHSP_CMD_PKA_CMD_SIG;
typedef volatile HSP_CMD_PKA_CMD_SIG* PVHSP_CMD_PKA_CMD_SIG;

typedef struct _HSP_CMD_PKA
{
    HSP_CMD_PKA_CMD_CODE Cmd_Code;
    HSP_CMD_PKA_CMD_RSLT Cmd_Rslt;
    HSP_CMD_PKA_CMD_ARG_1 Cmd_Arg_1;
    HSP_CMD_PKA_CMD_ARG_2 Cmd_Arg_2;
    HSP_CMD_PKA_CMD_SIG Cmd_Sig;

} HSP_CMD_PKA, *PHSP_CMD_PKA;
typedef volatile HSP_CMD_PKA* PVHSP_CMD_PKA;


//
// HSP CCS Command Code and Command Structure format.
//

typedef union _HSP_CMD_CCS_CMD_CODE
{
    struct
    {
        volatile uint32_t Ccs_Mode   : 5;
        volatile uint32_t Rsvd_27_5  : 23;
        volatile uint32_t Id         : 4;
    };

    volatile uint32_t u;

} HSP_CMD_CCS_CMD_CODE, *PHSP_CMD_CCS_CMD_CODE;
typedef volatile HSP_CMD_CCS_CMD_CODE* PVHSP_CMD_CCS_CMD_CODE;

//
// Hspcmd
// CCS
// First address pointer used by CCS command
//
typedef union _HSP_CMD_CCS_CMD_ADDR_1
{
    struct
    {
        volatile uint32_t Cmd_Addr_1  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_CCS_CMD_ADDR_1, *PHSP_CMD_CCS_CMD_ADDR_1;
typedef volatile HSP_CMD_CCS_CMD_ADDR_1* PVHSP_CMD_CCS_CMD_ADDR_1;

//
// Hspcmd
// CCS
// Second address pointer used by CCS command (if applicable)
//
typedef union _HSP_CMD_CCS_CMD_ADDR_2
{
    struct
    {
        volatile uint32_t Cmd_Addr_2  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_CCS_CMD_ADDR_2, *PHSP_CMD_CCS_CMD_ADDR_2;
typedef volatile HSP_CMD_CCS_CMD_ADDR_2* PVHSP_CMD_CCS_CMD_ADDR_2;

//
// Hspcmd
// CCS
// Third address pointer used by CCS command (if applicable)
//
typedef union _HSP_CMD_CCS_CMD_ADDR_3
{
    struct
    {
        volatile uint32_t Cmd_Addr_3  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_CCS_CMD_ADDR_3, *PHSP_CMD_CCS_CMD_ADDR_3;
typedef volatile HSP_CMD_CCS_CMD_ADDR_3* PVHSP_CMD_CCS_CMD_ADDR_3;

//
// Hspcmd
// CCS
// Fourth address pointer used by CCS command (if applicable)
//
typedef union _HSP_CMD_CCS_CMD_ADDR_4
{
    struct
    {
        volatile uint32_t Cmd_Addr_4  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_CCS_CMD_ADDR_4, *PHSP_CMD_CCS_CMD_ADDR_4;
typedef volatile HSP_CMD_CCS_CMD_ADDR_4* PVHSP_CMD_CCS_CMD_ADDR_4;

//
// Hspcmd
// CCS
// CCS command attributes (if applicable)
//
typedef union _HSP_CMD_CCS_CMD_ATTR
{
    struct
    {
        volatile uint32_t Cmd_Attr  : 32;
    };

    volatile uint32_t u;

} HSP_CMD_CCS_CMD_ATTR, *PHSP_CMD_CCS_CMD_ATTR;
typedef volatile HSP_CMD_CCS_CMD_ATTR* PVHSP_CMD_CCS_CMD_ATTR;

typedef struct _HSP_CMD_CCS
{
    HSP_CMD_CCS_CMD_CODE Cmd_Code;
    HSP_CMD_CCS_CMD_ADDR_1 Cmd_Addr_1;
    HSP_CMD_CCS_CMD_ADDR_2 Cmd_Addr_2;
    HSP_CMD_CCS_CMD_ADDR_3 Cmd_Addr_3;
    HSP_CMD_CCS_CMD_ADDR_4 Cmd_Addr_4;
    HSP_CMD_CCS_CMD_ATTR Cmd_Attr;

} HSP_CMD_CCS, *PHSP_CMD_CCS;
typedef volatile HSP_CMD_CCS* PVHSP_CMD_CCS;
