# Copyright (c) Microsoft Corporation. All rights reserved.

[package]
name = "softaes-tests"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "softaes-tests"
doctest = false
path = "src/softaes_tests.rs"
required-features = ["arm"]

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true
embedded-alloc.workspace = true
mcr-cpu.workspace = true
mcr-registers.workspace = true
mcr-crypto-softaes.workspace = true
mcr-error.workspace = true
mcr-interrupt-controller.workspace = true
mcr-test-harness.workspace = true
mcr-uart.workspace = true

[features]
# This feature is used to filter all these binary targets during normal builds
# (targets must be built with cargo arguments:
#     --target thumbv7em-none-eabihf \
#     --profile=firmware \
#     --features arm
arm = ["mcr-test-harness/arm"]


