// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HS_SHA_H_
#define HS_SHA_H_

#include <stdint.h>
#include "platform_api.h"
#include "crypto/hash.h"
#include "splibs/inc/spcryptotypes.h"
#include "status/msft_module_id.h"
#include "trap/hsp_interrupt_handler.h"


/* Defined in HSP register definition. */
struct Sha_regs;
struct Creg_regs_creg_crypto_group;

/**
 * The command structure to use for issuing HS-SHA commands.  This structure must be stored in HSP
 * shared RAM for HS-SHA to be able to access it and must be allocated at a 32-bit aligned address.
 */
struct hs_sha_command {
	uint32_t command_code;		/**< HS-SHA command to execute. */
	uint32_t digest;			/**< Address for the hash result. */
	uint32_t byte_count;		/**< Total byte count for the entire message. */
	uint32_t message_bytes;		/**< Byte count of the current message chunk. */
	uint32_t message_buff;		/**< Address of the message to hash. */
	uint32_t initial_digest;	/**< Address to a hashing context to resume. */
	uint32_t pass_message_buff;	/**< Address for an output buffer for the input message. */
	uint32_t ref_digest;		/**< Address to a reference digest used for comparison. */
};

/**
 * Memory structure in HSP shared SRAM that is required to be able to execute HS-SHA commands.  This
 * must be 32-bit aligned.
 */
struct hs_sha_cmd_buffer {
	struct hs_sha_command cmd;	/**< The command and arguments passed to the HS-SHA. */
	SP_MSG_512 digest;			/**< Digest buffer for both input and output. */
};


/**
 * Variable context for the HS-SHA driver instance.
 */
struct hs_sha_state {
	platform_mutex lock;		/**< Lock for synchronization. */
	platform_semaphore done;	/**< Semaphore indicating when a HW operation has completed. */
};

/**
 * Driver interface for the HS-SHA hardware block.
 */
struct hs_sha {
	struct hsp_interrupt_handler base;			/**< Base interface for handling HW interrupts. */
	struct hs_sha_state *state;					/**< Variable context for the driver instance. */
	struct Sha_regs *regs;						/**< Register interface to the HS-SHA. */
	struct Creg_regs_creg_crypto_group *irq;	/**< Register interface to HS-SHA interrupts. */
	struct hs_sha_cmd_buffer *buffer;			/**< Memory location for the HS-SHA command structure. */
	uint8_t *msg_buffer;						/**< Input buffer for message data not in shared memory. */
	size_t max_msg;								/**< Size of the shared message buffer. */

	/**
	 * Submit a command to the hardware for execution and block until the hardware has completed the
	 * request.
	 *
	 * @param sha The HS-SHA to use for command execution.
	 * @param error_code Error to return when the the command failure bit is set.
	 *
	 * @return 0 if the command was successfully executed or an error code.
	 */
	int (*execute_command) (const struct hs_sha *sha, int error_code);
};


/**
 * Align a length to the a hash block size.
 */
#define	HS_SHA_BLOCK_ALIGN(len, block)		((len) & ~((block) - 1))


int hs_sha_init_polling (struct hs_sha *sha, struct hs_sha_state *state, struct Sha_regs *regs,
	struct hs_sha_cmd_buffer *cmd_buffer, uint8_t *msg_buffer, size_t buffer_length);
int hs_sha_init_interrupt (struct hs_sha *sha, struct hs_sha_state *state, struct Sha_regs *regs,
	struct Creg_regs_creg_crypto_group *irq_regs, struct hs_sha_cmd_buffer *cmd_buffer,
	uint8_t *msg_buffer, size_t buffer_length);
int hs_sha_init_state (const struct hs_sha *sha);
void hs_sha_release (const struct hs_sha *sha);

int hs_sha_update_digest (const struct hs_sha *sha, const uint8_t *data, size_t length,
	const SP_MSG_512 *current, enum hash_type type, SP_MSG_512 *updated);
int hs_sha_finish_digest (const struct hs_sha *sha, const uint8_t *data, size_t length,
	size_t total_length, const SP_MSG_512 *current, enum hash_type type, uint8_t *digest,
	size_t digest_length);

void hs_sha_mark_as_in_use (const struct hs_sha *sha);
void hs_sha_mark_as_available (const struct hs_sha *sha);


#define	HS_SHA_ERROR(code)		ROT_ERROR (MSFT_MODULE_HS_SHA, code)

/**
 * Error codes that can be generated by the HS-SHA.
 */
enum {
	HS_SHA_INVALID_ARGUMENT = HS_SHA_ERROR (0x00),			/**< Input parameter is null or not valid. */
	HS_SHA_NO_MEMORY = HS_SHA_ERROR (0x01),					/**< Memory allocation failed. */
	HS_SHA_UPDATE_FAILED = HS_SHA_ERROR (0x02),				/**< Failed to update an intermediate digest. */
	HS_SHA_FINISH_FAILED = HS_SHA_ERROR (0x03),				/**< Failed to complete a calculated digest. */
	HS_SHA_INVALID_ADDRESS = HS_SHA_ERROR (0x04),			/**< A buffer is not in HSP shared SRAM. */
	HS_SHA_CMD_NOT_STARTED = HS_SHA_ERROR (0x05),			/**< The HS-SHA did not accept a submitted command. */
	HS_SHA_ADDRESS_NOT_ALIGNED = HS_SHA_ERROR (0x06),		/**< A buffer address is not word aligned. */
	HS_SHA_UNSUPPORTED_HASH_TYPE = HS_SHA_ERROR (0x07),		/**< The hash algorithm is not supported. */
	HS_SHA_DIGEST_BUFFER_TOO_SMALL = HS_SHA_ERROR (0x08),	/**< The digest output buffer is not large enough for the algorithm. */
	HS_SHA_NOT_BLOCK_ALIGNED = HS_SHA_ERROR (0x09),			/**< Data input is not aligned to the hash block size. */
	HS_SHA_SELF_TEST_FAILED = HS_SHA_ERROR (0x0a),			/**< A self-test of the HS-SHA HW failed. */
	HS_SHA_CMD_EXE_TIMEOUT = HS_SHA_ERROR (0x0b),			/**< SHA command execution timeout. */

	/* Error codes >0x80 are reserved for reporting bits from the HW status register. */
};

/**
 * An error has occurred with the hardware block.  The error code represents the status register
 * output.
 */
#define	HS_SHA_HW_ERROR(reg)	HS_SHA_ERROR (0x80 | ((reg & 0x78) >> 3))


#endif	/* HS_SHA_H_ */
