// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_GPIO_H_
#define HSP_GPIO_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "hsp_top.h"
#include "status/msft_module_id.h"
#include "trap/hsp_interrupt_handler.h"


/**
 * Configuration options for the internal PU/PD resistors on the GPIO.
 */
enum hsp_gpio_internal_pull {
	HSP_GPIO_INTERNAL_PULL_NONE,	/**< Don't enable any internal pull up or down. */
	HSP_GPIO_INTERNAL_PULL_UP,		/**< Enable the internal pull up. */
	HSP_GPIO_INTERNAL_PULL_DOWN,	/**< Enable the internal pull down. */
};

/**
 * Bit flags to use for configuring different types of GPIO interrupts.
 */
enum hsp_gpio_irq {
	HSP_GPIO_IRQ_RISING_EDGE = (1U << 0),	/**< Detection of a rising edge on the GPIO input. */
	HSP_GPIO_IRQ_FALLING_EDGE = (1U << 1),	/**< Detection of a falling edge on the GPIO input. */
	HSP_GPIO_IRQ_LEVEL_HIGH = (1U << 2),	/**< Detection of a high signal on the GPIO input. */
	HSP_GPIO_IRQ_LEVEL_LOW = (1U << 3),		/**< Detection of a low signal on the GPIO input. */
};

/**
 * Configuration data for a single GPIO.
 */
struct hsp_gpio_config {
	uint8_t gpio_num;					/**< Identifier of the GPIO. */
	bool is_output;						/**< Flag indicating if the GPIO should drive a value. */
	bool init_value;					/**< Initial value to use for an output GPIO. */
	bool init_value_por;				/**< Alternate initial value to use for an output GPIO on device POR. */
	enum hsp_gpio_internal_pull pull;	/**< Configuration for internal resistor pulls. */
};


/**
 * Driver for handling a single group of HSP GPIOs.
 */
struct hsp_gpio {
	struct hsp_interrupt_handler base;					/**< Single interrupt handler for all GPIOs. */
	struct Creg_regs_gpc_regs *regs;					/**< Register interface to the GPIOs. */
	const struct hsp_interrupt_handler **irq_handler;	/**< Handlers for individual GPIO IRQs. */
	size_t count;										/**< The number of support GPIOs. */
};


int hsp_gpio_init (struct hsp_gpio *gpio, struct Creg_regs_gpc_regs *gpio_regs,
	const struct hsp_interrupt_handler **irq_handler, size_t gpio_count);
int hsp_gpio_init_no_irq_support (struct hsp_gpio *gpio, struct Creg_regs_gpc_regs *gpio_regs,
	size_t gpio_count);
void hsp_gpio_release (const struct hsp_gpio *gpio);

int hsp_gpio_configure (const struct hsp_gpio *gpio, uint8_t gpio_num, bool is_output,
	enum hsp_gpio_internal_pull pull, bool init_value);
int hsp_gpio_configure_multiple (const struct hsp_gpio *gpio, const struct hsp_gpio_config *config,
	size_t count, bool is_por);

int hsp_gpio_read (const struct hsp_gpio *gpio, uint8_t gpio_num);
int hsp_gpio_write (const struct hsp_gpio *gpio, uint8_t gpio_num, bool value);
int hsp_gpio_toggle (const struct hsp_gpio *gpio, uint8_t gpio_num);

int hsp_gpio_enable_interrupt (const struct hsp_gpio *gpio, uint8_t gpio_num, uint8_t irq_type,
	const struct hsp_interrupt_handler *handler);
int hsp_gpio_disable_interrupt (const struct hsp_gpio *gpio, uint8_t gpio_num, uint8_t irq_type);
int hsp_gpio_disable_all_interrupts (const struct hsp_gpio *gpio, uint8_t gpio_num);

int hsp_gpio_get_irq_status (const struct hsp_gpio *gpio, uint8_t gpio_num, uint8_t *irq_type);
int hsp_gpio_get_raw_irq_status (const struct hsp_gpio *gpio, uint8_t gpio_num, uint8_t *irq_type);
int hsp_gpio_clear_irq_status (const struct hsp_gpio *gpio, uint8_t gpio_num, uint8_t irq_type);


#define	HSP_GPIO_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_GPIO, code)

/**
 * Error codes that can be generated by an HSP GPIO.
 */
enum {
	HSP_GPIO_INVALID_ARGUMENT = HSP_GPIO_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_GPIO_NO_MEMORY = HSP_GPIO_ERROR (0x01),			/**< Memory allocation failed. */
	HSP_GPIO_IRQS_UNSUPPORTED = HSP_GPIO_ERROR (0x02),	/**< GPIO IRQs are not supported by the driver. */
	HSP_GPIO_UNKNOWN_GPIO = HSP_GPIO_ERROR (0x03),		/**< The specified GPIO is not supported. */
	HSP_GPIO_NOT_OUTPUT = HSP_GPIO_ERROR (0x04),		/**< Attempted to write to an input GPIO. */
};


#endif	/* HSP_GPIO_H_ */
