// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_RNG_HW_H_
#define HSP_RNG_HW_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "platform_api.h"
#include "drivers/fuse_controller_interface.h"
#include "status/msft_module_id.h"


/**
 * The maximum value for the RNG entropy clock divider.
 */
#define	HSP_RNG_HW_MAX_CLOCK_DIVIDER		0x3ff


struct Rng_regs;	/* Defined in HSP register definition. */

/**
 * Variable context for a RNG driver.
 */
struct hsp_rng_hw_state {
	platform_mutex lock;	/**< Lock for synchronization. */
};

/**
 * Driver interface to the hardware random number generator within the HSP.
 */
struct hsp_rng_hw {
	struct hsp_rng_hw_state *state;					/**< Variable context for the driver instance. */
	struct Rng_regs *regs;							/**< Register interface for the RNG. */
	const struct fuse_controller_interface *fuses;	/**< Interface to the HSP fuses. */
	uint16_t clk_div_min;							/**< The minimum allowed clock divider calibration setting. */
	uint16_t clk_div_max;							/**< The maximum allowed clock divider calibration setting. */
};


int hsp_rng_hw_init (struct hsp_rng_hw *rng, struct hsp_rng_hw_state *state, struct Rng_regs *regs,
	const struct fuse_controller_interface *fuses, uint16_t clk_div_min, uint16_t clk_div_max);
int hsp_rng_hw_init_state (const struct hsp_rng_hw *rng, bool calibrate);
void hsp_rng_hw_release (const struct hsp_rng_hw *rng);

int hsp_rng_hw_get_calibration_data (const struct hsp_rng_hw *rng,
	uint8_t calibration[FUSE_CONTROLLER_RNG_CALIBRATION_LENGTH], bool *data_valid);
int hsp_rng_hw_recalibrate (const struct hsp_rng_hw *rng);

int hsp_rng_hw_get_random_word (const struct hsp_rng_hw *rng, uint32_t *data);
int hsp_rng_hw_get_random_buffer (const struct hsp_rng_hw *rng, uint8_t *data, size_t length);

void hsp_rng_hw_mark_as_in_use (const struct hsp_rng_hw *rng);
void hsp_rng_hw_mark_as_available (const struct hsp_rng_hw *rng);

void hsp_rng_hw_wait_for_reseed (const struct hsp_rng_hw *rng);
void hsp_rng_hw_wait_for_entropy_read_done (const struct hsp_rng_hw *rng);

/* Internal functions for use by derived types. */
int hsp_rng_hw_init_common (struct hsp_rng_hw *rng, struct hsp_rng_hw_state *state,
	struct Rng_regs *regs);
int hsp_rng_hw_init_state_common (const struct hsp_rng_hw *rng);


#define	HSP_RNG_HW_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_RNG_HW, code)

/**
 * Error codes that can be generated by the HSP RNG driver.
 */
enum {
	HSP_RNG_HW_INVALID_ARGUMENT = HSP_RNG_HW_ERROR (0x00),			/**< Input parameter is null or not valid. */
	HSP_RNG_HW_NO_MEMORY = HSP_RNG_HW_ERROR (0x01),					/**< Memory allocation failed. */
	HSP_RNG_HW_SELF_TEST_FAILED = HSP_RNG_HW_ERROR (0x02),			/**< Self-test of the DRBG failed. */
	HSP_RNG_HW_CALIBRATION_NOT_SUPPORTED = HSP_RNG_HW_ERROR (0x03),	/**< RNG calibration not supported. */
	HSP_RNG_HW_SELF_TEST_FAULT = HSP_RNG_HW_ERROR (0x04),			/**< A DRBG fault occurred during a self-test. */
};


#endif	/* HSP_RNG_HW_H_ */
