# ++
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
# Module Name:
#
#	CMakeLists.txt
#
# Abstract:
#
#	CMake script to build Manticore 2SP
#
# --

project(dc-scm-recovery LANGUAGES C ASM)

set(TARGET_IMG dc_scm_recovery)
set(TARGET_NAME ${TARGET_IMG}.elf)

include(Mbedtls)
include(FreeRTOS)

set(RECOVERY_DIR ${CERBERUS_ROOT}/projects/microsoft/hsp/manticore/sp/src/dc_scm/recovery)

# Location to find config files such as FreeRTOSConfig.h
set(FREERTOS_CONFIG_DIR "${RECOVERY_DIR}")

# @@MUST@@ come after setting the FREERTOS_CONFIG_DIR to ensure we pick up app-specific
# config files first.
include(${MANTICORE_SP_DIR}/../cmake/freertos_port.cmake)

# I2C mode is ignored for the recovery image.
unset(I2C_SLAVE_MODE)

add_executable(
	${TARGET_NAME}
	${MBEDTLS_SOURCES}
	${FREERTOS_SOURCES}
	${FREERTOS_PORTABLE_ROOT}/MemMang/heap_4.c
	${CORE_DIR}/asn1/asn1_util.c
	${CORE_DIR}/asn1/base64_core.c
	${CORE_DIR}/asn1/base64_mbedtls.c
	${CORE_DIR}/asn1/base64_thread_safe.c
	${CORE_DIR}/asn1/ecc_der_util.c
	${CORE_DIR}/asn1/x509_cert_build.c
	${CORE_DIR}/asn1/x509_extension_builder.c
	${CORE_DIR}/asn1/dice/tcg_dice_oid.c
	${CORE_DIR}/asn1/dice/x509_extension_builder_dice_tcbinfo.c
	${CORE_DIR}/asn1/dice/x509_extension_builder_dice_ueid.c
	${CORE_DIR}/asn1/x509_mbedtls.c
	${CORE_DIR}/asn1/x509_thread_safe.c
	${CORE_DIR}/attestation/attestation_responder.c
	${CORE_DIR}/attestation/pcr.c
	${CORE_DIR}/attestation/pcr_store.c
	${CORE_DIR}/cmd_interface/authorized_execution_config_reset.c
	${CORE_DIR}/cmd_interface/cerberus_protocol_master_commands.c
	${CORE_DIR}/cmd_interface/cerberus_protocol_optional_commands.c
	${CORE_DIR}/cmd_interface/cerberus_protocol_required_commands.c
	${CORE_DIR}/cmd_interface/cmd_authorization.c
	${CORE_DIR}/cmd_interface/cmd_background_handler.c
	${CORE_DIR}/cmd_interface/cmd_channel.c
	${CORE_DIR}/cmd_interface/cmd_channel_handler.c
	${CORE_DIR}/cmd_interface/cmd_interface.c
	${CORE_DIR}/cmd_interface/cmd_interface_multi_handler.c
	${CORE_DIR}/cmd_interface/config_reset.c
	${CORE_DIR}/cmd_interface/counter_manager_registers.c
	${CORE_DIR}/cmd_interface/device_manager.c
	${CORE_DIR}/cmd_interface/msg_transport.c
	${CORE_DIR}/common/auth_token.c
	${CORE_DIR}/common/authorization_allowed.c
	${CORE_DIR}/common/authorization_challenge.c
	${CORE_DIR}/common/authorization_disallowed.c
	${CORE_DIR}/common/buffer_util.c
	${CORE_DIR}/common/common_math.c
	${CORE_DIR}/common/image_header.c
	${CORE_DIR}/common/observable.c
	${CORE_DIR}/crypto/aes_gcm_mbedtls.c
	${CORE_DIR}/crypto/aes_key_wrap.c
	${CORE_DIR}/crypto/aes_key_wrap_with_padding.c
	${CORE_DIR}/crypto/checksum.c
	${CORE_DIR}/crypto/ecc_ecc_hw.c
	${CORE_DIR}/crypto/ecc_thread_safe.c
	${CORE_DIR}/crypto/ecdsa.c
	${CORE_DIR}/crypto/hash.c
	${CORE_DIR}/crypto/hash_thread_safe.c
	${CORE_DIR}/crypto/hkdf.c
	${CORE_DIR}/crypto/kdf.c
	${CORE_DIR}/crypto/rng_mbedtls.c
	${CORE_DIR}/crypto/rng_thread_safe.c
	${CORE_DIR}/crypto/rsa.c
	${CORE_DIR}/crypto/rsa_mbedtls.c
	${CORE_DIR}/crypto/rsa_thread_safe.c
	${CORE_DIR}/crypto/signature_verification.c
	${CORE_DIR}/crypto/signature_verification_ecc.c
	${CORE_DIR}/crypto/kat/aes_key_wrap_kat.c
	${CORE_DIR}/crypto/kat/aes_key_wrap_kat_vectors.c
	${CORE_DIR}/crypto/kat/hash_kat.c
	${CORE_DIR}/crypto/kat/hash_kat_vectors.c
	${CORE_DIR}/crypto/kat/hmac_kat_vectors.c
	${CORE_DIR}/crypto/kat/kdf_kat.c
	${CORE_DIR}/crypto/kat/kdf_kat_vectors.c
	${CORE_DIR}/fips/cmd_channel_error_state.c
	${CORE_DIR}/firmware/app_context_null.c
	${CORE_DIR}/firmware/firmware_component.c
	${CORE_DIR}/firmware/firmware_header.c
	${CORE_DIR}/firmware/firmware_update.c
	${CORE_DIR}/firmware/firmware_update_handler.c
	${CORE_DIR}/firmware/firmware_update_handler_revoke_after_reset.c
	${CORE_DIR}/firmware/firmware_update_observer_impactful.c
	${CORE_DIR}/firmware/impactful_update.c
	${CORE_DIR}/firmware/impactful_update_handler.c
	${CORE_DIR}/flash/flash_common.c
	${CORE_DIR}/flash/flash_store_contiguous_blocks.c
	${CORE_DIR}/flash/flash_updater.c
	${CORE_DIR}/flash/flash_util.c
	${CORE_DIR}/flash/spi_flash.c
	${CORE_DIR}/flash/spi_flash_sfdp.c
	${CORE_DIR}/host_fw/host_processor_single_full_bypass.c
	${CORE_DIR}/host_fw/host_state_manager.c
	${CORE_DIR}/host_fw/host_state_observer_dirty_reset.c
	${CORE_DIR}/keystore/keystore_flash.c
	${CORE_DIR}/logging/debug_log.c
	${CORE_DIR}/logging/log_flush_handler.c
	${CORE_DIR}/logging/logging_flash.c
	${CORE_DIR}/manifest/manifest_cmd_handler.c
	${CORE_DIR}/manifest/manifest_flash.c
	${CORE_DIR}/manifest/manifest_manager.c
	${CORE_DIR}/manifest/manifest_manager_flash.c
	${CORE_DIR}/manifest/manifest_pcr.c
	${CORE_DIR}/manifest/manifest_verification.c
	${CORE_DIR}/manifest/cfm/cfm_flash.c
	${CORE_DIR}/manifest/cfm/cfm_manager.c
	${CORE_DIR}/manifest/cfm/cfm_manager_flash.c
	${CORE_DIR}/manifest/cfm/cfm_observer_pcr.c
	${CORE_DIR}/manifest/cfm/manifest_cmd_handler_cfm.c
	${CORE_DIR}/manifest/pcd/manifest_cmd_handler_pcd.c
	${CORE_DIR}/manifest/pcd/pcd_flash.c
	${CORE_DIR}/manifest/pcd/pcd_manager.c
	${CORE_DIR}/manifest/pcd/pcd_manager_flash.c
	${CORE_DIR}/manifest/pcd/pcd_observer_pcr.c
	${CORE_DIR}/manifest/pfm/manifest_cmd_handler_pfm.c
	${CORE_DIR}/manifest/pfm/pfm_flash.c
	${CORE_DIR}/manifest/pfm/pfm_manager.c
	${CORE_DIR}/manifest/pfm/pfm_manager_flash.c
	${CORE_DIR}/manifest/pfm/pfm_observer_pcr.c
	${CORE_DIR}/manifest/pfm/pfm_observer_pending_reset.c
	${CORE_DIR}/mctp/cmd_interface_mctp_control.c
	${CORE_DIR}/mctp/cmd_interface_protocol_mctp_msft_vdm.c
	${CORE_DIR}/mctp/cmd_interface_protocol_mctp.c
	${CORE_DIR}/mctp/mctp_base_protocol.c
	${CORE_DIR}/mctp/mctp_control_protocol_commands.c
	${CORE_DIR}/mctp/mctp_interface.c
	${CORE_DIR}/mmio/mmio_register_block.c
	${CORE_DIR}/mmio/mmio_util.c
	${CORE_DIR}/recovery/cmd_interface_recovery.c
	${CORE_DIR}/recovery/recovery_image.c
	${CORE_DIR}/recovery/recovery_image_cmd_handler.c
	${CORE_DIR}/recovery/recovery_image_header.c
	${CORE_DIR}/recovery/recovery_image_manager.c
	${CORE_DIR}/recovery/recovery_image_observer_pcr.c
	${CORE_DIR}/recovery/recovery_image_section_header.c
	${CORE_DIR}/riot/riot_core.c
	${CORE_DIR}/riot/reference/RiotDerDec.c
	${CORE_DIR}/riot/reference/RiotDerEnc.c
	${CORE_DIR}/riot/reference/RiotX509Bldr.c
	${CORE_DIR}/riot/riot_key_manager.c
	${CORE_DIR}/spdm/cmd_interface_spdm.c
	${CORE_DIR}/spdm/cmd_interface_spdm_responder.c
	${CORE_DIR}/spdm/spdm_commands.c
	${CORE_DIR}/spdm/spdm_measurements.c
	${CORE_DIR}/spdm/spdm_measurements_discovery.c
	${CORE_DIR}/spdm/spdm_transcript_manager.c
	${CORE_DIR}/spi_filter/spi_filter_irq_handler.c
	${CORE_DIR}/spi_filter/spi_filter_irq_handler_dirty.c
	${CORE_DIR}/state_manager/state_manager.c
	${CORE_DIR}/state_manager/state_persistence_handler.c
	${CORE_DIR}/system/device_unlock_token.c
	${CORE_DIR}/system/event_task.c
	${CORE_DIR}/system/fatal_error.c
	${CORE_DIR}/system/periodic_task.c
	${CORE_DIR}/system/secure_device_unlock_policy.c
	${CORE_DIR}/system/security_manager.c
	${CORE_DIR}/system/security_policy.c
	${CORE_DIR}/system/system.c
	${CORE_DIR}/system/system_state_manager.c
	${MICROSOFT_DIR}/intrusion/intrusion_manager_msft.c
	${MICROSOFT_DIR}/msft_protocol/cmd_interface_msft.c
	${MICROSOFT_DIR}/msft_protocol/cmd_interface_msft_base.c
	${MICROSOFT_DIR}/msft_protocol/cmd_interface_msft_rot.c
	${MICROSOFT_DIR}/msft_protocol/cmd_interface_protocol_msft.c
	${MICROSOFT_DIR}/msft_protocol/mctp_notifier_msft.c
	${MICROSOFT_DIR}/msft_protocol/mctp_notifier_msft_const_list.c
	${MICROSOFT_DIR}/msft_protocol/msft_base_commands.c
	${MICROSOFT_DIR}/msft_protocol/msft_mctp_protocol.c
	${MICROSOFT_DIR}/msft_protocol/rot_commands.c
	${MICROSOFT_DIR}/msft_protocol/temperature_sensor_cluster.c
	${MICROSOFT_DIR}/riot/dice_oid.c
	${GCC_DIR}/platform_compiler.c
	${CERBERUS_FREERTOS_DIR}/cmd_channel_freertos.c
	${CERBERUS_FREERTOS_DIR}/event_task_freertos.c
	${CERBERUS_FREERTOS_DIR}/periodic_task_freertos.c
	${CERBERUS_FREERTOS_DIR}/platform.c
	${CERBERUS_FREERTOS_DIR}/static_os_tasks.c
	${CERBERUS_FREERTOS_DIR}/system_observer_stack_usage.c
	${HSP_DIR}/common/sram_util.c
	${HSP_DIR}/crypto/aes_ecb_hsp.c
	${HSP_DIR}/crypto/aes_hsp_hw_intf.c
	${HSP_DIR}/crypto/ecc_ccs.c
	${HSP_DIR}/drivers/kat/ccs_ksu_kat.c
	${HSP_DIR}/drivers/kat/ccs_ksu_kat_vectors.c
	${HSP_DIR}/firmware/hsp_fw_1sp.c
	${HSP_DIR}/firmware/hsp_fw_util.c
	${HSP_DIR}/firmware/key_manifest_hsp_firmware.c
	${HSP_DIR}/firmware/key_manifest_hsp_rom.c
	${HSP_DIR}/logging/code_path_integrity.c
	${HSP_DIR}/mmio/mmio_register_block_hsp.c
	${HSP_DIR}/mmio/mmio_register_block_soc.c
	${HSP_DIR}/mpu/hsp_mpu.c
	${HSP_DIR}/mpu/memory_protection_mpu_only.c
	${HSP_DIR}/riot/riot_core_hsp.c
	${HSP_DIR}/spi_filter/macronix_opcodes.c
	${HSP_DIR}/spi_filter/micron_opcodes.c
	${HSP_DIR}/spi_filter/spi_filter_hsp_irq_handler.c
	${HSP_DIR}/spi_filter/winbond_opcodes.c
	${HSP_DIR}/system/security_manager_hsp.c
	${HSP_DIR}/trap/hsp_interrupt_group.c
	${HSP_DIR}/trap/hsp_interrupt_vector.c
	${HSP_HW_DIR}/cmd_interface/cmd_channel_i2c_dw_apb.c
	${HSP_HW_DIR}/cmd_interface/cmd_channel_i2c_dw_apb_multimaster.c
	${HSP_HW_DIR}/cmd_interface/cmd_device_hsp.c
	${HSP_HW_DIR}/crypto/ecc_hw_pka.c
	${HSP_HW_DIR}/crypto/hash_hs_sha.c
	${HSP_HW_DIR}/crypto/hs_sha_multi_update.c
	${HSP_HW_DIR}/crypto/rng_hsp.c
	${HSP_HW_DIR}/drivers/ccs_ksu.c
	${HSP_HW_DIR}/drivers/crypto_hw.c
	${HSP_HW_DIR}/drivers/fuse_controller.c
	${HSP_HW_DIR}/drivers/hs_sha.c
	${HSP_HW_DIR}/drivers/hsp_dmb.c
	${HSP_HW_DIR}/drivers/hsp_aeb.c
	${HSP_HW_DIR}/drivers/hsp_aes.c
	${HSP_HW_DIR}/drivers/hsp_gpio.c
	${HSP_HW_DIR}/drivers/hsp_rng_hw.c
	${HSP_HW_DIR}/drivers/i2c_dw_apb.c
	${HSP_HW_DIR}/drivers/i2c_dw_apb_multimaster.c
	${HSP_HW_DIR}/drivers/spi_dwc_ssi.c
	${HSP_HW_DIR}/drivers/sram.c
	${HSP_HW_DIR}/firmware/hw_rot_hsp_rom.c
	${HSP_HW_DIR}/firmware/hw_rot_hsp_rom_no_fuses.c
	${HSP_HW_DIR}/flash/flash_master_dwc_ssi.c
	${HSP_HW_DIR}/freertos/freertos_utils.c
	${HSP_HW_DIR}/host_fw/host_control_hsp_gpio.c
	${HSP_HW_DIR}/host_fw/host_gpio_irq_event_manager.c
	${HSP_HW_DIR}/host_fw/host_gpio_irq_handler.c
	${HSP_HW_DIR}/host_fw/host_irq_control_hsp_gpio.c
	${HSP_HW_DIR}/mbedtls/mbedtls_port.c
	${HSP_HW_DIR}/spi_filter/spi_filter_hsp.c
	${HSP_HW_DIR}/system/real_time_clock_hsp.c
	${HSP_HW_DIR}/trap/hsp_interrupt.c
	${HSP_HW_DIR}/trap/hsp_trap.c
	${HSP_HW_DIR}/trap/hsp_trap_asm.S
	${HSP_API_DIR}/platform_clock_hsp.c
	${HSP_SDK_SOURCES}
	${MANTICORE_DIR}/firmware/firmware_image_manticore.c
	${MANTICORE_DIR}/firmware/graceful_shutdown.c
	${MANTICORE_DIR}/firmware/manticore_firmware_descriptor.c
	${MANTICORE_DIR}/firmware/manticore_firmware_package.c
	${MANTICORE_DIR}/firmware/manticore_measurements.c
	${MANTICORE_DIR}/logging/logging_collector.c
	${MANTICORE_DIR}/mpu/fence_manticore.c
	${MANTICORE_DIR}/mpu/memory_protection_manticore_sprt.c
	${MANTICORE_DIR}/msft_protocol/cmd_interface_msft_manticore.c
	${MANTICORE_DIR}/msft_protocol/manticore_commands.c
	${MANTICORE_DIR}/system/security_manager_hsp_manticore.c
	${MANTICORE_DIR}/system/security_policy_hsp_manticore.c
	${MANTICORE_PLATFORM_DIR}/system/temperature_sensor_tsen.c
	${MANTICORE_SP_DIR}/traps.c
	${MANTICORE_SP_DIR}/drivers/fuse_controller_manticore_fips.c
	${MANTICORE_SP_DIR}/firmware/hw_rot_firmware_key_manifest.c
	${DC_SCM_DIR}/build_version.c
	${DC_SCM_DIR}/reset_counter_init.c
	${DC_SCM_DIR}/sp_boot.c
	${DC_SCM_DIR}/firmware/firmware_update_observer_sprt.c
	${DC_SCM_DIR}/init/init_attestation.c
	${DC_SCM_DIR}/init/init_crypto.c
	${DC_SCM_DIR}/init/init_firmware.c
	${DC_SCM_DIR}/init/init_flash.c
	${DC_SCM_DIR}/init/init_host.c
	${DC_SCM_DIR}/init/init_i2c.c
	${DC_SCM_DIR}/init/init_i2c_multimaster.c
	${DC_SCM_DIR}/init/init_ipc.c
	${DC_SCM_DIR}/init/init_log.c
	${DC_SCM_DIR}/init/init_log_flush_handlers.c
	${DC_SCM_DIR}/init/init_manifest.c
	${DC_SCM_DIR}/init/init_spdm.c
	${DC_SCM_DIR}/init/init_system.c
	${RECOVERY_DIR}/init_cmd_recovery.c
	${RECOVERY_DIR}/recovery.c
	)

target_include_directories(
	${TARGET_NAME}
	PUBLIC
		${MBEDTLS_INCLUDES}
		${FREERTOS_INCLUDES}
		${CORE_DIR}
		${MICROSOFT_DIR}
		${GCC_DIR}
		${CERBERUS_FREERTOS_DIR}
		${HSP_DIR}
		${HSP_HW_DIR}
		${HSP_API_DIR}
		${HSP_SDK_INCLUDES}
		${MANTICORE_DIR}
		${MANTICORE_PLATFORM_DIR}
		${MANTICORE_SP_DIR}
		${ROM_DIR}
		${DC_SCM_DIR}
		${RECOVERY_DIR}
		${ARM_DIR}
		${RISCV_DIR}
	)

target_compile_definitions(
	${TARGET_NAME}
	PRIVATE
		CMD_ENABLE_DEBUG_LOG
		ECC_ENABLE_ECDH
		ECC_ENABLE_GENERATE_KEY_PAIR
		HASH_ENABLE_SHA1
		FIRMWARE_UPDATE_DISABLE_SELF_RESET
		HASH_ENABLE_SHA384
		HASH_ENABLE_SHA512
		LOGGING_SUPPORT_DEBUG_LOG
		MANTICORE_ENABLE_A0_SUPPORT
		X509_ENABLE_AUTHENTICATION
		X509_ENABLE_CREATE_CERTIFICATES
		MBEDTLS_CONFIG_FILE="${RECOVERY_DIR}/mbedTLS_config.h"
		PLATFORM_CLOCK_API="platform_clock_hsp.h"
		${FREERTOS_COMPILE_DEFS}
		${HW_BUILD_TARGET}
		DEBUG_STACK_USAGE
		MANTICORE_RECOVERY_IMG
	)

target_compile_options(
	${TARGET_NAME}
	PRIVATE
		-Os
		-fstack-protector-all
	)

target_link_options(
	${TARGET_NAME}
	PRIVATE
		-nostartfiles
		-Wl,--script=${CMAKE_CURRENT_LIST_DIR}/${TARGET_IMG}.ld
		-Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/${TARGET_IMG}.map
	)

add_custom_command(
	TARGET
		${TARGET_NAME}
	POST_BUILD
		COMMAND ${CMAKE_OBJCOPY} -O binary ${TARGET_NAME} ${TARGET_IMG}.bin
	BYPRODUCTS
		${TARGET_IMG}.bin
	)

add_custom_command(
	TARGET
		${TARGET_NAME}
	POST_BUILD
		COMMAND ${CMAKE_OBJDUMP} -xdhlSC ${TARGET_NAME} -Mno-aliases > ${TARGET_IMG}.dis
	BYPRODUCTS
		${TARGET_IMG}.dis
	)

add_custom_command(
	TARGET
		${TARGET_NAME}
	POST_BUILD
		COMMAND /usr/bin/objcopy -O verilog --set-section-flags .bss=alloc,load,contents ${TARGET_NAME} ${TARGET_IMG}In.vhx
	BYPRODUCTS
		${TARGET_IMG}In.vhx
	)

add_custom_command(
	TARGET
		${TARGET_NAME}
	POST_BUILD
		COMMAND "${HSP_SDK_UTIL_BIN}/eccgen/eccgen" "-t" "20080000" "-m" "384" "-b" "32"
		"-a" "19" "-f" "1" "-s" "-g" "-o" "${TARGET_IMG}.vhx" "${TARGET_IMG}In.vhx"
	DEPENDS
		${TARGET_IMG}In.vhx
	BYPRODUCTS
		${TARGET_IMG}.vhx
	)
