// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_WATCHDOG_H_
#define HSP_WATCHDOG_H_

#include <stdbool.h>
#include <stdint.h>
#include "mmio/mmio_register_block.h"
#include "status/msft_module_id.h"


/**
 * Implementation of a hardware watchdog using an HSP CREG timer.
 */
struct hsp_watchdog {
	const struct mmio_register_block *creg;	/**< Register interface for a struct Creg_regs mapping.  */
	size_t timer_regs;						/**< CREG offset for the hardware timer registers. */
	size_t fatal_err_regs;					/**< CREG offset for the fatal error registers. */
};


int hsp_watchdog_init (struct hsp_watchdog *watchdog, const struct mmio_register_block *creg,
	size_t timer_offset, size_t fatal_err_offset, uint32_t hsp_clk, uint32_t timeout_us);
int hsp_watchdog_init_timer (const struct hsp_watchdog *watchdog, uint32_t hsp_clk,
	uint32_t timeout_us);
void hsp_watchdog_release (const struct hsp_watchdog *watchdog);

int hsp_watchdog_start (const struct hsp_watchdog *watchdog, bool sticky_en);
int hsp_watchdog_refresh (const struct hsp_watchdog *watchdog);
int hsp_watchdog_stop (const struct hsp_watchdog *watchdog);


#define	HSP_WATCHDOG_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_WATCHDOG, code)

/**
 * Error codes that can be generated by the watchdog.
 */
enum {
	HSP_WATCHDOG_INVALID_ARGUMENT = HSP_WATCHDOG_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_WATCHDOG_NO_MEMORY = HSP_WATCHDOG_ERROR (0x01),			/**< Memory allocation failed. */
	HSP_WATCHDOG_INVALID_TIMEOUT = HSP_WATCHDOG_ERROR (0x02),	/**< The specified timeout cannot be supported by the timer. */
};


#endif	/* HSP_WATCHDOG_H_ */
