// Copyright (c) Microsoft Corporation. All rights reserved.
// This is an auto-generated file. Please do not modify manually.

#ifndef MANTICORE_HSM_LOG_TOKENS_H_
#define MANTICORE_HSM_LOG_TOKENS_H_

// *INDENT-OFF*
const char *manticore_hsm_log_tokens_str [] = {
    [0] = "[mcr_hsm::env] Failed the self test %d",
    [1] = "[mcr_hsm::env] Preop-Self test failed for %d with error %d",
    [2] = "[mcr_hsm::fsm::rsa_unwrap] [rsa_unwrap] Invalid State, state:%d event: %d",
    [3] = "[mcr_hsm::fsm::rsa_unwrap] [rsa_unwrap] Invalid Event, state:%d event: %d",
    [4] = "[mcr_hsm::fsm::rsa_unwrap] [rsa_unwrap] failed due to error: %d.", // Deprecated message
    [5] = "[mcr_hsm::fsm::rsa_unwrap] Timeout!! State: %d Res Op State: %d",
    [6] = "[mcr_hsm::fsm::open_key] [open_key] Invalid State, state:%d event: %d",
    [7] = "[mcr_hsm::fsm::open_key] [open_key] Invalid Event, state:%d event: %d",
    [8] = "[mcr_hsm::fsm::flush_session] [flush_session] Invalid Event, state:%d, event: %d",
    [9] = "[mcr_hsm::fsm::flush_session] [flush_session] begin_close_user_session returned err: %d",
    [10] = "[mcr_hsm::fsm::get_establish_cred_encryption_key] [get_establish_cred_encryption_keys] begin_ecc_pct_validation failed due to %d.", // Deprecated message
    [11] = "[mcr_hsm::fsm::get_establish_cred_encryption_key] [get_establish_cred_encryption_key] on_engine_ready_begin_pct_validation failed due to %d.", // Deprecated message
    [12] = "[mcr_hsm::fsm::get_establish_cred_encryption_key] [get_establish_cred_encryption_key] ECC PCT KeyAgreement Verification failed! Forcing crash for recovery.", // Deprecated message
    [13] = "[mcr_hsm::fsm::get_establish_cred_encryption_key] [get_establish_cred_encryption_key] continue_ecc_pct_validation failed due to %d.", // Deprecated message
    [14] = "[mcr_hsm::fsm::aes_gen_key] [aes_gen_key] Invalid Event, state:%d, event: %d",
    [15] = "[mcr_hsm::fsm::aes_gen_key] [aes_gen_key] begin_aesbulk256_gen_key returned err: %d", // Deprecated message
    [16] = "[mcr_hsm::fsm::attest_key] [attest_key] Invalid State, state:%d, event: %d",
    [17] = "[mcr_hsm::fsm::attest_key] [attest_key] Invalid Event, state:%d, event: %d",
    [18] = "[mcr_hsm::fsm::close_session] [close_session] Invalid Event, state:%d, event: %d",
    [19] = "[mcr_hsm::fsm::close_session] [close_session] begin_close_user_session err: %d",
    [20] = "[mcr_hsm::fsm::hsm_fsm] [hsm_fsm] IO Timed out while in %d",
    [21] = "[mcr_hsm::fsm::hsm_fsm] [hsm_fsm] DMA begin_txn error. (0x%08x) in begin_in_dma",
    [22] = "[mcr_hsm::fsm::hsm_fsm] [hsm_fsm] DMA begin_txn error. (0x%08x) in begin_out_dma",
    [23] = "[mcr_hsm::fsm::hsm_fsm] send_err_cqe: IO channel send error. (0x%08x)",
    [24] = "[mcr_hsm::fsm::hsm_fsm] send_cqe: DMA buffer not found",
    [25] = "[mcr_hsm::fsm::hsm_fsm] send_cqe: IO channel send error. (0x%08x)",
    [26] = "[mcr_hsm::fsm::hsm_fsm] IO channel send error. (0x%08x)",
    [27] = "[mcr_hsm::fsm::establish_credential] [establish_credential] begin_establish_credential err: %d", // Deprecated message
    [28] = "[mcr_hsm::fsm::establish_credential] [establish_credential] on_engine_ready begin_establish_credential err: %d",
    [29] = "[mcr_hsm::fsm::ecc_sign] [ecc_sign] Invalid State, state:%d event: %d",
    [30] = "[mcr_hsm::fsm::ecc_sign] [ecc_sign] Invalid Event, state:%d event: %d",
    [31] = "[mcr_hsm::fsm::test_action] [test_action] Missing negative self test ID",
    [32] = "[mcr_hsm::fsm::test_action] [test_action] Missing pin policy config",
    [33] = "[mcr_hsm::fsm::test_action] Invalid rng failure test id received",
    [34] = "[mcr_hsm::fsm::test_action] [test_action] trigger_crashdump_local: Missing crash info",
    [35] = "[mcr_hsm::fsm::test_action] [test_action] send_crashdump_request: Missing crash info",
    [36] = "[mcr_hsm::fsm::test_action] [test_action] Invalid negative self test ID",
    [37] = "[mcr_hsm::fsm::get_session_encryption_key] [get_session_encryption_keys] on_engine_ready_begin_pct_validation failed due to %d.", // Deprecated message
    [38] = "[mcr_hsm::fsm::get_session_encryption_key] [get_session_encryption_keys] begin_ecc_pct_validation failed due to %d.", // Deprecated message
    [39] = "[mcr_hsm::fsm::get_session_encryption_key] [get_session_encryption_key] ECC PCT KeyAgreement Verification failed! Forcing crash for recovery.", // Deprecated message
    [40] = "[mcr_hsm::fsm::get_session_encryption_key] [get_session_encryption_key] continue_ecc_pct_validation failed due to %d.", // Deprecated message
    [41] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] Invalid State, state:%d, event: %d", // Deprecated message
    [42] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] Invalid Event, state:%d, event: %d", // Deprecated message
    [43] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] on_cmd_complete: No operation to continue. Error: %d", // Deprecated message
    [44] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] begin_ecc_gen_key failed due to %d", // Deprecated message
    [45] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] begin_ecc_pct_validation failed due to %d", // Deprecated message
    [46] = "[mcr_hsm::fsm::ecc_gen_key] ECC PCT %d Verification failed! Forcing crash for recovery.", // Deprecated message
    [47] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] on_cmd_complete end_ecc_pct_validation failed due to %d", // Deprecated message
    [48] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] continue_ecc_pct_validation failed due to %d", // Deprecated message
    [49] = "[mcr_hsm::fsm::der_key_import] [der_key_import] Invalid State, state:%d, event: %d",
    [50] = "[mcr_hsm::fsm::der_key_import] [der_key_import] Invalid Event, state:%d, event: %d",
    [51] = "[mcr_hsm::fsm::der_key_import] [der_key_import] begin_import_der_crt_key returned err: %d", // Deprecated message
    [52] = "[mcr_hsm::fsm::der_key_import] [der_key_import] begin_import_der_aesbulk256_key returned err: %d", // Deprecated message
    [53] = "[mcr_hsm::fsm::rsa_mod_exp] [rsa_mod_exp] Invalid State, state:%d event: %d",
    [54] = "[mcr_hsm::fsm::rsa_mod_exp] [rsa_mod_exp] Invalid Event, state:%d event: %d",
    [55] = "[mcr_hsm::fsm::soft_aes] Soft AES Invalid Response", // Deprecated message
    [56] = "[mcr_hsm::fsm::get_unwrapping_key] [get_unwrapping_key] RSA PCT Unwrap Verification failed! Forcing crash for recovery.", // Deprecated message
    [57] = "[mcr_hsm::fsm::get_unwrapping_key] [get_unwrapping_key] failed due to %d.", // Deprecated message
    [58] = "[mcr_hsm::fsm::get_unwrapping_key] GetUnwrappingKey command timed out. %d",
    [59] = "[mcr_hsm::fsm::ecdh_key_exchange] [ecdh_key_exchange] Invalid State, state:%d event: %d",
    [60] = "[mcr_hsm::fsm::ecdh_key_exchange] [ecdh_key_exchange] Invalid Event, state:%d event: %d",
    [61] = "[mcr_hsm::fsm::change_pin] [change_pin] on_start begin_change_pin err: %d", // Deprecated message
    [62] = "[mcr_hsm::fsm::change_pin] [change_pin] on_engine_ready begin_change_pin err: %d", // Deprecated message
    [63] = "[mcr_hsm::fsm::change_pin] [change_pin] continue_change_pin err: %d", // Deprecated message
    [64] = "[mcr_hsm::fsm::reset_part] begin_delete_aesbulk256_user_keys %d", // Deprecated message
    [65] = "[mcr_hsm::fsm::res_cleanup_fsm] Unexpected: Resource cleanup for an already cleaned up resource %d.",
    [66] = "[mcr_hsm::fsm::res_cleanup_fsm] Unexpected: Resource cleanup completed for resource %d.",
    [67] = "[mcr_hsm::fsm::res_cleanup_fsm] PKA instance %d cleanup error",
    [68] = "[mcr_hsm::fsm::delete_key] [delete_key] Invalid event, state:%d, event: %d",
    [69] = "[mcr_hsm::fsm::delete_key] [delete_key], begin_delete_aesbulk256_key returned err: %d",
    [70] = "[mcr_hsm::fsm::open_session] [open_session] on_start: begin_open_session err: %d", // Deprecated message
    [71] = "[mcr_hsm::fsm::open_session] [open_session] on_engine_ready: begin_open_session err: %d",
    [72] = "[mcr_hsm::partition::part] [part] delete_session_keys: failed to delete key key_id=%d, Error: %d",
    [73] = "[mcr_hsm::partition::part] [part] Failed to send IPC message to FP: %d", // Deprecated message
    [74] = "[mcr_hsm::partition::part] [part] Failed to decode IPC message header: %d",
    [75] = "[mcr_hsm::partition::part] [part] Invalid IPC response with status %d",
    [76] = "[mcr_hsm::partition::part] [part] Spurious Message",
    [77] = "[mcr_hsm::partition::part] Establish cred key deletion failed %d. Ignoring error.",
    [78] = "[mcr_hsm::partition::session::app_sess::ecc] [ecc] ECC PCT Sign/Verify failed. Reporting failure to FSM.", // Deprecated message
    [79] = "[mcr_hsm::partition::session::app_sess::ecc] [ecc] ECC Verify operation failed: %d. Stopping validation.", // Deprecated message
    [80] = "[mcr_hsm::partition::session::app_sess::ecc] [ecc] Missing first shared secret for ECDH verification!", // Deprecated message
    [81] = "[mcr_hsm::partition::session::app_sess::ecc] [ecc] ECC PCT Key Agreement failed. Reporting failure to FSM.", // Deprecated message
    [82] = "[mcr_hsm::partition::session::app_sess::ecc] [ecc] ECC structural validation Public key length mismatch",
    [83] = "[mcr_hsm::partition::session::app_sess::ecc] [ecc] ECC structural validation Public key mismatch",
    [84] = "[mcr_hsm::partition::session::app_sess::ecc] [ecc] ECC structural validation Private key length mismatch",
    [85] = "[mcr_hsm::partition::session::app_sess::ecc] ECC structural validation Scalar d is not in the range 0 < d < n",
    [86] = "[mcr_hsm::partition::session::app_sess::mod] send_crashdump_request: Failed to send IPC message to Admin: %d",
    [87] = "[mcr_hsm::partition::session::app_sess::mod] [mod] Failed to send IPC message to FP: %d",
    [88] = "[mcr_hsm::partition::session::app_sess::mod] Invalid core id",
    [89] = "[mcr_hsm::partition::session::app_sess::mod] begin_neg_self_test_req: Failed to send IPC message to Admin: %d",
    [90] = "[mcr_hsm::partition::session::app_sess::mod] [mod] Failed to decode IPC message header: %d",
    [91] = "[mcr_hsm::partition::session::app_sess::mod] Negative self test failed with status: %d",
    [92] = "[mcr_hsm::partition::session::app_sess::aes] [aes] begin_import_der_aesbulk256_key_inner: Failed to send IPC message to FP: %d",
    [93] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_import_der_aesbulk256_key_inner: Failed to decode IPC message header: %d",
    [94] = "[mcr_hsm::partition::session::app_sess::aes] [aes] Import der key: Invalid IPC response with status %d",
    [95] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_import_der_aesbulk256_key_inner: Spurious Message",
    [96] = "[mcr_hsm::partition::session::app_sess::aes] [aes] begin_delete_aesbulk256_key_inner: Failed to send IPC message to FP: %d",
    [97] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_delete_aesbulk256_key_inner: Failed to decode IPC message header: %d",
    [98] = "[mcr_hsm::partition::session::app_sess::aes] [aes] Delete Key Operation: Invalid IPC response with status %d",
    [99] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_delete_aesbulk256_key_inner: Spurious Message",
    [100] = "[mcr_hsm::partition::session::app_sess::aes] [aes] begin_delete_aesbulk256_user_keys_inner: Failed to send IPC message to FP: %d", // Deprecated message
    [101] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_delete_aesbulk256_user_keys_inner: Failed to decode IPC message header: %d", // Deprecated message
    [102] = "[mcr_hsm::partition::session::app_sess::aes] [aes] Delete All keys: Invalid IPC response with status %d", // Deprecated message
    [103] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_delete_aesbulk256_user_keys_inner: Spurious Message", // Deprecated message
    [104] = "[mcr_hsm::partition::session::app_sess::aes] [aes] begin_rollback_aesbulk256_key_inner: Failed to send IPC message to FP: %d",
    [105] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_rollback_aesbulk256_key_inner: Failed to decode IPC message header: %d",
    [106] = "[mcr_hsm::partition::session::app_sess::aes] [aes] Delete key operation rollback: Invalid IPC response with status %d",
    [107] = "[mcr_hsm::partition::session::app_sess::aes] [aes] end_rollback_aesbulk256_key_inner: Spurious Message",
    [108] = "[mcr_hsm::self_test_handler] [rsa2k_mod] Failed to send self test response",
    [109] = "[mcr_hsm::self_test_handler] [rsa2k_crt] Failed to send self test response",
    [110] = "[mcr_hsm::self_test_handler] [ecdsa_engine] Failed to send self test response",
    [111] = "[mcr_hsm::self_test_handler] [ecdh_engine] Failed to send self test response",
    [112] = "[mcr_hsm::self_test_handler] [rng] Failed to send self test response",
    [113] = "[mcr_hsm::self_test_handler] Failed to send self test response",
    [114] = "[mcr_hsm] Starting HSM event loop...",
    [115] = "[mcr_hsm::handler] on_request_ready: spurious event",
    [116] = "[mcr_hsm::handler] on_response_complete: spurious event",
    [117] = "[mcr_hsm::handler] on_dma_complete: spurious event",
    [118] = "[mcr_hsm::handler] Failed to send FLR complete event",
    [119] = "[mcr_hsm::handler] on_flr: spurious event",
    [120] = "[mcr_hsm::handler] Invalid Header found in IPC message",
    [121] = "[mcr_hsm::handler] Invalid PcieFunction enable/disable message",
    [122] = "[mcr_hsm::handler] Invalid Set Resource message %d",
    [123] = "[mcr_hsm::handler] Invalid IPC Create Delete Submission Queue Message %d",
    [124] = "[mcr_hsm::handler] %d not Enabled",
    [125] = "[mcr_hsm::handler] Invalid Shutdown for reset request message",
    [126] = "[mcr_hsm::handler] iDFU Fault Injected: idfu_fault_pre_reset_hsm_shutdown_ipc_no_resp_err",
    [127] = "[mcr_hsm::handler] Failed to send prepare shutdown response to Admin core %d",
    [128] = "[mcr_hsm::handler] Schedule is busy in draining IOs",
    [129] = "[mcr_hsm::handler] iDFU Fault Injected: idfu_fault_pre_reset_hsm_shutdown_ipc_resp_err",
    [130] = "[mcr_hsm::handler] iDFU Fault Injected: idfu_fault_pre_reset_hsm_drain_timeout",
    [131] = "[mcr_hsm::handler] Invalid IPC message header %d",
    [132] = "[mcr_hsm::handler] Unhandled message with opcode 0x%X",
    [133] = "[mcr_hsm::handler] Failed to send response to Admin core %d",
    [134] = "[mcr_hsm::handler] on_pka: spurious event. Index: %d",
    [135] = "[mcr_hsm::handler] on_fp_ipc_response: spurious event",
    [136] = "[mcr_hsm::handler] on_hsp_ipc_response: spurious event",
    [137] = "[mcr_hsm::handler] on_admin_ipc_response: spurious event",
    [138] = "[mcr_hsm::handler] on_aes_unwrap_resp: spurious event",
    [139] = "[mcr_hsm::handler] Failed to receive self test request",
    [140] = "[app::exception_handlers] RNG Hardware error received. Fault code: %d",
    [141] = "[mcr_hsm::fsm::ecc_gen_key] on_cmd_complete: No operation to continue failed due to HsmErr::InvalidState.", // Deprecated message
    [142] = "[mcr_hsm::fsm::ecc_gen_key] begin_ecc_gen_key failed due to %d.", // Deprecated message
    [143] = "[mcr_hsm::fsm::ecc_gen_key] begin_ecc_pct_validation failed due to %d.", // Deprecated message
    [144] = "[mcr_hsm::fsm::ecc_gen_key] end_ecc_pct_validation failed due to %d.", // Deprecated message
    [145] = "[mcr_hsm::fsm::ecc_gen_key] continue_ecc_pct_validation failed due to %d.", // Deprecated message
    [146] = "[mcr_hsm::fsm::rsa_unwrap] [op_state: %d] failed due to %d.", // Deprecated message
    [147] = "[mcr_hsm::env] PCT Validation Failure: %d. System Reset Required! ",
    [148] = "[mcr_hsm::fsm::ecc_gen_key] [ecc_gen_key] [op state: %d] PCT Validation Error: %d.",
    [149] = "[mcr_hsm::fsm::get_establish_cred_encryption_key] [get_establish_cred_encryption_key] [op state: %d] PCT Validation Error: %d.",
    [150] = "[mcr_hsm::fsm::get_session_encryption_key] [get_session_encryption_key] [op state: %d] PCT Validation Error: %d.",
    [151] = "[app::exception_handlers] DTCM error received. Fault code: %d",
    [152] = "[mcr_hsm::fsm::part_init] [part_init] Unexpected event %d ",
    [153] = "[mcr_hsm::fsm::part_init] [part_init] Gen ID phase - expect to find UPKA engine on res ready",
    [154] = "[mcr_hsm::fsm::part_init] [part_init] Failed begin part id generation %d",
    [155] = "[mcr_hsm::fsm::part_init] [part_init] No context available for ending partition identifier generation.",
    [156] = "[mcr_hsm::fsm::part_init] [part_init] Failed end part id generation: %d", // Deprecated message
    [157] = "[mcr_hsm::handler] Failed to allocate partition init FSM",
    [158] = "[mcr_hsm::partition::part] [part] Failed to send IPC message to FP: %d",
    [159] = "[mcr_hsm::fsm::unmask_key] [unmask_key] Invalid Event, state:%d, event: %d",
    [160] = "[mcr_hsm::handler] Invalid Header found for fp to hsm IPC message",
    [161] = "[mcr_hsm::handler] Correctable ECC errors have exceeded threshold, Key vault memory reloaded",
    [162] = "[mcr_hsm::handler] Failed to send response to FP core %d",
    [163] = "[mcr_hsm::handler] Invalid op code found in IPC message",
    [164] = "[app::exception_handlers] ITCM error received. Fault code: %d",
    [165] = "[mcr_hsm::fsm::part_init] [part_init] Failed Continue part id generation: %d",
    [166] = "[mcr_hsm::fsm::part_init] [part_init] Failed begin PCT validation: %d",
    [167] = "[mcr_hsm::fsm::part_init] [part_init] Failed PCT final validation",
    [168] = "[mcr_hsm::fsm::part_init] [part_init] Failed end PCT validation: %d",
    [169] = "[mcr_hsm::fsm::part_init] [part_init] Failed continue PCT validation: %d",
    [170] = "[mcr_hsm::handler] Failed to get CDMA vault key entry",
    [171] = "[mcr_hsm::main] Failed to configure stack guard: invalid stack limit",
    [172] = "[mcr_hsm::partition::session::app_sess::mod] send_stack_validation_request: Failed to send IPC message to Admin: %d",
    [173] = "[mcr_hsm::partition::session::app_sess::mod] Invalid core id for stack validation",
    [174] = "[app::exception_handlers] Memory management fault received. CFSR=0x%x, MMFAR=0x%x",
};

#endif // MANTICORE_HSM_LOG_TOKENS_H_
// *INDENT-ON*
