// Copyright (c) Microsoft Corporation. All rights reserved.
// This is an auto-generated file. Please do not modify manually.

#ifndef MANTICORE_ADMIN_LOG_TOKENS_H_
#define MANTICORE_ADMIN_LOG_TOKENS_H_

// *INDENT-OFF*
const char *manticore_admin_log_tokens_str [] = {
    [0] = "[mcr_admin::preop_cdma_io] IPC response status: 0x%x",
    [1] = "[mcr_admin::main] Starting Admin event loop...",
    [2] = "[mcr_admin::main] Failed to configure stack guard: invalid stack limit",
    [3] = "[mcr_admin::fsm::telemetry] Telemetry FSM received unexpected event. Event: %d",
    [4] = "[mcr_admin::fsm::telemetry] Error running telemetry PCIe monitor, code 0x%x",
    [5] = "[mcr_admin::fsm::telemetry] Telemetry PCIe monitor is running normally. Link Speed: %d, Link Width: x%d",
    [6] = "[mcr_admin::fsm::telemetry] Unexpected PCIe Link. Link Speed: %d, Link Width: %d",
    [7] = "[mcr_admin::fsm::telemetry] Telemetry PCIe monitor not able to start, code 0x%x",
    [8] = "[mcr_admin::fsm::cast] Received timer event while waiting for cast resource",
    [9] = "[mcr_admin::fsm::cast] Invalid event. state: %d",
    [10] = "[mcr_admin::fsm::cast] on_fp_to_admin_channel_ready: Invalid state %d",
    [11] = "[mcr_admin::fsm::cast] on_fp_to_admin_ipc_response: Invalid state %d",
    [12] = "[mcr_admin::fsm::admin_fsm] Invalid state transition. Current state = %d",
    [13] = "[mcr_admin::fsm::vf_stop] VF Stop for PCIe function: %d",
    [14] = "[mcr_admin::fsm::vf_stop] [Vf_Stop] Unsupported event, expected StartCmd",
    [15] = "[mcr_admin::fsm::idfu] Late IPC_HSM_SHUTDOWN_RSP after %dus",
    [16] = "[mcr_admin::fsm::idfu] Late IPC_FP_SHUTDOWN_RSP after %dus",
    [17] = "[mcr_admin::fsm::idfu] Late resource %d acquire %dus",
    [18] = "[mcr_admin::fsm::idfu] Starting",
    [19] = "[mcr_admin::fsm::idfu] Stopped after %dus",
    [20] = "[mcr_admin::fsm::idfu] Admin abort with status: %d. State: (%d)",
    [21] = "[mcr_admin::fsm::idfu] HSM abort with status: %d. State: (%d)",
    [22] = "[mcr_admin::fsm::idfu] FP abort with status: %d. State: (%d)",
    [23] = "[mcr_admin::fsm::idfu] error_dfu: IPC_SP_SHUTDOWN_RSP %d",
    [24] = "[mcr_admin::fsm::idfu] Timeout in state %d resources: 0x%x",
    [25] = "[mcr_admin::fsm::idfu] handle_dfu_started: IPC_SP_SHUTDOWN_RSP %d",
    [26] = "[mcr_admin::fsm::idfu] Insufficient time to drain CP HSM/FP.",
    [27] = "[mcr_admin::fsm::idfu] IPC_CP_HSM_SHUTDOWN_REQ 0x%x",
    [28] = "[mcr_admin::fsm::idfu] IPC_FP_SHUTDOWN_REQ 0x%x",
    [29] = "[mcr_admin::fsm::idfu] Ready in %d us",
    [30] = "[mcr_admin::fsm::idfu] iDFU Abort with OperationTimeout: Failure sending IPC_SP_SHUTDOWN_RSP 0x%x",
    [31] = "[mcr_admin::fsm::idfu] iDFU Abort with OperationFailed: Failure sending IPC_SP_SHUTDOWN_RSP 0x%x",
    [32] = "[mcr_admin::fsm::idfu] IPC_SP_SHUTDOWN_RSP 0x%x",
    [33] = "[mcr_admin::fsm::idfu] No reset detected.",
    [34] = "[mcr_admin::fsm::idfu] Spurious IPC_CP_HSM_SHUTDOWN_RSP after %dus",
    [35] = "[mcr_admin::fsm::idfu] Spurious IPC_FP_SHUTDOWN_RSP after %dus",
    [36] = "[mcr_admin::fsm::cntrl] Failed to receive IPC message from HSM",
    [37] = "[mcr_admin::fsm::cntrl] Failed to decode IPC message from HSM",
    [38] = "[mcr_admin::fsm::cntrl] Failed to receive IPC message from FP",
    [39] = "[mcr_admin::fsm::cntrl] Failed to decode IPC message from FP",
    [40] = "[mcr_admin::fsm::cntrl] Fail to receive queue_delete_notification",
    [41] = "[mcr_admin::fsm::cntrl] Mismatch tags: received (%d) vs expected (%d)",
    [42] = "[mcr_admin::fsm::cntrl] Received deferred action for a different controller: %d",
    [43] = "[mcr_admin::fsm::cntrl] Error in enabling controller %d",
    [44] = "[mcr_admin::fsm::cntrl] [cntrl] Failed to send IPC message to FP: %d",
    [45] = "[mcr_admin::fsm::cntrl] [cntrl] Failed to send IPC message to HSM: %d",
    [46] = "[mcr_admin::fsm::delete_sq] [delete_sq] Invalid SQE: %d",
    [47] = "[mcr_admin::fsm::delete_sq] Get device Sq Failed %d",
    [48] = "[mcr_admin::fsm::delete_sq] Process HSM IPC failed %d",
    [49] = "[mcr_admin::fsm::delete_sq] [delete_sq] Delete device queue on_hsm_ipc_response: Delete submission queue failed %d",
    [50] = "[mcr_admin::fsm::delete_sq] Process FP IPC failed %d",
    [51] = "[mcr_admin::fsm::delete_sq] [delete_sq] Delete device queue on_fp_ipc_response: Delete submission queue failed %d",
    [52] = "[mcr_admin::fsm::delete_sq] [delete_sq] on_deferred_queue_deletion: Delete submission queue failed %d",
    [53] = "[mcr_admin::fsm::delete_sq] Failed to send FP IPC request %d",
    [54] = "[mcr_admin::fsm::delete_sq] Failed to send HSM IPC request %d",
    [55] = "[mcr_admin::fsm::vflr] Complete VFLR for %d",
    [56] = "[mcr_admin::fsm::vflr] [vflr] Failed to send IPC message to FP: %d",
    [57] = "[mcr_admin::fsm::vflr] [vflr] Failed to send IPC message to HSM: %d",
    [58] = "[mcr_admin::fsm::vf_prep] VF Prepare for PCIe function: %d",
    [59] = "[mcr_admin::fsm::vf_prep] [Vf Prepare] Unsupported event",
    [60] = "[mcr_admin::fsm::tdisp_int] [tdisp_int] TdispIntFsm timer elapsed, state: %d",
    [61] = "[mcr_admin::fsm::tdisp_int] [tdisp_int] Invalid interrupt source, source_mask: %d",
    [62] = "[mcr_admin::fsm::tdisp_int] [tdisp_int] Failed to send IPC message to HSP: %d",
    [63] = "[mcr_admin::fsm::tdisp_int] [tdisp_int] Failed to decode IPC message: %d",
    [64] = "[mcr_admin::fsm::tdisp_int] [tdisp_int] Invalid IPC response with status %d",
    [65] = "[mcr_admin::fsm::tdisp_int] [tdisp_int] Spurious Message",
    [66] = "[mcr_admin::fsm::vf_restore] VF Restore for PCIe function: %d",
    [67] = "[mcr_admin::fsm::vf_restore] [Vf Restore] Unsupported event",
    [68] = "[mcr_admin::fsm::vf_save] VF Save for PCIe function: %d",
    [69] = "[mcr_admin::fsm::vf_save] [Vf Save] Unsupported event",
    [70] = "[mcr_admin::fsm::vf_start] VF Start for PCIe function: %d",
    [71] = "[mcr_admin::fsm::vf_start] [Vf_Start] Unsupported event, expected StartCmd",
    [72] = "[mcr_admin::fsm::get_features] [get_features] Invalid SQE: %d",
    [73] = "[mcr_admin::fsm::get_res] [get_res] Invalid SQE: %d",
    [74] = "[mcr_admin::fsm::stop_interface] [stop_interface] Timer elapsed, state: %d",
    [75] = "[mcr_admin::fsm::stop_interface] [stop_interface] Failed to receive notification from queue",
    [76] = "[mcr_admin::fsm::stop_interface] [stop_interface] Message tag %d is not expected %d",
    [77] = "[mcr_admin::fsm::stop_interface] [stop_interface] Failed to send IPC message to FP: %d",
    [78] = "[mcr_admin::fsm::stop_interface] [stop_interface] Failed to send IPC message to HSM: %d",
    [79] = "[mcr_admin::fsm::stop_interface] [stop_interface] Failed to send response to HSP: %d",
    [80] = "[mcr_admin::fsm::doe] [doe] on_rx_ready Failed to recv DOE message: %d",
    [81] = "[mcr_admin::fsm::doe] [doe] on_doe_go: Failed to recv DOE message: %d",
    [82] = "[mcr_admin::fsm::doe] Failed to end recv DOE message: %d",
    [83] = "[mcr_admin::fsm::doe] Failed to decode IPC message: %d",
    [84] = "[mcr_admin::fsm::doe] [doe] Invalid IPC response with status %d",
    [85] = "[mcr_admin::fsm::doe] [doe] Spurious Message",
    [86] = "[mcr_admin::fsm::doe] [doe] on_ipc_response: Failed to send DOE message: %d",
    [87] = "[mcr_admin::fsm::doe] [doe] on_tx_ready: Failed to send DOE message: %d",
    [88] = "[mcr_admin::fsm::doe] Failed to send IPC message to HSP: %d",
    [89] = "[mcr_admin::fsm::pcie] PCIE_PERST_UP Error: 0x%08x",
    [90] = "[mcr_admin::fsm::pcie] PF FLR complete",
    [91] = "[mcr_admin::fsm::pcie] Perst Down complete",
    [92] = "[mcr_admin::fsm::set_res] [set_res] Invalid SQE: %d",
    [93] = "[mcr_admin::fsm::set_res] Failed to set resource count: %d",
    [94] = "[mcr_admin::fsm::set_res] [set_res] Invalid IPC response with status %d",
    [95] = "[mcr_admin::fsm::aes_gcm_ext] Statemachine error %d",
    [96] = "[mcr_admin::fsm::aes_gcm_ext] AES-GCM Decrypt Tag Mismatch",
    [97] = "[mcr_admin::fsm::aes_gcm_ext] Failed to send AES GCM response entry to response queue",
    [98] = "[mcr_admin::fsm::aes_gcm_ext] Invalid state transition in AesGcmExtFsm. Current state = %d",
    [99] = "[mcr_admin::fsm::delete_cq] [delete_cq] Invalid SQE: %d",
    [100] = "[mcr_admin::fsm::delete_cq] Delete Cq Failed %d",
    [101] = "[mcr_admin::fsm::set_features] [set_features] Invalid SQE: %d",
    [102] = "[mcr_admin::env] Failed the self test %d",
    [103] = "[mcr_admin::env] Preop-Self test failed for %d with error %d",
    [104] = "[mcr_admin::handler] Invalid IPC message header",
    [105] = "[mcr_admin::handler] Cannot decode opcode. Invalid IPC message opcode",
    [106] = "[mcr_admin::handler] Opcode does not match. Invalid IPC message opcode",
    [107] = "[mcr_admin::handler] Invalid IPC message",
    [108] = "[mcr_admin::handler] Invalid IPC message for TriggerStackValidation",
    [109] = "[mcr_admin::handler] Invalid stack error type",
    [110] = "[mcr_admin::handler] Invalid IPC message for Negative self test.",
    [111] = "[mcr_admin::handler] Invalid test ID in negative self test IPC payload.",
    [112] = "[mcr_admin::handler] Invalid Header found in IPC message",
    [113] = "[mcr_admin::handler] Invalid Shutdown for reset request message",
    [114] = "[mcr_admin::handler] handle_invalid_message_opcode: Invalid IPC message header %d",
    [115] = "[mcr_admin::handler] Unhandled message with opcode 0x%X",
    [116] = "[mcr_admin::handler] Failed to send response to HSP core %d",
    [117] = "[mcr_admin::handler] send_hsm_ipc_response: Invalid IPC message header %d",
    [118] = "[mcr_admin::handler] Failed to send response to hsm core %d",
    [119] = "[app::exception_handlers] Memory management fault received. CFSR=0x%x, MMFAR=0x%x",
    [120] = "[app::exception_handlers] DTCM error received. Fault code: %d",
    [121] = "[app::exception_handlers] ITCM error received. Fault code: %d",
    [122] = "[app::exception_handlers] GDMA Data Structure Error. Fault code: %d",
    [123] = "[app::exception_handlers] GDMA Data Access Error. Fault code: %d",
    [124] = "[app::exception_handlers] GDMA Delivery Queue Error. Fault code: %d",
    [125] = "[app::exception_handlers] GDMA Completion Queue Error. Fault code: %d",
};

#endif // MANTICORE_ADMIN_LOG_TOKENS_H_
// *INDENT-ON*
