// SPDX-License-Identifier: MIT
// Copyright (c) 2021-2026 Marvell

#ifndef FP3CORE_LDSCRIPTS_M7MEMMAP_H_
#define FP3CORE_LDSCRIPTS_M7MEMMAP_H_


#define CM7_BOOT_FROM     0x0
#define CM7_EXEC_FROM     0x0

/**
 * IRAM
 */
#define FPS_CPU0_IRAM_START        0x0
#define FPS_CPU1_IRAM_START        0x0
#define FPS_CPU2_IRAM_START        0x0
#define FPS_CPU0_IRAM_SIZE         0x8000     // 32K
#define FPS_CPU1_IRAM_SIZE         0x8000     // 32K
#define FPS_CPU2_IRAM_SIZE         0x8000     // 32K
#define FPS_CPU0_IRAM_END   FPS_CPU0_IRAM_START + FPS_CPU0_IRAM_SIZE
#define FPS_CPU1_IRAM_END   FPS_CPU1_IRAM_START + FPS_CPU1_IRAM_SIZE
#define FPS_CPU2_IRAM_END   FPS_CPU2_IRAM_START + FPS_CPU2_IRAM_SIZE
/**
 * DTCM
 */
#define FPS_CPU0_DTCM_START       0x20000000
#define FPS_CPU1_DTCM_START       0x20000000
#define FPS_CPU2_DTCM_START       0x20000000
#define FPS_CPU0_DTCM_SIZE        0x8000      // 32K
#define FPS_CPU1_DTCM_SIZE        0x10000     // 64K
#define FPS_CPU2_DTCM_SIZE        0x8000      // 32K
#define FPS_CPU0_DTCM_END   FPS_CPU0_DTCM_START + FPS_CPU0_DTCM_SIZE
#define FPS_CPU1_DTCM_END   FPS_CPU1_DTCM_START + FPS_CPU1_DTCM_SIZE
#define FPS_CPU2_DTCM_END   FPS_CPU2_DTCM_START + FPS_CPU2_DTCM_SIZE

/**
 * share DTCM
 */
#define FPS_CPU01_SHARE_DTCM_START       0x20020000
#define FPS_CPU12_SHARE_DTCM_START       0x20020000
#define FPS_CPU20_SHARE_DTCM_START       0x20020000
#define FPS_CPU01_SHARE_DTCM_SIZE        0x4000     // 16K
#define FPS_CPU12_SHARE_DTCM_SIZE        0x4000     // 16K
#define FPS_CPU20_SHARE_DTCM_SIZE        0x4000     // 16K

/**
 * STACK and C2SV
 */
#define C2SV_SIZE           0x20
#define FPS_CPU0_STACK_SIZE 0x200
#define FPS_CPU1_STACK_SIZE 0x200
#define FPS_CPU2_STACK_SIZE 0x200

// split FPS CPU01 share DTCM for C2SV + Stack of FPS CPU0, total 0x220
#define FPS_CPU0_STACK_PROTECT   (FPS_CPU01_SHARE_DTCM_START + FPS_CPU01_SHARE_DTCM_SIZE - C2SV_SIZE) //C2SV_START
#define FPS_CPU0_STACK_START  (FPS_CPU0_STACK_PROTECT)
#define FPS_CPU0_STACK_BOT    (FPS_CPU0_STACK_START - FPS_CPU0_STACK_SIZE)

// split FPS CPU12 share DTCM for C2SV + Stack of FPS CPU1, total 0x220
#define FPS_CPU1_STACK_PROTECT   (FPS_CPU12_SHARE_DTCM_START + FPS_CPU12_SHARE_DTCM_SIZE - C2SV_SIZE) //C2SV_START
#define FPS_CPU1_STACK_START  (FPS_CPU1_STACK_PROTECT)
#define FPS_CPU1_STACK_BOT    (FPS_CPU1_STACK_START - FPS_CPU1_STACK_SIZE)

// split FPS CPU20 share DTCM for C2SV + Stack of FPS CPU2, total 0x220
#define FPS_CPU2_STACK_PROTECT   (FPS_CPU20_SHARE_DTCM_START + FPS_CPU20_SHARE_DTCM_SIZE - C2SV_SIZE) //C2SV_START
#define FPS_CPU2_STACK_START  (FPS_CPU2_STACK_PROTECT)
#define FPS_CPU2_STACK_BOT    (FPS_CPU2_STACK_START - FPS_CPU2_STACK_SIZE)

#define M7_FPS_CRASH_DUMP_COUNTER_SIZE          0x4 // 32bits
#define M7_FPS_CPU01_SHARE_DTCM_END        FPS_CPU0_STACK_BOT // M7_FPS_CPU01_SHARE_DTCM_START + FPS_CPU01_SHARE_DTCM_SIZE
#define M7_FPS_CPU12_SHARE_DTCM_END        FPS_CPU1_STACK_BOT // M7_FPS_CPU12_SHARE_DTCM_START + FPS_CPU12_SHARE_DTCM_SIZE
#define M7_FPS_CPU20_SHARE_DTCM_END        FPS_CPU2_STACK_BOT // M7_FPS_CPU20_SHARE_DTCM_START + FPS_CPU20_SHARE_DTCM_SIZE

/**
 * MMIO and DATA section
 */
// split FPS CPU0 DTCM for MMIO + data section
#define FPS_CPU0_DTCM_MMIO_SIZE   0x6020
#define FPS_CPU0_DTCM_MMIO_START (FPS_CPU0_DTCM_START)
#define FPS_CPU0_DTCM_DATA_START (FPS_CPU0_DTCM_START + FPS_CPU0_DTCM_MMIO_SIZE)
#define FPS_CPU0_DTCM_DATA_SIZE  (FPS_CPU0_DTCM_SIZE - FPS_CPU0_DTCM_MMIO_SIZE)

// split FPS CPU1 DTCM for MMIO
#define FPS_CPU1_DTCM_MMIO_SIZE  0x10000     // 64KB for DFL buffer
#define FPS_CPU1_DTCM_MMIO_START (FPS_CPU1_DTCM_START)

// split FPS CPU12 share DTCM for data section of FPS CPU1
#define FPS_CPU12_SHARE_DTCM_MMIO_SIZE (M7_FPS_CPU12_SHARE_DTCM_MMIO_END - FPS_CPU12_SHARE_DTCM_MMIO_START)
#define FPS_CPU1_DTCM_DATA_START M7_FPS_CPU12_SHARE_DTCM_MMIO_END //(FPS_CPU12_SHARE_DTCM_MMIO_START + FPS_CPU12_SHARE_DTCM_MMIO_SIZE)
#define FPS_CPU1_DTCM_DATA_SIZE \
    (FPS_CPU12_SHARE_DTCM_SIZE - FPS_CPU12_SHARE_DTCM_MMIO_SIZE - C2SV_SIZE - FPS_CPU1_STACK_SIZE)

// split FPS CPU2 DTCM for MMIO + data section
#define FPS_CPU2_DTCM_MMIO_SIZE   0x2900
#define FPS_CPU2_DTCM_MMIO_START (FPS_CPU2_DTCM_START)
#define FPS_CPU2_DTCM_DATA_START (FPS_CPU2_DTCM_START + FPS_CPU2_DTCM_MMIO_SIZE)
#define FPS_CPU2_DTCM_DATA_SIZE  (FPS_CPU2_DTCM_SIZE - FPS_CPU2_DTCM_MMIO_SIZE)

// MMIO initial for share DTCM
#define FPS_CPU01_SHARE_DTCM_MMIO_START  (FPS_CPU01_SHARE_DTCM_START)
#define FPS_CPU01_SHARE_DTCM_MMIO_SIZE   (FPS_CPU01_SHARE_DTCM_SIZE)
#define FPS_CPU12_SHARE_DTCM_MMIO_START  (FPS_CPU12_SHARE_DTCM_START)
#define FPS_CPU20_SHARE_DTCM_MMIO_START  (FPS_CPU20_SHARE_DTCM_START)
#define FPS_CPU20_SHARE_DTCM_MMIO_SIZE   (FPS_CPU20_SHARE_DTCM_SIZE)

/**
 * pSRAM
 */
// split pSRAM: MMIO + EX MONITOR
#define PSRAM_START           0x00010000
#define PSRAM_SIZE            0x8000        // 32K
#define PSRAM_END             (PSRAM_START + PSRAM_SIZE)
#define PSRAM_MIDDEL_SIZE     0x1080        // 4096 bytes for m7 status and pi/ci
#define PSRAM_EXMON_SIZE      0x80          // 128-bytes
#define PSRAM_UART_DUMP_SIZE  0x3480        // 12K Log Buffer + 1.xK Others
#define PSRAM_CERBERUS_LOGGING_BUFFER_ARRAY_SIZE 0x150
#define PSRAM_LOG_BUFFER_SIZE 0x800                           ///< 2K bytes for one buffer
#define PSRAM_LOG_BUFFER_NUMBER_PER_FP_CPU 2                  ///< 2 buffers for single FP_CPU

#define PSRAM_CP2FP_MSG_DEPTH 0x10UL
#define PSRAM_CP2FP_REQ_RES_MSG_DEPTH 0x8UL
#define PSRAM_CP2FP_MSG_ELMNT_SIZE 0x40
#define PSRAM_CP2FP_MSG_SIZE (PSRAM_CP2FP_MSG_ELMNT_SIZE * PSRAM_CP2FP_MSG_DEPTH)
#define PSRAM_CP2FP_MSG_MASK (PSRAM_CP2FP_MSG_DEPTH - 1)
#define PSRAM_CP2FP_REQ_RES_MSG_SIZE (PSRAM_CP2FP_MSG_ELMNT_SIZE * PSRAM_CP2FP_REQ_RES_MSG_DEPTH)
#define PSRAM_CP2FP_REQ_RES_MSG_MASK (PSRAM_CP2FP_REQ_RES_MSG_DEPTH - 1)
#define PSRAM_FP2CP_MSG_DEPTH      0x10UL
#define PSRAM_FP2CP_REQ_RES_MSG_DEPTH      0x8UL
#define PSRAM_FP2CP_MSG_ELMNT_SIZE 0x40
#define PSRAM_FP2CP_MSG_DATA_SIZE  0x40
#define PSRAM_FP2CP_MSG_SIZE (PSRAM_FP2CP_MSG_ELMNT_SIZE * PSRAM_FP2CP_MSG_DEPTH)
#define PSRAM_FP2CP_MSG_MASK (PSRAM_FP2CP_MSG_DEPTH - 1)

#define PSRAM_FP2CP_REQ_RES_MSG_SIZE (PSRAM_FP2CP_MSG_ELMNT_SIZE * PSRAM_FP2CP_REQ_RES_MSG_DEPTH)
#define PSRAM_FP2CP_REQ_RES_MSG_MASK (PSRAM_FP2CP_REQ_RES_MSG_DEPTH - 1)

#define PSRAM_INTL_CPUX2CPUY_MSG_DEPTH      0x10
#define PSRAM_INTL_CPUX2CPUY_MSG_ELMNT_SIZE 0x4
#define PSRAM_INTL_CPUX2CPUY_MSG_SIZE \
    (PSRAM_INTL_CPUX2CPUY_MSG_DEPTH * PSRAM_INTL_CPUX2CPUY_MSG_ELMNT_SIZE)
#define PSRAM_INTL_ALL_MSG_SIZE (PSRAM_INTL_CPUX2CPUY_MSG_SIZE * _M7_CORES_ * 2)
#define PSRAM_INTL_CPUX2CPUY_MSG_MASK ((uint8_t)PSRAM_INTL_CPUX2CPUY_MSG_DEPTH - 1)

#define PSRAM_FP_TO_CP_ERROR_COMMAND_QUEUE_SIZE    0x800
#define PSRAM_FP_TO_CP_ERROR_COMPLETION_QUEUE_SIZE 0x800
#define PSRAM_FP_CPUx_STATUS_SIZE         0x4
#define PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE 0x4
#define PSRAM_FP_CPIO_CDMA_ERR_CODE_ADDR_SIZE        0x4
#define PSRAM_FP_CPIO_CDMA_STATUS_SIZE    0x4
#define PSRAM_RSVD_FOR_FUTURE_USE_SIZE    0x8
#define PSRAM_DATA_BACKUP_HEADER_SIZE 0xC
#define PSRAM_DATA_BACKUP_LENGTH_SIZE 0x4
#define PSRAM_DFL_BACKUP_SIZE 0x440
#define PSRAM_LOGGING_BACKUP_LENGTH_SIZE 0x4
#define PSRAM_LOGGING_BACKUP_SIZE 0x30
#define PSRAM_LOGGING_LOG_HANDLE_SIZE 0xC // 9 bytes + padding for alignment
#define PSRAM_FPS_FLR_REQUSET_BIT_MAP_SIZE 0x8
#define PSRAM_MMIO_RVSD_SIZE 0x50

#define PSRAM_TOP_RVSD_SIZE 0x800

/**
 * pSRAM top allocation
 *
 * CP0 to FP MSG         (64 bytes * 8 ):  0x200
 * CP0 to FP RESP MSG    (64 bytes * 8 ):  0x200
 * FP to CP0 MSG         (64 bytes * 8 ):  0x200
 * FP to CP0 RESP MSG    (64 bytes * 8 ):  0x200
 * CPU0 to CPU1 MSG      (4 bytes * 16) :  0x40
 * CPU1 to CPU0 MSG      (4 bytes * 16) :  0x40
 * CPU1 to CPU2 MSG      (4 bytes * 16) :  0x40
 * CPU2 to CPU1 MSG      (4 bytes * 16) :  0x40
 * CPU2 to CPU0 MSG      (4 bytes * 16) :  0x40
 * CPU0 to CPU2 MSG      (4 bytes * 16) :  0x40
 * CP1 to FP MSG         (64 bytes * 8 ):  0x200
 * CP1 to FP RESP MSG    (64 bytes * 8 ):  0x200
 * FP to CP1 MSG         (64 bytes * 8 ):  0x200
 * FP to CP1 RESP MSG    (64 bytes * 8 ):  0x200
 * [reserved]            (2048 bytes)   :  0x800
 *
 * Total:                              0x1980 (address from 0x10000 to 0x1197F)
 */
// 64 bytes * 16 = 1k bytes
#define PSRAM_CP0toFP_REQ_MSG_ADDR (PSRAM_START)
// 64 bytes * 16 = 1k bytes
#define PSRAM_FPtoCP0_RES_MSG_ADDR (PSRAM_CP0toFP_REQ_MSG_ADDR + PSRAM_CP2FP_MSG_SIZE)
// 4 bytes * 16 = 64 bytes
#define PSRAM_INTL_CPU0_2_CPU1_MSG_ADDR (PSRAM_FPtoCP0_RES_MSG_ADDR + PSRAM_FP2CP_MSG_SIZE)
// 4 bytes * 16 = 64 bytes
#define PSRAM_INTL_CPU1_2_CPU0_MSG_ADDR (PSRAM_INTL_CPU0_2_CPU1_MSG_ADDR + PSRAM_INTL_CPUX2CPUY_MSG_SIZE)
// 4 bytes * 16 = 64 bytes
#define PSRAM_INTL_CPU1_2_CPU2_MSG_ADDR (PSRAM_INTL_CPU1_2_CPU0_MSG_ADDR + PSRAM_INTL_CPUX2CPUY_MSG_SIZE)
// 4 bytes * 16 = 64 bytes
#define PSRAM_INTL_CPU2_2_CPU1_MSG_ADDR (PSRAM_INTL_CPU1_2_CPU2_MSG_ADDR + PSRAM_INTL_CPUX2CPUY_MSG_SIZE)
// 4 bytes * 16 = 64 bytes
#define PSRAM_INTL_CPU2_2_CPU0_MSG_ADDR (PSRAM_INTL_CPU2_2_CPU1_MSG_ADDR + PSRAM_INTL_CPUX2CPUY_MSG_SIZE)
// 4 bytes * 16 = 64 bytes
#define PSRAM_INTL_CPU0_2_CPU2_MSG_ADDR (PSRAM_INTL_CPU2_2_CPU0_MSG_ADDR + PSRAM_INTL_CPUX2CPUY_MSG_SIZE)
// 64 bytes * 16 = 1k bytes
#define PSRAM_CP1toFP_REQ_MSG_ADDR (PSRAM_INTL_CPU0_2_CPU2_MSG_ADDR + PSRAM_INTL_CPUX2CPUY_MSG_SIZE)
// 64 bytes * 16 = 1k bytes
#define PSRAM_FPtoCP1_RES_MSG_ADDR (PSRAM_CP1toFP_REQ_MSG_ADDR + PSRAM_CP2FP_MSG_SIZE)
// 390 bytes
#define PSRAM_TOP_RVSD (PSRAM_FPtoCP1_RES_MSG_ADDR + PSRAM_FP2CP_MSG_SIZE)

#define PSRAM_TOP_END_ADDR (PSRAM_TOP_RVSD + PSRAM_TOP_RVSD_SIZE)

/**
 * pSRAM MMIO allocation
 *
 * [reserved]                (80 bytes)     : 0x50
 * [backup] Backup Header    (12 bytes)     : 0xC
 * [backup] DFL list length  (4 bytes)      : 0x4
 * [backup] DFL list (2 bytes * (512 + 32)) : 0x440
 * [backup] logging length       (4 bytes)  : 0x4
 * [backup] logging          (48 bytes)     : 0x30
 * PSRAM_LOGGING_CPU0_LOG_HANDLE (12 bytes) : 0xC
 * PSRAM_LOGGING_CPU1_LOG_HANDLE (12 bytes) : 0xC
 * PSRAM_LOGGING_CPU2_LOG_HANDLE (12 bytes) : 0xC
 *
 * Total                                    : 0x4F8 (address from 0x11980 to 0x11E78)
 */

#define PSRAM_MMIO_START (PSRAM_TOP_END_ADDR)
// #define PSRAM_MMIO_SIZE \
//     (PSRAM_SIZE - (PSRAM_MMIO_START - PSRAM_START) - (PSRAM_EXMON_SIZE + PSRAM_UART_DUMP_SIZE))
// 12 bytes
#define PSRAM_BACKUP_DATA_HEADER_ADDR (PSRAM_MMIO_START + PSRAM_MMIO_RVSD_SIZE)
// 4 bytes
#define PSRAM_DFL_LIST_BACKUP_LENGTH_ADDR (PSRAM_BACKUP_DATA_HEADER_ADDR + PSRAM_DATA_BACKUP_HEADER_SIZE)
// (512+32) * 2 (bytes) = 1088 bytes
#define PSRAM_DFL_LIST_BACKUP (PSRAM_DFL_LIST_BACKUP_LENGTH_ADDR + PSRAM_DATA_BACKUP_LENGTH_SIZE)
// 4 bytes
#define PSRAM_LOGGING_BACKUP_LENGTH_ADDR (PSRAM_DFL_LIST_BACKUP + PSRAM_DFL_BACKUP_SIZE)
// 48 bytes
#define PSRAM_LOGGING_BACKUP (PSRAM_LOGGING_BACKUP_LENGTH_ADDR + PSRAM_DATA_BACKUP_LENGTH_SIZE)

// Log Handle for FP 0 12 Bytes
#define PSRAM_LOGGING_CPU0_LOG_HANDLE (PSRAM_LOGGING_BACKUP + PSRAM_LOGGING_BACKUP_SIZE)
// Log Handle for FP 1 12 Bytes
#define PSRAM_LOGGING_CPU1_LOG_HANDLE (PSRAM_LOGGING_CPU0_LOG_HANDLE + PSRAM_LOGGING_LOG_HANDLE_SIZE)
// Log Handle for FP 2 12 Bytes
#define PSRAM_LOGGING_CPU2_LOG_HANDLE (PSRAM_LOGGING_CPU1_LOG_HANDLE + PSRAM_LOGGING_LOG_HANDLE_SIZE)

#define PSRAM_MMIO_RVSD (PSRAM_LOGGING_CPU2_LOG_HANDLE + PSRAM_LOGGING_LOG_HANDLE_SIZE)

#define OLD_PSRAM_DFL_LIST_BACKUP (0x10980)
#define OLD_PSRAM_LOGGING_BACKUP  (0x10DC0)

#define PSRAM_RESET_TYPE_SIZE           0x4
#define PSRAM_RESET_TYPE ((PSRAM_LOG_DUMP_START - PSRAM_MIDDEL_SIZE) - PSRAM_RESET_TYPE_SIZE)

/**
 * pSRAM MMIO - MIDDLE allocation
 *
 * CP DFL BUF           (128 bytes * 1) : 0x80
 * FP CPU0 STATUS       (4 bytes * 1) :   0x4
 * FP CPU1 STATUS       (4 bytes * 1) :   0x4
 * FP CPU2 STATUS       (4 bytes * 1) :   0x4
 * CP0 to FP PI         (4 bytes * 1) :   0x4
 * CP0 to FP CI         (4 bytes * 1) :   0x4
 * FP to CP0 PI         (4 bytes * 1) :   0x4
 * FP to CP0 CI         (4 bytes * 1) :   0x4
 * CPU0 to CPU1 PI      (4 bytes * 1) :   0x4
 * CPU0 to CPU1 CI      (4 bytes * 1) :   0x4
 * CPU1 to CPU0 PI      (4 bytes * 1) :   0x4
 * CPU1 to CPU0 CI      (4 bytes * 1) :   0x4
 * CPU1 to CPU2 PI      (4 bytes * 1) :   0x4
 * CPU1 to CPU2 CI      (4 bytes * 1) :   0x4
 * CPU2 to CPU1 PI      (4 bytes * 1) :   0x4
 * CPU2 to CPU1 CI      (4 bytes * 1) :   0x4
 * CPU2 to CPU0 PI      (4 bytes * 1) :   0x4
 * CPU2 to CPU0 CI      (4 bytes * 1) :   0x4
 * CPU0 to CPU2 PI      (4 bytes * 1) :   0x4
 * CPU0 to CPU2 CI      (4 bytes * 1) :   0x4
 * FP ALIVE STATUS      (4 bytes * 1) :   0x4
 * FP CPIO CDMA STATUS  (4 bytes * 1) :   0x4
 * CP1 to FP PI         (4 bytes * 1) :   0x4
 * CP1 to FP CI         (4 bytes * 1) :   0x4
 * FP to CP1 PI         (4 bytes * 1) :   0x4
 * FP to CP1 CI         (4 bytes * 1) :   0x4
 * ERROR PENDING QUEUE PI (4 bytes * 1) : 0x4
 * ERROR PENDING QUEUE CI (4 bytes * 1) : 0x4
 * FLR request bit map (8 bytes * 1) : 0x8
 * [reserved]        (3980 bytes)   :  0xF8C
 *
 * Total:                              0x1080 (address from 0x13B00 to 0x14B7F)
 */
#define PSRAM_MIDDEL_START (PSRAM_LOG_DUMP_START - PSRAM_MIDDEL_SIZE)

#define PSRAM_CP_DFL_BUF_ADDR (PSRAM_MIDDEL_START) // 128 bytes * 1 = 128 bytes
#define PSRAM_FP_CPU0_STATUS_ADDR (PSRAM_CP_DFL_BUF_ADDR + DFL_BUFF_ELMNT_SIZE) // 4 bytes * 1 = 4 bytes (total 21)
#define PSRAM_FP_CPU1_STATUS_ADDR (PSRAM_FP_CPU0_STATUS_ADDR + PSRAM_FP_CPUx_STATUS_SIZE)
#define PSRAM_FP_CPU2_STATUS_ADDR (PSRAM_FP_CPU1_STATUS_ADDR + PSRAM_FP_CPUx_STATUS_SIZE)
#define PSRAM_CP0toFP_REQ_PI_ADDR  (PSRAM_FP_CPU2_STATUS_ADDR + PSRAM_FP_CPUx_STATUS_SIZE)
#define PSRAM_CP0toFP_REQ_CI_ADDR  (PSRAM_CP0toFP_REQ_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_FPtoCP0_RES_PI_ADDR  (PSRAM_CP0toFP_REQ_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_FPtoCP0_RES_CI_ADDR  (PSRAM_FPtoCP0_RES_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU0_2_CPU1_PI_ADDR (PSRAM_FPtoCP0_RES_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU0_2_CPU1_CI_ADDR (PSRAM_INTL_CPU0_2_CPU1_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU1_2_CPU0_PI_ADDR (PSRAM_INTL_CPU0_2_CPU1_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU1_2_CPU0_CI_ADDR (PSRAM_INTL_CPU1_2_CPU0_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU1_2_CPU2_PI_ADDR (PSRAM_INTL_CPU1_2_CPU0_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU1_2_CPU2_CI_ADDR (PSRAM_INTL_CPU1_2_CPU2_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU2_2_CPU1_PI_ADDR (PSRAM_INTL_CPU1_2_CPU2_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU2_2_CPU1_CI_ADDR (PSRAM_INTL_CPU2_2_CPU1_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU2_2_CPU0_PI_ADDR (PSRAM_INTL_CPU2_2_CPU1_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU2_2_CPU0_CI_ADDR (PSRAM_INTL_CPU2_2_CPU0_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU0_2_CPU2_PI_ADDR (PSRAM_INTL_CPU2_2_CPU0_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_INTL_CPU0_2_CPU2_CI_ADDR (PSRAM_INTL_CPU0_2_CPU2_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_FP_CPIO_CDMA_ERR_CODE_ADDR (PSRAM_INTL_CPU0_2_CPU2_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_FP_CPIO_CDMA_STATUS_ADDR (PSRAM_FP_CPIO_CDMA_ERR_CODE_ADDR + PSRAM_FP_CPIO_CDMA_ERR_CODE_ADDR_SIZE)
#define PSRAM_CP1toFP_REQ_PI_ADDR (PSRAM_FP_CPIO_CDMA_STATUS_ADDR + PSRAM_FP_CPIO_CDMA_STATUS_SIZE)
#define PSRAM_CP1toFP_REQ_CI_ADDR (PSRAM_CP1toFP_REQ_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_FPtoCP1_RES_PI_ADDR (PSRAM_CP1toFP_REQ_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_FPtoCP1_RES_CI_ADDR (PSRAM_FPtoCP1_RES_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_RSVD_FOR_FUTURE_USE_ADDR (PSRAM_FPtoCP1_RES_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE) // This is reserved 8 bytes which can be used in the future.
#define PSRAM_FLR_REQUEST_BITMAP (PSRAM_RSVD_FOR_FUTURE_USE_ADDR + PSRAM_RSVD_FOR_FUTURE_USE_SIZE)
// 64 bytes * 8 = 512 bytes
#define PSRAM_FPtoCP0_REQ_MSG_ADDR (PSRAM_FLR_REQUEST_BITMAP + PSRAM_FPS_FLR_REQUSET_BIT_MAP_SIZE)
#define PSRAM_FPtoCP0_REQ_PI_ADDR (PSRAM_FPtoCP0_REQ_MSG_ADDR + PSRAM_FP2CP_REQ_RES_MSG_SIZE)
#define PSRAM_FPtoCP0_REQ_CI_ADDR (PSRAM_FPtoCP0_REQ_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
// 64 bytes * 8 = 512 bytes
#define PSRAM_CP0toFP_RES_MSG_ADDR (PSRAM_FPtoCP0_REQ_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_CP0toFP_RES_PI_ADDR (PSRAM_CP0toFP_RES_MSG_ADDR + PSRAM_FP2CP_REQ_RES_MSG_SIZE)
#define PSRAM_CP0toFP_RES_CI_ADDR (PSRAM_CP0toFP_RES_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
// 64 bytes * 8 = 512 bytes
#define PSRAM_FPtoCP1_REQ_MSG_ADDR (PSRAM_CP0toFP_RES_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_FPtoCP1_REQ_PI_ADDR (PSRAM_FPtoCP1_REQ_MSG_ADDR + PSRAM_FP2CP_REQ_RES_MSG_SIZE)
#define PSRAM_FPtoCP1_REQ_CI_ADDR (PSRAM_FPtoCP1_REQ_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
// 64 bytes * 8 = 512 bytes
#define PSRAM_CP1toFP_RES_MSG_ADDR (PSRAM_FPtoCP1_REQ_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_CP1toFP_RES_PI_ADDR (PSRAM_CP1toFP_RES_MSG_ADDR + PSRAM_FP2CP_REQ_RES_MSG_SIZE)
#define PSRAM_CP1toFP_RES_CI_ADDR (PSRAM_CP1toFP_RES_PI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)
#define PSRAM_MIDDEL_END (PSRAM_CP1toFP_RES_CI_ADDR + PSRAM_FP_CPUX2CPUY_MSG_PI_CI_SIZE)

/**
 * pSRAM logging allocation
 *
 * FP CPU0 Log buffer       (4096 bytes) :   0x1000
 * FP CPU1 Log buffer       (4096 bytes) :   0x1000
 * FP CPU2 Log buffer       (4096 bytes) :   0x1000
 * RSVD Buffer              (1152 bytes) :   0x480
 *
 * Total:                   0x3480 (address from 0x14B80 to 0x18000)
 */
#define PSRAM_LOG_DUMP_START (PSRAM_END - PSRAM_UART_DUMP_SIZE)

/**
 * GENERAL DEFINITION
 */
#define MAX_SUPPORT_CMD_NUM 512
#define MAX_SUPPORT_CMD_NUM_QUEUE_1 32
#define EXTRA_SUPPORT_CMD_NUM 8    // for inbound queue 128 and 129 (65 QB support)

#define IB_CQ_ELMNT_SIZE 16
#define IB_CQ_DEPTH (MAX_SUPPORT_CMD_NUM)
#define IB_CQ_SIZE (IB_CQ_ELMNT_SIZE * IB_CQ_DEPTH)
#define IB_CQ_1_DEPTH 32
#define IB_CQ_1_SIZE (IB_CQ_ELMNT_SIZE * IB_CQ_1_DEPTH)

#define OB_CQ_ELMNT_SIZE (IB_CQ_ELMNT_SIZE)
#define OB_CQ_0_DEPTH (IB_CQ_DEPTH)
#define OB_CQ_0_SIZE (OB_CQ_ELMNT_SIZE * OB_CQ_0_DEPTH)
#define OB_CQ_1_DEPTH 32
#define OB_CQ_1_SIZE (OB_CQ_ELMNT_SIZE * OB_CQ_1_DEPTH)

#define IB_DFL_ELMNT_SIZE 8
#define IB_DFL_0_DEPTH (MAX_SUPPORT_CMD_NUM)
#define IB_DFL_0_SIZE (IB_DFL_ELMNT_SIZE * IB_DFL_0_DEPTH)
#define IB_DFL_1_DEPTH 32
#define IB_DFL_1_SIZE (IB_DFL_ELMNT_SIZE * IB_DFL_1_DEPTH)

#define OB_OSL_ELMNT_SIZE 16
#define OB_OSL_0_DEPTH (MAX_SUPPORT_CMD_NUM)
#define OB_OSL_0_SIZE (OB_OSL_ELMNT_SIZE * OB_OSL_0_DEPTH)
#define OB_OSL_1_DEPTH 32
#define OB_OSL_1_SIZE (OB_OSL_ELMNT_SIZE * OB_OSL_1_DEPTH)

#define SLOT_STATUS_ELMNT_SIZE 1
#define SLOT_STATUS_DEPTH 144    // use 130 only, setup 144 for 0x10 alignment
#define SLOT_STATUS_SIZE (SLOT_STATUS_ELMNT_SIZE * SLOT_STATUS_DEPTH)

#define IBQ2OBQ_ELMNT_SIZE 1
#define IBQ2OBQ_DEPTH 144        // use 130 only, setup 144 for 0x10 alignment
#define IBQ2OBQ_SIZE (IBQ2OBQ_ELMNT_SIZE * IBQ2OBQ_DEPTH)

#define DFL_BUFF_ELMNT_SIZE 128
#define DFL_0_BUFF_DEPTH (MAX_SUPPORT_CMD_NUM)
#define DFL_0_BUFF_SIZE (DFL_BUFF_ELMNT_SIZE * DFL_0_BUFF_DEPTH)
#define DFL_1_BUFF_DEPTH 32
#define DFL_1_BUFF_SIZE (DFL_BUFF_ELMNT_SIZE * DFL_1_BUFF_DEPTH)

#define CDMA_SQ_ELMNT_SIZE 16
#define CDMA_SQ_DEPTH 64
#define CDMA_SQ_SIZE (CDMA_SQ_ELMNT_SIZE * CDMA_SQ_DEPTH)

#define CDMA_CQ_ELMNT_SIZE 8
#define CDMA_CQ_DEPTH 64
#define CDMA_CQ_SIZE (CDMA_CQ_ELMNT_SIZE * CDMA_CQ_DEPTH)

#define KEY_TABLE_RGID_TO_VALID_ELMNT_SIZE 1
#define KEY_TABLE_RGID_TO_VALID_DEPTH 80        // use 65 only, setup 80 for 0x10 alignment
#define KEY_TABLE_RGID_TO_VALID_SIZE (KEY_TABLE_RGID_TO_VALID_ELMNT_SIZE * KEY_TABLE_RGID_TO_VALID_DEPTH)

#define KEY_TABLE_RGID_TO_OWNER_VFID_ELMNT_SIZE 1
#define KEY_TABLE_RGID_TO_OWNER_VFID_DEPTH 80   // use 65 only, setup 80 for 0x10 alignment
#define KEY_TABLE_RGID_TO_OWNER_VFID_SIZE (KEY_TABLE_RGID_TO_OWNER_VFID_ELMNT_SIZE * KEY_TABLE_RGID_TO_OWNER_VFID_DEPTH)

#define KEY_TABLE_KEY_TO_OWNER_VFID_ELMNT_SIZE 1
#define KEY_TABLE_KEY_TO_OWNER_VFID_DEPTH 512
#define KEY_TABLE_KEY_TO_OWNER_VFID_SIZE (KEY_TABLE_KEY_TO_OWNER_VFID_ELMNT_SIZE * KEY_TABLE_KEY_TO_OWNER_VFID_DEPTH)

#define M7_SHARE_KEY_INDEX_NUM     464   // FP IO:  RG 65 * 7 = 455,  CDMA IO: 456-462,  463 and 464 is for memory alignment only, not for use
#define M7_SHARE_KEY_FLAG_ELEMENT_SIZE 1
#define M7_SHARE_KEY_SESSION_ID_ELEMENT_SIZE 2
#define M7_SHARE_KEY_APP_ID_ELEMENT_SIZE 1

#define M7_SHARE_KEY_FLAG_SIZE  (M7_SHARE_KEY_INDEX_NUM * M7_SHARE_KEY_FLAG_ELEMENT_SIZE)
#define M7_SHARE_KEY_SESSION_ID_SIZE (M7_SHARE_KEY_INDEX_NUM * M7_SHARE_KEY_SESSION_ID_ELEMENT_SIZE)
#define M7_SHARE_KEY_APP_ID_SIZE (M7_SHARE_KEY_INDEX_NUM * M7_SHARE_KEY_APP_ID_ELEMENT_SIZE)

#define M7_SHARE_ERROR_PENDING_QUEUE_ELMNT_SIZE 4
#define M7_SHARE_ERROR_PENDING_QUEUE_DEPTH 64
#define M7_SHARE_ERROR_PENDING_QUEUE_SIZE (M7_SHARE_ERROR_PENDING_QUEUE_ELMNT_SIZE * M7_SHARE_ERROR_PENDING_QUEUE_DEPTH)

#define M7_SHARE_CMD_ENTRY_SIZE 4
#define M7_SHARE_CMD_ENTRY_DEPTH (MAX_SUPPORT_CMD_NUM + EXTRA_SUPPORT_CMD_NUM)
#define M7_SHARE_CMD_ARRAY_SIZE  (M7_SHARE_CMD_ENTRY_SIZE * M7_SHARE_CMD_ENTRY_DEPTH)

#define M7_SHARE_CMD_ENTRY_TINY_SIZE 4
#define M7_SHARE_CMD_ENTRY_TINY_DEPTH (MAX_SUPPORT_CMD_NUM + EXTRA_SUPPORT_CMD_NUM)
#define M7_SHARE_CMD_ARRAY_TINY_SIZE  (M7_SHARE_CMD_ENTRY_TINY_SIZE * M7_SHARE_CMD_ENTRY_TINY_DEPTH)

#define M7_SHARE_RETRY_CMD_ENTRY_SIZE 4
#define M7_SHARE_RETRY_CMD_ENTRY_DEPTH MAX_SUPPORT_CMD_NUM
#define M7_SHARE_RETRY_CMD_ENTRY_INFO_SIZE  (M7_SHARE_RETRY_CMD_ENTRY_SIZE * M7_SHARE_RETRY_CMD_ENTRY_DEPTH)

#define M7_SHARE_REFILL_CE_DFL_ENTRY_SIZE 4
#define M7_SHARE_REFILL_CE_DFL_ENTRY_DEPTH MAX_SUPPORT_CMD_NUM
#define M7_SHARE_REFILL_CE_DFL_ENTRY_INFO_SIZE  (M7_SHARE_REFILL_CE_DFL_ENTRY_SIZE * M7_SHARE_REFILL_CE_DFL_ENTRY_DEPTH)

#define M7_SHARE_VF_ENABLED_BIT_MAP_SIZE   0x8
#define M7_SHARE_VF_CMD_EXIST_BIT_MAP_SIZE 0x8
#define M7_SHARE_VF_65_ENABLED_BIT_MAP_SIZE   0x8
#define M7_SHARE_VF_65_CMD_EXIST_BIT_MAP_SIZE 0x8
#define M7_SHARE_QB_ENABLED_BIT_MAP_SIZE   0x210    // 8 bytes * 65 = 0x208
#define M7_SHARE_QB_65_ENABLED_BIT_MAP_SIZE   0x50  // use 65 bytes only, setup 0x50 for 0x10 alignment

#define M7_SHARE_VF_INFO_STRUCT_SIZE  16
#define M7_SHARE_VF_INFO_NUM   65
#define M7_SHARE_VF_INFO_SIZE (M7_SHARE_VF_INFO_STRUCT_SIZE * M7_SHARE_VF_INFO_NUM)

#define M7_SHARE_QB_INFO_STRUCT_SIZE  16
#define M7_SHARE_QB_INFO_NUM   65
#define M7_SHARE_QB_INFO_SIZE (M7_SHARE_QB_INFO_STRUCT_SIZE * M7_SHARE_QB_INFO_NUM)
#define M7_SHARE_VF_CREDIT_INFO  4
#define M7_SHARE_VF_CREDIT_INFO_NUM   (65 + 3)  // allocate an extra VF for 0x10 alginment
#define M7_SHARE_VF_CREIDT_INFO_SIZE  (M7_SHARE_VF_CREDIT_INFO * M7_SHARE_VF_CREDIT_INFO_NUM)
#define M7_SHARE_VF_REMAIN_CREIDT_INFO_SIZE (M7_SHARE_VF_CREDIT_INFO * M7_SHARE_VF_CREDIT_INFO_NUM)
#define M7_SHARE_TOTAL_CREDIT_SIZE 0x10  // use 4 bytes only

#define M7_LOG_BUF_INFO_SIZE       32

#define M7_CP_IO_INTERNAL_BUF_SIZE 192

#define M7_CRASHDUMP_INFO_SIZE  128     // This needs to be greater than or equal to CrashDumpPackage Size

#define M7_CPU1_SUBMIT_ABORT_INFO_SIZE 144  // use 130 only, setup 144 for 0x10 alignment

#define M7_CMDA_IDLE_CMD_DFL_BUF_SIZE  128

#define M7_ABORT_BITMAP_SIZE  144           // use 130 only, setup 144 for 0x10 alignment
#define M7_CDMA_FATAL_ERROR_OCCUR_FLAG_SIZE 16

#define M7_OUTSTANDING_IO_CNT_SIZE  16
#define M7_ACCUMULATE_IO_CNT_SIZE  16

#define M7_FPS_CPU20_ADMIN_ABORT_COUNT_SIZE 16

#define M7_FP_MODE_SIZE 16

#define M7_FPS_CA_2_IBPHYQID_TABLE_SIZE  144    // use 130 only, setup 144 for 0x10 alignment
#define M7_FPS_IBPHYQID_2_CA_TABLE_SIZE  144    // use 130 only, setup 144 for 0x10 alignment

#define M7_FPS_LOG_GDMA_DQ_PI_SIZE 0x10  // Logging backup

#define M7_FPS_FLR_REQUSET_BIT_MAP_LOCAL_SIZE 0x8

#define M7_FPS_FLR_QUEUE_BLOCK_BIT_MAP_LOCAL_SIZE 0x8
#define M7_FPS_FLR_QUEUE_BLOCK_BIT_65_MAP_LOCAL_SIZE 0x10


#define M7_ERR_INJECTION_BITMAP_SIZE 0x8 // 64 bits
#define M7_ERR_INJECT_DEPTH 0x3F //0x3F
#define M7_ERR_INJECT_SIZE 0x8
#define M7_ERR_INJECT_TOTAL_SIZE (M7_ERR_INJECT_SIZE * M7_ERR_INJECT_DEPTH)

#define M7_FPS_VF_QOS_LATENCY_BITMAP_SIZE 0x8 // 64
#define M7_FPS_VF65_QOS_LATENCY_BITMAP_SIZE 0x4
#define M7_QOS_PENALTY_PER_VF_SIZE 0x4
#define M7_QOS_PENALTY_NUM 68   // use 65 only, but allocate 68 for 0x10 alignment
#define M7_QOS_PENALTY_SIZE (M7_QOS_PENALTY_PER_VF_SIZE * M7_QOS_PENALTY_NUM)
#define M7_SHARE_QOS_VF_BITMAP_SIZE   0x8
#define M7_SHARE_QOS_VF_65_BITMAP_SIZE   0x8
#define M7_SHARE_WEIGHT_ROUND_ROBIN_SIZE 0x4
#define  M7_FPS_CPU12_CDMA_IO_ABORT_BIT_SIZE   0x8

#define M7_FPS_CPU20_FIPS_APPROVAL_STS_ARRAY_SIZE 0x50 // use 65 bytes only, setup 0x50 for 0x10 alignment

#define UCD_IBOB_CORE_OFFSET     0x4000
#define UCD_IBOB_IQOQ_OFFSET     0x1000

#define UCD_CPU_CREG_WIN_STRIDE  0x400   // per HIU
#define UCD_HOST_CREG_WIN_STRIDE 0x4000  // per HIU
#define UCD_CPU_CREG_VF_OFF      (0x8000 / UCD_CPU_CREG_WIN_STRIDE)
#define UCD_HOST_CREG_VF_OFF     (0x80000 / UCD_HOST_CREG_WIN_STRIDE)

#define UCD_QUERY_DATA_SIZE PSRAM_FP2CP_MSG_DATA_SIZE

#define GCM_REQUEST_QUEUE_SIZE 0x1058 //4168 + 16 bytes [521*8 + 16]
#define GCM_RESPONSE_QUEUE_SIZE 0x834 //2084 + 16 bytes [521*4 + 16]
#define GCM_REQ_RESP_QUEUE_ENTRIES 0x209 //520 + 1 entries
#define GCM_IV_QUEUE_SIZE 0x634 //1572 + 16 bytes [131*12 + 16]
#define GCM_IV_QUEUE_ENTRIES 0x83 //130 + 1 entries


/**
 * MMIO allocation in FPS CPU0 DTCM
 *
 * IB CQ 0    (16 bytes * 512):  0x2000
 * OB CQ 0    (16 bytes * 512):  0x2000
 * OB CQ 1    (16 bytes * 32) :  0x200
 * DFL List 0 (8 bytes * 512) :  0x1000
 * DFL List 3 (8 bytes * 32)  :  0x100
 * IB CQ 1    (16 bytes * 32) :  0x200
 *
 * Total:                        0x5500
 */
#define M7_FPS_CPU0_IBCQ_0_ADDR (FPS_CPU0_DTCM_MMIO_START)
#define M7_FPS_CPU0_OBCQ_0_ADDR (M7_FPS_CPU0_IBCQ_0_ADDR + IB_CQ_SIZE)
#define M7_FPS_CPU0_OBCQ_1_ADDR (M7_FPS_CPU0_OBCQ_0_ADDR + OB_CQ_0_SIZE)
#define M7_FPS_CPU0_DFL_LIST_0_ADDR (M7_FPS_CPU0_OBCQ_1_ADDR + OB_CQ_1_SIZE)
#define M7_FPS_CPU0_DFL_LIST_1_ADDR (M7_FPS_CPU0_DFL_LIST_0_ADDR + IB_DFL_0_SIZE)
#define M7_FPS_CPU0_IBCQ_1_ADDR (M7_FPS_CPU0_DFL_LIST_1_ADDR + IB_DFL_1_SIZE)
#define M7_FPS_CPU0_DTCM_MMIO_END (M7_FPS_CPU0_IBCQ_1_ADDR + IB_CQ_1_SIZE)

/**
 * MMIO allocation in FPS CPU1 DTCM
 *
 * DFL 0 Buffer (128 bytes * 512): 0x10000
 *
 * Total:                          0x10000
 */
#define M7_FPS_CPU1_DFL_BUFF_ADDR (FPS_CPU1_DTCM_MMIO_START)
#define M7_FPS_CPU1_DTCM_MMIO_END (M7_FPS_CPU1_DFL_BUFF_ADDR + DFL_0_BUFF_SIZE)

/**
 * MMIO allocation in FPS CPU2 DTCM
 *
 * OSL List 0 (16 bytes * 512):    0x2000
 * CDMA CQ    (8 bytes * 64)  :    0x200
 * UCD QUERY DATA (1 bytes * 60) : 0x3C
 * OSL List 1 (16 bytes * 32) :    0x200
 *
 * Total:                          0x243C
 */
#define M7_FPS_CPU2_OSL_LIST_0_ADDR (FPS_CPU2_DTCM_MMIO_START)
#define M7_FPS_CPU2_CDMA_CQ_ENTRY_ADDR (M7_FPS_CPU2_OSL_LIST_0_ADDR + OB_OSL_0_SIZE)
#define M7_FPS_CPU2_UCD_QUERY_DATA (M7_FPS_CPU2_CDMA_CQ_ENTRY_ADDR + CDMA_CQ_SIZE)
#define M7_FPS_CPU2_OSL_LIST_1_ADDR (M7_FPS_CPU2_UCD_QUERY_DATA + UCD_QUERY_DATA_SIZE)
#define M7_FPS_CPU2_DTCM_MMIO_END (M7_FPS_CPU2_OSL_LIST_1_ADDR + OB_OSL_1_SIZE)

/**
 * MMIO allocation in FPS CPU01 share DTCM
 *
 * CE base (4 bytes * 520):       0x820
 * QB info (16 bytes * 65):       0x410
 * VF info (16 bytes * 65):       0x410
 * VF credit (4 bytes * 68):      0x110
 * VF remain credit:              0x110
 * VF enabled bit mapping:        0x8
 * VF65 enabled bit mapping:      0x8
 * VF existing cmd bit mapping:   0x8
 * VF65 existing cmd bit mapping: 0x8
 * QB enabled bit mapping:        0x210
 * QB65 enabled bit mapping:      0x50
 * RGID to VF mapping table:      0x80
 * KEY to VF mapping table:       0x200
 * Log buffer info:               0x20
 * Crash dump info:               0x80
 * Submit abort info:             0x90
 * Ca index to IB physical id mapping: 0x90
 * Ib physical id to ca index mapping: 0x90
 * Log GDMA DQ pi:                0x10
 * Total credit of all VF:        0x10
 * Session ID  (464 * 2)          0x3A0        
 * Key Flag    (464 * 1)          0x1D0
 * Key App ID  (464 * 1)          0x1D0
 * CrashDump counter              0x4
 *
 * Total:                         0x2114
 */
#define M7_FPS_CPU01_CMD_ARRAY_BASE_ADDR  FPS_CPU01_SHARE_DTCM_MMIO_START
#define M7_FPS_CPU01_QB_INFO_BASE (M7_FPS_CPU01_CMD_ARRAY_BASE_ADDR + M7_SHARE_CMD_ARRAY_SIZE)
#define M7_FPS_CPU01_VF_INFO_BASE (M7_FPS_CPU01_QB_INFO_BASE + M7_SHARE_QB_INFO_SIZE)
#define M7_FPS_CPU01_VF_CREDIT_INFO_BASE (M7_FPS_CPU01_VF_INFO_BASE + M7_SHARE_VF_INFO_SIZE)
#define M7_FPS_CPU01_VF_REMAIN_CREDIT_INFO_BASE (M7_FPS_CPU01_VF_CREDIT_INFO_BASE + M7_SHARE_VF_CREIDT_INFO_SIZE)
#define M7_FPS_CPU01_VF_ENABLE_BIT_MAP_ADDR (M7_FPS_CPU01_VF_REMAIN_CREDIT_INFO_BASE + M7_SHARE_VF_REMAIN_CREIDT_INFO_SIZE)
#define M7_FPS_CPU01_VF_65_ENABLE_BIT_MAP_ADDR (M7_FPS_CPU01_VF_ENABLE_BIT_MAP_ADDR + M7_SHARE_VF_ENABLED_BIT_MAP_SIZE)
#define M7_FPS_CPU01_VF_CMD_EXIST_BIT_MAP_ADDR (M7_FPS_CPU01_VF_65_ENABLE_BIT_MAP_ADDR + M7_SHARE_VF_65_ENABLED_BIT_MAP_SIZE)
#define M7_FPS_CPU01_VF_65_CMD_EXIST_BIT_MAP_ADDR (M7_FPS_CPU01_VF_CMD_EXIST_BIT_MAP_ADDR + M7_SHARE_VF_CMD_EXIST_BIT_MAP_SIZE)
#define M7_FPS_CPU01_QB_ENABLE_BIT_MAP_ADDR (M7_FPS_CPU01_VF_65_CMD_EXIST_BIT_MAP_ADDR + M7_SHARE_VF_65_CMD_EXIST_BIT_MAP_SIZE)
#define M7_FPS_CPU01_QB_65_ENABLE_BIT_MAP_ADDR (M7_FPS_CPU01_QB_ENABLE_BIT_MAP_ADDR + M7_SHARE_QB_ENABLED_BIT_MAP_SIZE)
#define M7_FPS_CPU01_KEY_TABLE_RGID_TO_OWNER_VFID_ADDR (M7_FPS_CPU01_QB_65_ENABLE_BIT_MAP_ADDR + M7_SHARE_QB_65_ENABLED_BIT_MAP_SIZE)
#define M7_FPS_CPU01_KEY_TABLE_KEY_TO_OWNER_VFID_ADDR (M7_FPS_CPU01_KEY_TABLE_RGID_TO_OWNER_VFID_ADDR + KEY_TABLE_RGID_TO_OWNER_VFID_SIZE)
#define M7_FPS_CPU01_LOG_BUF_INFO_ADDR (M7_FPS_CPU01_KEY_TABLE_KEY_TO_OWNER_VFID_ADDR + KEY_TABLE_KEY_TO_OWNER_VFID_SIZE)
#define M7_FPS_CPU01_CRASHDUMP_INFO_ADDR (M7_FPS_CPU01_LOG_BUF_INFO_ADDR + M7_LOG_BUF_INFO_SIZE)
#define M7_FPS_CPU01_M7_CPU1_SUBMIT_ABORT_INFO (M7_FPS_CPU01_CRASHDUMP_INFO_ADDR + M7_CRASHDUMP_INFO_SIZE)
#define M7_FPS_CPU01_CA_2_IBPHYQID_TABLE (M7_FPS_CPU01_M7_CPU1_SUBMIT_ABORT_INFO + M7_CPU1_SUBMIT_ABORT_INFO_SIZE)
#define M7_FPS_CPU01_IBPHYQID_2_CA_TABLE (M7_FPS_CPU01_CA_2_IBPHYQID_TABLE + M7_FPS_CA_2_IBPHYQID_TABLE_SIZE)
#define M7_FPS_CPU01_LOG_GDMA_DQ_PI (M7_FPS_CPU01_IBPHYQID_2_CA_TABLE + M7_FPS_IBPHYQID_2_CA_TABLE_SIZE)
#define M7_FPS_CPU01_TOTAL_CREDIT_ADDR (M7_FPS_CPU01_LOG_GDMA_DQ_PI + M7_FPS_LOG_GDMA_DQ_PI_SIZE)
#ifdef NEW_AES_KEY_VALIDATION_SUPPORT
#define M7_FPS_CPU01_KEY_SESSION_ID_ADDR (M7_FPS_CPU01_TOTAL_CREDIT_ADDR + M7_SHARE_TOTAL_CREDIT_SIZE)
#define M7_FPS_CPU01_KEY_FLAG_ADDR (M7_FPS_CPU01_KEY_SESSION_ID_ADDR + M7_SHARE_KEY_SESSION_ID_SIZE)
#define M7_FPS_CPU01_KEY_APP_ID_ADDR (M7_FPS_CPU01_KEY_FLAG_ADDR + M7_SHARE_KEY_FLAG_SIZE)
#define M7_FPS_CPU01_SHARE_DTCM_MMIO_END (M7_FPS_CPU01_KEY_APP_ID_ADDR + M7_SHARE_KEY_APP_ID_SIZE)
#else
#define M7_FPS_CPU01_SHARE_DTCM_MMIO_END (M7_FPS_CPU01_TOTAL_CREDIT_ADDR + M7_SHARE_TOTAL_CREDIT_SIZE)
#endif
#define M7_FPS_CPU01_CRASH_DUMP_COUNTER (M7_FPS_CPU01_SHARE_DTCM_END - M7_FPS_CRASH_DUMP_COUNTER_SIZE)
//#define M7_FPS_CPU01_SHARE_DTCM_MMIO_END (M7_FPS_CPU01_CRASH_DUMP_COUNTER + 10)
#if M7_FPS_CPU01_SHARE_DTCM_MMIO_END > M7_FPS_CPU01_CRASH_DUMP_COUNTER
COMPILE_ASSERT(0, "Total code size exceeds memory limit!");
#endif

/**
 * MMIO allocation in FPS CPU12 share DTCM
 *
 * DFL 1 Buffer (128 bytes * 32):        0x1000
 * CDMA SQ entries(16 bytes * 64):       0x400
 * SubKey table(1 byte * 65):            0x50
 * Log buffer:                           0x20
 * Internal buffer of CP I/O:            0xc0
 * Crash dump info:                      0x80
 * CDMA LIST 1 buffer:                   0x80
 * Abort command bit mapping:            0x90
 * CDMA fatal error flag:                0x10
 * FP mode:                              0x10
 * Error injection bitmap:               0x8
 * Error injection table(8 bytes * 63):  0x1F8
 * Log GDMA DQ pi:                       0x10
 * QoS Penalty (4 bytes * 65):           0x110
 * QoS VF bitmap (8 bytes):              0x8
 * QoS VF 65 bitmap (8 bytes):           0x8
 * CDMA IO abort bit:                    0x8
 * Weight Round Robin (4 bytes)          0x4
 * GCM IV queue (12 bytes * 131 + 16)    0x634
 * CDMA Vault access sequence lock       0x4
 * CrashDump counter                     0x4
 * Total:                                0x2058
 */
#define M7_FPS_CPU12_DFL_1_BUFF_ADDR   FPS_CPU12_SHARE_DTCM_MMIO_START
#define M7_FPS_CPU12_CDMA_SQ_ENTRY_ADDR (M7_FPS_CPU12_DFL_1_BUFF_ADDR + DFL_1_BUFF_SIZE)
#define M7_FPS_CPU12_KEY_TABLE_RGID_TO_VALID_ADDR (M7_FPS_CPU12_CDMA_SQ_ENTRY_ADDR + CDMA_SQ_SIZE)
#define M7_FPS_CPU12_LOG_BUF_INFO_ADDR (M7_FPS_CPU12_KEY_TABLE_RGID_TO_VALID_ADDR + KEY_TABLE_RGID_TO_VALID_SIZE)
#define M7_FPS_CPU12_CP_IO_INTERNAL_BUF_ADDR (M7_FPS_CPU12_LOG_BUF_INFO_ADDR + M7_LOG_BUF_INFO_SIZE)
#define M7_FPS_CPU12_CRASHDUMP_INFO_ADDR (M7_FPS_CPU12_CP_IO_INTERNAL_BUF_ADDR + M7_CP_IO_INTERNAL_BUF_SIZE)
#define M7_FPS_CPU12_CDMA_LIST_1_DFL_BUFF_ADDR (M7_FPS_CPU12_CRASHDUMP_INFO_ADDR + M7_CRASHDUMP_INFO_SIZE)
#define M7_FPS_CPU12_ABORT_BITMAP_ADDR (M7_FPS_CPU12_CDMA_LIST_1_DFL_BUFF_ADDR + M7_CMDA_IDLE_CMD_DFL_BUF_SIZE)
#define M7_FPS_CPU12_CDMA_FATAL_ERROR_OCCUR_FLAG (M7_FPS_CPU12_ABORT_BITMAP_ADDR + M7_ABORT_BITMAP_SIZE)
#define M7_FPS_CPU12_FP_MODE_ADDR (M7_FPS_CPU12_CDMA_FATAL_ERROR_OCCUR_FLAG + M7_CDMA_FATAL_ERROR_OCCUR_FLAG_SIZE)
#if SUPPORT_MSGERROR_INJECTION
#define M7_FPS_CPU12_ERR_INJECTION_BITMAP (M7_FPS_CPU12_FP_MODE_ADDR + M7_FP_MODE_SIZE)
#define M7_FPS_CPU12_ERR_INJECTION_START (M7_FPS_CPU12_ERR_INJECTION_BITMAP + M7_ERR_INJECTION_BITMAP_SIZE)
#define M7_FPS_CPU12_LOG_GDMA_DQ_PI (M7_FPS_CPU12_ERR_INJECTION_START + M7_ERR_INJECT_TOTAL_SIZE)
#else
#define M7_FPS_CPU12_CDMA_SLOT_ABORT_QUEUE (M7_FPS_CPU12_FP_MODE_ADDR + M7_FP_MODE_SIZE)
#define M7_FPS_CPU12_LOG_GDMA_DQ_PI (M7_FPS_CPU12_CDMA_SLOT_ABORT_QUEUE + M7_ERR_INJECTION_BITMAP_SIZE + M7_ERR_INJECT_TOTAL_SIZE)
#endif
#define M7_FPS_CPU12_QOS_PENALTY_ADDR (M7_FPS_CPU12_LOG_GDMA_DQ_PI + M7_FPS_LOG_GDMA_DQ_PI_SIZE)
#define M7_FPS_CPU12_QOS_VF_BITMAP_ADDR (M7_FPS_CPU12_QOS_PENALTY_ADDR + M7_QOS_PENALTY_SIZE)
#define M7_FPS_CPU12_QOS_VF_65_BITMAP_ADDR (M7_FPS_CPU12_QOS_VF_BITMAP_ADDR + M7_SHARE_QOS_VF_BITMAP_SIZE)
#define M7_FPS_CPU12_CDMA_IO_ABORT_BIT_ADDR (M7_FPS_CPU12_QOS_VF_65_BITMAP_ADDR + M7_SHARE_QOS_VF_65_BITMAP_SIZE)
#define M7_FPS_CPU12_WEIGHT_ROUND_ROBIN_ADDR (M7_FPS_CPU12_CDMA_IO_ABORT_BIT_ADDR + M7_FPS_CPU12_CDMA_IO_ABORT_BIT_SIZE)
#define M7_FPS_CPU12_GCM_IV_QUEUE_ADDR (M7_FPS_CPU12_WEIGHT_ROUND_ROBIN_ADDR + M7_SHARE_WEIGHT_ROUND_ROBIN_SIZE)
#define M7_FPS_CPU12_SHARE_DTCM_MMIO_END (M7_FPS_CPU12_GCM_IV_QUEUE_ADDR + GCM_IV_QUEUE_SIZE)

#define M7_FPS_CPU12_CDMA_VAULT_SEQ_LOCK_SIZE 4
#define M7_FPS_CPU12_CDMA_VAULT_SEQ_LOCK (M7_FPS_CPU12_SHARE_DTCM_END - (M7_FPS_CRASH_DUMP_COUNTER_SIZE + M7_FPS_CPU12_CDMA_VAULT_SEQ_LOCK_SIZE))

#define M7_FPS_CPU12_CRASH_DUMP_COUNTER (M7_FPS_CPU12_SHARE_DTCM_END - M7_FPS_CRASH_DUMP_COUNTER_SIZE)
//#define M7_FPS_CPU12_SHARE_DTCM_MMIO_END (M7_FPS_CPU12_CRASH_DUMP_COUNTER + 10)
#if M7_FPS_CPU12_SHARE_DTCM_MMIO_END > M7_FPS_CPU12_CDMA_VAULT_SEQ_LOCK
COMPILE_ASSERT(0, "Total code size exceeds memory limit!");
#endif
/**
 * MMIO allocation in FPS CPU20 share DTCM
 *
 * Slot status:                     0x90
 * Table of IB queue to OB queue:   0x90
 * CE tiny base (4 bytes * 520):    0x820
 * Error pending queue base:        0x80
 * Log buffer info:                 0x20
 * Crash dump info:                 0x80
 * Outstanding I/O count:           0x10
 * Accumulate I/O count:            0x10
 * Admin Abort Count:               0x10
 * Ca index to IB physical id mapping: 0x90
 * Ib physical id to ca index mapping: 0x90
 * Log GDMA DQ pi:                  0x10
 * FLR request bit map:             0x8
 * FLR queue bit map:               0x8
 * FLR 65 queue bit map:            0x10
 * Retry CE queue:                  0x800
 * Refill CE and DFL queue:         0x800
 * FIPS approval status array       0x50
 * GCM request queue                0x1054
 * GCM response queue               0x834
 * CrashDump counter                0x4
 *
 * Total:                           0x34bc
 */
#define M7_FPS_CPU20_SLOT_STATUS_ADDR (FPS_CPU20_SHARE_DTCM_START)
#define M7_FPS_CPU20_IBQ2OBQ_ADDR (M7_FPS_CPU20_SLOT_STATUS_ADDR + SLOT_STATUS_SIZE)
#define M7_FPS_CPU20_CMD_ARRAY_TINY_BASE_ADDR (M7_FPS_CPU20_IBQ2OBQ_ADDR + IBQ2OBQ_SIZE)
#define M7_FPS_CPU20_ERROR_PENDING_QUEUE_BASE_ADDR (M7_FPS_CPU20_CMD_ARRAY_TINY_BASE_ADDR + M7_SHARE_CMD_ARRAY_TINY_SIZE)
#define M7_FPS_CPU20_LOG_BUF_INFO_ADDR (M7_FPS_CPU20_ERROR_PENDING_QUEUE_BASE_ADDR + M7_SHARE_ERROR_PENDING_QUEUE_SIZE)
#define M7_FPS_CPU20_CRASHDUMP_INFO_ADDR (M7_FPS_CPU20_LOG_BUF_INFO_ADDR + M7_LOG_BUF_INFO_SIZE)
#define M7_FPS_CPU20_OUTSTANDING_IO_CNT_ADDR (M7_FPS_CPU20_CRASHDUMP_INFO_ADDR + M7_CRASHDUMP_INFO_SIZE)
#define M7_FPS_CPU20_ACCUMULATE_IO_CNT_ADDR (M7_FPS_CPU20_OUTSTANDING_IO_CNT_ADDR + M7_OUTSTANDING_IO_CNT_SIZE)
#define M7_FPS_CPU20_ADMIN_ABORT_COUNT_ADDR (M7_FPS_CPU20_ACCUMULATE_IO_CNT_ADDR + M7_ACCUMULATE_IO_CNT_SIZE)
#define M7_FPS_CPU20_CA_2_IBPHYQID_TABLE (M7_FPS_CPU20_ADMIN_ABORT_COUNT_ADDR + M7_FPS_CPU20_ADMIN_ABORT_COUNT_SIZE)
#define M7_FPS_CPU20_IBPHYQID_2_CA_TABLE (M7_FPS_CPU20_CA_2_IBPHYQID_TABLE + M7_FPS_CA_2_IBPHYQID_TABLE_SIZE)
#define M7_FPS_CPU20_LOG_GDMA_DQ_PI (M7_FPS_CPU20_IBPHYQID_2_CA_TABLE + M7_FPS_IBPHYQID_2_CA_TABLE_SIZE)
#define M7_FPS_CPU20_FLR_REQUSET_BIT_MAP_LOCAL (M7_FPS_CPU20_LOG_GDMA_DQ_PI + M7_FPS_LOG_GDMA_DQ_PI_SIZE)
#define M7_FPS_CPU20_FLR_QUEUE_BLOCK_BIT_MAP_LOCAL (M7_FPS_CPU20_FLR_REQUSET_BIT_MAP_LOCAL + M7_FPS_FLR_REQUSET_BIT_MAP_LOCAL_SIZE)
#define M7_FPS_CPU20_FLR_QUEUE_BLOCK_65_BIT_MAP_LOCAL (M7_FPS_CPU20_FLR_QUEUE_BLOCK_BIT_MAP_LOCAL + M7_FPS_FLR_QUEUE_BLOCK_BIT_MAP_LOCAL_SIZE)
#define M7_FPS_CPU20_RETRY_CE_QUEUE (M7_FPS_CPU20_FLR_QUEUE_BLOCK_65_BIT_MAP_LOCAL + M7_FPS_FLR_QUEUE_BLOCK_BIT_65_MAP_LOCAL_SIZE)
#define M7_FPS_CPU20_REFILL_CE_DFL_QUEUE (M7_FPS_CPU20_RETRY_CE_QUEUE + M7_SHARE_RETRY_CMD_ENTRY_INFO_SIZE)
#define M7_FPS_CPU20_FIPS_APPROVAL_STS_ARRAY (M7_FPS_CPU20_REFILL_CE_DFL_QUEUE + M7_SHARE_REFILL_CE_DFL_ENTRY_INFO_SIZE)
#define M7_FPS_CPU20_GCM_REQUEST_QUEUE (M7_FPS_CPU20_FIPS_APPROVAL_STS_ARRAY + M7_FPS_CPU20_FIPS_APPROVAL_STS_ARRAY_SIZE)
#define M7_FPS_CPU20_GCM_RESPONSE_QUEUE (M7_FPS_CPU20_GCM_REQUEST_QUEUE + GCM_REQUEST_QUEUE_SIZE)
#define M7_FPS_CPU20_SHARE_DTCM_MMIO_END (M7_FPS_CPU20_GCM_RESPONSE_QUEUE + GCM_RESPONSE_QUEUE_SIZE)
#define M7_FPS_CPU20_CRASH_DUMP_COUNTER (M7_FPS_CPU20_SHARE_DTCM_END - M7_FPS_CRASH_DUMP_COUNTER_SIZE)
//#define M7_FPS_CPU20_SHARE_DTCM_MMIO_END (M7_FPS_CPU20_CRASH_DUMP_COUNTER + 10)
#if M7_FPS_CPU20_SHARE_DTCM_MMIO_END > M7_FPS_CPU20_CRASH_DUMP_COUNTER
COMPILE_ASSERT(0, "Total code size exceeds memory limit!");
#endif

/**
 * GSRAM
 */
#define MEM_GSRAM_START       0xE0460000
#define MEM_GSRAM_SIZE        0x20000

/**
 * UCD register
 */
#define UCD_CPU_CREG_WIN_STRIDE      0x400      // per HIU
#define UCD_HOST_CREG_WIN_STRIDE     0x4000     // per HIU

#define UCD_CPU_CREG_PF_ADDR_START 0xA1100000       // offset UCD_CPU_REG_WIN_STRIDE
#define UCD_CPU_CREG_VF_BASE_ADDR_START 0xA1108000  // offset UCD_CPU_REG_WIN_STRIDE
#define UCD_CMN_REGS_ADDR 0xA1200000
#define UCD_CMN_IB_LGC2PHYS_REGS_ADDR 0xA1201000
#define UCD_CMN_OB_LGC2PHYS_REGS_ADDR 0xA1202000
#define UCD_IB_REGS_ADDR 0xA1280000
#define UCD_OB_REGS_ADDR 0xA12C0000
#define UCD_HOST_CREG_PF_ADDR_START 0xA1300000      // offset UCD_HOST_REG_WIN_STRIDE
#define UCD_HOST_CREG_VF_ADDR_START 0xA1380000      // offset UCD_HOST_REG_WIN_STRIDE

/**
 * CDMA register
 */
#define CDMA_REG_ADDR 0xA0C00000

/**
 * GDMA register
 */
#define GDMA_REG_ADDR 0xA0000000

/**
 * FPS register
 */
#define FPS_REG_ADDR 0x40000000
#define FPS_REG_CMDA_SQ_CI_PHY_ADDR 0xa1e00880
#define FPS_REG_CMDA_CQ_CI_PHY_ADDR 0xa1e00580


/**
 * TCON register
 */
#define TCON_REG_ADDR 0xB0005000

/**
 * Cortexm7 register
 */
#define CORTEXM7_REG_ADDR 0xE0000000

/**
 * Flash map
 */
#define FP_CORE_BINARY_SIZE 0x20000
#define FPS_CPU0_FLASH_START 0
#define FPS_CPU1_FLASH_START (FPS_CPU0_FLASH_START + FP_CORE_BINARY_SIZE)
#define FPS_CPU2_FLASH_START (FPS_CPU1_FLASH_START + FP_CORE_BINARY_SIZE)

#define CPU_PHYSICAL_DTCM_ADDR_MASK 0x0FFFFFFFUL
#define CPU0_PHYSICAL_DTCM_ADDR 0xA3000000
#define CPU1_PHYSICAL_DTCM_ADDR 0xA3200000UL
#define CPU2_PHYSICAL_DTCM_ADDR 0xA3400000UL
#define CPU_AXIM_AHBS_ADDR_MASK 0x000FFFFFUL
#define CPU1_AXIM_CPU0_AHBS_BASE_ADDR 0x30000000UL
#define CPU2_AXIM_CPU0_AHBS_BASE_ADDR 0x30000000UL
#define CPU0_AXIM_CPU1_AHBS_BASE_ADDR 0x30200000UL
#define CPU2_AXIM_CPU1_AHBS_BASE_ADDR 0x30200000UL
#define CPU0_AXIM_CPU2_AHBS_BASE_ADDR 0x30400000
#define CPU1_AXIM_CPU2_AHBS_BASE_ADDR 0x30400000UL
#define PSRAM_BASE_ADDR (PSRAM_START)
#define PSRAM_PHYSICAL_ADDR 0xA3E00000
#define PHYSICAL_FPS_REG_ADDR_MASK 0x0FFFFFFFUL
#define PHYSICAL_FPS_REG_ADDR (0xA1E00000UL)
#define FPS_DTCM_BANK12_OFFSET 0x10000
#define CPU1_ACCESS_SHARE_TCM01_FROM_CPU0_OFFSET 0x10000000
#define CPU0_ACCESS_SHARE_TCM01_FROM_CPU1_OFFSET 0x10200000
#define CPU2_ACCESS_SHARE_TCM20_FROM_CPU0_OFFSET 0x10000000
#define CPU2_ACCESS_SHARE_TCM01_FROM_CPU1_OFFSET 0x10200000
#define getCPU0TCMPhysicalAddress(vir) ((vir & CPU_PHYSICAL_DTCM_ADDR_MASK) | CPU0_PHYSICAL_DTCM_ADDR)
#define getCPU1TCMPhysicalAddress(vir) ((vir & CPU_PHYSICAL_DTCM_ADDR_MASK) | CPU1_PHYSICAL_DTCM_ADDR)
#define getCPU2TCMPhysicalAddress(vir) ((vir & CPU_PHYSICAL_DTCM_ADDR_MASK) | CPU2_PHYSICAL_DTCM_ADDR)
#define CPU0AccessCPU1TCMMem(vir) ((vir & CPU_AXIM_AHBS_ADDR_MASK) | CPU0_AXIM_CPU1_AHBS_BASE_ADDR)
#define CPU0AccessCPU2TCMMem(vir) ((vir & CPU_AXIM_AHBS_ADDR_MASK) | CPU0_AXIM_CPU2_AHBS_BASE_ADDR)
#define CPU1AccessCPU0TCMMem(vir) ((vir & CPU_AXIM_AHBS_ADDR_MASK) | CPU1_AXIM_CPU0_AHBS_BASE_ADDR)
#define CPU1AccessCPU2TCMMem(vir) ((vir & CPU_AXIM_AHBS_ADDR_MASK) | CPU1_AXIM_CPU2_AHBS_BASE_ADDR)
#define CPU2AccessCPU0TCMMem(vir) ((vir & CPU_AXIM_AHBS_ADDR_MASK) | CPU2_AXIM_CPU0_AHBS_BASE_ADDR)
#define CPU2AccessCPU1TCMMem(vir) ((vir & CPU_AXIM_AHBS_ADDR_MASK) | CPU2_AXIM_CPU1_AHBS_BASE_ADDR)
#define getpSRAMPhysicalAddress(vir) ((vir - PSRAM_BASE_ADDR) | PSRAM_PHYSICAL_ADDR)
#define getFPSRegPhysicalAddress(vir) ((vir & PHYSICAL_FPS_REG_ADDR_MASK) | PHYSICAL_FPS_REG_ADDR)
#define GET_FPS_BANK2_ADDR_FROM_BANK1(addr) ((addr + FPS_DTCM_BANK12_OFFSET))
#define CPU1_ACCESS_SHARE_TCM01_FROM_CPU0(addr) ((addr) + CPU1_ACCESS_SHARE_TCM01_FROM_CPU0_OFFSET - FPS_DTCM_BANK12_OFFSET)
#define CPU0_ACCESS_SHARE_TCM01_FROM_CPU1(addr) (addr + CPU0_ACCESS_SHARE_TCM01_FROM_CPU1_OFFSET + FPS_DTCM_BANK12_OFFSET)
#define CPU2_ACCESS_SHARE_TCM20_FROM_CPU0(addr) (addr + CPU2_ACCESS_SHARE_TCM20_FROM_CPU0_OFFSET + FPS_DTCM_BANK12_OFFSET)
#define CPU2_ACCESS_SHARE_TCM01_FROM_CPU1(addr) ((addr) + CPU2_ACCESS_SHARE_TCM01_FROM_CPU1_OFFSET + FPS_DTCM_BANK12_OFFSET)

#endif  // FP3CORE_LDSCRIPTS_M7MEMMAP_H_
