// Copyright (c) Microsoft Corporation. All rights reserved.
// This is an autogenerated file using mem_map_gen.py. Do not edit manually.

#ifndef CDMA_MEM_MAP_H_
#define CDMA_MEM_MAP_H_

enum {
	CDMA_MEM_MAP_KEY_VAULT = 0xa0c01000,
	CDMA_MEM_MAP_KEY_VAULT_SIZE = 0x4000,
};


#endif	//	CDMA_MEM_MAP_H_
