// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef MSFT_DEVICE_ID_H_
#define MSFT_DEVICE_ID_H_


#define	MSFT_DEVICE_ID_CERBERUS					0x0000
#define	MSFT_DEVICE_ID_OMC						0x0001
#define	MSFT_DEVICE_ID_MANTICORE				0x0002
#define	MSFT_DEVICE_ID_CMC						0x0003
#define MSFT_DEVICE_ID_HSP_ATHENA				0x0004
#define MSFT_DEVICE_ID_HSP_PIONEER				0x0005
#define MSFT_DEVICE_ID_TIP						0x0006
#define MSFT_DEVICE_ID_HSP_KINGSGATE			0x0007
#define MSFT_DEVICE_ID_HSP_BRAGA                0x0008
#define MSFT_DEVICE_ID_HSP_BRAGA_R				0x0009

#define	MSFT_SUBSYSTEM_DEVICE_ID_OVERLAKE		0x0000
#define	MSFT_SUBSYSTEM_DEVICE_ID_CERBERUS		0x0001
#define	MSFT_SUBSYSTEM_DEVICE_ID_OMC			0x0002
#define	MSFT_SUBSYSTEM_DEVICE_ID_DC_SCM			0x0003
#define	MSFT_SUBSYSTEM_DEVICE_ID_CMC			0x0004


#endif	/* MSFT_DEVICE_ID_H_ */
