// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef CMD_INTERFACE_MSFT_H_
#define CMD_INTERFACE_MSFT_H_

#include <stdint.h>
#include "cmd_interface/cmd_interface.h"
#include "status/msft_module_id.h"


/**
 * An entry to associate a command handler to a command set identifier for a MSFT command interface.
 */
struct cmd_interface_msft_cmd_set_entry {
	const struct cmd_interface *intf;	/**< The interface to handle messages for the command set. */
	uint8_t set_id;						/**< The target message command set to handle with this entry. */
};

/**
 * Command interface for processing any Microsoft Vendor Defined Protocol (MVDP) messages.  This
 * handler doesn't process any messages directly.  Rather, it's responsible for general message
 * validation and routing.
 */
struct cmd_interface_msft {
	struct cmd_interface base;								/**< Base command interface. */
	const struct cmd_interface_msft_cmd_set_entry *entries;	/**< The list of command set entries. */
	size_t entry_count;										/**< THe number of command set entries. */
};


int cmd_interface_msft_cmd_set_entry_init (struct cmd_interface_msft_cmd_set_entry *entry,
	struct cmd_interface *intf, uint8_t set_id);

int cmd_interface_msft_init (struct cmd_interface_msft *intf,
	const struct cmd_interface_msft_cmd_set_entry *entries, size_t entry_count);
void cmd_interface_msft_release (const struct cmd_interface_msft *intf);

size_t cmd_interface_msft_get_cmd_set_count (const struct cmd_interface_msft *intf);


#define	CMD_HANDLER_MSFT_ERROR(code)				ROT_ERROR (MSFT_MODULE_CMD_HANDLER_MSFT, code)

/**
 * Error codes that can be generated by the MSFT command handler.
 */
enum {
	CMD_HANDLER_MSFT_INVALID_ARGUMENT = CMD_HANDLER_MSFT_ERROR (0x00),		/**< Input parameter is null or not valid. */
	CMD_HANDLER_MSFT_NO_MEMORY = CMD_HANDLER_MSFT_ERROR (0x01),				/**< Memory allocation failed. */
	CMD_HANDLER_MSFT_PAYLOAD_TOO_SHORT = CMD_HANDLER_MSFT_ERROR (0x02),		/**< The request does not contain the minimum amount of data. */
	CMD_HANDLER_MSFT_BAD_LENGTH = CMD_HANDLER_MSFT_ERROR (0x03),			/**< The payload length is wrong for the request. */
	CMD_HANDLER_MSFT_OUT_OF_RANGE = CMD_HANDLER_MSFT_ERROR (0x04),			/**< A request argument is not within the valid range. */
	CMD_HANDLER_MSFT_UNKNOWN_COMMAND = CMD_HANDLER_MSFT_ERROR (0x05),		/**< A command does not represent a known request. */
	CMD_HANDLER_MSFT_UNSUPPORTED_INDEX = CMD_HANDLER_MSFT_ERROR (0x06),		/**< Request for information with an unsupported index was received. */
	CMD_HANDLER_MSFT_BUF_TOO_SMALL = CMD_HANDLER_MSFT_ERROR (0x07),			/**< Provided buffer too small for output. */
	CMD_HANDLER_MSFT_UNSUPPORTED_MSG = CMD_HANDLER_MSFT_ERROR (0x08),		/**< The message is not valid for the handler. */
	CMD_HANDLER_MSFT_UNSUPPORTED_OPERATION = CMD_HANDLER_MSFT_ERROR (0x09),	/**< The requested operation is not supported. */
	CMD_HANDLER_MSFT_UNKNOWN_COMMAND_SET = CMD_HANDLER_MSFT_ERROR (0x0a),	/**< A command does not belong to a known command set. */
	CMD_HANDLER_MSFT_BAD_MAX_RESPONSE = CMD_HANDLER_MSFT_ERROR (0x0b),		/**< The message max response length is not valid. */
	CMD_HANDLER_MSFT_INCOMPATIBLE = CMD_HANDLER_MSFT_ERROR (0x0c),			/**< The message version is not compatible with the handler. */
	CMD_HANDLER_MSFT_UNSUPPORTED_CMD = CMD_HANDLER_MSFT_ERROR (0x0d),		/**< The command is not supported by the handler. */
	CMD_HANDLER_MSFT_NO_HEADER_SPACE = CMD_HANDLER_MSFT_ERROR (0x0e),		/**< There is not enough room in a message buffer for the MVDP header. */
};


#endif	/* CMD_INTERFACE_MSFT_H_ */
