// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef TEMPERATURE_SENSOR_CLUSTER_H_
#define TEMPERATURE_SENSOR_CLUSTER_H_

#include <stdint.h>
#include "status/msft_module_id.h"
#include "system/temperature_sensor.h"


/* Forward declare structure for temperature output to avoid circular dependency. */
struct msft_base_temperature_reading;

/**
 * Manages a set of temperature sensors.
 */
struct temperature_sensor_cluster {
	const struct temperature_sensor *const *sensors;	/**< An array of sensor entries to manage. */
	size_t sensor_count;								/**< The number of entries in the sensors array. */
};


int temperature_sensor_cluster_init (struct temperature_sensor_cluster *cluster,
	const struct temperature_sensor *const *sensors, size_t sensor_count);
void temperature_sensor_cluster_release (const struct temperature_sensor_cluster *cluster);

size_t temperature_sensor_cluster_get_sensor_count (
	const struct temperature_sensor_cluster *cluster);
int temperature_sensor_cluster_get_sensor (const struct temperature_sensor_cluster *cluster,
	size_t index, const struct temperature_sensor **sensor);

int temperature_sensor_cluster_sensor_range_get_temps (
	const struct temperature_sensor_cluster *cluster, size_t index,
	struct msft_base_temperature_reading *temps, size_t count);


#define TEMP_SENSOR_CLUSTER_ERROR(code)		ROT_ERROR (MSFT_MODULE_TEMP_SENSOR_CLUSTER, code)

/**
 * Error codes that can be generated by the temperature sensor cluster.
 */
enum {
	TEMP_SENSOR_CLUSTER_INVALID_ARGUMENT = TEMP_SENSOR_CLUSTER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	TEMP_SENSOR_CLUSTER_NO_MEMORY = TEMP_SENSOR_CLUSTER_ERROR (0x01),			/**< Memory allocation failed. */
	TEMP_SENSOR_CLUSTER_OUT_OF_RANGE = TEMP_SENSOR_CLUSTER_ERROR (0x02),		/**< Sensor index is out of range. */
};


#endif	/* TEMPERATURE_SENSOR_CLUSTER_H_ */
