# SPDX-License-Identifier: MIT
# Copyright (c) 2021-2026 Marvell

# ---------------------------------------------------------
#
#  Variables need to be defined first
#
#
# ---------------------------------------------------------

# Check that given variables are set and all have non-empty values,
# die with an error otherwise.
#
# Params:
#   1. Variable name(s) to test.
#   2. (optional) Error message to print.

check_defined =  \
    $(strip $(foreach 1,$1, \
        $(call __check_defined,$1,$(strip $(value 2)))))

__check_defined = \
    $(if $(value $1),, \
      $(error Undefined $1$(if $2, ($2))))


check_file_exist =  \
    $(if $(wildcard $1),, \
      $(error File $1 does not exist!))


# ---------------------------------------------------------
#
#  Standard Options
#
#
# ---------------------------------------------------------

# ARM-Toolchiain is available at https://developer.arm.com/
ARM_TOOLCHAIN_VER = gcc-arm-none-eabi-7-2017-q4-major
# ARM Toolchain search path  variable
REL := $(shell find /usr/local/ /opt/ -type d -name $(ARM_TOOLCHAIN_VER))
ifeq ($(strip $(REL)),)
REL := $(shell whereis arm-none-eabi-gcc-7.2.1 | sed 's/^[^ ]* //' | sed 's/bin\/arm-none-eabi-gcc-7.2.1//g')
ifeq ($(strip $(REL)),)
$(error Failed to find arm-toolchain "$(ARM_TOOLCHAIN_VER)")
endif
endif

# Shell command
PWD := pwd
RM := rm
CAT := cat
SREC_CAT := $(REL)/sim_tools/srecord-1.64/bin/srec_cat
HEXDUMP  := /usr/bin/hexdump
GCC_VER  := 4_9
#GCC_VER  := 6_2
#GCC_ARM_TOOLCHAIN := $/proj/$(MRVL_PROJECT)/release/sim_tools/gcc-linaro-arm-none-eabi-4_9-2014q4


# Tool Chains
ifeq ($(GCC_VER),4_9)
GCC_ARM_TOOLCHAIN := $(REL)
else ifeq ($(GCC_VER),6_2)
GCC_ARM_TOOLCHAIN := $(REL)
endif

CC      =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-gcc
CXX     =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-g++
AS      =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-gcc

ifeq ($(CORTEX_CORE),m7)
  #LD    =  $(CC)
  LD    =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-ld.bfd
  #LD    =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-ld
else ifeq ($(CORTEX_CORE),r5)
  LD    =  $(CC)
else
  $(error "CORTEX_CORE=$(CORTEX_CORE) unsupported")
endif

OBJCOPY =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-objcopy
OBJDUMP =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-objdump
SIZE    =  $(GCC_ARM_TOOLCHAIN)/bin/arm-none-eabi-size


# Options for specific architecture
ifeq ($(CORTEX_CORE),m7)
  ARCH_FLAGS=-mthumb -march=armv7e-m
else ifeq ($(CORTEX_CORE),r5)
  ARCH_FLAGS=-mthumb -march=armv7-r
else
  $(error "CORTEX_CORE=$(CORTEX_CORE) unsupported")
endif


#
CFLAGS=$(ARCH_FLAGS) $(INC_OPTS) -c -O3 -fno-delete-null-pointer-checks -g -std=c11 -D$(NAME)Core -DDEBUG_LEVEL=$(DEBUG_LEVEL) -DPLATFORM=$(PLATFORM) -DRAID_MODE=$(RAID_MODE) -DSTRIPE_SIZE=$(STRIPE_SIZE) -DLBA_SIZE=$(LBA_SIZE) -DMPS=$(MPS) $(CSDEFINES)  -DMEM_MAP_FW
#CFLAGS=$(ARCH_FLAGS) $(INC_OPTS) -c -O1 -g -std=c99 -D$(NAME)Core -DDEBUG_LEVEL=$(DEBUG_LEVEL) -DPLATFORM=$(PLATFORM) -DRAID_MODE=$(RAID_MODE) -DSTRIPE_SIZE=$(STRIPE_SIZE) -DLBA_SIZE=$(LBA_SIZE) -DMPS=$(MPS) $(CSDEFINES)

CXXFLAGS=$(ARCH_FLAGS) $(INC_OPTS) -c -g -O3 -xc++ -std=gnu++14  -fno-rtti -fno-exceptions -fpermissive -Wno-invalid-offsetof -mcpu=cortex-m7 -D$(NAME)Core -DDEBUG_LEVEL=$(DEBUG_LEVEL) -DPLATFORM=$(PLATFORM) -DRAID_MODE=$(RAID_MODE) -DSTRIPE_SIZE=$(STRIPE_SIZE) -DLBA_SIZE=$(LBA_SIZE) -DMPS=$(MPS) $(CSDEFINES)  -DMEM_MAP_FW

# Org
#CXXFLAGS=$(ARCH_FLAGS) $(INC_OPTS) -c -g -O3 -Os -mfloat-abi=soft  -xc++ -std=gnu++14 -fno-exceptions -fno-rtti -Wno-invalid-offsetof -mcpu=cortex-m7 -D$(NAME)Core -DDEBUG_LEVEL=$(DEBUG_LEVEL) -DPLATFORM=$(PLATFORM) -DRAID_MODE=$(RAID_MODE) -DSTRIPE_SIZE=$(STRIPE_SIZE) -DLBA_SIZE=$(LBA_SIZE) -DMPS=$(MPS) $(CSDEFINES)  -DMEM_MAP_FW

ifneq ($(FLASH_BOOT),)
CFLAGS += -DFLASH_BOOT=$(FLASH_BOOT)
endif

ifeq ($(PLATFORM),)
override PLATFORM := NRAE
endif

ifneq ($(MODE),)
CFLAGS += -DMODE_$(MODE)
CXXFLAGS += -DMODE_$(MODE)
endif

ifneq ($(LOGGING),)
CFLAGS += -DLOGGING_NEW_SCHEME
CXXFLAGS += -DLOGGING_NEW_SCHEME
endif

ifeq "$(QMGR)" "QUEUE_BLOCK_BALANCE"
CFLAGS   += -DQUEUE_BLOCK_BALANCE
CXXFLAGS += -DQUEUE_BLOCK_BALANCE
endif

ifeq "$(ERRINJECT)" "ENABLE"
CFLAGS   += -DSUPPORT_ERROR_INJECTION
CXXFLAGS += -DSUPPORT_ERROR_INJECTION
endif

ifeq "$(NEWAESKEYVALIDATION)" "ENABLE"
CFLAGS   += -DNEW_AES_KEY_VALIDATION_SUPPORT
CXXFLAGS += -DNEW_AES_KEY_VALIDATION_SUPPORT
endif

ifeq "$(FPCLEARPSRAM)" "ENABLE"
CFLAGS   += -DWA_ZEROOUT_PSRAM_IN_FP
CXXFLAGS += -DWA_ZEROOUT_PSRAM_IN_FP
endif

ifeq "$(MCRTESTHOOKS)" "ENABLE"
CFLAGS   += -DMCR_TEST_HOOKS
CXXFLAGS += -DMCR_TEST_HOOKS
endif

ifeq "$(DEBUGBUILD)" "ENABLE"
CFLAGS   += -DDEBUG_BUILD
CXXFLAGS += -DDEBUG_BUILD
endif

ifeq "$(PRERESETFAULTINJECTION)" "ENABLE"
CFLAGS   += -DPRE_RESET_FAULT_INJECTION_SUPPORT
CXXFLAGS += -DPRE_RESET_FAULT_INJECTION_SUPPORT
endif

ifeq "$(POSTRESETFAULTINJECTION)" "ENABLE"
CFLAGS   += -DPOST_RESET_FAULT_INJECTION_SUPPORT
CXXFLAGS += -DPOST_RESET_FAULT_INJECTION_SUPPORT
endif

ifeq "$(LIONPERF_SUPPORT)" "ENABLE"
CFLAGS   += -DLIONPERF_SUPPORT
CXXFLAGS += -DLIONPERF_SUPPORT
endif

#CXXFLAGS=$(CFLAGS)
ASFLAGS= $(ARCH_FLAGS) $(INC_OPTS) -c $(CSDEFINES)

ifeq ($(CORTEX_CORE),m7)
  #LFLAGS= -Xlinker -Map=$(NAME).map
  #LFLAGS=$(LIB_OPTS) -Xlinker -Map=$(NAME).map
  LFLAGS=$(LIB_OPTS) -Map=$(NAME).map
else ifeq ($(CORTEX_CORE),r5)
  LFLAGS=$(LIB_OPTS) -Xlinker -Map=$(NAME).map
else
  $(error "CORTEX_CORE=$(CORTEX_CORE) unsupported")
endif

COPYFLAGS = -O verilog --set-section-flags .bss=alloc,load,contents
COPYFLAGS_BIN = -O binary --set-section-flags .bss=alloc,load,contents
DUMPFLAGS = -D -S

ifeq ($(GCC_VER),4_9)
   ifeq ($(CORTEX_CORE),m7)
     #LIB_OPTS=-L . \
              -L $(GCC_ARM_TOOLCHAIN)/lib/gcc/arm-none-eabi/7.2.1/thumb/v7e-m/ \
              -L $(GCC_ARM_TOOLCHAIN)/arm-none-eabi/lib/thumb/v7e-m/ \
              -lgcc \
              -lc
     LIB_OPTS=-L . \
              -L $(GCC_ARM_TOOLCHAIN)/lib/gcc/arm-none-eabi/7.2.1/thumb/v7e-m/ \
              -L $(GCC_ARM_TOOLCHAIN)/arm-none-eabi/lib/thumb/v7e-m/ \
              -lgcc\
              -lstdc++ \
              -lc
   else ifeq ($(CORTEX_CORE),r5)
     LIB_OPTS=-L . \
              -L $(GCC_ARM_TOOLCHAIN)/lib/gcc/arm-none-eabi/5.4.1/armv7-ar/thumb/ \
              -L $(GCC_ARM_TOOLCHAIN)/arm-none-eabi/lib/armv7-ar/thumb/ \
              -lgcc \
              -lc \
              --specs=nano.specs -nostartfiles
   else
     $(error "CORTEX_CORE=$(CORTEX_CORE) unsupported")
   endif
else ifeq ($(GCC_VER),6_2)
   ifeq ($(CORTEX_CORE),m7)
     LIB_OPTS=-L . \
              -L $(GCC_ARM_TOOLCHAIN)/lib/gcc/arm-none-eabi/6.2.1/thumb/v7e-m/ \
              -L $(GCC_ARM_TOOLCHAIN)/arm-none-eabi/lib/thumb/v7e-m/ \
              -lgcc \
              -lc
   else ifeq ($(CORTEX_CORE),r5)
     LIB_OPTS=-L . \
              -L $(GCC_ARM_TOOLCHAIN)/lib/gcc/arm-none-eabi/6.2.1/thumb/v7-ar/ \
              -L $(GCC_ARM_TOOLCHAIN)/arm-none-eabi/lib/thumb/v7-ar/ \
              -lgcc \
              -lc \
              --specs=nano.specs -nostartfiles
   else
     $(error "CORTEX_CORE=$(CORTEX_CORE) unsupported")
   endif
endif

INC_OPTS=-I$(MAKECONF_DIR)/ldscripts -I$(MAKECONF_DIR)/hal/common/ -I$(ODIR) -I$(HAL_DIR) -I$(RAL_DIR)


#
# PATH
#
CURDIR := $(shell $(PWD))

# SIM_PRJ must be set
$(call check_defined, SIM_PRJ)

# BLDDIR must be set
$(call check_defined,BLDDIR)
BLDPATH := $(shell cd $(BLDDIR) && $(PWD))
ODIR=$(BLDPATH)/$(NAME)_compile

# RAID_MODE must be set
#$(call check_defined, RAID_MODE)

# MAKECONF_DIR is the directory for Makefile.conf. Must be set by parent Makefile
$(call check_defined,MAKECONF_DIR)

#
# Other variables
THIS_MAKEFILE:= $(CURDIR)/Makefile
DEBUG_LEVEL ?= 2
STRIPE_SIZE ?= 7
LBA_SIZE ?= 12
MPS ?= 12
#PLATFORM ?= NRAE
HAL_DIR ?= $(MAKECONF_DIR)/hal
RAL_DIR ?= $(MAKECONF_DIR)/ral
SYS_DIR ?= $(MAKECONF_DIR)/CM7/system
OSYSDIR ?= $(BLDPATH)/system

# ---------------------------------------------------------
#
#  General Purpose Rules
#
#
# ---------------------------------------------------------

.SUFFIXES:
	MAKEFLAGS += --no-builtin-rules

.SECONDEXPANSION:

.PHONY: all clean info output

.DEFAULT:
	@echo "Usage: make all | clean"

FORCE:

info:
	@echo "#INFO: Executing $(THIS_MAKEFILE) ...";

clean:
	@$(RM) -rf $(ODIR);$(RM) -rf $(OSYSDIR);echo $(DEFAULT_GOAL)

output:
	@test -d $(ODIR) || mkdir $(ODIR); \
        $(RM) -f $(ODIR)/*;


# for debug: print variable
#  e.g. make print-CURDIR
print-%: FORCE
	@echo $*=$($*)



# ---------------------------------------------------------
#
#  Common Rules
#
#
# ---------------------------------------------------------

#    Macro Rule: C_STATIC_RULE
#
#    This macro creates a rule which build list of object files from respective .c files.
#    The rule is implemented based on GNU static pattern rule.
#
#    Syntax:
#
#        $(eval $(call C_STATIC_RULE,<target>,<srcdir>,<opt>)
#
#           target:   the variable which is list of .o files (with stem)
#           srcdir:   the directory where the source resides
#           opt:      the additioanl option
#
#    Example:
#        my_obj = a.o b.o c.o
#        my_opt = -I/porj/inc/
#        my_srcdir = /proj/fw/ccp/src
#
#        $(eval $(call C_STATIC_RULE,$(my_obj),$(my_srcdir)),$(my_opt)))
#
define C_STATIC_RULE
$(1): $(ODIR)/%.o: $(2)/%.c
	@echo ; \
        echo "$$(THIS_MAKEFILE): ****** Building $$@...";
	@mkdir -p $$(@D)
	$(CC) $(CFLAGS) -o $$@ $$< -I$(2) $(3)
endef

define CPP_STATIC_RULE
$(1): $(ODIR)/%.o: $(2)/%.cpp
	@echo ; \
        echo "$$(THIS_MAKEFILE): ****** Building CPP$$@...";
	@mkdir -p $$(@D)
	$(CXX) $(CXXFLAGS) -o $$@ $$< -I$(2) $(3)
endef

#    Macro Rule: S_STATIC_RULE
#
#    This macro creates a rule which build list of object files from respective .S files.
#    The rule is implemented based on GNU static pattern rule.
#
#    Syntax:
#
#        $(eval $(call S_STATIC_RULE,<target>,<srcdir>,<opt>)
#
#           target:   the variable which is list of .S files (with stem)
#           srcdir:   the directory where the source resides
#           opt:      the additional option
#
#    Example:
#        my_obj = a.o b.o c.o
#        my_opt = -I/porj/inc/
#        my_srcdir = /proj/fw/ccp/src
#        $(eval $(call S_STATIC_RULE,$(my_obj),$(my_srcdir),$(my_opt)))
#
define S_STATIC_RULE
$(1): $(ODIR)/%.o: $(2)/%.S
	@echo ; \
        echo "$$(THIS_MAKEFILE): ****** Building $$@...";
	$(AS) $(ASFLAGS) -o $$@ $$< -I$(2) $(3)
endef


#    Macro Rule: TIM_RULE
#
#    This macro creates binary file based on TIM input descriptor file
#
#    Syntax:
#
#        $(eval $(call TIM_RULE,<target> <tim_src>,<tim_srcdir>,<tim_opt>)
#
#           target:     target name
#           tim_src:    source TIM descriptor file
#           tim_srcdir: directory where the source TIM resides
#           opt:        additioanl TIM option
#
#    Example:
#        src = bootloader.tim
#        srcdir = /proj/fw/tim
#        opt = -media 1
#
#        $(eval $(call TIM_RULE,tim,$(src),$(srcdir)),$(opt)))
#
define TIM_RULE
$(1):
	@echo ; \
        echo "$$(THIS_MAKEFILE): ****** Building $$@...";
	cd $(ODIR); \
	$(SIM_PRJ)/fw/tools/timv4_builder.pl -i $(3)/$(2) -o $(2).bin $(4);
endef


#    Macro Rule: OTP_RULE
#
#    This macro creates binary file based on OTP input descriptor file
#
#    Syntax:
#
#        $(eval $(call OTP_RULE,<target> <otp_src>,<otp_srcdir>,<otp_opt>)
#
#           target:     target name
#           otp_src:    source OTP descriptor file
#           otp_srcdir: directory where the source OTP resides
#           opt:        additioanl OTP option
#
#    Example:
#        src = bootloader.otp
#        srcdir = /proj/fw/tim
#        opt =
#
#        $(eval $(call OTP_RULE,otp,$(src),$(srcdir)),$(opt)))
#
define OTP_RULE
$(1):
	@echo ; \
        echo "$$(THIS_MAKEFILE): ****** Building $$@...";
	cd $(ODIR); \
	$(SIM_PRJ)/fw/tools/otp_builder.pl -i $(3)/$(2) -o $(2).bin $(4);
endef
