// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef TEMPERATURE_SENSOR_H_
#define TEMPERATURE_SENSOR_H_

#include <stdint.h>
#include "status/msft_module_id.h"


/**
 * Defines the API for temperature sensor access.
 */
struct temperature_sensor {
	/**
	 * Get the temperature sensor reading.
	 *
	 * @param temp_sensor The temperature sensor driver instance to use.
	 * @param temp Output for the current temperature reading from the sensor in hundredths of a
	 *  degree Celsius.
	 *
	 * @return 0 if temperature sensor reading successfully retrieved or an error code.
	*/
	int (*get_temp) (const struct temperature_sensor *temp_sensor, int16_t *temp);
};


#define TEMP_SENSOR_ERROR(code)		ROT_ERROR (MSFT_MODULE_TEMP_SENSOR, code)

/**
 * Error codes that can be generated by the temperature sensor driver.
 */
enum {
	TEMP_SENSOR_INVALID_ARGUMENT = TEMP_SENSOR_ERROR (0x00),	/**< Input parameter is null or not valid. */
	TEMP_SENSOR_NO_MEMORY = TEMP_SENSOR_ERROR (0x01),			/**< Memory allocation failed. */
	TEMP_SENSOR_GET_TEMP_FAILED = TEMP_SENSOR_ERROR (0x02),		/**< Failed to get temperature. */
};


#endif	/* TEMPERATURE_SENSOR_H_ */
