// SPDX-License-Identifier: MIT
// Copyright (c) 2021-2026 Marvell

/***********************************************************************************
 *
 * @file ArmIntrinsics.h
 *
 * Header file for Arm Intrinsics
 *
 ***********************************************************************************/
#pragma once
#ifdef __cplusplus
extern "C"
{
#endif

/***********************************************************************************
 *                                                                                  *
 * Dependencies                                                                     *
 *                                                                                  *
 ***********************************************************************************/

/***********************************************************************************
 *                                                                                  *
 * Constant Definitions                                                             *
 *                                                                                  *
 ***********************************************************************************/

/***********************************************************************************
 *                                                                                  *
 * Macros Definitions                                                               *
 *                                                                                  *
 ***********************************************************************************/

/***********************************************************************************
 *                                                                                  *
 * Private Data Type Definitions                                                    *
 *                                                                                  *
 ***********************************************************************************/

/***********************************************************************************
 *                                                                                  *
 * Public Function Declarations                                                     *
 *                                                                                  *
 ***********************************************************************************/
//-----------------------------------------------------------------------------
/**
    @brief  Get return address.\n

    @param[in]  N/A

    @return     return address
 **/
//-----------------------------------------------------------------------------
unsigned int __return_address(void);

//-----------------------------------------------------------------------------
/**
    @brief  Get current SP.\n

    @param[in]  N/A

    @return     SP
 **/
//-----------------------------------------------------------------------------
inline unsigned int __current_sp(void)
{
    return 0;
}

//-----------------------------------------------------------------------------
/**
    @brief  inserts a BKPT instruction into the instruction stream generated by the compiler.\n

    @param[in]  val    a compile-time constant integer

    @return     N/A
 **/
//-----------------------------------------------------------------------------
void __breakpoint(int val);

//-----------------------------------------------------------------------------
/**
    @brief   returns the a value with the bit order is to be reversed.

    @param[in]  val     the data value whose bit order is to be reversed.

    @return    the data value with the bit order is to be reversed.
 **/
//-----------------------------------------------------------------------------
unsigned int __rbit(unsigned int value);

//-----------------------------------------------------------------------------
/**
    @brief  count the number of leading zeros of a data value .\n

    @param[in]  val    data

    @return     the number of leading zeros in val
 **/
//-----------------------------------------------------------------------------
unsigned char __clz(unsigned int value);

//-----------------------------------------------------------------------------
/**
    @brief  rotate a value right by a specified number of places .\n

    @param[in]  val    data

    @return     the number of leading zeros in val
 **/
//-----------------------------------------------------------------------------
unsigned int __ror(unsigned int val, unsigned int shift);

//-----------------------------------------------------------------------------
/**
    @brief  creates a special sequence point that prevents operations with side
            effects from moving past it under all circumstances .\n

    @param[in]  N/A

    @return     N/A
 **/
//-----------------------------------------------------------------------------
void __schedule_barrier(void);

//-----------------------------------------------------------------------------
/**
    @brief  inserts a NOP instruction or an equivalent code sequence into the instruction stream .\n

    @param[in]  N/A

    @return     N/A
 **/
//-----------------------------------------------------------------------------
void __nop(void);

//-----------------------------------------------------------------------------
/**
    @brief  causes all variables that are visible outside the current function,
            such as variables that have pointers to them passed into or out of the function,
            to be written back to memory if they have been changed .\n

    @param[in]  N/A

    @return     N/A
 **/
//-----------------------------------------------------------------------------
void __force_stores(void);

//-----------------------------------------------------------------------------
/**
    @brief  inserts a WFI instruction into the instruction stream generated by the compiler .\n

    @param[in]  N/A

    @return     N/A
 **/
//-----------------------------------------------------------------------------
void __wfi(void);

//-----------------------------------------------------------------------------
/**
    @brief  Data sync Barrier.\n

    @param[in]  int

    @return     N/A
 **/
//-----------------------------------------------------------------------------
void __dsb(unsigned int);

//-----------------------------------------------------------------------------
/**
    @brief  REV.\n

    @param[in]  unsigned int

    @return     unsigned int
 **/
//-----------------------------------------------------------------------------
unsigned int __rev(unsigned int value);

#ifdef __cplusplus
}
#endif
