// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef ECC_HW_PKA_H_
#define ECC_HW_PKA_H_

#include <stddef.h>
#include <stdint.h>
#include "platform_api.h"
#include "crypto/ecc_hw.h"
#include "drivers/hsp_rng_hw.h"
#include "splibs/inc/spcryptotypes.h"
#include "trap/hsp_interrupt_handler.h"


/* Defined in HSP register definition. */
struct Pka_regs;
struct Creg_regs_creg_crypto_group;

/**
 * Container for a 256-bit integer used by PKA with modular operations.
 */
union ecc_hw_pka_int_256 {
	struct {
		SP_MSG_256 value;	/**< The integer value. */
		uint32_t mask;		/**< Arithmetic masking used when represented in Montgomery format. */
	};

	/**
	 * Montgomery formatted data that is used as input or output values to PKA.
	 */
	uint8_t mont[SP_MSG_256_SIZE + sizeof (uint32_t)];
};

/**
 * Container for a 384-bit integer used by PKA with modular operations.
 */
union ecc_hw_pka_int_384 {
	struct {
		SP_MSG_384 value;	/**< The integer value. */
		uint32_t mask;		/**< Arithmetic masking used when represented in Montgomery format. */
	};

	/**
	 * Montgomery formatted data that is used as input or output values to PKA.
	 */
	uint8_t mont[SP_MSG_384_SIZE + sizeof (uint32_t)];
};

/**
 * Container for a 521-bit integer used by PKA with modular operations.
 */
union ecc_hw_pka_int_521 {
	struct {
		SP_MSG_521_ALIGNED value;	/**< The integer value. */
		uint32_t mask;				/**< Arithmetic masking used when represented in Montgomery format. */
	};

	/**
	 * Montgomery formatted data that is used as input or output values to PKA.
	 */
	uint8_t mont[SP_MSG_521_ALIGNED_SIZE + sizeof (uint32_t)];
};

/**
 * Length of an integer in Montgomery format.
 *
 * @param x The number of bytes in the integer.
 *
 * @return Length of the Montgomery representation for the value, in bytes.
 */
#define	ECC_HW_PKA_MONT_LENGTH_FROM_BYTES(x)	((((x) + 0x3) & ~0x3) + 4)

/**
 * Length of an integer in Montgomery format.
 *
 * @param x The number of bits in the integer.
 *
 * @return Length of the Montgomery representation for the value, in bytes.
 */
#define	ECC_HW_PKA_MONT_LENGTH_FROM_BITS(x)		(((((x) + 31) / 8) & ~0x3) + 4)


/**
 * The command structure to use for issuing PKA commands.  This structure must be stored in HSP
 * shared RAM for PKA to be able to access it and must be allocated at a 32-bit aligned address.
 */
struct ecc_hw_pka_command {
	uint32_t command_code;	/**< The command that should be executed. */
	uint32_t result;		/**< Pointer to the result generated by the command. */
	uint32_t arg1;			/**< First input argument for the command. */
	uint32_t arg2;			/**< Second input argument for the command. */
	uint32_t arg3;			/**< Third input argument for the command. */
};

/**
 * Memory buffer to use for passing arguments to the PKA for command execution.  Which inputs are
 * necessary depends on the command that is being executed.
 *
 * The types of input are grouped for memory efficiency while providing the necessary buffers for
 * all supported commands.
 */
struct ecc_hw_pka_input {
	union {
		union {
			SP_MSG_256 sha256;										/**< 256-bit digest. */
			SP_MSG_384 sha384;										/**< 384-bit digest. */
			SP_MSG_512 sha512;										/**< 512-bit digest. */
			uint8_t bytes[SP_MSG_512_SIZE];							/**< Raw byte array access to the input digest. */
		} digest;
		union {
			SP_MSG_256 p256;										/**< Prime for P256 ECC operations. */
			SP_MSG_384 p384;										/**< Prime for P384 ECC operations. */
			SP_MSG_521_ALIGNED p521;								/**< Prime for P521 ECC operations. */
			uint8_t bytes[SP_MSG_521_ALIGNED_SIZE];					/**< Raw byte array access to the curve prime. */
		} ecc_prime;												/**< ECC curve prime value (p). */
		union {
			SP_MSG_256 p256;										/**< 256-bit integer value for a modular operation. */
			SP_MSG_384 p384;										/**< 384-bit integer value for a modular operation. */
			SP_MSG_521_ALIGNED p521;								/**< 521-bit integer value for a modular operation. */
			uint8_t bytes[SP_MSG_521_ALIGNED_SIZE];					/**< Raw byte array access the integer value. */
		} int_arg1;													/**< Normal representation of an integer value (little endian). */
		union {
			union ecc_hw_pka_int_256 p256;							/**< 256-bit Montgomery value for a modular operation. */
			union ecc_hw_pka_int_384 p384;							/**< 384-bit Montgomery value for a modular operation. */
			union ecc_hw_pka_int_521 p521;							/**< 521-bit Montgomery value for a modular operation. */
			uint8_t bytes[ECC_HW_PKA_MONT_LENGTH_FROM_BITS (521)];	/**< Raw byte array access to the Montgomery representation. */
		} mont_arg1;												/**< Montgomery representation of an integer value. */
	};

	union {
		union {
			SP_ECDSA_P256_PUBLIC p256;								/**< P256 ECC point or public key. */
			SP_ECDSA_P384_PUBLIC p384;								/**< P384 ECC point or public key. */
			SP_ECDSA_P521_ALIGNED_PUBLIC p521;						/**< P521 ECC point or public key. */
			uint8_t bytes[SP_ECDSA_P521_ALIGNED_PUBLIC_KEY_SIZE];	/**< Raw byte array access to the ECC public key. */
		} public;													/**< ECC public key input. */
		union {
			SP_MSG_256 p256;										/**< P256 ECC private key. */
			SP_MSG_384 p384;										/**< P384 ECC private key. */
			SP_MSG_521_ALIGNED p521;								/**< P521 ECC private key. */
			uint8_t bytes[SP_MSG_521_ALIGNED_SIZE];					/**< Raw byte array access to the ECC private key. */
		} private;													/**< ECC private key input. */
		union {
			SP_MSG_256 p256;										/**< 256-bit integer value for a modular operation. */
			SP_MSG_384 p384;										/**< 384-bit integer value for a modular operation. */
			SP_MSG_521_ALIGNED p521;								/**< 521-bit integer value for a modular operation. */
			uint8_t bytes[SP_MSG_521_ALIGNED_SIZE];					/**< Raw byte array access the integer value. */
		} int_arg2;													/**< Normal representation of an integer value (little endian). */
		union {
			union ecc_hw_pka_int_256 p256;							/**< 256-bit Montgomery value for a modular operation. */
			union ecc_hw_pka_int_384 p384;							/**< 384-bit Montgomery value for a modular operation. */
			union ecc_hw_pka_int_521 p521;							/**< 521-bit Montgomery value for a modular operation. */
			uint8_t bytes[ECC_HW_PKA_MONT_LENGTH_FROM_BITS (521)];	/**< Raw byte array access to the Montgomery representation. */
		} mont_arg2;												/**< Montgomery representation of an integer value. */
	};

	union {
		union {
			SP_ECDSA_P256_SIGNATURE p256;							/**< An P256 ECDSA signature. */
			SP_ECDSA_P384_SIGNATURE p384;							/**< An P384 ECDSA signature. */
			SP_ECDSA_P521_ALIGNED_SIGNATURE p521;					/**< An P521 ECDSA signature. */
			uint8_t bytes[SP_ECDSA_P521_ALIGNED_SIGNATURE_SIZE];	/**< Raw byte array access to the ECDSA signature. */
		} signature;												/**< Input buffer for ECDSA signatures. */
		union {
			SP_ECDSA_P256_PUBLIC p256;								/**< P256 ECC point or public key. */
			SP_ECDSA_P384_PUBLIC p384;								/**< P384 ECC point or public key. */
			SP_ECDSA_P521_ALIGNED_PUBLIC p521;						/**< P521 ECC point or public key. */
			uint8_t bytes[SP_ECDSA_P521_ALIGNED_PUBLIC_KEY_SIZE];	/**< Raw byte array access to the ECC point. */
		} point;													/**< ECC point on a curve. */
	};
};

/**
 * The output structure that is generated by PKA commands.  The output that is generated depends on
 * the command that was executed.
 */
union ecc_hw_pka_output {
	uint32_t is_not_valid;										/**< Signature and point verification result. */
	union {
		SP_ECDSA_P256_SIGNATURE p256;							/**< An P256 ECDSA signature. */
		SP_ECDSA_P384_SIGNATURE p384;							/**< An P384 ECDSA signature. */
		SP_ECDSA_P521_ALIGNED_SIGNATURE p521;					/**< An P521 ECDSA signature. */
		uint8_t bytes[SP_ECDSA_P521_ALIGNED_SIGNATURE_SIZE];	/**< Raw byte array access to the ECDSA signature. */
	} signature;												/**< A generated ECDSA signature. */
	union {
		SP_ECDSA_P256_PUBLIC p256;								/**< A point on the P256 curve. */
		SP_ECDSA_P384_PUBLIC p384;								/**< A point on the P384 curve. */
		SP_ECDSA_P521_ALIGNED_PUBLIC p521;						/**< A point on the P521 curve. */
		uint8_t bytes[SP_ECDSA_P521_ALIGNED_PUBLIC_KEY_SIZE];	/**< Raw byte array access to the ECC point. */
	} point;													/**< The result of ECC point arithmetic. */
	union {
		SP_ECDSA_P256_PRIVATE p256;								/**< A P256 ECC key pair. */
		SP_ECDSA_P384_PRIVATE p384;								/**< A P384 ECC key pair. */
		SP_ECDSA_P521_ALIGNED_PRIVATE p521;						/**< A P521 ECC key pair. */
		uint8_t bytes[SP_ECDSA_P521_ALIGNED_PRIVATE_KEY_SIZE];	/**< Raw byte array access to the ECC key pair. */
	} key_pair;													/**< ECC public/private key pair. */
	union {
		SP_MSG_256 p256;										/**< Montgomery constant for the P256 curve. */
		SP_MSG_384 p384;										/**< Montgomery constant for the P384 curve. */
		SP_MSG_521_ALIGNED p521;								/**< Montgomery constant for the P521 curve. */
		uint8_t bytes[SP_MSG_521_ALIGNED_SIZE];					/**< Raw byte array access to the Montgomery constant. */
	} mont_const;												/**< R^2 value from Montgomery constant calculation. */
	union {
		SP_MSG_256 p256;										/**< 256-bit integer value from a modular operation. */
		SP_MSG_384 p384;										/**< 384-bit integer value from a modular operation. */
		SP_MSG_521_ALIGNED p521;								/**< 521-bit integer value from a modular operation. */
		uint8_t bytes[SP_MSG_521_ALIGNED_SIZE];					/**< Raw byte array access the integer value. */
	} int_result;												/**< Integer result from a modular operation (little endian). */
	union {
		union ecc_hw_pka_int_256 p256;							/**< 256-bit Montgomery result from a modular operation. */
		union ecc_hw_pka_int_384 p384;							/**< 384-bit Montgomery result from a modular operation. */
		union ecc_hw_pka_int_521 p521;							/**< 512-bit Montgomery result from a modular operation. */
		uint8_t bytes[ECC_HW_PKA_MONT_LENGTH_FROM_BITS (521)];	/**< Raw byte array access to the Montgomery representation. */
	} mont_result;												/**< Montgomery result from a modular operation. */
};

/**
 * Memory structure in HSP shared SRAM that is required to be able to execute PKA commands.  This
 * must be 32-bit aligned.
 */
struct ecc_hw_pka_cmd_buffer {
	struct ecc_hw_pka_command cmd;	/**< The command and arguments passed to the PKA. */
	struct ecc_hw_pka_input input;	/**< The input provided to the PKA. */
	union ecc_hw_pka_output output;	/**< The output generated from the PKA. */
};


/**
 * Variable context for the PKA driver instance.
 */
struct ecc_hw_pka_state {
	platform_mutex lock;		/**< Lock for synchronization. */
	platform_semaphore done;	/**< Semaphore indicating when a HW operation has completed. */
};

/**
 * Driver for utilizing the PKA hardware accelerator within HSP.
 */
struct ecc_hw_pka {
	struct ecc_hw base;						/**< Base interface for ECC HW accelerators. */
	struct hsp_interrupt_handler base_irq;	/**< Base interface for handling HW interrupts. */

	/**
	 * Interface for performing PKA memory wipe
	 *
	 * @param pka The PKA executing the command.
	 *
	 * @returns 0 if the command completed successfully or an error code.
	 */
	int (*memory_wipe) (const struct ecc_hw_pka *pka);

	struct ecc_hw_pka_state *state;				/**< Variable context for the driver. */
	struct Pka_regs *regs;						/**< Register interface to the PKA. */
	struct Creg_regs_creg_crypto_group *irq;	/**< Register interface to PKA interrupts. */
	const struct hsp_rng_hw *rng;				/**< Interface to the hardware RNG. */
	struct ecc_hw_pka_cmd_buffer *buffer;		/**< Memory location for the PKA command structure. */

	/**
	 * Submit a command to the hardware for execution and block until the hardware has completed the
	 * request.
	 *
	 * @param pka The PKA executing the command.
	 * @param error_code Error to return when the the command failure bit is set.
	 *
	 * @returns 0 if the command completed successfully or an error code.
	 */
	int (*submit_command) (const struct ecc_hw_pka *pka, int error_code);
};


int ecc_hw_pka_init_polling (struct ecc_hw_pka *pka, struct ecc_hw_pka_state *state,
	struct Pka_regs *regs, const struct hsp_rng_hw *rng, struct ecc_hw_pka_cmd_buffer *cmd_buffer);
int ecc_hw_pka_init_interrupt (struct ecc_hw_pka *pka, struct ecc_hw_pka_state *state,
	struct Pka_regs *regs, struct Creg_regs_creg_crypto_group *irq_regs,
	const struct hsp_rng_hw *rng, struct ecc_hw_pka_cmd_buffer *cmd_buffer);
int ecc_hw_pka_init_state (const struct ecc_hw_pka *pka);
void ecc_hw_pka_release (const struct ecc_hw_pka *pka);

void ecc_hw_pka_mark_as_in_use (const struct ecc_hw_pka *pka);
void ecc_hw_pka_mark_as_available (const struct ecc_hw_pka *pka);


/**
 * An error has occurred with the hardware block.  The error code represents the status register
 * output.
 */
#define	ECC_HW_PKA_HW_ERROR(reg)		ECC_HW_ERROR (0x80 | ((reg & 0x38) >> 3))


#endif	/* ECC_HW_PKA_H_ */
