// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef SOC_CRASHDUMP_INTERFACE_H_
#define SOC_CRASHDUMP_INTERFACE_H_

#include <stdbool.h>
#include <stdint.h>
#include "crashdump/hsp_crashdump_handler.h"
#include "crashdump/hsp_crashdump_packet.h"
#include "crashdump/soc_crashdump_packet.h"
#include "drivers/hsp_dmb.h"
#include "firmware/manticore_firmware_descriptor.h"
#include "marvell/RegTcon.h"
#include "mmio/mmio_register_block_soc_static.h"
#include "status/manticore_module_id.h"


/**
 * Number of times, pulling on crashdump magic number to identify if crashdump
 * is in place
 */
#define SOC_CRASHDUMP_INTERFACE_NUM_TIMES_PULLING 50

/**
 * Max numbers of crashes. Once crash reaches to this number, the reset would be suspended.
 */
#define MAX_CRASH_COUNT 5

/**
 * Bit number for tcon_regs wakeupCtrl.b.WAKEUP_ENABLE.
 */
#define	WAKEUP_CTR1_WAKEUP_ENABLE_BIT		0

/**
 * Bit number for tcon_regs wakeupCtrl.b.WKINTR_LEVEL_EN.
 */
#define	WAKEUP_CTR1_WKINTR_LEVEL_EN_BIT		8

/**
 * Bit count for tcon_regs wakeupCtrl.b.WAKEUP_ENABLE.
 */
#define	WAKEUP_CTR1_WAKEUP_ENABLE_BIT_COUNT	2

/**
 * Bit count for tcon_regs wakeupCtrl.b.WKINTR_LEVEL_EN.
 */
#define	WAKEUP_CTR1_WKINTR_LEVEL_EN_BIT_COUNT	2


/**
 * Crashdump SoC interface to make SoC access for crashdump operations.
 */
struct soc_crashdump_interface {
	/**
	 * Trigger an interrupt on ARM cores to preempt their code from hanging operation.
	 *
	 * @param[in] api The SoC crashdump interface instance to use.
	 *
	 * @return 0 if the request was successfully processed or an error code.
	*/
	int (*trigger_crash_int) (const struct soc_crashdump_interface *api);

	/**
	 * Get status from all ARM cores.
	 *
	 * @param[in] api The SoC crashdump interface instance to use.
	 * @param[out] failed_core_id The ID of core that failed to get the status from it.
	 * @param[out] status The status of ARM cores.
	 *
	 * @return 0 if the request was successfully processed or an error code.
	*/
	int (*get_all_core_status) (const struct soc_crashdump_interface *api,
		enum soc_crashdump_arm_core_id *failed_core_id, uint32_t *status);

	/**
	 * Set status on all ARM cores.
	 *
	 * @param[in] api The crashdump API instance to use.
	 *
	 * @return 0 if the request was successfully processed or an error code.
	*/
	int (*set_all_core_status) (const struct soc_crashdump_interface *api,
		enum soc_crashdump_arm_core_id *failed_core_id);

	/**
	 * Clear status from a ARM core.
	 *
	 * @param[in] api The SoC crashdump interface instance to use.
	 * @param[in] id The core ID.
	 *
	 * @return 0 if the request was successfully processed or an error code.
	*/
	int (*clear_core_status) (const struct soc_crashdump_interface *api,
		enum soc_crashdump_arm_core_id id);

	/**
	 * Get crashdumps from ARM cores.
	 *
	 * @param[in] api The SoC crashdump interface instance to use.
	 * @param[in] fw_version The build version number for the firmware package.
	 * @param[out] available If crashdumps from an ARM core is available, it is true;
	 * it is false otherwise.
	 * @param[out] failed_core_id The ID of core that failed to get the crashdump from it.
	 *
	 * @return 0 if the request was successfully processed or an error code.
	*/
	int (*get_crashdumps_from_cores) (const struct soc_crashdump_interface *api,
		const uint8_t *fw_version, bool *available, enum soc_crashdump_arm_core_id *failed_core_id);

	/**
	 * Make device warm reset.
	 *
	 * @param[in] api The SoC crashdump interface instance to use.
	 *
	 * @return 0 if the request was successfully processed or an error code.
	*/
	int (*reset) (const struct soc_crashdump_interface *api);

	hsp_crashdump_handler_reset_callback reset_device;	/**< Reset callback. Once it is invoked, it would get device into warm reset. */
	const struct hsp_dmb *dmb;							/**< HSP DMB object used to map and unmap memory regions outside of HSP domain. */
	const struct mmio_register_block *mmio;				/**< The interface object used to access registers via MMIO. */
	uint32_t *crash_count;								/**< Persistent RAM, such as sticky register, used to store crash count. */
};


int soc_crashdump_interface_init (struct soc_crashdump_interface *soc_api,
	const struct hsp_dmb *dmb, const struct mmio_register_block *mmio, uint32_t *crash_count,
	hsp_crashdump_handler_reset_callback reset_callback);
void soc_crashdump_interface_release (const struct soc_crashdump_interface *soc_api,
	const struct hsp_dmb *dmb);


#define	CRASHDUMP_SOC_INTERFACE_ERROR(code)      \
	ROT_ERROR (MANTICORE_MODULE_CRASHDUMP_SOC_INTERFACE, code)

/**
 * Error codes that can be generated by the Crashdump interface.
 *
 * Note: Commented error codes have been deprecated.
 */
enum {
	SOC_CRASHDUMP_INTERFACE_INVALID_ARGUMENT = CRASHDUMP_SOC_INTERFACE_ERROR (0x00),		/**< Input parameter is null or not valid. */
	SOC_CRASHDUMP_INTERFACE_NO_MEMORY = CRASHDUMP_SOC_INTERFACE_ERROR (0x01),				/**< Memory allocation failed. */
	SOC_CRASHDUMP_INTERFACE_TRIGGER_CRASH_FAILED = CRASHDUMP_SOC_INTERFACE_ERROR (0x02),	/**< Failed to trigger a core crash. */
	SOC_CRASHDUMP_INTERFACE_GET_STATUS_FAILED = CRASHDUMP_SOC_INTERFACE_ERROR (0x03),		/**< Failed to get current core status. */
	SOC_CRASHDUMP_INTERFACE_SET_STATUS_FAILED = CRASHDUMP_SOC_INTERFACE_ERROR (0x04),		/**< Failed to set current core status. */
	SOC_CRASHDUMP_INTERFACE_CLEAR_STATUS_FAILED = CRASHDUMP_SOC_INTERFACE_ERROR (0x05),		/**< Failed to clear the current core status. */
	SOC_CRASHDUMP_INTERFACE_GET_CRASHDUM_FAILED = CRASHDUMP_SOC_INTERFACE_ERROR (0x06),		/**< Failed to get core crash dumps. */
	SOC_CRASHDUMP_INTERFACE_RESET_FAILED = CRASHDUMP_SOC_INTERFACE_ERROR (0x07),			/**< Failed to reset the device. */
};


#endif	/* SOC_CRASHDUMP_INTERFACE_H_ */
