// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef MANTICORE_PCR_H_
#define MANTICORE_PCR_H_

#include "attestation/pcr_store.h"


/**
 * Identifiers for each set of Manticore measurements.
 */
enum {
	MANTICORE_PCR_ROM,		/**< Measurements of ROM and 1SP firmware. */
	MANTICORE_PCR_SPRT,		/**< Measurements of SPRT firmware. */
	MANTICORE_PCR_SOC,		/**< Measurements of SoC firmware. */
	MANTICORE_PCR_CERBERUS,	/**< Measurements for Cerberus configuration and state. */
};

/* The number of measurements in each PCR. */
#define MANTICORE_PCR_ROM_MEASUREMENTS			9	/**< Number of ROM measurements. */
#define MANTICORE_PCR_SPRT_MEASUREMENTS			9	/**< Number of SPRT measurements. */
#define MANTICORE_PCR_SOC_MEASUREMENTS			10	/**< Number of SoC firmware measurements. */

#define MANTICORE_PCR_CERBERUS_MEASUREMENTS		8	/**< Number of Cerberus measurements with chassis intrusion. */


/**
 * PCR measurement types
 */
enum {
	PCR_MEASUREMENT_TYPE_ROM_SECURITY_STATE = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		0),
	PCR_MEASUREMENT_TYPE_ROM_OWNER_PUBLIC_KEY = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		1),
	PCR_MEASUREMENT_TYPE_ROM_KEY_MANIFEST_SVN = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		2),
	PCR_MEASUREMENT_TYPE_ROM_TENANCY_COUNTER = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		3),
	PCR_MEASUREMENT_TYPE_ROM_FW_PUBLIC_KEY = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		4),
	PCR_MEASUREMENT_TYPE_ROM_SECONDARY_PUBLIC_KEY = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		5),
	PCR_MEASUREMENT_TYPE_ROM_FW_SVN = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		6),
	PCR_MEASUREMENT_TYPE_ROM_FW_BUILD_VERSION = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		7),
	PCR_MEASUREMENT_TYPE_ROM_FW_IMAGE = PCR_MEASUREMENT (MANTICORE_PCR_ROM,
		8),
	PCR_MEASUREMENT_TYPE_SPRT_SECURITY_POLICY = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		0),
	PCR_MEASUREMENT_TYPE_SPRT_FW_KEY_MANIFEST = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		1),
	PCR_MEASUREMENT_TYPE_SPRT_FW_KEY_MANIFEST_SVN = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		2),
	PCR_MEASUREMENT_TYPE_SPRT_FW_PUBLIC_KEY = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		3),
	PCR_MEASUREMENT_TYPE_SPRT_FW_SVN = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		4),
	PCR_MEASUREMENT_TYPE_SPRT_FW_BUILD_VERSION = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		5),
	PCR_MEASUREMENT_TYPE_SPRT_FW_IMAGE = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		6),
	PCR_MEASUREMENT_TYPE_SPRT_AEB_STATE = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		7),
	PCR_MEASUREMENT_TYPE_SPRT_AEB_LOCKED_STATE = PCR_MEASUREMENT (MANTICORE_PCR_SPRT,
		8),
	PCR_MEASUREMENT_TYPE_SOC_FW_KEY_MANIFEST = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		0),
	PCR_MEASUREMENT_TYPE_SOC_FW_KEY_MANIFEST_SVN = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		1),
	PCR_MEASUREMENT_TYPE_SOC_FW_PUBLIC_KEY = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		2),
	PCR_MEASUREMENT_TYPE_SOC_FW_SVN = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		3),
	PCR_MEASUREMENT_TYPE_SOC_FW_BUILD_VERSION = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		4),
	PCR_MEASUREMENT_TYPE_SOC_CP_IMAGE = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		5),
	PCR_MEASUREMENT_TYPE_SOC_FP0_IMAGE = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		6),
	PCR_MEASUREMENT_TYPE_SOC_FP1_IMAGE = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		7),
	PCR_MEASUREMENT_TYPE_SOC_FP2_IMAGE = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		8),
	PCR_MEASUREMENT_TYPE_SOC_PCIE_PHY_IMAGE = PCR_MEASUREMENT (MANTICORE_PCR_SOC,
		9),
	PCR_MEASUREMENT_TYPE_CERBERUS_PFM_1 = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		0),
	PCR_MEASUREMENT_TYPE_CERBERUS_PFM_1_VALID = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		1),
	PCR_MEASUREMENT_TYPE_CERBERUS_PFM_1_ID = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		2),
	PCR_MEASUREMENT_TYPE_CERBERUS_PFM_1_PLATFORM_ID = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		3),
	PCR_MEASUREMENT_TYPE_CERBERUS_PCD = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		4),
	PCR_MEASUREMENT_TYPE_CERBERUS_PCD_ID = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		5),
	PCR_MEASUREMENT_TYPE_CERBERUS_PCD_PLATFORM_ID = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		6),
	PCR_MEASUREMENT_TYPE_CERBERUS_CHASSIS_INTRUSION = PCR_MEASUREMENT (MANTICORE_PCR_CERBERUS,
		7),
};


#endif	/* MANTICORE_PCR_H_ */
