// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef ROT_MEMORY_MAP_H_
#define ROT_MEMORY_MAP_H_

#include <stdint.h>
#include "mem_map/gsram_mem_map.h"
#include "mem_map/psram_mem_map.h"


/*************************
 * Manticore flash layout
 *************************/

/**
 * Internal Flash (4MB)
 */

/**
 * The base flash address for the main keystore, growing down.  This includes RIoT certificates and
 * manifest keys.
 */
#define	MAIN_KEYSTORE_ADDR				0x3ff000

/**
 * IDs for data that is stored in the main keystore.
 */
enum {
	RIOT_DEVICE_ID_KEY = 0,		/**< ID for the Device ID cert that chains to the root CA. */
	RIOT_ROOT_CA_KEY,			/**< ID for the external root CA certificate. */
	RIOT_INTERMEDIATE_CA_KEY,	/**< ID for the external ICA certificate. */
	PFM_PORT1_VERIFICATION_KEY,	/**< ID for the key used to verify PFMs for Port 1. */
	PCD_VERIFICATION_KEY,		/**< ID for the key used to verify PCDs. */
	DEVICE_UNLOCK_POLICY,		/**< ID for the active device unlock policy. */
	MAIN_KEYSTORE_MAX_KEYS,		/**< The maximum number of keys supported by the main keystore. */
};

/* Unallocated sectors:  0x3e6000 - 0x3f9000 */

/**
 * The flash address where application context information will be stored.
 */
#define	APP_CONTEXT_ADDR				0x3e4000

/**
 * The flash address for storing system state information.
 */
#define	SYSTEM_STATE_ADDR				0x3e2000

/**
 * The flash address for storing host state information.
 */
static const uint32_t host_state_addr = 0x3e0000;

/**
 * Flash addresses for the first region for storing PFMs.
 */
static const uint32_t host_pfm_region1_addr = 0x3d0000;

/**
 * Flash addresses for the second region for storing PFMs.
 */
static const uint32_t host_pfm_region2_addr = 0x3c0000;

/**
 * Flash addresses for storing CFMs.
 */
static const uint32_t cfm_region_addr[2] = {
	0x3b0000,
	0x3a0000
};

/**
 * Flash addresses for storing PCDs.
 */
static const uint32_t pcd_region_addr[2] = {
	0x390000,
	0x380000
};

/**
 * Storage space for allocated for each fTPM instance.  Each fTPM has 16kB of NV storage, plus 4kB
 * of encryption metadata, and a redundant copy.
 */
#define	FTPM_NV_STORAGE_SIZE			0xa000

/**
 * Flash address for fTPM1 non-volatile storage.
 */
#define	FTPM1_NV_STORAGE_ADDR			0x376000

/**
 * Flash address for fTPM0 non-volatile storage.
 */
#define	FTMP0_NV_STORAGE_ADDR			0x36c000

/* Unallocated sectors: 0x200000 - 0x36b000 */

/**
 * The maximum size for a Manticore firmware image.  Each FW region will be this size.
 */
#define	MANTICORE_IMAGE_MAX_SIZE		0x200000

/**
 * Flash address for the Manticore main boot image.
 */
#define	MANTICORE_MAIN_BOOT_ADDR		0x000000


/**
 * External Flash (16MB)
 */

/**
 * Flash address for the Manticore recovery boot image.
 */
#define	MANTICORE_RECOVERY_BOOT_ADDR	0x000000

/**
 * Flash address for the Manticore staging image.
 */
#define	MANTICORE_STAGING_ADDR			0x200000


/**
 * Ephemeral RSA key cache address
 */
#define RSA_KEY_CACHE_FLASH_ADDR		0x400000

/**
 * Number of flash sectors allocated for the ephemeral key cache.  Each sector has a size of 4KB.
 */
#define RSA_KEY_CACHE_FLASH_SECTORS		512

/* Unallocated sectors:  0x600000 - 0x9ff000 */

/**
 * The flash address for storing CP crash dumps.
 */
#define	CP_CRASH_DUMP_ADDR				0x900000

/**
 * The amount of space allocated for CP crash dumps.
 */
#define	CP_CRASH_DUMP_SIZE				0x100000

/**
 * The flash address for storing CP crash dumps.
 */
#define	FP_CRASH_DUMP_ADDR				0xa00000

/**
 * The amount of space allocated for CP crash dumps.
 */
#define	FP_CRASH_DUMP_SIZE				0x100000

/**
 * The flash address for storing CP crash dumps.
 */
#define	SP_CRASH_DUMP_ADDR				0xb00000

/**
 * The amount of space allocated for CP crash dumps.
 */
#define	SP_CRASH_DUMP_SIZE				0x70000

/**
 * Address for redundant storage of the main keystore.
 */
#define	REDUNDANT_KEYSTORE_ADDR			0xb70000

/**
 * The flash address for temporary storage of 64 vTPM contexts, including encryption metadata.
 */
#define	VTPM_CONTEXT_ADDR				0xb80000

/**
 * The flash address for storing debug log entries.
 */
#define	DEBUG_LOGGING_ADDR				0xfc0000


/*******************
 * SP Shared memory
 *******************/

/**
 * Address where the data generated by 1SP is stored.  Use the last 12k block of DTCM.  The shared
 * structure is defined in manticore_1sp.h.
 */
#define	SP1_SHARED_ADDRESS				0x2012d000


/****************
 * CP TCM
 ****************/

/**
 * SoC address for the start of CP ITCM.
 */
#define	MANTICORE_SOC_CP_ITCM_ADDRESS	0x60000000

/**
 * Total size of the CP ITCM.
 */
#define	MANTICORE_SOC_CP_ITCM_SIZE		(512 * 1024)

/**
 * SoC address for the start of CP0 DTCM.
 */
#define	MANTICORE_SOC_CP0_DTCM_ADDRESS	0x60200000

/**
 * Total size of the CP0 DTCM.
 */
#define	MANTICORE_SOC_CP0_DTCM_SIZE		(256 * 1024)

/**
 * SoC address for the start of CP1 DTCM.
 */
#define	MANTICORE_SOC_CP1_DTCM_ADDRESS	0x60600000

/**
 * Total size of the CP1 DTCM.
 */
#define	MANTICORE_SOC_CP1_DTCM_SIZE		(256 * 1024)


/****************
 * FPS TCM
 ****************/

/**
 * SoC address for the start of FP0 ITCM.
 */
#define	MANTICORE_SOC_FP0_ITCM_ADDRESS		0xa2000000

/**
 * Total size of the FP0 ITCM.
 */
#define	MANTICORE_SOC_FP0_ITCM_SIZE			(32 * 1024)

/**
 * SoC address for the start of FP0 DTCM.
 */
#define	MANTICORE_SOC_FP0_DTCM_ADDRESS		0xa3000000

/**
 * Total size of the FP0 DTCM.
 */
#define	MANTICORE_SOC_FP0_DTCM_SIZE			(32 * 1024)

/**
 * SoC address for the start of shared DTCM from FP0 to FP1.
 */
#define	MANTICORE_SOC_FP0_FP1_DTCM_ADDRESS	0xa3020000

/**
 * Total size of the shared DTCM from FP0 to FP1.
 */
#define	MANTICORE_SOC_FP0_FP1_DTCM_SIZE		(16 * 1024)

/**
 * SoC address for the start of shared DTCM from FP0 to FP2.
 */
#define	MANTICORE_SOC_FP0_FP2_DTCM_ADDRESS	0xa3030000

/**
 * Total size of the shared DTCM from FP0 to FP2.
 */
#define	MANTICORE_SOC_FP0_FP2_DTCM_SIZE		(16 * 1024)

/**
 * SoC address for the start of FP1 ITCM.
 */
#define	MANTICORE_SOC_FP1_ITCM_ADDRESS		0xa2200000

/**
 * Total size of the FP1 ITCM.
 */
#define	MANTICORE_SOC_FP1_ITCM_SIZE			(32 * 1024)

/**
 * SoC address for the start of FP1 DTCM.
 */
#define	MANTICORE_SOC_FP1_DTCM_ADDRESS		0xa3200000

/**
 * Total size of the FP1 DTCM.
 */
#define	MANTICORE_SOC_FP1_DTCM_SIZE			(64 * 1024)

/**
 * SoC address for the start of shared DTCM from FP1 to FP0.
 */
#define	MANTICORE_SOC_FP1_FP0_DTCM_ADDRESS	0xa3230000

/**
 * Total size of the shared DTCM from FP1 to FP0.
 */
#define	MANTICORE_SOC_FP1_FP0_DTCM_SIZE		(16 * 1024)

/**
 * SoC address for the start of shared DTCM from FP1 to FP2.
 */
#define	MANTICORE_SOC_FP1_FP2_DTCM_ADDRESS	0xa3220000

/**
 * Total size of the shared DTCM from FP1 to FP2.
 */
#define	MANTICORE_SOC_FP1_FP2_DTCM_SIZE		(16 * 1024)

/**
 * SoC address for the start of FP2 ITCM.
 */
#define	MANTICORE_SOC_FP2_ITCM_ADDRESS		0xa2400000

/**
 * Total size of the FP2 ITCM.
 */
#define	MANTICORE_SOC_FP2_ITCM_SIZE			(32 * 1024)

/**
 * SoC address for the start of FP2 DTCM.
 */
#define	MANTICORE_SOC_FP2_DTCM_ADDRESS		0xa3400000

/**
 * Total size of the FP2 DTCM.
 */
#define	MANTICORE_SOC_FP2_DTCM_SIZE			(32 * 1024)

/**
 * SoC address for the start of shared DTCM from FP2 to FP0.
 */
#define	MANTICORE_SOC_FP2_FP0_DTCM_ADDRESS	0xa3420000

/**
 * Total size of the shared DTCM from FP2 to FP0.
 */
#define	MANTICORE_SOC_FP2_FP0_DTCM_SIZE		(16 * 1024)

/**
 * SoC address for the start of shared DTCM from FP2 to FP1.
 */
#define	MANTICORE_SOC_FP2_FP1_DTCM_ADDRESS	0xa3430000

/**
 * Total size of the shared DTCM from FP2 to FP1.
 */
#define	MANTICORE_SOC_FP2_FP1_DTCM_SIZE		(16 * 1024)


/****************
 * GSRAM
 ****************/

/**
 * SoC address for the start of GSRAM.
 */
#define	MANTICORE_SOC_GSRAM_ADDRESS						0x61000000

/**
 * Total size of the GSRAM.
 */
#define	MANTICORE_SOC_GSRAM_SIZE						(2 * 1024 * 1024)

/**
 * ScC address of the request IPC queue for the Admin to HSP channel.
 */
#define IPC_ADMIN_TO_HSP_REQUEST_QUEUE_SOC_ADDRESS		GSRAM_MEM_MAP_ADMIN_TO_HSP_IPC_TX_QUEUE_CI

/**
 * SoC address of the response IPC queue for the Admin to HSP channel.
 */
#define IPC_ADMIN_TO_HSP_RESPONSE_QUEUE_SOC_ADDRESS		GSRAM_MEM_MAP_ADMIN_TO_HSP_IPC_RX_QUEUE_CI

/**
 * SoC address of the request IPC queue for the HSM to HSP channel.
 */
#define IPC_HSM_TO_HSP_REQUEST_QUEUE_SOC_ADDRESS		GSRAM_MEM_MAP_HSM_TO_HSP_IPC_TX_QUEUE_CI

/**
 * SoC address of the response IPC queue for the HSM to HSP channel.
 */
#define IPC_HSM_TO_HSP_RESPONSE_QUEUE_SOC_ADDRESS		GSRAM_MEM_MAP_HSM_TO_HSP_IPC_RX_QUEUE_CI

/**
 * SoC address of the request IPC queue for the HSP to Admin channel.
 */
#define IPC_HSP_TO_ADMIN_REQUEST_QUEUE_SOC_ADDRESS		GSRAM_MEM_MAP_HSP_TO_ADMIN_IPC_TX_QUEUE_CI

/**
 * SoC address of the response IPC queue for the HSP to Admin channel.
 */
#define IPC_HSP_TO_ADMIN_RESPONSE_QUEUE_SOC_ADDRESS		GSRAM_MEM_MAP_HSP_TO_ADMIN_IPC_RX_QUEUE_CI

/**
 * SoC address of the request IPC queue for the HSP to Admin Stop Interface channel.
 */
#define IPC_HSP_TO_ADMIN_STOP_INTF_REQUEST_QUEUE_SOC_ADDRESS        \
		GSRAM_MEM_MAP_HSP_TO_ADMIN_STOP_INTERFACE_IPC_TX_QUEUE_CI

/**
 * SoC address of the response IPC queue for the HSP to Admin Stop Interface channel.
 */
#define IPC_HSP_TO_ADMIN_STOP_INTF_RESPONSE_QUEUE_SOC_ADDRESS       \
		GSRAM_MEM_MAP_HSP_TO_ADMIN_STOP_INTERFACE_IPC_RX_QUEUE_CI

/**
 * SoC address of the CP0 debug_log_ring_buffer structure
 */
#define CP0_DEBUG_LOG_RING_BUFFER						GSRAM_MEM_MAP_CP0_DEBUG_LOG_RING_BUFFER_SIZE

/**
 * SoC address of the CP0 debug log array
 */
#define CP0_DEBUG_LOG_BUFFER_ARRAY						GSRAM_MEM_MAP_CP0_DEBUG_LOG_BUFFER_QUEUE
#define CP0_DEBUG_LOG_BUFFER_ARRAY_SIZE                 \
		GSRAM_MEM_MAP_CP0_DEBUG_LOG_BUFFER_QUEUE_SIZE

/**
 * SoC address of the CP1 debug_log_ring_buffer structure
 */
#define CP1_DEBUG_LOG_RING_BUFFER						GSRAM_MEM_MAP_CP1_DEBUG_LOG_RING_BUFFER_SIZE

/**
 * SoC address of the CP1 debug log array
 */
#define CP1_DEBUG_LOG_BUFFER_ARRAY						GSRAM_MEM_MAP_CP1_DEBUG_LOG_BUFFER_QUEUE
#define CP1_DEBUG_LOG_BUFFER_ARRAY_SIZE                 \
		GSRAM_MEM_MAP_CP1_DEBUG_LOG_BUFFER_QUEUE_SIZE

/**
 * SoC address in GSRAM where data shared with CP will get stored.
 */
#define	CP_SHARED_GSRAM_ADDRESS							GSRAM_MEM_MAP_POR_MEASUREMENTS

/**
 * SoC address of IDE key context
 */
#define IDE_KEY_CONTEXT_ADDRESS							GSRAM_MEM_MAP_IDE_KM_CONTEXT

/**
 * SoC address in GSRAM where the CMVP test identifier will be stored.
 */
#define	CMVP_TEST_CASE_ADDRESS							GSRAM_MEM_MAP_NEGATIVE_SELF_TEST

/**
 * SoC address in GSRAM where the table containing BKS1 and BKS2 will be stored.
 */
#define	BKS_TABLE_ADDRESS								GSRAM_MEM_MAP_BKS_TABLE

/**
 * SoC address in GSRAM of the HSM partition persistent store.  This region holds the RSA
 * ephemeral unwrapping-key slots that are produced by the SP key cache and consumed by HSM.
 */
#define	HSM_PART_PERSISTENT_STORE_ADDRESS				GSRAM_MEM_MAP_HSM_PART_PERSISTENT_STORE


/****************
 * PSRAM
 ****************/

/**
 * SoC address for the start of PSRAM.
 */
#define MANTICORE_SOC_PSRAM_ADDRESS						0xa3e00000

/**
 * Total size of the PSRAM.
 */
#define MANTICORE_SOC_PSRAM_SIZE						(32 * 1024)

/**
 * SoC address for the indicator specifying what type of reset has been performed by the device.
 */
#define	SOC_RESET_TYPE_ADDRESS							PSRAM_MEM_MAP_RESET_TYPE

/**
 * SoC address of the FP0 debug_log_ring_buffer structure
 */
#define FP0_DEBUG_LOG_RING_BUFFER						PSRAM_MEM_MAP_FP0_DEBUG_LOG_RING_BUFFER_SIZE

/**
 * SoC address of the FP0 debug log array
 */
#define FP0_DEBUG_LOG_BUFFER_ARRAY						PSRAM_MEM_MAP_FP0_DEBUG_LOG_BUFFER_QUEUE
#define FP0_DEBUG_LOG_BUFFER_ARRAY_SIZE                 \
		PSRAM_MEM_MAP_FP0_DEBUG_LOG_BUFFER_QUEUE_SIZE

/**
 * SoC address of the FP1 debug_log_ring_buffer structure
 */
#define FP1_DEBUG_LOG_RING_BUFFER						PSRAM_MEM_MAP_FP1_DEBUG_LOG_RING_BUFFER_SIZE

/**
 * SoC address of the FP1 debug log array
 */
#define FP1_DEBUG_LOG_BUFFER_ARRAY						PSRAM_MEM_MAP_FP1_DEBUG_LOG_BUFFER_QUEUE
#define FP1_DEBUG_LOG_BUFFER_ARRAY_SIZE                 \
		PSRAM_MEM_MAP_FP1_DEBUG_LOG_BUFFER_QUEUE_SIZE

/**
 * SoC address of the FP2 debug_log_ring_buffer structure
 */
#define FP2_DEBUG_LOG_RING_BUFFER						PSRAM_MEM_MAP_FP2_DEBUG_LOG_RING_BUFFER_SIZE

/**
 * SoC address of the FP2 debug log array
 */
#define FP2_DEBUG_LOG_BUFFER_ARRAY						PSRAM_MEM_MAP_FP2_DEBUG_LOG_BUFFER_QUEUE
#define FP2_DEBUG_LOG_BUFFER_ARRAY_SIZE                 \
		PSRAM_MEM_MAP_FP2_DEBUG_LOG_BUFFER_QUEUE_SIZE


/****************************
 * Static application memory
 ****************************/

/* TODO:  Define in the future as necessary to support dev vs. prod builds. */
#if 0
/**
 * Address where the manifest verification key will be stored.
 */
#define	MANIFEST_KEY_ADDRESS            0x00000200
#define MANIFEST_KEY_SECTION_STR(x)     #x
#define MANIFEST_KEY_SECTION(x)         MANIFEST_KEY_SECTION_STR (.ARM.__at_ ## x)
#define MANIFEST_KEY_ATTRIB_ADDR(x)     MANIFEST_KEY_SECTION (x)
#define MANIFEST_KEY_ATTRIBUTE_STR      MANIFEST_KEY_ATTRIB_ADDR (MANIFEST_KEY_ADDRESS)
#define MANIFEST_KEY_ATTRIBUTE          __attribute__((section(MANIFEST_KEY_ATTRIBUTE_STR)))
#else
#define MANIFEST_KEY_ATTRIBUTE
#endif


#endif	/* ROT_MEMORY_MAP_H_ */
