// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef UID_EFUSE_H_
#define UID_EFUSE_H_

#include <stdint.h>
#include "platform_api.h"
#include "status/manticore_module_id.h"


/**
 * The length of the UID in the eFuses.
 */
#define UID_EFUSE_LENGTH		12

/**
 * The global address of the UID eFuses.
 */
#define UID_EFUSE_ADDR			0xB0002000


/**
 * Variable context for a UID eFuse instance.
*/
struct uid_efuse_state {
	platform_mutex lock;	/**< Lock for synchronization. */
};

/**
 * Context for access of UID eFuses.
 */
struct uid_efuse {
	struct uid_efuse_state *state;	/**< Variable context for the instance. */
	void *addr;						/**< Base address of UID eFuses. */
};


int uid_efuse_init (struct uid_efuse *uid, struct uid_efuse_state *state, void *addr);
int uid_efuse_init_state (const struct uid_efuse *uid);
void uid_efuse_release (const struct uid_efuse *uid);

int uid_efuse_get_uid (const struct uid_efuse *uid, uint8_t *uid_out, size_t len);


#define	UID_EFUSE_ERROR(code)			ROT_ERROR (MANTICORE_MODULE_UID_EFUSE, code)

/**
 * Error codes that can be generated by the UID eFuse interface.
 */
enum {
	UID_EFUSE_INVALID_ARGUMENT = UID_EFUSE_ERROR (0x00),	/**< Input parameter is null or not valid. */
	UID_EFUSE_NO_MEMORY = UID_EFUSE_ERROR (0x01),			/**< Memory allocation failure. */
	UID_EFUSE_BUFFER_TOO_SMALL = UID_EFUSE_ERROR (0x02),	/**< Buffer too small. */
};


#endif	/* UID_EFUSE_H_ */
