// Copyright (c) Microsoft Corporation. All rights reserved.

#![allow(unused_imports)]
#![allow(dead_code)]

use mcr_ddi_types::HMAC384_TAG_SIZE;
use mcr_types::SecureByteArray;

use crate::error::HsmErr;

/// BK Boot Masking Key: A key that is constant in the firmware. This key is used for boot-time operations
/// to ensure the integrity and confidentiality of the boot process.
pub const BK_BOOT_MASKING_KEY: [u8; 48] = [
    0x5f, 0xb0, 0x8b, 0x84, 0xb2, 0x8c, 0x54, 0xc5, 0x73, 0x5c, 0x73, 0x07, 0x96, 0x99, 0xc0, 0xd0,
    0xe6, 0x11, 0x84, 0x8f, 0x65, 0xa1, 0xa5, 0x8e, 0x75, 0x72, 0x43, 0x59, 0x9e, 0x99, 0x2c, 0x88,
    0xe5, 0x73, 0x98, 0x75, 0xb4, 0x0d, 0xa1, 0x24, 0x08, 0x36, 0x70, 0xa7, 0x65, 0xa1, 0x36, 0x7d,
];

pub trait CryptEnv {
    /// Generates an HMAC384 tag for the given data using the environment key.
    ///
    /// # Arguments
    ///
    /// * `key`: The key to be used for tag generation.
    /// * `data`: The data to be authenticated.
    ///
    /// # Returns
    /// * `Ok([u8; 48])` - The generated HMAC384 tag.
    /// * `Err(HsmErr)` - If the tag generation fails.
    ///
    ///  NOTE: HMAC Key acquisition is implementation specific and should be handled by the environment.
    fn hmac384_tag(
        &self,
        key: &[u8],
        data: &[u8],
    ) -> Result<SecureByteArray<HMAC384_TAG_SIZE>, HsmErr>;

    /// Calculates the length of the data on encryption when using AES-CBC 256.
    ///
    /// # Arguments
    ///
    /// * `plaintext_len`: The length of the plaintext data.
    ///
    /// # Returns
    /// * The length of the encrypted data.
    fn aescbc256_enc_data_len(&self, plaintext_len: usize) -> usize;

    /// Encrypt data using AES-CBC 256 with encryption key from the environment.
    ///
    /// # Arguments
    ///
    /// * `key`: The key to be used for encryption.
    /// * `plaintext`: The data to be encrypted.
    /// * `iv`: The Initialization Vector (IV) used for the encryption. This is generated by the function and returned.
    /// * `ciphertext`: The buffer to write the encrypted data into.
    ///
    /// # Returns
    /// * `Ok(usize)` - The length of the encrypted data.
    /// * `Err(HsmErr)` - If the encryption fails.
    ///
    /// NOTE: Encryption key acquisition is implementation specific and should be handled by the environment.
    fn aescbc256_encrypt(
        &self,
        key: &[u8],
        plaintext: &[u8],
        iv: &mut [u8],
        ciphertext: &mut [u8],
    ) -> Result<usize, HsmErr>;

    /// Decrypt data using AES-CBC 256 with decryption key from the environment.
    ///
    /// # Arguments
    ///
    /// * `key`: The key to be used for decryption.
    /// * `iv`: The Initialization Vector (IV) for the decryption.
    /// * `ciphertext`: The data to be decrypted.
    /// * `plaintext`: The buffer to write the decrypted data into.
    ///
    /// # Returns
    /// * `Ok(usize)` - The length of the decrypted data.
    /// * `Err(HsmErr)` - If the decryption fails.
    ///
    /// NOTE: Decryption key acquisition is implementation specific and should be handled by the environment.
    fn aescbc256_decrypt(
        &self,
        key: &[u8],
        iv: &[u8],
        ciphertext: &[u8],
        plaintext: &mut [u8],
    ) -> Result<usize, HsmErr>;

    /// KBKDF (Key-Based Key Derivation Function) using HMAC-SHA384 in counter mode
    /// Following NIST SP 800-108 specification
    ///
    /// # Parameters
    /// - `key`: Key Derivation Key (KDK) - in BMK context this would be BK3
    /// - `label`: Optional label for domain separation (up to 32 bytes)
    /// - `context`: Optional context - in BMK derivation, this would be concatenation of BKS1 + BKS2
    /// - `out_len`: Desired output key length in bytes.
    /// - `output`: Output buffer to write derived key material
    ///
    /// # Returns
    /// - `Ok(())` on success
    /// - `Err(HsmErr)` on failure
    ///
    fn kbkdf_sha384(
        &self,
        key: &[u8],
        label: Option<&[u8]>,
        context: Option<&[u8]>,
        out_len: usize,
        output: &mut [u8],
    ) -> Result<(), HsmErr>;

    /// Generates random bytes using the environment's random number generator.
    ///
    /// # Arguments
    /// * `output`: The buffer to write the random bytes into.
    ///
    /// # Returns
    /// * `Ok(())` - If the random bytes were successfully generated.
    /// * `Err(HsmErr)` - If the random number generation fails.
    fn generate_random(&self, output: &mut [u8]) -> Result<(), HsmErr>;
}
