# Copyright (c) Microsoft Corporation. All rights reserved.

[package]
name = "mcr-crypto-sha"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield-struct.workspace = true
bitfield.workspace = true
cortex-m.workspace = true
mcr-ddi-mbor.workspace = true
mcr-error.workspace = true
mcr-mem-map.workspace = true
mcr-registers.workspace = true
mcr-self-test.workspace = true
mcr-soc.workspace = true
mcr-tcon.workspace = true
mcr-types.workspace = true
zeroize.workspace = true

[lib]
doctest = false

[features]
fips_validation_hooks = []