// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef SRAM_UTIL_H_
#define SRAM_UTIL_H_

#include <stddef.h>
#include <stdint.h>
#include "drivers/hsp_dmb.h"
#include "status/msft_module_id.h"


/**
 * Defines a single, contiguous block of SRAM memory within HSP address space.
 */
struct sram_block {
	const void *start;	/**< Starting address of the block of SRAM. */
	size_t length;		/**< Number of bytes in the block. */
};


bool sram_is_address_in_block (const struct sram_block *sram, const void *addr);
int sram_data_fits_in_block (const struct sram_block *sram, const void *addr, size_t length);

bool sram_is_address_inside_region (const void *region_start, size_t region_size,
	const void *address);
int sram_is_range_inside_region (const void *region_start, size_t region_size,
	const void *range_start, size_t range_size);


/**
 * Defines a single, contiguous block of SRAM memory in the SoC address space.
 */
struct soc_sram_block {
	uint64_t start;		/**< Starting address of the block of SRAM. */
	uint64_t length;	/**< Number of bytes in the block. */
};


bool sram_is_soc_address_in_block (const struct soc_sram_block *sram, uint64_t addr);
int sram_data_fits_in_soc_block (const struct soc_sram_block *sram, uint64_t addr, uint64_t length);

bool sram_is_soc_address_inside_region (uint64_t region_start, uint64_t region_size,
	uint64_t address);
int sram_is_soc_range_inside_region (uint64_t region_start, uint64_t region_size,
	uint64_t range_start, uint64_t range_size);

int sram_erase_soc_memory (const struct hsp_dmb *dmb, uint64_t address, uint64_t length);
int sram_erase_soc_memory_blocks (const struct hsp_dmb *dmb, const struct soc_sram_block *sram,
	size_t count);


#define	HSP_SRAM_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_SRAM, code)

/**
 * Error codes that can be generated by the HSP SRAM utilities.
 */
enum {
	HSP_SRAM_INVALID_ARGUMENT = HSP_SRAM_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_SRAM_NO_MEMORY = HSP_SRAM_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* SRAM_UTIL_H_ */
