// Copyright (c) Microsoft Corporation. All rights reserved.

#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "hsp_intrusion_irq_handler.h"
#include "common/common_math.h"
#include "common/type_cast.h"
#include "common/unused.h"
#include "intrusion/intrusion_logging.h"


/**
 * The period to wait until contents of HSP tamper and tamper count register
 * become available.
 */
#define HSP_INTRUSION_IRQ_HANDLER_DELAY_MS			(5 * 1000)


/**
 * Process the intrusion events once an intrusion IRQ interrupt is detected.
 *
 * @param handler The interrupt handler.
 *
 * @return Returns 0 if success, else an error code
 */
static int hsp_intrusion_irq_handler_process_events (
	const struct hsp_intrusion_irq_handler *handler)
{
	int status;
	uint32_t int_status;

	/* Check pending interrupts. */
	status = handler->rtc->get_interrupt_status (handler->rtc, &int_status);
	if (status != 0) {
		return status;
	}

	/* Process events generated by the HSP intrusion HW. */
	if (int_status & REAL_TIME_CLOCK_HSP_INTSTS_INTRUSION_MASK) {
		/* Wait for HSP_INTRUSION_IRQ_HANDLER_DELAY_MS, then identify and process
		 * intrusion event. */
		status = platform_timer_arm_one_shot (&handler->state->timer,
			HSP_INTRUSION_IRQ_HANDLER_DELAY_MS);
	}

	return status;
}

void hsp_intrusion_irq_handler_prepare (const struct periodic_task_handler *handler)
{
	const struct hsp_intrusion_irq_handler *hsp =
		(const struct hsp_intrusion_irq_handler*) handler;
	int status;

	// Update CID PCR with the initial state
	status = hsp->manager->check_state (hsp->manager);
	if (status != 0) {
		debug_log_create_entry (DEBUG_LOG_SEVERITY_ERROR, DEBUG_LOG_COMPONENT_INTRUSION,
			INTRUSION_LOGGING_CHECK_FAILED, status,	0);
	}
}

const platform_clock* hsp_intrusion_irq_handler_get_next_execution (
	const struct periodic_task_handler *handler)
{
	UNUSED (handler);

	/* Do not wait to call execute again. */
	return NULL;
}

void hsp_intrusion_irq_handler_execute (const struct periodic_task_handler *handler)
{
	int status;
	const struct hsp_intrusion_irq_handler *hsp =
		(const struct hsp_intrusion_irq_handler*) handler;

	/* Clear any tamper or alarm pending interrupts. */
	status = hsp->rtc->clear_interrupt_status (hsp->rtc,
		REAL_TIME_CLOCK_HSP_INTSTS_INTRUSION_MASK | REAL_TIME_CLOCK_HSP_INTSTS_ALARM_MASK);
	if (status != 0) {
		debug_log_create_entry (DEBUG_LOG_SEVERITY_ERROR, DEBUG_LOG_COMPONENT_INTRUSION,
			INTRUSION_LOGGING_HW_ERROR, status, 0);

		return;
	}

	/* Enable intrusion interrupt. */
	status = hsp->rtc->set_interrupt_enable (hsp->rtc, REAL_TIME_CLOCK_HSP_INTEN_INTRUSION_MASK);
	if (status != 0) {
		debug_log_create_entry (DEBUG_LOG_SEVERITY_ERROR, DEBUG_LOG_COMPONENT_INTRUSION,
			INTRUSION_LOGGING_HW_ERROR, status, 0);

		return;
	}

	/* This shouldn't fail, but it doesn't really matter if it does.
	 * Nothing will happen if no interrupt status bits have been set. */
	platform_semaphore_wait (&hsp->state->rtc_event, 0);

	/* Either intrusion or alarm interrupt was triggered. */
	status = hsp_intrusion_irq_handler_process_events (hsp);
	if (status != 0) {
		debug_log_create_entry (DEBUG_LOG_SEVERITY_ERROR, DEBUG_LOG_COMPONENT_INTRUSION,
			INTRUSION_LOGGING_HW_ERROR, status, 0);
	}
}

bool hsp_intrusion_irq_handler_handle_interrupt (const struct hsp_interrupt_handler *handler,
	uintptr_t param)
{
	int status;
	const struct hsp_intrusion_irq_handler *hsp = TO_DERIVED_TYPE (handler,
		const struct hsp_intrusion_irq_handler, base_irq);

	UNUSED (param);

	/* Disable intrusion interrupt. */
	status = hsp->rtc->set_interrupt_enable (hsp->rtc, 0);
	if (status != 0) {
		return false;
	}

	platform_semaphore_post_from_isr (&hsp->state->rtc_event);

	return true;
}

/**
 * Identify and process intrusion event.
 *
 * @param handler The instance of intrusion HSP IRQ handler.
 *
 */
void hsp_intrusion_irq_handler_handle_intrusion (const struct hsp_intrusion_irq_handler *handler)
{
	int status;

	status =
		handler->intrusion_state->base.check (
		(struct intrusion_state*) &handler->intrusion_state->base);

	/* Intrusion was detected by HW. */
	if (status != 0) {
		status = handler->manager->handle_intrusion (handler->manager);
		if (status != 0) {
			debug_log_create_entry (DEBUG_LOG_SEVERITY_ERROR, DEBUG_LOG_COMPONENT_INTRUSION,
				INTRUSION_LOGGING_HANDLE_FAILED, status, 0);
		}
	}
}

/**
 * Initialize an interrupt handler for a single HSP RTC.
 *
 * @param handler The interrupt handler to initialize.
 * @param state Variable context for the interrupt handler.  This must be uninitialized.
 * @param rtc The HSP RTC generating the interrupts.
 * @param port_irq Port handler for RTC events.
 * @param clear_irq Flag indicating if the current interrupt status should be cleared.
 * @param manager Instance of intrusion manager.
 * @param intrusion_state The instance of intrusion state HSP.
 *
 * @return 0 if the interrupt handler was successfully initialized or an error code.
 */
int hsp_intrusion_irq_handler_init (struct hsp_intrusion_irq_handler *handler,
	struct hsp_intrusion_irq_handler_state *state, const struct real_time_clock_hsp *rtc,
	bool clear_irq, struct intrusion_manager *manager,
	const struct intrusion_state_hsp *intrusion_state)
{
	if ((handler == NULL) || (state == NULL) || (rtc == NULL) ||
		(manager == NULL) || (intrusion_state == NULL)) {
		return REAL_TIME_CLOCK_INVALID_ARGUMENT;
	}

	memset (handler, 0, sizeof (struct hsp_intrusion_irq_handler));

	handler->base.prepare = hsp_intrusion_irq_handler_prepare;
	handler->base.get_next_execution = hsp_intrusion_irq_handler_get_next_execution;
	handler->base.execute = hsp_intrusion_irq_handler_execute;
	handler->base_irq.handle_interrupt = hsp_intrusion_irq_handler_handle_interrupt;
	handler->manager = manager;
	handler->state = state;
	handler->rtc = rtc;
	handler->intrusion_state = intrusion_state;

	return hsp_intrusion_irq_handler_init_state (handler, clear_irq);
}

/**
 * Initialize only the variable state for an HSP RTC interrupt handler.  The rest of the
 * instance is assumed to already have been initialized.
 *
 * This is generally used with static initialization.
 *
 * @param handler The interrupt handler that contains the state to initialize.
 * @param clear_irq Flag indicating if the current interrupt status should be cleared.
 *
 * @return 0 if the handler state was successfully initialized or an error code.
 */
int hsp_intrusion_irq_handler_init_state (const struct hsp_intrusion_irq_handler *handler,
	bool clear_irq)
{
	int status;

	if ((handler == NULL) || (handler->state == NULL) || (handler->rtc == NULL)) {
		return REAL_TIME_CLOCK_INVALID_ARGUMENT;
	}

	memset (handler->state, 0, sizeof (struct hsp_intrusion_irq_handler_state));

	status = platform_semaphore_init (&handler->state->rtc_event);
	if (status != 0) {
		goto semaphore_free;
	}

	status = platform_timer_create (&handler->state->timer,
		(timer_callback) hsp_intrusion_irq_handler_handle_intrusion, (void*) handler);
	if (status != 0) {
		goto delete_timer_semaphore_free;
	}

	if (clear_irq) {
		status = handler->rtc->clear_interrupt_status (handler->rtc,
			REAL_TIME_CLOCK_HSP_INTSTS_INTRUSION_MASK | REAL_TIME_CLOCK_HSP_INTSTS_ALARM_MASK);
		if (status != 0) {
			goto delete_timer_semaphore_free;
		}
	}

	return 0;

delete_timer_semaphore_free:
	platform_timer_delete (&handler->state->timer);
semaphore_free:
	platform_semaphore_free (&handler->state->rtc_event);

	return status;
}

/**
 * Release the resources used for an HSP RTC interrupt handler.  The interrupts will also be
 * disabled.
 *
 * @param handler The interrupt handler to release.
 */
void hsp_intrusion_irq_handler_release (const struct hsp_intrusion_irq_handler *handler)
{
	if (handler) {
		handler->rtc->set_interrupt_enable (handler->rtc, 0);
		platform_semaphore_free (&handler->state->rtc_event);
		platform_timer_delete (&handler->state->timer);
	}
}
