/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    chkpt_1sp_sprt_execute.c

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#include "precomp.h"
#include "chkpt_1sp_sprt_execute.h"

// clang-format off

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_START_SPRT_EXECUTE = 
{
    .Digest0 = 0x005AD6D9,
    .Digest1 = 0x15D89CB4,
    .Digest2 = 0x807D2C03,
    .Digest3 = 0x29BF7D7A,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000000
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_RESET_PCR3 = 
{
    .Digest0 = 0x54E056DF,
    .Digest1 = 0x813871E7,
    .Digest2 = 0x245EB111,
    .Digest3 = 0x83AAD9FD,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_RESET_PCR3_DONE = 
{
    .Digest0 = 0x6242A758,
    .Digest1 = 0x9498C562,
    .Digest2 = 0x58C64278,
    .Digest3 = 0x0837482D,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_APPLY_SECURITY_CFG = 
{
    .Digest0 = 0x4E7F4BC0,
    .Digest1 = 0x610C7BFA,
    .Digest2 = 0xA53FBABA,
    .Digest3 = 0x180C14BB,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_APPLY_SECURITY_CFG_DONE = 
{
    .Digest0 = 0x6E87E4AC,
    .Digest1 = 0x2727175D,
    .Digest2 = 0xD0A32EAA,
    .Digest3 = 0x7C25614F,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOCK_SHARED_DATA = 
{
    .Digest0 = 0x7FC11B2E,
    .Digest1 = 0x877821DF,
    .Digest2 = 0x7B1C06AC,
    .Digest3 = 0x48A0FFDD,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOCK_SHARED_DATA_DONE = 
{
    .Digest0 = 0x863777F3,
    .Digest1 = 0x0C233D16,
    .Digest2 = 0xCF638012,
    .Digest3 = 0xA8ADB083,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_PREPARE_SPRT = 
{
    .Digest0 = 0xC688EDDA,
    .Digest1 = 0x3D88EDFA,
    .Digest2 = 0x6CF0FE0B,
    .Digest3 = 0x98942BF0,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_PREPARE_SPRT_DONE = 
{
    .Digest0 = 0xA7B46F5B,
    .Digest1 = 0x42B8DCC7,
    .Digest2 = 0x63B88398,
    .Digest3 = 0xDA75D34F,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000001
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_FINISH = 
{
    .Digest0 = 0x00000000,
    .Digest1 = 0x00000000,
    .Digest2 = 0x00000000,
    .Digest3 = 0x00000000,
    .Timer0  = 0x00000000,
    .Timer1  = 0x00000001,
    .Fence   = {
                   .NoExpiration = 1, 
                   .PrivStopAllowed = 1, 
                   .UserStopAllowed = 1, 
               },
    .Ctrl    = 0x00000000
};

// clang-format on
