/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    chkpt_1sp_sprt_execute.h

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#pragma once

// clang-format off

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_START_SPRT_EXECUTE;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_RESET_PCR3;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_RESET_PCR3_DONE;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_APPLY_SECURITY_CFG;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_APPLY_SECURITY_CFG_DONE;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOCK_SHARED_DATA;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOCK_SHARED_DATA_DONE;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_PREPARE_SPRT;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_PREPARE_SPRT_DONE;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_FINISH;

// clang-format on
