/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    chkpt_1sp_load_internal.c

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#include "precomp.h"
#include "chkpt_1sp_load_internal.h"

// clang-format off

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOAD_INTERNAL = 
{
    .Digest0 = 0x1C0B628E,
    .Digest1 = 0x2612B8EC,
    .Digest2 = 0xC2D48C30,
    .Digest3 = 0x856B278F,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000000
};

const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOAD_INTERNAL_DONE = 
{
    .Digest0 = 0x00000000,
    .Digest1 = 0x00000000,
    .Digest2 = 0x00000000,
    .Digest3 = 0x00000000,
    .Timer0  = 0x20000000,
    .Timer1  = 0x00000000,
    .Fence   = {
                   .WriteLockMpu = 1, 
                   .AebLock = 1, 
               },
    .Ctrl    = 0x00000000
};

// clang-format on
