/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    chkpt_1sp_load_internal.h

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#pragma once

// clang-format off

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOAD_INTERNAL;

extern const HSP_CHKPT_CONFIG MANTICORE_1SP_CHECKPOINT_LOAD_INTERNAL_DONE;

// clang-format on
