// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_INTERRUPT_HANDLER_H_
#define HSP_INTERRUPT_HANDLER_H_

#include <stdbool.h>
#include <stdint.h>


struct hsp_interrupt_handler;


/**
 * Handler function that is called when the target interrupt is observed.
 *
 * @param handler The current handler instance
 * @param param Parameter passed from the assembly trap handler
 *
 * @return true if the interrupt was handled, else false
 */
typedef bool (*hsp_interrupt_handler_func) (const struct hsp_interrupt_handler *handler,
	uintptr_t param);

/**
 * Base interface to use with components that need to process interrupts generated by the HSP.
 */
struct hsp_interrupt_handler {
	hsp_interrupt_handler_func handle_interrupt;
};


#endif	/* HSP_INTERRUPT_HANDLER_H_ */
