# Copyright (c) Microsoft Corporation. All rights reserved.

[package]
name = "mcr-mem-map-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
doctest = false

[dependencies]
anyhow.workspace = true
convert_case.workspace = true
darling.workspace = true
paste.workspace = true
quote.workspace = true
regex.workspace = true
syn.workspace = true
