// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef EPHEMERAL_KEY_MONITOR_H_
#define EPHEMERAL_KEY_MONITOR_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "platform_api.h"
#include "crypto/aes_key_wrap_interface.h"
#include "drivers/hsp_dmb.h"
#include "keystore/key_cache.h"
#include "status/manticore_module_id.h"
#include "system/periodic_task.h"


/**
 * Per-slot layout of the HSM Part Persistent Store in shared GSRAM (design doc §3).  Shared SP<->CP
 * ABI: the CP writes byte +22, the SP reads it.  Accessors are file-static in the .c.
 *   +0..21   reserved for other HSP metadata (not touched here)
 *   +22      unwrapping_key_required - Gate 1, CP-written: 1 = PFN armed, stage a key
 *   +23      unwrapping_key_bk_valid - Gate 2, publish handshake: 1 = payload at +24 is valid
 *   +24..539 RSA-2K private key, PKA little-endian `d || n || e`
 */
#define	PART_PERSISTENT_STORE_SLOT_SIZE				3072u
#define	PART_PERSISTENT_STORE_REQUIRED_OFFSET		22u
#define	PART_PERSISTENT_STORE_VALID_OFFSET			23u
#define	PART_PERSISTENT_STORE_KEY_OFFSET			24u
#define	PART_PERSISTENT_STORE_KEY_SIZE				516u

#define	PART_PERSISTENT_STORE_SLOT_COUNT			65u

/* The PKA-LE key payload must fit within a slot, after the two gate bytes. */
_Static_assert (PART_PERSISTENT_STORE_KEY_OFFSET + PART_PERSISTENT_STORE_KEY_SIZE <=
	PART_PERSISTENT_STORE_SLOT_SIZE, "RSA key payload overflows the persistent-store slot");
_Static_assert (PART_PERSISTENT_STORE_REQUIRED_OFFSET < PART_PERSISTENT_STORE_KEY_OFFSET,
	"Gate 1 (required) byte must precede the key payload");
_Static_assert (PART_PERSISTENT_STORE_VALID_OFFSET < PART_PERSISTENT_STORE_KEY_OFFSET,
	"Gate 2 (valid) byte must precede the key payload");
_Static_assert (PART_PERSISTENT_STORE_REQUIRED_OFFSET != PART_PERSISTENT_STORE_VALID_OFFSET,
	"the two gate bytes must occupy distinct offsets");


/**
 * Max length of a DER-encoded RSA-2K private key on flash.  The monitor converts it to the 516-byte
 * PKA-LE payload at runtime, so the on-flash format stays DER.
 */
#define	EPHEMERAL_KEY_MONITOR_RSA_2K_DER_MAX_SIZE	1270


/**
 * Size of the injected working buffer: holds the DER key from `key_cache.remove()` (unwrapped in
 * place), then the converter writes the 516-byte PKA-LE payload back into the same buffer.
 */
#define	EPHEMERAL_KEY_MONITOR_KEY_BUFFER_SIZE   \
	AES_KEY_WRAP_INTERFACE_WRAPPED_LENGTH (EPHEMERAL_KEY_MONITOR_RSA_2K_DER_MAX_SIZE)


/**
 * Variable context for the ephemeral key monitor.
 */
struct ephemeral_key_monitor_state {
	platform_clock next;	/**< Time at which the next execution should run. */
	bool next_valid;		/**< Indicates the next timeout has been initialized. */
};

/**
 * Handler that periodically scans the GSRAM partition persistent store and refills each empty
 * unwrapping-key slot from the flash key cache, stopping per-slot on any error (retried next tick).
 */
struct ephemeral_key_monitor {
	struct periodic_task_handler base;			/**< Base interface for task integration. */
	struct ephemeral_key_monitor_state *state;	/**< Variable context for the handler. */
	const struct hsp_dmb *dmb;					/**< DMB interface used to map GSRAM slot windows. */
	const struct key_cache *key_cache;			/**< Flash-backed key cache feeding refill attempts. */
	uint8_t *key_buffer;						/**< Injected working buffer: DER key in, PKA-LE payload out. */
	size_t key_buffer_len;						/**< Length of the injected working buffer, in bytes. */
	uint32_t period_ms;							/**< Time between scan ticks, in milliseconds. */
	uint64_t part_persistent_store_base;		/**< SoC base address of the HSM Part Persistent Store. */
};


int ephemeral_key_monitor_init (struct ephemeral_key_monitor *monitor,
	struct ephemeral_key_monitor_state *state, const struct hsp_dmb *dmb,
	const struct key_cache *key_cache, uint8_t *key_buffer, size_t key_buffer_len,
	uint32_t period_ms, uint64_t part_persistent_store_base);
int ephemeral_key_monitor_init_state (const struct ephemeral_key_monitor *monitor);
void ephemeral_key_monitor_release (const struct ephemeral_key_monitor *monitor);


#define	EPHEMERAL_KEY_MONITOR_ERROR(code)  ROT_ERROR (MANTICORE_MODULE_EPHEMERAL_KEY_MONITOR, code)

/**
 * Error codes that can be generated by the ephemeral key monitor module.
 */
enum {
	EPHEMERAL_KEY_MONITOR_INVALID_ARGUMENT = EPHEMERAL_KEY_MONITOR_ERROR (0x00),			/**< Input parameter is null or not valid. */
	EPHEMERAL_KEY_MONITOR_NO_MEMORY = EPHEMERAL_KEY_MONITOR_ERROR (0x01),					/**< Memory allocation failure. */
	EPHEMERAL_KEY_MONITOR_DMB_MAP_FAILED = EPHEMERAL_KEY_MONITOR_ERROR (0x02),				/**< Failed to map the slot window in GSRAM. */
	EPHEMERAL_KEY_MONITOR_CONVERT_SMALL_OUTPUT = EPHEMERAL_KEY_MONITOR_ERROR (0x03),		/**< Output buffer is too small for the PKA-LE layout. */
	EPHEMERAL_KEY_MONITOR_CONVERT_KEY_PARSE_FAILED = EPHEMERAL_KEY_MONITOR_ERROR (0x04),	/**< Failed to parse the DER-encoded key. */
	EPHEMERAL_KEY_MONITOR_CONVERT_KEY_NOT_RSA = EPHEMERAL_KEY_MONITOR_ERROR (0x05),			/**< Parsed key is not an RSA key. */
	EPHEMERAL_KEY_MONITOR_CONVERT_KEY_EXPORT_FAILED = EPHEMERAL_KEY_MONITOR_ERROR (0x06),	/**< Failed to export raw RSA components. */
	EPHEMERAL_KEY_MONITOR_SLOT_SKIPPED = EPHEMERAL_KEY_MONITOR_ERROR (0x07),				/**< Slot intentionally skipped (PFN not/no-longer armed); not a failure. */
};


#endif	/* EPHEMERAL_KEY_MONITOR_H_ */
