/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    rom_chkpt_part2_flash.h

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#pragma once

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_START_FLASH_LOAD;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_HAND_OFF_FLASH_NEXT;

