/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    rom_chkpt_part1.h

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#pragma once

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_INIT;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_UNLOCK_MPU;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_LOCK_MPU;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_UNLOCK_CRYPTO;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_HAND_OFF_FIRMWARE_LOAD;

