/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    rom_chkpt_part2_recovery.h

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#pragma once

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_START_RECOVERY_LOAD;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_RECOVERY_VERIFY;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_HAND_OFF_RECOVERY_NEXT;

