/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    rom_chkpt_part3.h

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#pragma once

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_ROM_FINALIZE;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_FINISH;

