// Copyright (c) Microsoft Corporation. All rights reserved.

#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "common/common_math.h"
#include "common/type_cast.h"
#include "common/unused.h"
#include "spi_filter/spi_filter_hsp_irq_handler.h"
#include "spi_filter/spi_filter_logging.h"


/**
 * Interrupt status bits for the HSP SPI filter.
 */
enum {
	SPI_FILTER_HSP_IRQ_HANDLER_DIRTY = (1U << 0),		/**< SPI filter detected an operation that modified flash. */
	SPI_FILTER_HSP_IRQ_HANDLER_BLOCKED = (1U << 1),		/**< SPI filter blocked an illegal opcode from the host. */
	SPI_FILTER_HSP_IRQ_HANDLER_BYTE_MODE = (1U << 2),	/**< The SPI filter detected a change in the flash address mode. */
};


/**
 * Handle an interrupt for a blocked SPI command.
 *
 * @param handler The handler context for processing.
 * @param port The filter port generating the interrupt.
 */
static void spi_filter_hsp_irq_handler_blocked_opcode (
	const struct spi_filter_hsp_irq_handler *handler, int port)
{
	uint8_t opcode;
	int status;

	opcode = handler->filter->get_blocked_opcode (handler->filter);

	/* Only log each blocked opcode value once. */
	if (!common_math_is_bit_set_in_array (handler->state->blocked, sizeof (handler->state->blocked),
		opcode)) {
		status = debug_log_create_entry (DEBUG_LOG_SEVERITY_INFO, DEBUG_LOG_COMPONENT_SPI_FILTER,
			SPI_FILTER_LOGGING_BLOCKED_COMMAND, port, opcode);

		if (status == 0) {
			common_math_set_bit_in_array (handler->state->blocked, sizeof (handler->state->blocked),
				opcode);
		}
	}
}

/**
 * Handle an interrupt for a switch in the filter address mode.
 *
 * @param handler The handler context for processing.
 * @param port The filter port generating the interrupt.
 */
static void spi_filter_hsp_irq_handler_address_mode (
	const struct spi_filter_hsp_irq_handler *handler, int port)
{
	spi_filter_address_mode mode;
	int status;

	status = handler->filter->base.get_addr_byte_mode (&handler->filter->base, &mode);

	debug_log_create_entry ((status == 0) ? DEBUG_LOG_SEVERITY_INFO : DEBUG_LOG_SEVERITY_ERROR,
		DEBUG_LOG_COMPONENT_SPI_FILTER, SPI_FILTER_LOGGING_ADDRESS_MODE, port,
		(status == 0) ? mode : (uint32_t) status);
}

/**
 * Process events generated by the HSP SPI filter.
 *
 * @param handler The handler context for processing.
 * @param event_irq Bitmask of the events generated by the SPI filter.
 */
static void spi_filter_hsp_irq_handler_process_events (
	const struct spi_filter_hsp_irq_handler *handler, uint32_t event_irq)
{
	int port;

	if (event_irq != 0) {
		port = handler->filter->base.get_port (&handler->filter->base);

		/* Generate a log entry any time the SPI filter triggers an interrupt.  However, don't log
		 * interrupts that are only for blocked opcodes.  These get logged differently and it
		 * prevents filling the log with messages for blocked opcode IRQs.
		 *
		 * Address mode changes also don't need to get logged here, since those always generate a
		 * different log entry. */
		if (event_irq &
			~(SPI_FILTER_HSP_IRQ_HANDLER_BLOCKED | SPI_FILTER_HSP_IRQ_HANDLER_BYTE_MODE)) {
			debug_log_create_entry (DEBUG_LOG_SEVERITY_INFO, DEBUG_LOG_COMPONENT_SPI_FILTER,
				SPI_FILTER_LOGGING_IRQ_STATUS, port, event_irq);
		}

		if (event_irq & SPI_FILTER_HSP_IRQ_HANDLER_DIRTY) {
			handler->port_irq->ro_flash_dirty (handler->port_irq);
		}

		if (event_irq & SPI_FILTER_HSP_IRQ_HANDLER_BLOCKED) {
			spi_filter_hsp_irq_handler_blocked_opcode (handler, port);
		}

		if (event_irq & SPI_FILTER_HSP_IRQ_HANDLER_BYTE_MODE) {
			spi_filter_hsp_irq_handler_address_mode (handler, port);
		}
	}
}

void spi_filter_hsp_irq_handler_prepare (const struct periodic_task_handler *handler)
{
	const struct spi_filter_hsp_irq_handler *hsp =
		(const struct spi_filter_hsp_irq_handler*) handler;
	uint32_t irq_status;

	/* Get and clear the current status of any interrupts before enabling interrupt processing. */
	irq_status = hsp->filter->get_interrupt_status (hsp->filter);

	/* Enable interrupt before processing any existing interrupts so new events during processing
	 * trigger the interrupt handler. */
	hsp->filter->set_interrupt_enable (hsp->filter, SPI_FILTER_HSP_IRQ_HANDLER_DIRTY |
		SPI_FILTER_HSP_IRQ_HANDLER_BLOCKED | SPI_FILTER_HSP_IRQ_HANDLER_BYTE_MODE);

	spi_filter_hsp_irq_handler_process_events (hsp, irq_status);
}

const platform_clock* spi_filter_hsp_irq_handler_get_next_execution (
	const struct periodic_task_handler *handler)
{
	UNUSED (handler);

	/* Do not wait to call execute again. */
	return NULL;
}

void spi_filter_hsp_irq_handler_execute (const struct periodic_task_handler *handler)
{
	const struct spi_filter_hsp_irq_handler *hsp =
		(const struct spi_filter_hsp_irq_handler*) handler;
	uint32_t event_irq;

	/* This shouldn't fail, but it doesn't really matter if it does.  Nothing will happen if no
	 * interrupt status bits have been set. */
	platform_semaphore_wait (&hsp->state->filter_event, 0);

	/* Get a local copy of the interrupt status and clear the bits that will be processed.  This is
	 * to ensure any new interrupts don't get missed while processing the current ones. */
	event_irq = hsp->state->event_irq;
	hsp->state->event_irq &= ~event_irq;

	spi_filter_hsp_irq_handler_process_events (hsp, event_irq);

	/* This task handler is naturally a loop, so there is no need to loop on the event IRQs until
	 * they are clear.  Any new interrupts will get handled on the next invocation of this
	 * handler. */
}

bool spi_filter_hsp_irq_handler_handle_interrupt (const struct hsp_interrupt_handler *handler,
	uintptr_t param)
{
	const struct spi_filter_hsp_irq_handler *hsp = TO_DERIVED_TYPE (handler,
		const struct spi_filter_hsp_irq_handler, base_irq);
	uint32_t irq_enabled;

	UNUSED (param);

	irq_enabled = hsp->filter->get_interrupt_enable (hsp->filter);
	if (irq_enabled == 0) {
		/* The SPI filter has no interrupts enabled, so the interrupt is not for this instance. */
		return false;
	}

	/* Update the internal status to aggregate all interrupts received. */
	hsp->state->event_irq |= hsp->filter->get_interrupt_status (hsp->filter);
	platform_semaphore_post_from_isr (&hsp->state->filter_event);

	return true;
}

/**
 * Initialize an interrupt handler for a single HSP SPI filter.
 *
 * @param handler The interrupt handler to initialize.
 * @param state Variable context for the interrupt handler.  This must be uninitialized.
 * @param filter The HSP SPI filter generating the interrupts.
 * @param port_irq Port handler for SPI filter events.
 * @param clear_irq Flag indicating if the current interrupt status should be cleared.
 *
 * @return 0 if the interrupt handler was successfully initialized or an error code.
 */
int spi_filter_hsp_irq_handler_init (struct spi_filter_hsp_irq_handler *handler,
	struct spi_filter_hsp_irq_handler_state *state, const struct spi_filter_hsp *filter,
	const struct spi_filter_irq_handler *port_irq, bool clear_irq)
{
	if ((handler == NULL) || (state == NULL) || (filter == NULL) || (port_irq == NULL)) {
		return SPI_FILTER_IRQ_INVALID_ARGUMENT;
	}

	memset (handler, 0, sizeof (struct spi_filter_hsp_irq_handler));

	handler->base.prepare = spi_filter_hsp_irq_handler_prepare;
	handler->base.get_next_execution = spi_filter_hsp_irq_handler_get_next_execution;
	handler->base.execute = spi_filter_hsp_irq_handler_execute;

	handler->base_irq.handle_interrupt = spi_filter_hsp_irq_handler_handle_interrupt;

	handler->state = state;
	handler->filter = filter;
	handler->port_irq = port_irq;

	return spi_filter_hsp_irq_handler_init_state (handler, clear_irq);
}

/**
 * Initialize only the variable state for an HSP SPI filter interrupt handler.  The rest of the
 * instance is assumed to already have been initialized.
 *
 * This is generally used with static initialization.
 *
 * @param handler The interrupt handler that contains the state to initialize.
 * @param clear_irq Flag indicating if the current interrupt status should be cleared.
 *
 * @return 0 if the handler state was successfully initialized or an error code.
 */
int spi_filter_hsp_irq_handler_init_state (const struct spi_filter_hsp_irq_handler *handler,
	bool clear_irq)
{
	int status;

	if ((handler == NULL) || (handler->state == NULL) || (handler->filter == NULL) ||
		(handler->port_irq == NULL)) {
		return SPI_FILTER_IRQ_INVALID_ARGUMENT;
	}

	memset (handler->state, 0, sizeof (struct spi_filter_hsp_irq_handler_state));

	status = platform_semaphore_init (&handler->state->filter_event);
	if (status != 0) {
		return status;
	}

	if (clear_irq) {
		handler->filter->get_interrupt_status (handler->filter);
	}

	return 0;
}

/**
 * Release the resources used for an HSP SPI filter interrupt handler.  The interrupts will also be
 * disabled.
 *
 * @param handler The interrupt handler to release.
 */
void spi_filter_hsp_irq_handler_release (const struct spi_filter_hsp_irq_handler *handler)
{
	if (handler) {
		handler->filter->set_interrupt_enable (handler->filter, 0);
	}
}
