// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_MAILBOX_MSG_HANDLER_INTERFACE_H_
#define HSP_MAILBOX_MSG_HANDLER_INTERFACE_H_

#include <stddef.h>
#include <stdint.h>
#include "hsp_mailbox_msg.h"
#include "status/msft_module_id.h"


/**
 * Interface for executing mailbox messages and sending response to the caller.
 */
struct hsp_mailbox_msg_handler_interface {
	/**
	 * Process incoming request from mailbox message and send the
	 * response to the caller.
	 *
	 * @param msg_handler The command interface for processing the incoming request.
	 * @param request incoming request from the mailbox.
	 * @param response outgoing response sent to the caller after processing the command.
	 *
	 * @return 0 if the processing was successful or an error code.
	 */
	int (*process_msg) (const struct hsp_mailbox_msg_handler_interface *msg_handler,
		const struct hsp_mailbox_msg *request, struct hsp_mailbox_msg *response);
};

#define	HSP_MAILBOX_MSG_HANDLER_ERROR(code)	ROT_ERROR (MSFT_MODULE_HSP_MAILBOX_MSG_HANDLER, code)

/**
 * Error codes that can be generated by a mailbox message handler.
 */
enum {
	HSP_MAILBOX_MSG_HANDLER_INVALID_ARGUMENT = HSP_MAILBOX_MSG_HANDLER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_MAILBOX_MSG_HANDLER_NO_MEMORY = HSP_MAILBOX_MSG_HANDLER_ERROR (0x01),			/**< Memory allocation failed. */
	HSP_MAILBOX_MSG_HANDLER_INVALID_CMD = HSP_MAILBOX_MSG_HANDLER_ERROR (0x02),			/**< Invalid command. */
	HSP_MAILBOX_MSG_HANDLER_INVALID_BUFFER_SIZE = HSP_MAILBOX_MSG_HANDLER_ERROR (0x03),	/**< Invalid Buffer size. */
	HSP_MAILBOX_MSG_HANDLER_PROCESS_FAILED = HSP_MAILBOX_MSG_HANDLER_ERROR (0x04),		/**< Process Message failed. */
};


#endif	/* MAILBOX_MSG_HANDLER_INTERFACE_H_ */
