// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_MAILBOX_INTERFACE_H_
#define HSP_MAILBOX_INTERFACE_H_

#include <stdbool.h>
#include <stdint.h>
#include "status/msft_module_id.h"


/**
 * Defines the interface to an HSP mailbox.
 *
 * send_* functions are for manipulating the outgoing FIFO + controls
 * recv_* functions are for manipulating the incoming FIFO + controls
 */
struct hsp_mailbox_interface {
	/**
	 * Pushes a 32-bit word to the outgoing FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 * @param data The data to push to the FIFO
	 *
	 * @return 0 if the push was successful or an error code.
	 */
	int (*send_fifo_push) (const struct hsp_mailbox_interface *mailbox, uint32_t data);

	/**
	 * Sets the valid bit on the outgoing FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 *
	 * @return 0 if the set was successful or an error code.
	 */
	int (*send_set_valid) (const struct hsp_mailbox_interface *mailbox);

	/**
	 * Sets the err bit on the outgoing FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 *
	 * @return 0 if the set was successful or an error code.
	 */
	int (*send_set_err) (const struct hsp_mailbox_interface *mailbox);

	/**
	 * Reads the status information for the outgoing FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 * @param is_valid Optional pointer to variable in which to store the valid bit. Can be set to NULL if not needed.
	 * @param is_err Optional pointer to variable in which to store the err bit. Can be set to NULL if not needed.
	 * @param count Optional pointer to variable in which to store the FIFO count. Can be set to NULL if not needed.
	 *
	 * @return 0 if the read was successful or an error code.
	 */
	int (*send_get_status) (const struct hsp_mailbox_interface *mailbox, bool *is_valid,
		bool *is_err, uint32_t *count);

	/**
	 * Pops a 32-bit word from the incoming FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 * @param data Pointer to variable in which to store the FIFO value
	 *
	 * @return 0 if the pop was successful or an error code.
	 */
	int (*recv_fifo_pop) (const struct hsp_mailbox_interface *mailbox, uint32_t *data);

	/**
	 * Reads the status information for the incoming FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 * @param is_valid Optional pointer to variable in which to store the valid bit. Can be set to NULL if not needed.
	 * @param is_err Optional pointer to variable in which to store the err bit. Can be set to NULL if not needed.
	 * @param count Optional pointer to variable in which to store the FIFO count. Can be set to NULL if not needed.
	 *
	 * @return 0 if the read was successful or an error code.
	 */
	int (*recv_get_status) (const struct hsp_mailbox_interface *mailbox, bool *is_valid,
		bool *is_err, uint32_t *count);

	/**
	 * Clears the valid bit on the incoming FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 *
	 * @return 0 if the clear was successful or an error code.
	 */
	int (*recv_clear_valid) (const struct hsp_mailbox_interface *mailbox);

	/**
	 * Clears the err bit on the incoming FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 *
	 * @return 0 if the clear was successful or an error code.
	 */
	int (*recv_clear_err) (const struct hsp_mailbox_interface *mailbox);

	/**
	 * Enables/disables the fifo_valid interrupt on the incoming FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 *
	 * @return 0 if the enable/disable was successful or an error code.
	 */
	int (*recv_enable_fifo_valid_interrupt) (const struct hsp_mailbox_interface *mailbox,
		bool enabled);

	/**
	 * Enables/disables the err interrupt on the incoming FIFO
	 *
	 * @param mailbox The mailbox interface for accessing the hardware
	 *
	 * @return 0 if the enable/disable was successful or an error code.
	 */
	int (*recv_enable_err_interrupt) (const struct hsp_mailbox_interface *mailbox, bool enabled);
};

#define	HSP_MAILBOX_ERROR(code) ROT_ERROR (MSFT_MODULE_HSP_MAILBOX, code)

/**
 * Error codes that can be generated by the HSP mailbox.
 */
enum {
	HSP_MAILBOX_INVALID_ARGUMENT = HSP_MAILBOX_ERROR (0x00),						/**< Input parameter not valid. */
	HSP_MAILBOX_NO_MEMORY = HSP_MAILBOX_ERROR (0x01),								/**< Memory not available. */
	HSP_MAILBOX_SEND_FIFO_PUSH_FAILED = HSP_MAILBOX_ERROR (0x02),					/**< Failed to fifo push. */
	HSP_MAILBOX_SEND_SET_VALID_FAILED = HSP_MAILBOX_ERROR (0x03),					/**< Failed to set valid bit. */
	HSP_MAILBOX_SEND_SET_ERR_FAILED = HSP_MAILBOX_ERROR (0x04),						/**< Failed to set err bit. */
	HSP_MAILBOX_SEND_GET_STATUS_FAILED = HSP_MAILBOX_ERROR (0x05),					/**< Failed to get status. */
	HSP_MAILBOX_RECV_FIFO_POP_FAILED = HSP_MAILBOX_ERROR (0x06),					/**< Failed to fifo pop. */
	HSP_MAILBOX_RECV_GET_STATUS_FAILED = HSP_MAILBOX_ERROR (0x07),					/**< Failed to get status. */
	HSP_MAILBOX_RECV_CLEAR_VALID_FAILED = HSP_MAILBOX_ERROR (0x08),					/**< Failed to clear valid bit. */
	HSP_MAILBOX_RECV_CLEAR_ERROR_FAILED = HSP_MAILBOX_ERROR (0x09),					/**< Failed to clear error bit. */
	HSP_MAILBOX_RECV_ENABLE_FIFO_VALID_INTERRUPT_FAILED = HSP_MAILBOX_ERROR (0x0A),	/**< Failed to enable fifo valid interrupt. */
	HSP_MAILBOX_RECV_ENABLE_ERR_INTERRUPT_FAILED = HSP_MAILBOX_ERROR (0x0B),		/**< Failed to eanble err interrupt. */
};


#endif	/* HSP_MAILBOX_INTERFACE_H_ */
