// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_MAILBOX_PROTOCOL_INTERFACE_H_
#define HSP_MAILBOX_PROTOCOL_INTERFACE_H_

#include <stdint.h>
#include "mailbox/hsp_mailbox_msg.h"
#include "status/msft_module_id.h"

/**
 * Defines the interface to the hsp_mailbox_protocol.
 */
struct hsp_mailbox_protocol_interface {
	/**
	 * Sends a message using the mailbox prototol
	 *
	 * @param protocol The protocol interface for accessing the mailbox
	 * @param message The message to send via the mailbox
	 *
	 * @return 0 if the send was successful or an error code.
	 */
	int (*send) (const struct hsp_mailbox_protocol_interface *protocol,
		const struct hsp_mailbox_msg *message);

	/**
	 * Requests a fifo flush from the receiver of the outgoing side of the mailbox
	 *
	 * @param protocol The protocol interface for accessing the mailbox
	 *
	 * @return 0 if the request was successful or an error code.
	 */
	int (*request_flush) (const struct hsp_mailbox_protocol_interface *protocol);

	/**
	 * Receives a message using the mailbox prototol
	 *
	 * Will automatically flush if the following error conditions are detected:
	 *		- Error bit was set: HSP_MAILBOX_PROTOCOL_RECV_ERR_BIT_SET
	 *		- An invalid fifo count was detected:
	 *				HSP_MAILBOX_PROTOCOL_RECV_FIFO_NO_DATA or
	 *				HSP_MAILBOX_PROTOCOL_RECV_FIFO_OVERFLOW
	 *
	 * HSP_MAILBOX_PROTOCOL_RECV_FIFO_NOT_VALID as a return error code can be
	 * used during polling operations. It means that there was not a valid message
	 * in the fifo.
	 *
	 * @param protocol The protocol interface for accessing the mailbox
	 * @param message The message to send via the mailbox
	 *
	 * @return 0 if the receive was successful or an error code.
	 */
	int (*receive) (const struct hsp_mailbox_protocol_interface *protocol,
		struct hsp_mailbox_msg *message);

	/**
	 * Flushes the fifo on the incoming side of the mailbox
	 *
	 * @param protocol The protocol interface for accessing the mailbox
	 *
	 * @return 0 if the flush was successful or an error code.
	 */
	int (*flush) (const struct hsp_mailbox_protocol_interface *protocol);
};

#define	HSP_MAILBOX_PROTOCOL_ERROR(code) ROT_ERROR (MSFT_MODULE_HSP_MAILBOX_PROTOCOL, code)

/**
 * Error codes that can be generated by the HSP mailbox protocol.
 */
enum {
	HSP_MAILBOX_PROTOCOL_INVALID_ARGUMENT = HSP_MAILBOX_PROTOCOL_ERROR (0x00),		/**< Input parameter not valid. */
	HSP_MAILBOX_PROTOCOL_NO_MEMORY = HSP_MAILBOX_PROTOCOL_ERROR (0x01),				/**< Memory not available. */
	HSP_MAILBOX_PROTOCOL_SEND_FAILED = HSP_MAILBOX_PROTOCOL_ERROR (0x02),			/**< Failed to send */
	HSP_MAILBOX_PROTOCOL_SEND_INVALID_SIZE = HSP_MAILBOX_PROTOCOL_ERROR (0x03),		/**< Invalid mailbox size */
	HSP_MAILBOX_PROTOCOL_SEND_ERR_BIT_SET = HSP_MAILBOX_PROTOCOL_ERROR (0x04),		/**< Err bit set when attenpting send. */
	HSP_MAILBOX_PROTOCOL_SEND_FIFO_VALID_SET = HSP_MAILBOX_PROTOCOL_ERROR (0x05),	/**< Fifo valid bit set when attempting send */
	HSP_MAILBOX_PROTOCOL_SEND_FIFO_NOT_EMPTY = HSP_MAILBOX_PROTOCOL_ERROR (0x06),	/**< Fifo not empty when attempting send */
	HSP_MAILBOX_PROTOCOL_REQUEST_FLUSH_FAILED = HSP_MAILBOX_PROTOCOL_ERROR (0x07),	/**< Failed to request flush */
	HSP_MAILBOX_PROTOCOL_RECV_FAILED = HSP_MAILBOX_PROTOCOL_ERROR (0x08),			/**< Failed to receive */
	HSP_MAILBOX_PROTOCOL_RECV_ERR_BIT_SET = HSP_MAILBOX_PROTOCOL_ERROR (0x09),		/**< Err bit set when attenpting receive. */
	HSP_MAILBOX_PROTOCOL_RECV_FIFO_NOT_VALID = HSP_MAILBOX_PROTOCOL_ERROR (0x0A),	/**< Fifo valid bit not set when attempting receive */
	HSP_MAILBOX_PROTOCOL_RECV_FIFO_NO_DATA = HSP_MAILBOX_PROTOCOL_ERROR (0x0B),		/**< Fifo is empty when attempting read */
	HSP_MAILBOX_PROTOCOL_RECV_FIFO_OVERFLOW = HSP_MAILBOX_PROTOCOL_ERROR (0x0C),	/**< Fifo contains more data than can be handled */
	HSP_MAILBOX_PROTOCOL_FLUSH_FAILED = HSP_MAILBOX_PROTOCOL_ERROR (0x0D),			/**< Failed to flush */
};


#endif	/* HSP_MAILBOX_PROTOCOL_INTERFACE_H_ */
