// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef CMD_INTERFACE_TDISP_EVENT_POLICY_H
#define CMD_INTERFACE_TDISP_EVENT_POLICY_H

#include "cmd_interface/cmd_interface.h"
#include "host_fw/host_processor_observer.h"
#include "ipc/ipc_channel.h"
#include "pcisig/ide/ide_driver.h"
#include "pcisig/ide/ide_driver_observer.h"
#include "pcisig/tdisp/tdisp_driver.h"
#include "pcisig/tdisp/tdisp_driver_observer.h"
#include "spdm/spdm_protocol_session_observer.h"
#include "status/manticore_module_id.h"


/**
 * TDISP event policy sources identifying specific events that can be handled by the TDISP event
 * policy.
 */
enum cmd_interface_tdisp_event_policy_source {
	CMD_INTERFACE_TDISP_EVENT_POLICY_SOURCE_TDISP = 0x0,			/**< TDISP event. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_SOURCE_IDE = 0x1,				/**< IDE event. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_SOURCE_PCIE_FLR = 0x2,			/**< PCIe Function Level Reset event. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_SOURCE_PCIE_PERST_UP = 0x3,	/**< PCIe PERST up event. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_SOURCE_PCIE_PERST_DOWN = 0x4,	/**< PCIe PERST down event. */
};

#pragma pack(push, 1)
/**
 * TDISP event policy request and response payload structure.
 */
struct cmd_interface_tdisp_event_policy_payload {
	uint32_t source;	/**< The source of the event. */
	uint64_t vf_mask;	/**< Mask indicating which virtual functions are impacted by the source event. */
	uint32_t pf_mask;	/**< Mask indicating whether the Physical Function is impacted by the source event. */
	uint32_t reg[5];	/**< Register data associated with the source event. */
};

#pragma pack(pop)

/**
 * Structure for keeping TDISP event policy runtime state
 */
struct cmd_interface_tdisp_event_policy_state {
	bool skip_on_ide_set_stop_processing;	/**< Indicates whether to skip ide_on_set_stop processing or not */
};

/**
 * TDISP event policy command interface.  This interface receives requests which indicate events
 * impacting TDISP state (e.g. TDISP errors, IDE errors, TDISP stop interface requests, PCIe FLR or
 * PERST) and processes them through calls to the respective drivers or IPC requests.
 */
struct cmd_interface_tdisp_event_policy {
	struct cmd_interface base;								/**< Base command interface. */
	const struct ipc_channel *ipc_to_admin;					/**< Channel to use for sending IPC requests from HSP to Admin. */
	const struct ide_driver *ide;							/**< IDE driver interface. */
	const struct tdisp_driver *tdisp;						/**< TDISP driver interface. */
	uint32_t ipc_timeout_per_fn;							/**< Timeout to use per function for IPC operations to Admin, in milliseconds. */
	struct spdm_protocol_session_observer spdm_observer;	/**< SPDM observer to notify of SPDM session events. */
	struct ide_driver_observer ide_observer;				/**< IDE driver observer to notify of IDE driver events. */
	struct tdisp_driver_observer tdisp_observer;			/**< TDISP driver observer to notify of TDISP driver events. */
	struct host_processor_observer host_observer;			/**< Host processor observer to notify of host events. */
	struct cmd_interface_tdisp_event_policy_state *state;	/**< TDISP event policy state */
};


int cmd_interface_tdisp_event_policy_init (struct cmd_interface_tdisp_event_policy *policy,
	struct cmd_interface_tdisp_event_policy_state *state, struct ipc_channel *ipc_to_admin,
	struct ide_driver *ide, struct tdisp_driver *tdisp, uint32_t ipc_timeout_per_fn_ms);
void cmd_interface_tdisp_event_policy_release (
	const struct cmd_interface_tdisp_event_policy *policy);
int cmd_interface_tdisp_event_policy_init_state (
	const struct cmd_interface_tdisp_event_policy *policy);

#define	CMD_INTERFACE_TDISP_EVENT_POLICY_ERROR(code) \
		ROT_ERROR (MANTICORE_MODULE_CMD_INTERFACE_TDISP_EVENT_POLICY, code)

/**
 * Error codes that can be generated by the TDISP event policy command interface.
 */
enum {
	CMD_INTERFACE_TDISP_EVENT_POLICY_INVALID_ARGUMENT =
		CMD_INTERFACE_TDISP_EVENT_POLICY_ERROR (0x00),											/**< Input parameter is null or not valid. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_NO_MEMORY = CMD_INTERFACE_TDISP_EVENT_POLICY_ERROR (0x01),	/**< Memory allocation failed. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_UNSUPPORTED_OPERATION =
		CMD_INTERFACE_TDISP_EVENT_POLICY_ERROR (0x02),											/**< The operation is not supported. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_INVALID_MSG_SIZE =
		CMD_INTERFACE_TDISP_EVENT_POLICY_ERROR (0x03),											/**< The message size is incorrect. */
	CMD_INTERFACE_TDISP_EVENT_POLICY_INVALID_SOURCE =
		CMD_INTERFACE_TDISP_EVENT_POLICY_ERROR (0x04),											/**< Invalid source mask. */
};


#endif	/* CMD_INTERFACE_TDISP_EVENT_POLICY_H */
