// Copyright (c) Microsoft Corporation. All rights reserved.

#include "hsp_top.h"
#include "init_crypto.h"
#include "init_error.h"
#include "init_firmware.h"
#include "init_flash.h"
#include "init_spdm.h"
#include "init_system.h"
#include "manticore_rom.h"
#include "rot_memory_map.h"
#include "sp_boot.h"
#include "task_priority.h"
#include "task_stack_size.h"
#include "common/array_size.h"
#include "crypto/signature_verification_ecc_static.h"
#include "firmware/app_context_null_static.h"
#include "firmware/firmware_update_observer_impactful_static.h"
#include "firmware/firmware_update_observer_sprt_static.h"
#include "firmware/hw_rot_firmware_key_manifest_static.h"
#include "firmware/hw_rot_hsp_rom_no_fuses_static.h"
#include "firmware/impactful_update_static.h"
#include "firmware/manticore_fw_keys.h"
#include "splibs/hsprt/riscvcpu.h"


/**
 * The amount of time each impactful update authorization will be valid for.  This should be long
 * enough to successfully receive and process an image, but it should be short enough to reduce the
 * possibility of stale authorization granting the ability to run an impactful update.
 */
#define	MANTICORE_IMPACTFUL_AUTHORIZATION_TIME		(90 * 60 * 1000)	/* 90 min */

/**
 * The amount of time to wait for prepare firmware update execution to complete before timing out
 * and returning an error.
 */
#define	MANTICORE_PREPARE_UPDATE_WAIT_TIME			(10 * 1000)			/* 10 seconds */


/**
 * Firmware image partitioning information.
 */
static const struct firmware_flash_map flash_fw_partitions = {
	.active_flash = &flash_internal.base,
	.active_addr = MANTICORE_MAIN_BOOT_ADDR,
	.active_size = MANTICORE_IMAGE_MAX_SIZE,
	.backup_flash = NULL,
	.staging_flash = &flash_external.base,
	.staging_addr = MANTICORE_STAGING_ADDR,
	.staging_size = MANTICORE_IMAGE_MAX_SIZE,
	.recovery_flash = &flash_external.base,
	.recovery_addr = MANTICORE_RECOVERY_BOOT_ADDR,
	.recovery_size = MANTICORE_IMAGE_MAX_SIZE,
	.rec_backup_flash = NULL
};

#ifdef MANTICORE_ENABLE_A0_SUPPORT
/**
 * Firmware image partitioning information for A0, since internal flash can't be used for booting.
 *
 */
static const struct firmware_flash_map flash_fw_partitions_a0 = {
	.active_flash = &flash_external.base,
	.active_addr = MANTICORE_MAIN_BOOT_ADDR,
	.active_size = MANTICORE_IMAGE_MAX_SIZE,
	.backup_flash = NULL,
	.staging_flash = &flash_external.base,
	.staging_addr = MANTICORE_STAGING_ADDR,
	.staging_size = MANTICORE_IMAGE_MAX_SIZE,
	.recovery_flash = &flash_internal.base,
	.recovery_addr = MANTICORE_RECOVERY_BOOT_ADDR,
	.recovery_size = MANTICORE_IMAGE_MAX_SIZE,
	.rec_backup_flash = NULL
};
#endif

/**
 * Data populated by ROM that can be used with local static initialization.
 */
static struct manticore_rom_shared_sram *const rom_shared_static =
	(struct manticore_rom_shared_sram*) HSP_ADDR_MAP_SHAREDRAM_ADDRESS;

/**
 * Data populated by 1SP that can be used with local static initialization.
 */
static const struct manticore_1sp_shared_data *const sp1_shared_static =
	(struct manticore_1sp_shared_data*) SP1_SHARED_ADDRESS;

/**
 * Context for the 1SP HW RoT.
 */
static struct hw_rot_hsp_rom_state rot_1sp_context;

/**
 * Interface to the HW-backed RoT state for 1SP firmware.
 *
 * TODO:  This is going to stomp over the RSVD1 cache generated by ROM.  There is nothing currently
 * implemented that uses this data, but debug unlock leverages RSVD1.  It also may not matter since
 * secure, run-time code will have direct access to the fuses, but might prefer to use the cached
 * values.  In any case, this needs to be considered and handled (or explicitly not handled) in some
 * way.
 */
static const struct hw_rot_hsp_rom_no_fuses rot_1sp =
	hw_rot_hsp_rom_no_fuses_static_init (&rot_1sp_context, &fuses.base,
	(struct Gfc_regs*) HSP_ADDR_MAP_GFC_ADDRESS, &ccs.base, NULL, 2,
	&rom_shared_static->overlap.internal.tenancy);

/**
 * HW backed RoT for the firmware key manifest.
 *
 * The root key provided to this instance won't be checked during update image verification, so the
 * fact that we are using the current boot context's key here isn't an issue.
 */
static const struct hw_rot_firmware_key_manifest rot_manifest =
	hw_rot_firmware_key_manifest_static_init (&fuses.base,
	(struct Gfc_regs*) HSP_ADDR_MAP_GFC_ADDRESS, &ccs,
	&rom_shared_static->firmware.pcr_log[1].fw_public_key.data.key, NULL);

/**
 * Variable context for the firmware key manifest ECDSA handler.
 */
static struct signature_verification_ecc_state img_keys_ecdsa_context;

/**
 * ECDSA verification for the firmware key manifest.  This actually does not get used, but needs to
 * be present for initialization checks.
 */
static const struct signature_verification_ecc img_keys_ecdsa =
	signature_verification_ecc_static_init (&img_keys_ecdsa_context, &shared_ecc.base);

/**
 * Firmware key manifest for the currently running image.
 *
 * The only argument to this that actually matters is the memory location that contains the keys.
 * Nothing else is actually going to get used since these are loaded into memory, verified, and
 * protected by 1SP.  The root key and RoT don't really need to be accurate for this data.  They do
 * need to be valid pointers to pass initialization checks, though.
 */
const struct key_manifest_hsp_firmware img_keys =
	key_manifest_hsp_firmware_static_init (&sp1_shared_static->fw_keys, &rot_manifest.base,
	&security_mgr.base.base, &img_keys_ecdsa.base,
	rom_shared_static->firmware.pcr_log[1].fw_public_key.data.key.AsBytes,
	SP_ECDSA_P384_PUBLIC_KEY_SIZE, NULL, 0);

/**
 * Variable context for the interface for handling firmware image updates.
 */
static struct firmware_image_manticore_state update_img_context;

/**
 * The interface to use when updating a firmware image.
 */
const struct firmware_image_manticore updating_img =
	firmware_image_manticore_static_init (&updating_img, &update_img_context, &shared_hash.base,
	&shared_ecc.base, &pka.base, &ccs.base, &rot_1sp.base.base, &rot_manifest.base,
	&security_mgr.base.base, &sp1_shared_static->fw_descriptor,
	&sp1_shared_static->fips_certifed_1sp);

/**
 * List of contexts that should be checked to determine if a firmware update will be impactful.
 */
static const struct impactful_check *const impactful_checks[] = {
	&updating_img.base_impactful,
#ifndef MANTICORE_RECOVERY_IMG
	&spdm_impactful.base
#endif
};

/**
 * Variable context for the impactful update handler.
 */
static struct impactful_update_state impactful_context;

/**
 * Handler for managing impactful firmware updates.
 */
static const struct impactful_update impactful = impactful_update_static_init (&impactful_context,
	impactful_checks, ARRAY_SIZE (impactful_checks));

/**
 * Authorized execution handler to allow impactful updates to be accepted by the device.
 */
const struct authorized_execution_allow_impactful allow_impactful_execution =
	authorized_execution_allow_impactful_static_init (&impactful.base,
	MANTICORE_IMPACTFUL_AUTHORIZATION_TIME);

/**
 * State management for the running image.
 */
static const struct app_context_null running_state = app_context_null_static_init;

/**
 * Variable context for the Manticore firmware updater.
 */
static struct firmware_update_state fw_updater_context;


/**
 * The module for updating Manticore firmware.
 */
SECTION (".sprtro.fw_updater")
struct firmware_update fw_updater;

/**
 * Observer for firmware updates to handle checks for impactful updates.
 */
static const struct firmware_update_observer_impactful impactful_observer =
	firmware_update_observer_impactful_static_init (&impactful.base);

/**
 * Observer for tracking firmware updates for SPRT state management across impactless updates.
 */
static const struct firmware_update_observer_sprt sprt_observer =
	firmware_update_observer_sprt_static_init (&impactful.base);

/**
 * Variable context for the Manticore firmware update handler.
 */
static struct firmware_update_handler_state fw_handler_context;

/**
 * Handler for Manticore firmware update actions.
 */
const struct firmware_update_handler_revoke_after_reset fw_handler =
	firmware_update_handler_revoke_after_reset_static_init_keep_recovery_updated (
	&fw_handler_context, &fw_updater, &manticore_update.base);

/**
 * Handler for prepare firmware update requests with authorization.
 */
const struct authorized_execution_prepare_firmware_update prepare_fw_update =
	authorized_execution_prepare_firmware_update_static_init (&fw_handler.base.base_ctrl,
	MANTICORE_PREPARE_UPDATE_WAIT_TIME);

/**
 * Handler for impactful Manticore firmware updates.
 */
const struct impactful_update_handler impactful_handler =
	impactful_update_handler_static_init (&fw_handler.base, &impactful.base);

/**
 * List of handlers for the firmware update task.
 */
static const struct event_task_handler *const fw_handlers[] = {
	&fw_handler.base.base_event, &impactful_handler.base_event
};

/**
 * Variable context for the firmware update task.
 */
static struct event_task_freertos_state manticore_update_context;

/**
 * The task for executing Manticore firmware updates.
 */
const struct event_task_freertos manticore_update =
	event_task_freertos_static_init (&manticore_update_context, &system_mgr, fw_handlers,
	ARRAY_SIZE (fw_handlers));

/**
 * Statically allocated task control block for the firmware update handler task.
 */
static StaticTask_t update_task_tcb;

/**
 * Statically allocated stack for the firmware update handler task.
 */
static StackType_t update_task_stack[FW_UPDATE_TASK_STACK_WORDS];


/**
 * Initialize access to the running firmware image information.
 *
 * @return 0 if the operation was successful or an error code.
 */
int initialize_running_image_access ()
{
	const struct key_manifest_public_key *key;
	int status;

	/* This won't fail and init doesn't actually matter, anyway. */
	signature_verification_ecc_init_state (&img_keys_ecdsa, NULL, 0);

	status = key_manifest_hsp_firmware_init_keys_from_memory (&img_keys);
	if (status != 0) {
		return status;
	}

	/* Sanity check to make sure the required keys are available from the manifest instance.  None
	 * of these should ever fail since the bootloader checks for presence of these keys before
	 * loading the image. */

	key = img_keys.base.get_manifest_key (&img_keys.base);
	if (key == NULL) {
		return INIT_MISSING_MANIFEST_ROOT_KEY;
	}

	key = key_manifest_hsp_firmware_get_public_key (&img_keys, MANTICORE_FW_KEYS_DEBUG_UNLOCK_KEY);
	if (key == NULL) {
		return INIT_MISSING_DEBUG_UNLOCK_KEY;
	}

	key = key_manifest_hsp_firmware_get_public_key (&img_keys,
		MANTICORE_FW_KEYS_CLEAR_MANIFEST_KEY);
	if (key == NULL) {
		return INIT_MISSING_CLEAR_MANIFEST_KEY;
	}

	key = key_manifest_hsp_firmware_get_public_key (&img_keys,
		MANTICORE_FW_KEYS_INTRUSION_RESET_KEY);
	if (key == NULL) {
		return INIT_MISSING_INTRUSION_RESET_KEY;
	}

	key = key_manifest_hsp_firmware_get_public_key (&img_keys, MANTICORE_FW_KEYS_ID_RENEWAL_KEY);
	if (key == NULL) {
		return INIT_MISSING_IDENTITY_RENEWAL_KEY;
	}

	key = key_manifest_hsp_firmware_get_public_key (&img_keys,
		MANTICORE_FW_KEYS_FIRMWARE_UPDATE_KEY);
	if (key == NULL) {
		return INIT_MISSING_FIRMWARE_UPDATE_KEY;
	}

	key = key_manifest_hsp_firmware_get_public_key (&img_keys, MANTICORE_FW_KEYS_RMA_KEY);
	if (key == NULL) {
		return INIT_MISSING_RMA_KEY;
	}

	return 0;
}

/**
 * Initialize the Manticore firmware updater.
 *
 * @param impactful_check Enable the check for impactful updates during firmware update flows.
 *
 * @return 0 if the firmware updater was successfully initialized or an error code.
 */
int initialize_firmware_updater (bool impactful_check)
{
	int img_version;
	bool update_no_auth;
	int status;

	status = hw_rot_hsp_rom_no_fuses_init_state (&rot_1sp,
		&rom_shared->firmware.pcr_log[1].owner_public_key.data.key, &shared_hash.base,
		(union hw_rot_hsp_rom_tenancy_counter*)
		rom_shared->firmware.pcr_log[1].tenancy_counter.data.counter);
	if (status != 0) {
		return status;
	}

	status = firmware_image_manticore_init_state (&updating_img);
	if (status != 0) {
		return status;
	}

	status = impactful_update_init_state (&impactful);
	if (status != 0) {
		return status;
	}

	img_version =
		manticore_firmware_descriptor_get_earliest_allowed_revision (&sp1_shared->fw_descriptor);

	update_no_auth = security_policy_hsp_manticore_allow_no_auth_firmware_update (&sec_policy);

#ifdef MANTICORE_ENABLE_A0_SUPPORT
	if (MANTICORE_IS_A0 (soc_revision)) {
		if (update_no_auth) {
			status = firmware_update_init (&fw_updater, &fw_updater_context,
				&flash_fw_partitions_a0, &running_state.base, &updating_img.base,
				&security_mgr.base.base, &shared_hash.base, img_version);
		}
		else {
			status = firmware_update_init_authorized (&fw_updater, &fw_updater_context,
				&flash_fw_partitions_a0, &running_state.base, &updating_img.base,
				&security_mgr.base.base, &shared_hash.base, img_version);
		}
	}
	else
#endif
	{
		if (update_no_auth) {
			status = firmware_update_init (&fw_updater, &fw_updater_context, &flash_fw_partitions,
				&running_state.base, &updating_img.base, &security_mgr.base.base, &shared_hash.base,
				img_version);
		}
		else {
			status = firmware_update_init_authorized (&fw_updater, &fw_updater_context,
				&flash_fw_partitions, &running_state.base, &updating_img.base,
				&security_mgr.base.base, &shared_hash.base, img_version);
		}
	}
	if (status != 0) {
		return status;
	}

	if (recovery_boot) {
		/* Since we are running the recovery image, we know the recovery revision for that image.
		 * Set it directly rather than reading flash again to detect this information. */
		img_version =
			manticore_firmware_descriptor_get_recovery_revision (&sp1_shared->fw_descriptor);
		firmware_update_set_recovery_revision (&fw_updater, img_version);
	}

	if (impactful_check) {
		status = firmware_update_add_observer (&fw_updater, &impactful_observer.base);
		if (status != 0) {
			return status;
		}

		status = firmware_update_add_observer (&fw_updater, &sprt_observer.base);
		if (status != 0) {
			return status;
		}
	}

	/* Skip the active image restore if there is an impactful update in the main flash partition. */
	status = firmware_update_handler_init_state_control_preparation (&fw_handler.base,
		recovery_boot, (!impactful_check || has_updated_impactful_firmware ()));
	if (status != 0) {
		return status;
	}

	status = event_task_freertos_init_state (&manticore_update);
	if (status != 0) {
		return status;
	}

	/* If this is an impactless update, change the firmware update status to reflect this.  If the
	 * device has booted from recovery, then this is a rollback condition. */
	if (is_impactless_update ()) {
		if (recovery_boot) {
			fw_handler.base.base_notify.status_change (&fw_handler.base.base_notify,
				UPDATE_STATUS_ROLLBACK);
		}
		else {
			fw_handler.base.base_notify.status_change (&fw_handler.base.base_notify,
				UPDATE_STATUS_BOOT_UPDATED_IMAGE);
		}
	}

	return 0;
}

/**
 * Allocate the task for handling firmware update commands.  The task will not be started.
 *
 * @return 0 if the task was allocated successfully or an error code.
 */
int allocate_firmware_update_task ()
{
	return event_task_freertos_allocate_static (&manticore_update, &update_task_tcb,
		update_task_stack, FW_UPDATE_TASK_STACK_WORDS, "FW Update", CERBERUS_PRIORITY_NORMAL);
}
