// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef INIT_ERROR_H_
#define INIT_ERROR_H_

#include "status/rot_status.h"


// *INDENT-OFF*
#define	INIT_ERROR(code)							ROT_ERROR (ROT_MODULE_INIT, code)

/**
 * Error codes that can be generated by the initialization task.
 */
enum {
	INIT_INVALID_ARGUMENT = INIT_ERROR (0x00),				/**< Input parameter is null or not valid. */
	INIT_NO_MEMORY = INIT_ERROR (0x01),						/**< Memory allocation failed. */
	// INIT_WINBOND_FAILED = INIT_ERROR (0x02),				/**< Failed to initialize Winbond flash. */
	// INIT_CPLD_FAILED = INIT_ERROR (0x03),				/**< Failed to program CPLD. */
	// INIT_CPLD_NO_IMAGE = INIT_ERROR (0x04),				/**< No image currently running in the CPLD. */
	INIT_PCR_VERIFICATION_FAILED = INIT_ERROR (0x05),		/**< Failed to verify integrity of shared PCR values */
	// INIT_NO_FIRMWARE_HEADER = INIT_ERROR (0x06),			/**< No firmware image found on the running image. */
	// INIT_INITIAL_SECURITY_CFG = INIT_ERROR (0x07),		/**< Initial configuration of chip security. */
	INIT_MISSING_MANIFEST_ROOT_KEY = INIT_ERROR (0x08),		/**< FW key manifest is missing the manifest root key. */
	INIT_MISSING_DEBUG_UNLOCK_KEY = INIT_ERROR (0x09),		/**< FW key manifest is missing the debug unlock key. */
	INIT_MISSING_CLEAR_MANIFEST_KEY = INIT_ERROR (0x0a),	/**< FW key manifest is missing the clear manifest key. */
	INIT_MISSING_INTRUSION_RESET_KEY = INIT_ERROR (0x0b),	/**< FW key manifest is missing the intrusion reset key. */
	INIT_MISSING_IDENTITY_RENEWAL_KEY = INIT_ERROR (0x0c),	/**< FW key manifest is missing the identity renewal key. */
	INIT_DIFFERENT_PHY_MEASUREMENT = INIT_ERROR (0x0d),		/**< A different PHY firmware was loaded than what was measured. */
	INIT_INVALID_MAIN_PHY_IMAGE = INIT_ERROR (0x0e),		/**< The staged Main PHY firmware image is malformed. */
	INIT_INVALID_COMMON_PHY_IMAGE = INIT_ERROR (0x0f),		/**< The staged Common PHY firmware image is malformed. */
	INIT_INVALID_LANE_PHY_IMAGE = INIT_ERROR (0x10),		/**< The staged Lane PHY firmware image is malformed. */
	INIT_PHY_INIT_FAILED = INIT_ERROR (0x11),				/**< Failed to initialize the PCIe PHY. */
	// INIT_PHY_SMALL_BUFFER = INIT_ERROR (0x12),			/**< Memory buffer is too small for the PHY image. */
	INIT_PHY0_BAD_IMAGE = INIT_ERROR (0x13),				/**< PHY0 contains an invalid firmware image. */
	INIT_PHY1_BAD_IMAGE = INIT_ERROR (0x14),				/**< PHY1 contains an invalid firmware image. */
	INIT_MISSING_FIRMWARE_UPDATE_KEY = INIT_ERROR (0x15),	/**< FW key manifest is missing the firmware update key. */
	INIT_MISSING_RMA_KEY = INIT_ERROR (0x16),				/**< FW key manifest is missing the RMA key. */
	INIT_GSRAM_ECC_ERROR = INIT_ERROR (0x17),				/**< GSRAM ECC error occurred. */
	INIT_ITCM_ECC_ERROR = INIT_ERROR (0x18),				/**< ITCM ECC error occurred. */
};
// *INDENT-ON*


#endif	/* INIT_ERROR_H_ */
