/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    rom_chkpt_unsecure.c

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#include "precomp.h"
#include "rom_chkpt_unsecure.h"

// clang-format off

SECTION (".romsecrets.ROM_CHECKPOINT_UNSECURE_INIT")
const HSP_CHKPT_CONFIG ROM_CHECKPOINT_UNSECURE_INIT = {
	.Digest0 = 0xB07F96AD,
	.Digest1 = 0x5916C2E1,
	.Digest2 = 0x74E62860,
	.Digest3 = 0x4DDF4AE1,
	.Timer0 = 0x00000000,
	.Timer1 = 0x00000001,
	.Fence = {
		.NoExpiration = 1,
		.PrivStopAllowed = 1,
		.UserStopAllowed = 1,
	},
	.Ctrl = 0x00000000
};


SECTION (".romsecrets.ROM_CHECKPOINT_UNSECURE_FINISH")
const HSP_CHKPT_CONFIG ROM_CHECKPOINT_UNSECURE_FINISH = {
	.Digest0 = 0x00000000,
	.Digest1 = 0x00000000,
	.Digest2 = 0x00000000,
	.Digest3 = 0x00000000,
	.Timer0 = 0x00000000,
	.Timer1 = 0x00000001,
	.Fence = {
		.NoExpiration = 1,
		.PrivStopAllowed = 1,
		.UserStopAllowed = 1,
	},
	.Ctrl = 0x00000000
};

// clang-format on
