/*++

    Copyright (C) Microsoft Corporation. All rights reserved.

Module Name:

    rom_chkpt_unsecure.h

Abstract:

    * * * Autogenerated using chkptgen * * *
    * * *    do not modify manually    * * *

Author:

    chkptgen.exe

--*/

#pragma once

// clang-format off

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_UNSECURE_INIT;

extern const HSP_CHKPT_CONFIG ROM_CHECKPOINT_UNSECURE_FINISH;

// clang-format on
