// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef MEMORY_PROTECTION_H_
#define MEMORY_PROTECTION_H_

#include "status/msft_module_id.h"


/**
 * Handler for configuring memory protection mechanisms within the device.  These include hardware
 * isolation for SoC cores, MPU configuration, RISC-V PMP, or any other applicable method of memory
 * protection.
 */
struct memory_protection {
	/**
	 * Apply an appropriate configuration to the HSP Memory Protection Unit (MPU) for the current
	 * execution context.  Any static configuration for RISC-V Physical Memory Protection (PMP) will
	 * also be applied.
	 *
	 * @param mem_protect The memory protection configuration to apply.
	 *
	 * @return 0 if the MPU was configured successfully or an error code.
	 */
	int (*configure_hsp_mpu) (const struct memory_protection *mem_protect);

	/**
	 * Apply the necessary configuration to hardware isolation features of the SoC.
	 *
	 * @param mem_protect The memory protection configuration to apply.
	 *
	 * @return 0 if the SoC fences were configured successfully or an error code.
	 */
	int (*configure_soc_fences) (const struct memory_protection *mem_protect);
};


#define	MEMORY_PROTECTION_ERROR(code)		ROT_ERROR (MSFT_MODULE_MEMORY_PROTECTION, code)

/**
 * Error codes that can be generated by device memory protection.
 */
enum {
	MEMORY_PROTECTION_INVALID_ARGUMENT = MEMORY_PROTECTION_ERROR (0x00),		/**< Input parameter is null or not valid. */
	MEMORY_PROTECTION_NO_MEMORY = MEMORY_PROTECTION_ERROR (0x01),				/**< Memory allocation failed. */
	MEMORY_PROTECTION_CONFIG_MPU_FAILED = MEMORY_PROTECTION_ERROR (0x02),		/**< Failed to configure HSP MPU. */
	MEMORY_PROTECTION_CONFIG_FENCES_FAILED = MEMORY_PROTECTION_ERROR (0x03),	/**< Failed to configure SoC hardware fences. */
};


#endif	/* MEMORY_PROTECTION_H_ */
