// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from mcr-cp-reg.xml

#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
#[derive(Clone, Copy)]
pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio> = ureg::RealMmio> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl RegisterBlock<ureg::RealMmio> {
    pub fn block() -> Self {
        unsafe { Self::new(0xb000c000 as *mut u32) }
    }
}
impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new(ptr: *mut u32) -> Self {
        Self {
            ptr,
            mmio: core::default::Default::default(),
        }
    }
}
impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
        Self { ptr, mmio }
    }
    /// Block memory ECC enable register
    ///
    /// Read value: [`gsram::regs::MemeccenbReadVal`]; Write value: [`gsram::regs::MemeccenbWriteVal`]
    #[inline(always)]
    pub fn memeccenb(&self) -> ureg::RegRef<crate::gsram::meta::Memeccenb, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x40 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory ECC enable set register
    ///
    /// Read value: [`gsram::regs::MemeccsetReadVal`]; Write value: [`gsram::regs::MemeccsetWriteVal`]
    #[inline(always)]
    pub fn memeccset(&self) -> ureg::RegRef<crate::gsram::meta::Memeccset, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x44 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory ECC enable clear register
    ///
    /// Read value: [`gsram::regs::MemeccclrReadVal`]; Write value: [`gsram::regs::MemeccclrWriteVal`]
    #[inline(always)]
    pub fn memeccclr(&self) -> ureg::RegRef<crate::gsram::meta::Memeccclr, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x48 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory initialization register
    ///
    /// Read value: [`gsram::regs::MeminitReadVal`]; Write value: [`gsram::regs::MeminitWriteVal`]
    #[inline(always)]
    pub fn meminit(&self) -> ureg::RegRef<crate::gsram::meta::Meminit, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x4c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Memory unit interrupt cause register
    ///
    /// Read value: [`gsram::regs::MemintsttReadVal`]; Write value: [`gsram::regs::MemintsttWriteVal`]
    #[inline(always)]
    pub fn memintstt(&self) -> ureg::RegRef<crate::gsram::meta::Memintstt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x50 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Memory unit interrupt enable register
    ///
    /// Read value: [`gsram::regs::MemintenbReadVal`]; Write value: [`gsram::regs::MemintenbWriteVal`]
    #[inline(always)]
    pub fn memintenb(&self) -> ureg::RegRef<crate::gsram::meta::Memintenb, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x54 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Memory unit interrupt enable set register
    ///
    /// Read value: [`gsram::regs::MemintsetReadVal`]; Write value: [`gsram::regs::MemintsetWriteVal`]
    #[inline(always)]
    pub fn memintset(&self) -> ureg::RegRef<crate::gsram::meta::Memintset, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x58 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Memory unit interrupt enable clear register
    ///
    /// Read value: [`gsram::regs::MemintclrReadVal`]; Write value: [`gsram::regs::MemintclrWriteVal`]
    #[inline(always)]
    pub fn memintclr(&self) -> ureg::RegRef<crate::gsram::meta::Memintclr, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x5c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Error injection bit low register
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn errinjblo(&self) -> ureg::RegRef<crate::gsram::meta::Errinjblo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x60 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Error injection bit high register
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn errinjbhi(&self) -> ureg::RegRef<crate::gsram::meta::Errinjbhi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x64 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Error injection address register
    ///
    /// Read value: [`gsram::regs::ErrinjadrReadVal`]; Write value: [`gsram::regs::ErrinjadrWriteVal`]
    #[inline(always)]
    pub fn errinjadr(&self) -> ureg::RegRef<crate::gsram::meta::Errinjadr, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x70 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Error injection control and status register
    ///
    /// Read value: [`gsram::regs::ErrinjctsReadVal`]; Write value: [`gsram::regs::ErrinjctsWriteVal`]
    #[inline(always)]
    pub fn errinjcts(&self) -> ureg::RegRef<crate::gsram::meta::Errinjcts, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x74 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory single bit error log register 0
    ///
    /// Read value: [`gsram::regs::Errslog0ReadVal`]; Write value: [`gsram::regs::Errslog0WriteVal`]
    #[inline(always)]
    pub fn errslog0(&self) -> ureg::RegRef<crate::gsram::meta::Errslog0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x80 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory single bit error log register 1
    ///
    /// Read value: [`gsram::regs::Errslog1ReadVal`]; Write value: [`gsram::regs::Errslog1WriteVal`]
    #[inline(always)]
    pub fn errslog1(&self) -> ureg::RegRef<crate::gsram::meta::Errslog1, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x84 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory single bit error status register
    ///
    /// Read value: [`gsram::regs::ErrsstsReadVal`]; Write value: [`gsram::regs::ErrsstsWriteVal`]
    #[inline(always)]
    pub fn errssts(&self) -> ureg::RegRef<crate::gsram::meta::Errssts, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x90 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory single bit error threshold register
    ///
    /// Read value: [`gsram::regs::ErrsthrReadVal`]; Write value: [`gsram::regs::ErrsthrWriteVal`]
    #[inline(always)]
    pub fn errsthr(&self) -> ureg::RegRef<crate::gsram::meta::Errsthr, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x94 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory double bit error log register 0
    ///
    /// Read value: [`gsram::regs::Errdlog0ReadVal`]; Write value: [`gsram::regs::Errdlog0WriteVal`]
    #[inline(always)]
    pub fn errdlog0(&self) -> ureg::RegRef<crate::gsram::meta::Errdlog0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xa0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory double bit error status register
    ///
    /// Read value: [`gsram::regs::ErrdstsReadVal`]; Write value: [`gsram::regs::ErrdstsWriteVal`]
    #[inline(always)]
    pub fn errdsts(&self) -> ureg::RegRef<crate::gsram::meta::Errdsts, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xb0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory double bit error threshold register
    ///
    /// Read value: [`gsram::regs::ErrdthrReadVal`]; Write value: [`gsram::regs::ErrdthrWriteVal`]
    #[inline(always)]
    pub fn errdthr(&self) -> ureg::RegRef<crate::gsram::meta::Errdthr, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xb4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory arbitration control register 0
    ///
    /// Read value: [`gsram::regs::Memarbctl0ReadVal`]; Write value: [`gsram::regs::Memarbctl0WriteVal`]
    #[inline(always)]
    pub fn memarbctl0(&self) -> ureg::RegRef<crate::gsram::meta::Memarbctl0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xc0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Parity_Error_Control
    ///
    /// Read value: [`gsram::regs::ParctrlReadVal`]; Write value: [`gsram::regs::ParctrlWriteVal`]
    #[inline(always)]
    pub fn parctrl(&self) -> ureg::RegRef<crate::gsram::meta::Parctrl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xd0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Parity_Error_Log
    ///
    /// Read value: [`gsram::regs::Parerr0ReadVal`]; Write value: [`gsram::regs::Parerr0WriteVal`]
    #[inline(always)]
    pub fn parerr0(&self) -> ureg::RegRef<crate::gsram::meta::Parerr0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xd4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Block memory access control register
    ///
    /// Read value: [`gsram::regs::Memmap0ReadVal`]; Write value: [`gsram::regs::Memmap0WriteVal`]
    #[inline(always)]
    pub fn memmap0(&self) -> ureg::RegRef<crate::gsram::meta::Memmap0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x100 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Master 0 WRR arbitration weight register
    ///
    /// Read value: [`gsram::regs::Mst0weiReadVal`]; Write value: [`gsram::regs::Mst0weiWriteVal`]
    #[inline(always)]
    pub fn mst0_wei(&self) -> ureg::RegRef<crate::gsram::meta::Mst0wei, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x200 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
}
pub mod regs {
    //! Types that represent the values held by registers.
    #[derive(Clone, Copy)]
    pub struct Errdlog0ReadVal(u32);
    impl Errdlog0ReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 28) & 0xf
        }
        /// Double_Bit_Error_Segment
        ///
        /// These error-log registers are used to save the first-ECC-double-bit failed information.
        /// This field indicate which segment (8Bytes) have ECC double bit failed
        #[inline(always)]
        pub fn double_bit_error_segment(&self) -> u32 {
            (self.0 >> 24) & 0xf
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_1(&self) -> u32 {
            (self.0 >> 21) & 7
        }
        /// Double_Bit_Error_Address
        ///
        /// Indicate bit [21:5] of the first failed address
        #[inline(always)]
        pub fn double_bit_error_address(&self) -> u32 {
            (self.0 >> 5) & 0xffff
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_2(&self) -> u32 {
            (self.0 >> 1) & 0xf
        }
        /// Double_Bit_Error_Channel
        ///
        /// Indicate which channel cause this ECC-failed:
        /// + 0x0 : Master 0 Read channel
        /// + 0x1 : Master 0 Write channel
        #[inline(always)]
        pub fn double_bit_error_channel(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
    }
    impl From<u32> for Errdlog0ReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Errdlog0ReadVal> for u32 {
        fn from(val: Errdlog0ReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrdstsReadVal(u32);
    impl ErrdstsReadVal {
        /// Double_Bit_Error_Log_Valid
        ///
        /// This bit indicates the validity of log information specified in Block memory double-bit error log 0. This bit is set automatically by hardware upon detecting the Double_Bit_Error_Counter is changed from 0 to 1 and the log information is updated to error log registers. SW clears the bit by writing 1'b1. Only after the bit is clear, HW is allowed to update log registers for next error.
        #[inline(always)]
        pub fn double_bit_error_log_valid(&self) -> bool {
            ((self.0 >> 31) & 1) != 0
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 22) & 0x1ff
        }
        /// Double_Bit_Error_HWID
        ///
        /// This field specifies indicates the HWID number of master which issued the transaction.
        #[inline(always)]
        pub fn double_bit_error_hwid(&self) -> u32 {
            (self.0 >> 16) & 0x3f
        }
        /// Double_Bit_Error_Counter
        ///
        /// This field specifies indicates the number of double bit error detected. The counter is increased by 1 unit for every error detected till read or when the counter reaches 0xFFFF value.
        /// If any 2-bit error orcur in between reading this register (clear counter to 0) and write 1 to Double_Bit_Error_Log_Valid (enable logging again), the error information still be logged correctly
        #[inline(always)]
        pub fn double_bit_error_counter(&self) -> u32 {
            (self.0 >> 0) & 0xffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ErrdstsWriteVal {
            ErrdstsWriteVal(self.0)
        }
    }
    impl From<u32> for ErrdstsReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrdstsReadVal> for u32 {
        fn from(val: ErrdstsReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrdstsWriteVal(u32);
    impl ErrdstsWriteVal {
        /// Double_Bit_Error_Log_Valid
        ///
        /// This bit indicates the validity of log information specified in Block memory double-bit error log 0. This bit is set automatically by hardware upon detecting the Double_Bit_Error_Counter is changed from 0 to 1 and the log information is updated to error log registers. SW clears the bit by writing 1'b1. Only after the bit is clear, HW is allowed to update log registers for next error.
        #[inline(always)]
        pub fn double_bit_error_log_valid(self, val: bool) -> Self {
            Self((self.0 & !(1 << 31)) | (u32::from(val) << 31))
        }
    }
    impl From<u32> for ErrdstsWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrdstsWriteVal> for u32 {
        fn from(val: ErrdstsWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrdthrReadVal(u32);
    impl ErrdthrReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 16) & 0xffff
        }
        /// Double_Bit_Error_Threshold
        ///
        /// This field specifies the threshold to trigger interrupt. When number of double bit errors detected by hardware exceeds the value specified in this counter the Block_Mem_Double_Bit_Error bit of Memory unit interrupt cause register is set to 1b.
        #[inline(always)]
        pub fn double_bit_error_threshold(&self) -> u32 {
            (self.0 >> 0) & 0xffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ErrdthrWriteVal {
            ErrdthrWriteVal(self.0)
        }
    }
    impl From<u32> for ErrdthrReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrdthrReadVal> for u32 {
        fn from(val: ErrdthrReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrdthrWriteVal(u32);
    impl ErrdthrWriteVal {
        /// Double_Bit_Error_Threshold
        ///
        /// This field specifies the threshold to trigger interrupt. When number of double bit errors detected by hardware exceeds the value specified in this counter the Block_Mem_Double_Bit_Error bit of Memory unit interrupt cause register is set to 1b.
        #[inline(always)]
        pub fn double_bit_error_threshold(self, val: u32) -> Self {
            Self((self.0 & !(0xffff << 0)) | ((val & 0xffff) << 0))
        }
    }
    impl From<u32> for ErrdthrWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrdthrWriteVal> for u32 {
        fn from(val: ErrdthrWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrinjadrReadVal(u32);
    impl ErrinjadrReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 21) & 0x7ff
        }
        /// Err_Addr
        ///
        /// Specify 8-byte aligned address where the error is injected. The address is logical (or AXI) address.
        #[inline(always)]
        pub fn err_addr(&self) -> u32 {
            (self.0 >> 3) & 0x3ffff
        }
        /// Reserved
        #[inline(always)]
        pub fn rsvd_1(&self) -> u32 {
            (self.0 >> 0) & 7
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ErrinjadrWriteVal {
            ErrinjadrWriteVal(self.0)
        }
    }
    impl From<u32> for ErrinjadrReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrinjadrReadVal> for u32 {
        fn from(val: ErrinjadrReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrinjadrWriteVal(u32);
    impl ErrinjadrWriteVal {
        /// Err_Addr
        ///
        /// Specify 8-byte aligned address where the error is injected. The address is logical (or AXI) address.
        #[inline(always)]
        pub fn err_addr(self, val: u32) -> Self {
            Self((self.0 & !(0x3ffff << 3)) | ((val & 0x3ffff) << 3))
        }
    }
    impl From<u32> for ErrinjadrWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrinjadrWriteVal> for u32 {
        fn from(val: ErrinjadrWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrinjctsReadVal(u32);
    impl ErrinjctsReadVal {
        /// Inj_Done
        ///
        /// When 1'b1 is written to Inj_Trig bit, this bit is cleared to 1'b0 by hardware, and will be set to 1'b1 after the error injection process is done.
        /// 0: Error injection process has NOT been done
        /// 1: Error injection process has been done
        /// Note: if the set and clear condition happen at the same time, the clear condition is given priority.
        #[inline(always)]
        pub fn inj_done(&self) -> bool {
            ((self.0 >> 31) & 1) != 0
        }
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 1) & 0x3fffffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ErrinjctsWriteVal {
            ErrinjctsWriteVal(self.0)
        }
    }
    impl From<u32> for ErrinjctsReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrinjctsReadVal> for u32 {
        fn from(val: ErrinjctsReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrinjctsWriteVal(u32);
    impl ErrinjctsWriteVal {
        /// Inj_Trig
        ///
        /// Write 1'b1 to this bit to start the error injection process. Write 1'b0 has no effect.
        #[inline(always)]
        pub fn inj_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for ErrinjctsWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrinjctsWriteVal> for u32 {
        fn from(val: ErrinjctsWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Errslog0ReadVal(u32);
    impl Errslog0ReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 28) & 0xf
        }
        /// Single_Bit_Error_Segment
        ///
        /// These error-log registers are used to save the first-ECC-single-bit failed information. This field indicate which segment (8Bytes) have ECC single bit failed
        #[inline(always)]
        pub fn single_bit_error_segment(&self) -> u32 {
            (self.0 >> 24) & 0xf
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_1(&self) -> u32 {
            (self.0 >> 21) & 7
        }
        /// Single_Bit_Error_Address
        ///
        /// Indicate bit [20:5] of the first failed address
        #[inline(always)]
        pub fn single_bit_error_address(&self) -> u32 {
            (self.0 >> 5) & 0xffff
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_2(&self) -> u32 {
            (self.0 >> 1) & 0xf
        }
        /// Single_Bit_Error_Channel
        ///
        /// Indicate which channel cause this ECC-failed:
        /// + 0x0 : Master 0 Read channel
        /// + 0x1 : Master 0 Write channel
        #[inline(always)]
        pub fn single_bit_error_channel(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
    }
    impl From<u32> for Errslog0ReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Errslog0ReadVal> for u32 {
        fn from(val: Errslog0ReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Errslog1ReadVal(u32);
    impl Errslog1ReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> bool {
            ((self.0 >> 31) & 1) != 0
        }
        /// Single_Bit_Error_Syndrome_3
        ///
        /// Indicate Syndrome of Segment 3 (Byte 24 -> 32). Only valid if Single_Bit_Error_segment[3] is 1'b1
        #[inline(always)]
        pub fn single_bit_error_syndrome_3(&self) -> u32 {
            (self.0 >> 24) & 0x7f
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_1(&self) -> bool {
            ((self.0 >> 23) & 1) != 0
        }
        /// Single_Bit_Error_Syndrome_2
        ///
        /// Indicate Syndrome of Segment 2 (Byte 16 -> 23). Only valid if Single_Bit_Error_segment[2] is 1'b1
        #[inline(always)]
        pub fn single_bit_error_syndrome_2(&self) -> u32 {
            (self.0 >> 16) & 0x7f
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_2(&self) -> bool {
            ((self.0 >> 15) & 1) != 0
        }
        /// Single_Bit_Error_Syndrome_1
        ///
        /// Indicate Syndrome of Segment 1 (Byte 8 -> 15). Only valid if Single_Bit_Error_segment[1] is 1'b1
        #[inline(always)]
        pub fn single_bit_error_syndrome_1(&self) -> u32 {
            (self.0 >> 8) & 0x7f
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_3(&self) -> bool {
            ((self.0 >> 7) & 1) != 0
        }
        /// Single_Bit_Error_Syndrome_0
        ///
        /// Indicate Syndrome of Segment 0 (Byte 0 -> 7). Only valid if Single_Bit_Error_segment[0] is 1'b1
        #[inline(always)]
        pub fn single_bit_error_syndrome_0(&self) -> u32 {
            (self.0 >> 0) & 0x7f
        }
    }
    impl From<u32> for Errslog1ReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Errslog1ReadVal> for u32 {
        fn from(val: Errslog1ReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrsstsReadVal(u32);
    impl ErrsstsReadVal {
        /// Single_Bit_Error_Log_Valid
        ///
        /// This bit indicates the validity of log information specified in Block memory single-bit error log 0/1/2. This bit is set automatically by hardware upon detecting the Single_Bit_Error_Counter is changed from 0 to 1 and the log information is updated to error log registers. SW clears the bit by writing 1'b1. Only after the bit is clear, HW is allowed to update log registers for next error.
        #[inline(always)]
        pub fn single_bit_error_log_valid(&self) -> bool {
            ((self.0 >> 31) & 1) != 0
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 22) & 0x1ff
        }
        /// Single_Bit_Error_HWID
        ///
        /// This field specifies indicates the HWID number of master which issued the transaction.
        #[inline(always)]
        pub fn single_bit_error_hwid(&self) -> u32 {
            (self.0 >> 16) & 0x3f
        }
        /// Single_Bit_Error_Counter
        ///
        /// This field specifies indicates the number of single bit error detected. The counter is increased by 1 unit for every error detected till read or when the counter reaches 0xFFFF value.
        /// If any 1-bit error orcur in between reading this register (clear counter to 0) and write 1 to Single_Bit_Error_Log_Valid (enable logging again), the error information still be logged correctly
        #[inline(always)]
        pub fn single_bit_error_counter(&self) -> u32 {
            (self.0 >> 0) & 0xffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ErrsstsWriteVal {
            ErrsstsWriteVal(self.0)
        }
    }
    impl From<u32> for ErrsstsReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrsstsReadVal> for u32 {
        fn from(val: ErrsstsReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrsstsWriteVal(u32);
    impl ErrsstsWriteVal {
        /// Single_Bit_Error_Log_Valid
        ///
        /// This bit indicates the validity of log information specified in Block memory single-bit error log 0/1/2. This bit is set automatically by hardware upon detecting the Single_Bit_Error_Counter is changed from 0 to 1 and the log information is updated to error log registers. SW clears the bit by writing 1'b1. Only after the bit is clear, HW is allowed to update log registers for next error.
        #[inline(always)]
        pub fn single_bit_error_log_valid(self, val: bool) -> Self {
            Self((self.0 & !(1 << 31)) | (u32::from(val) << 31))
        }
    }
    impl From<u32> for ErrsstsWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrsstsWriteVal> for u32 {
        fn from(val: ErrsstsWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrsthrReadVal(u32);
    impl ErrsthrReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 16) & 0xffff
        }
        /// Single_Bit_Error_Threshold
        ///
        /// This field specifies the threshold to trigger interrupt. When number of single bit errors detected and corrected by hardware exceeds the value specified in this counter the Block_Mem_Single_Bit_Error bit of Memory unit interrupt cause register is set to 1b.
        #[inline(always)]
        pub fn single_bit_error_threshold(&self) -> u32 {
            (self.0 >> 0) & 0xffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ErrsthrWriteVal {
            ErrsthrWriteVal(self.0)
        }
    }
    impl From<u32> for ErrsthrReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrsthrReadVal> for u32 {
        fn from(val: ErrsthrReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrsthrWriteVal(u32);
    impl ErrsthrWriteVal {
        /// Single_Bit_Error_Threshold
        ///
        /// This field specifies the threshold to trigger interrupt. When number of single bit errors detected and corrected by hardware exceeds the value specified in this counter the Block_Mem_Single_Bit_Error bit of Memory unit interrupt cause register is set to 1b.
        #[inline(always)]
        pub fn single_bit_error_threshold(self, val: u32) -> Self {
            Self((self.0 & !(0xffff << 0)) | ((val & 0xffff) << 0))
        }
    }
    impl From<u32> for ErrsthrWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrsthrWriteVal> for u32 {
        fn from(val: ErrsthrWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Memarbctl0ReadVal(u32);
    impl Memarbctl0ReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 4) & 0xfffffff
        }
        /// Block_Memory_Arb_Mode
        ///
        /// This field speifies the arbitration mode
        /// - Bit 3 specifies whether the arbitration is done in cell basic or AXI packet basic
        /// 0: Cell-base (default)
        /// 1: Packet-base. This is only supported if Block_Memory_Mapping_Mode is NOT 3'b000 nor 3'b001
        /// - Bit 2 is a reserved bit, always read as 0
        /// - Bit [1:0] specify the arbitration algorithm
        /// 00: Fixed arbitration (AXI-Read 0 > AXI-Read 1 > … > AXI-Read 3> AXI-Write 0 > AXI-Write 1 > … > AXI-Write 3). Note if fixed arbitration is selected, always packet-base is considered.
        /// 01: Round-robin arbitration
        /// 10, 11: Weighted round-robin arbitration (default)
        #[inline(always)]
        pub fn block_memory_arb_mode(&self) -> u32 {
            (self.0 >> 0) & 0xf
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> Memarbctl0WriteVal {
            Memarbctl0WriteVal(self.0)
        }
    }
    impl From<u32> for Memarbctl0ReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Memarbctl0ReadVal> for u32 {
        fn from(val: Memarbctl0ReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Memarbctl0WriteVal(u32);
    impl Memarbctl0WriteVal {
        /// Block_Memory_Arb_Mode
        ///
        /// This field speifies the arbitration mode
        /// - Bit 3 specifies whether the arbitration is done in cell basic or AXI packet basic
        /// 0: Cell-base (default)
        /// 1: Packet-base. This is only supported if Block_Memory_Mapping_Mode is NOT 3'b000 nor 3'b001
        /// - Bit 2 is a reserved bit, always read as 0
        /// - Bit [1:0] specify the arbitration algorithm
        /// 00: Fixed arbitration (AXI-Read 0 > AXI-Read 1 > … > AXI-Read 3> AXI-Write 0 > AXI-Write 1 > … > AXI-Write 3). Note if fixed arbitration is selected, always packet-base is considered.
        /// 01: Round-robin arbitration
        /// 10, 11: Weighted round-robin arbitration (default)
        #[inline(always)]
        pub fn block_memory_arb_mode(self, val: u32) -> Self {
            Self((self.0 & !(0xf << 0)) | ((val & 0xf) << 0))
        }
    }
    impl From<u32> for Memarbctl0WriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Memarbctl0WriteVal> for u32 {
        fn from(val: Memarbctl0WriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemeccclrReadVal(u32);
    impl MemeccclrReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 8) & 0xffffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> MemeccclrWriteVal {
            MemeccclrWriteVal(self.0)
        }
    }
    impl From<u32> for MemeccclrReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemeccclrReadVal> for u32 {
        fn from(val: MemeccclrReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemeccclrWriteVal(u32);
    impl MemeccclrWriteVal {
        /// Block_Memory_ECC_Enb_Clr
        ///
        /// Writing 1b is to clear the corresonding bit in Block_Memory_ECC_Enb field of Block Memory ECC enable register to 0b , writing 0b has no effect
        #[inline(always)]
        pub fn block_memory_ecc_enb_clr(self, val: u32) -> Self {
            Self((self.0 & !(0xff << 0)) | ((val & 0xff) << 0))
        }
    }
    impl From<u32> for MemeccclrWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemeccclrWriteVal> for u32 {
        fn from(val: MemeccclrWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemeccenbReadVal(u32);
    impl MemeccenbReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 8) & 0xffffff
        }
        /// Block_Mem_ECC_Enb
        ///
        /// This field is to enable or disable ECC for block memory.
        /// Bit[0] is for block memory of which is index is 0, bit[1] for block memory of which index is 1, etc..
        /// 0: ECC for the block memory is disabled (default)
        /// 1: ECC for the block memory is enabled
        /// The value in this register is set/clear using Block Memory ECC enable set/clear register. The register itself is read only.
        #[inline(always)]
        pub fn block_mem_ecc_enb(&self) -> u32 {
            (self.0 >> 0) & 0xff
        }
    }
    impl From<u32> for MemeccenbReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemeccenbReadVal> for u32 {
        fn from(val: MemeccenbReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemeccsetReadVal(u32);
    impl MemeccsetReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 8) & 0xffffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> MemeccsetWriteVal {
            MemeccsetWriteVal(self.0)
        }
    }
    impl From<u32> for MemeccsetReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemeccsetReadVal> for u32 {
        fn from(val: MemeccsetReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemeccsetWriteVal(u32);
    impl MemeccsetWriteVal {
        /// Block Memory ECC Enb Set
        ///
        /// Writing 1b is to set the corresonding bit in Block_Memory_ECC_Enb field of Block Memory ECC enable register to 1b , writing 0b has no effect
        #[inline(always)]
        pub fn memeccset(self, val: u32) -> Self {
            Self((self.0 & !(0xff << 0)) | ((val & 0xff) << 0))
        }
    }
    impl From<u32> for MemeccsetWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemeccsetWriteVal> for u32 {
        fn from(val: MemeccsetWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MeminitReadVal(u32);
    impl MeminitReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 17) & 0x7fff
        }
        /// Block_Memory_Init_Start
        ///
        /// Writing 1b to this field while it's 0b will trigger memory initilization process.
        /// During initialization, all-zero 256b data (or 32Byte) is written into the memory in 1 clock cycle.
        /// When the initialization is done, this bit is cleared to 0b,
        /// and the corresonding interrupt status bit is set 1'b1.
        #[inline(always)]
        pub fn block_memory_init_start(&self) -> bool {
            ((self.0 >> 16) & 1) != 0
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_1(&self) -> u32 {
            (self.0 >> 11) & 0x1f
        }
        /// Block_Memory_Base_Index
        ///
        /// This field indicate the base index of the block memory to be initialized. It's 0's base value.
        #[inline(always)]
        pub fn block_memory_base_index(&self) -> u32 {
            (self.0 >> 8) & 7
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_2(&self) -> u32 {
            (self.0 >> 3) & 0x1f
        }
        /// No_Block_Memory
        ///
        /// This field specifies number of block memory to be initialized. It's a 0's base value and the block memory index will be wrap-arounded. For example if Block_Memory_Base_Index is 0xF, and No_Block_Memory_Index is 1, then the block memory of which index 15 is initialized, next block memory of which index 0 is initialized. Note that depending on memory mapping mode the corresponding physical memory is initialized.
        #[inline(always)]
        pub fn no_block_memory(&self) -> u32 {
            (self.0 >> 0) & 7
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> MeminitWriteVal {
            MeminitWriteVal(self.0)
        }
    }
    impl From<u32> for MeminitReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MeminitReadVal> for u32 {
        fn from(val: MeminitReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MeminitWriteVal(u32);
    impl MeminitWriteVal {
        /// Block_Memory_Init_Start
        ///
        /// Writing 1b to this field while it's 0b will trigger memory initilization process.
        /// During initialization, all-zero 256b data (or 32Byte) is written into the memory in 1 clock cycle.
        /// When the initialization is done, this bit is cleared to 0b,
        /// and the corresonding interrupt status bit is set 1'b1.
        #[inline(always)]
        pub fn block_memory_init_start(self, val: bool) -> Self {
            Self((self.0 & !(1 << 16)) | (u32::from(val) << 16))
        }
        /// Block_Memory_Base_Index
        ///
        /// This field indicate the base index of the block memory to be initialized. It's 0's base value.
        #[inline(always)]
        pub fn block_memory_base_index(self, val: u32) -> Self {
            Self((self.0 & !(7 << 8)) | ((val & 7) << 8))
        }
        /// No_Block_Memory
        ///
        /// This field specifies number of block memory to be initialized. It's a 0's base value and the block memory index will be wrap-arounded. For example if Block_Memory_Base_Index is 0xF, and No_Block_Memory_Index is 1, then the block memory of which index 15 is initialized, next block memory of which index 0 is initialized. Note that depending on memory mapping mode the corresponding physical memory is initialized.
        #[inline(always)]
        pub fn no_block_memory(self, val: u32) -> Self {
            Self((self.0 & !(7 << 0)) | ((val & 7) << 0))
        }
    }
    impl From<u32> for MeminitWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MeminitWriteVal> for u32 {
        fn from(val: MeminitWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemintclrReadVal(u32);
    impl MemintclrReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 7) & 0x1ffffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> MemintclrWriteVal {
            MemintclrWriteVal(self.0)
        }
    }
    impl From<u32> for MemintclrReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemintclrReadVal> for u32 {
        fn from(val: MemintclrReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemintclrWriteVal(u32);
    impl MemintclrWriteVal {
        /// Block_Mem_Init_Done_Int_Enb_Clr
        ///
        /// Similar specification as for Block_Mem_Single_Bit_Error_Int_Enb_Clr field
        #[inline(always)]
        pub fn block_mem_init_done_int_enb_clr(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Block_Mem_Double_Bit_Error_Int_Enb_Clr
        ///
        /// Similar specification as for Block_Mem_Single_Bit_Error_Int_Enb_Clr field
        #[inline(always)]
        pub fn block_mem_double_bit_error_int_enb_clr(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// Block_Mem_Single_Bit_Error_Int_Enb_Clr
        ///
        /// Writing 1b to this field is to clear the corresonding bit in Memory unit interrupt enable register to 0b. Writing 0b has no effect.
        #[inline(always)]
        pub fn block_mem_single_bit_error_int_enb_clr(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for MemintclrWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemintclrWriteVal> for u32 {
        fn from(val: MemintclrWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemintenbReadVal(u32);
    impl MemintenbReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 7) & 0x1ffffff
        }
        /// Block_Mem_Init_Done_Int_Enb
        ///
        /// Similar specification as for Block_Mem_Single_Bit_Error_Int_Enb field
        #[inline(always)]
        pub fn block_mem_init_done_int_enb(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Block_Mem_Double_Bit_Error_Int_Enb
        ///
        /// Similar specification as for Block_Mem_Single_Bit_Error_Int_Enb field
        #[inline(always)]
        pub fn block_mem_double_bit_error_int_enb(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Block_Mem_Single_Bit_Error_Int_Enb
        ///
        /// This field is interrupt generation enable bit for Block_Mem_Single_Bit_Error interrupt cause
        /// 1: Enable the interrupt generation when the corrosonding cause is 1b
        /// 0: Disable/Mask the interrupt generation
        /// The bit is read only, and can only be set/clear using the corresonding bit in Memory unit interrupt enable set/clear register.
        #[inline(always)]
        pub fn block_mem_single_bit_error_int_enb(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
    }
    impl From<u32> for MemintenbReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemintenbReadVal> for u32 {
        fn from(val: MemintenbReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemintsetReadVal(u32);
    impl MemintsetReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 7) & 0x1ffffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> MemintsetWriteVal {
            MemintsetWriteVal(self.0)
        }
    }
    impl From<u32> for MemintsetReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemintsetReadVal> for u32 {
        fn from(val: MemintsetReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemintsetWriteVal(u32);
    impl MemintsetWriteVal {
        /// Block_Mem_Init_Done_Int_Enb_Set
        ///
        /// Similar specification as for Block_Mem_Single_Bit_Error_Int_Enb_Set
        #[inline(always)]
        pub fn block_mem_init_done_int_enb_set(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Block_Mem_Double_Bit_Error_Int_Enb_Set
        ///
        /// Similar specification as for Block_Mem_Single_Bit_Error_Int_Enb_Set
        #[inline(always)]
        pub fn block_mem_double_bit_error_int_enb_set(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// Block_Mem_Single_Bit_Error_Int_Enb_Set
        ///
        /// Writing 1b to this field is to set the corresonding bit in Memory unit interrupt enable register to 1b. Writing 0b has no effect.
        #[inline(always)]
        pub fn block_mem_single_bit_error_int_enb_set(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for MemintsetWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemintsetWriteVal> for u32 {
        fn from(val: MemintsetWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemintsttReadVal(u32);
    impl MemintsttReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 7) & 0x1ffffff
        }
        /// Block_Mem_Init_Done
        ///
        /// This field is set to 1b the memory initialization process is done. It's cleared to 0b by writing 0b to this bit, writing 1b has no effect.
        #[inline(always)]
        pub fn block_mem_init_done(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Block_Mem_Double_Bit_Error
        ///
        /// This field is set to 1b when total number of recorded double-bit error is greater than the specified thresholding value. It's cleared to 0b by writing 0b to this bit, writing 1b has no effect.
        #[inline(always)]
        pub fn block_mem_double_bit_error(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Block_Mem_Single_Bit_Error
        ///
        /// This field is set to 1b when total number of recorded single-bit error is greater than the specified thresholding value. It's cleared to 0b by writing 0b to this bit, writing 1b has no effect.
        #[inline(always)]
        pub fn block_mem_single_bit_error(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> MemintsttWriteVal {
            MemintsttWriteVal(self.0)
        }
    }
    impl From<u32> for MemintsttReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemintsttReadVal> for u32 {
        fn from(val: MemintsttReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct MemintsttWriteVal(u32);
    impl MemintsttWriteVal {
        /// Block_Mem_Init_Done
        ///
        /// This field is set to 1b the memory initialization process is done. It's cleared to 0b by writing 0b to this bit, writing 1b has no effect.
        #[inline(always)]
        pub fn block_mem_init_done(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Block_Mem_Double_Bit_Error
        ///
        /// This field is set to 1b when total number of recorded double-bit error is greater than the specified thresholding value. It's cleared to 0b by writing 0b to this bit, writing 1b has no effect.
        #[inline(always)]
        pub fn block_mem_double_bit_error(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// Block_Mem_Single_Bit_Error
        ///
        /// This field is set to 1b when total number of recorded single-bit error is greater than the specified thresholding value. It's cleared to 0b by writing 0b to this bit, writing 1b has no effect.
        #[inline(always)]
        pub fn block_mem_single_bit_error(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for MemintsttWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<MemintsttWriteVal> for u32 {
        fn from(val: MemintsttWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Memmap0ReadVal(u32);
    impl Memmap0ReadVal {
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn reserved_0(&self) -> u32 {
            (self.0 >> 3) & 0x1fffffff
        }
        /// Block_Memory_Mapping_Mode
        ///
        /// Specify how to map AXI write address to block memory index 'b1XX:  'b000:  (Default) 'b001:  'b010:  'b011:
        #[inline(always)]
        pub fn block_memory_mapping_mode(&self) -> u32 {
            (self.0 >> 0) & 7
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> Memmap0WriteVal {
            Memmap0WriteVal(self.0)
        }
    }
    impl From<u32> for Memmap0ReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Memmap0ReadVal> for u32 {
        fn from(val: Memmap0ReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Memmap0WriteVal(u32);
    impl Memmap0WriteVal {
        /// Block_Memory_Mapping_Mode
        ///
        /// Specify how to map AXI write address to block memory index 'b1XX:  'b000:  (Default) 'b001:  'b010:  'b011:
        #[inline(always)]
        pub fn block_memory_mapping_mode(self, val: u32) -> Self {
            Self((self.0 & !(7 << 0)) | ((val & 7) << 0))
        }
    }
    impl From<u32> for Memmap0WriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Memmap0WriteVal> for u32 {
        fn from(val: Memmap0WriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Mst0weiReadVal(u32);
    impl Mst0weiReadVal {
        /// Master_0_Write_Weight
        ///
        /// This field specifies the weight for write request from AXI master 0
        #[inline(always)]
        pub fn master_0_write_weight(&self) -> u32 {
            (self.0 >> 16) & 0xffff
        }
        /// Master_0_Read_Weight
        ///
        /// This field specifies the weight for read request from AXI master 0
        #[inline(always)]
        pub fn master_0_read_weight(&self) -> u32 {
            (self.0 >> 0) & 0xffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> Mst0weiWriteVal {
            Mst0weiWriteVal(self.0)
        }
    }
    impl From<u32> for Mst0weiReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Mst0weiReadVal> for u32 {
        fn from(val: Mst0weiReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Mst0weiWriteVal(u32);
    impl Mst0weiWriteVal {
        /// Master_0_Write_Weight
        ///
        /// This field specifies the weight for write request from AXI master 0
        #[inline(always)]
        pub fn master_0_write_weight(self, val: u32) -> Self {
            Self((self.0 & !(0xffff << 16)) | ((val & 0xffff) << 16))
        }
        /// Master_0_Read_Weight
        ///
        /// This field specifies the weight for read request from AXI master 0
        #[inline(always)]
        pub fn master_0_read_weight(self, val: u32) -> Self {
            Self((self.0 & !(0xffff << 0)) | ((val & 0xffff) << 0))
        }
    }
    impl From<u32> for Mst0weiWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Mst0weiWriteVal> for u32 {
        fn from(val: Mst0weiWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ParctrlReadVal(u32);
    impl ParctrlReadVal {
        /// Parity_Mode
        ///
        /// This field detemines parity mode
        /// 0: Odd mode
        /// 1: Even mode
        #[inline(always)]
        pub fn parity_mode(&self) -> bool {
            ((self.0 >> 31) & 1) != 0
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 18) & 0x1fff
        }
        /// Parity_error_write_injection_trigger
        ///
        /// Write 1 to this field will trigger a parity error on the next write transaction. It is automatically cleared
        #[inline(always)]
        pub fn parity_error_write_inj_trig(&self) -> bool {
            ((self.0 >> 17) & 1) != 0
        }
        /// Parity_error_read_injection_trigger
        ///
        /// Write 1 to this field will trigger a parity error on the next read transaction. It is automatically cleared
        #[inline(always)]
        pub fn parity_error_read_inj_trig(&self) -> bool {
            ((self.0 >> 16) & 1) != 0
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_1(&self) -> u32 {
            (self.0 >> 4) & 0xfff
        }
        /// Parity_Error_Write_Response_SLV_ERR_disable
        ///
        /// This field detemines how AXI write response is returned to the master 0 for a write parity error request
        /// 0: Returns SLV_ERR write response
        /// 1: Returns normal write response
        #[inline(always)]
        pub fn parity_error_write_response_slv_err_dis(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// Parity_Error_Read_Response_SLV_ERR_disable
        ///
        /// This field detemines how AXI read response is returned to the master 0 for a read parity error request
        /// 0: Returns SLV_ERR read response
        /// 1: Returns normal read response
        #[inline(always)]
        pub fn parity_error_read_response_slv_err_dis(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Parity_Error_Generate_Enable
        ///
        /// This field detemines the parity generating for read data is enable or not
        #[inline(always)]
        pub fn parity_error_generate_enable(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Parity_Error_Check_Enable
        ///
        /// This field detemines the parity checking for write data is enable or not
        #[inline(always)]
        pub fn parity_error_check_enable(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ParctrlWriteVal {
            ParctrlWriteVal(self.0)
        }
    }
    impl From<u32> for ParctrlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ParctrlReadVal> for u32 {
        fn from(val: ParctrlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ParctrlWriteVal(u32);
    impl ParctrlWriteVal {
        /// Parity_Mode
        ///
        /// This field detemines parity mode
        /// 0: Odd mode
        /// 1: Even mode
        #[inline(always)]
        pub fn parity_mode(self, val: bool) -> Self {
            Self((self.0 & !(1 << 31)) | (u32::from(val) << 31))
        }
        /// Parity_error_write_injection_trigger
        ///
        /// Write 1 to this field will trigger a parity error on the next write transaction. It is automatically cleared
        #[inline(always)]
        pub fn parity_error_write_inj_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 17)) | (u32::from(val) << 17))
        }
        /// Parity_error_read_injection_trigger
        ///
        /// Write 1 to this field will trigger a parity error on the next read transaction. It is automatically cleared
        #[inline(always)]
        pub fn parity_error_read_inj_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 16)) | (u32::from(val) << 16))
        }
        /// Parity_Error_Write_Response_SLV_ERR_disable
        ///
        /// This field detemines how AXI write response is returned to the master 0 for a write parity error request
        /// 0: Returns SLV_ERR write response
        /// 1: Returns normal write response
        #[inline(always)]
        pub fn parity_error_write_response_slv_err_dis(self, val: bool) -> Self {
            Self((self.0 & !(1 << 3)) | (u32::from(val) << 3))
        }
        /// Parity_Error_Read_Response_SLV_ERR_disable
        ///
        /// This field detemines how AXI read response is returned to the master 0 for a read parity error request
        /// 0: Returns SLV_ERR read response
        /// 1: Returns normal read response
        #[inline(always)]
        pub fn parity_error_read_response_slv_err_dis(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Parity_Error_Generate_Enable
        ///
        /// This field detemines the parity generating for read data is enable or not
        #[inline(always)]
        pub fn parity_error_generate_enable(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// Parity_Error_Check_Enable
        ///
        /// This field detemines the parity checking for write data is enable or not
        #[inline(always)]
        pub fn parity_error_check_enable(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for ParctrlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ParctrlWriteVal> for u32 {
        fn from(val: ParctrlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct Parerr0ReadVal(u32);
    impl Parerr0ReadVal {
        /// Parity_Error_Counter
        ///
        /// This field specifies indicates the number of parity error detected. The counter is increased by 1 unit for every error detected till read or when the counter reaches 0xF value.
        #[inline(always)]
        pub fn parity_error_counter(&self) -> u32 {
            (self.0 >> 28) & 0xf
        }
        /// Reserved
        ///
        /// This field is reserved for future use
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 22) & 0x3f
        }
        /// Parity_Error_Address
        ///
        /// This field captures the address of the first write transaction which has parity error
        #[inline(always)]
        pub fn parity_error_address(&self) -> u32 {
            (self.0 >> 0) & 0x3fffff
        }
    }
    impl From<u32> for Parerr0ReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<Parerr0ReadVal> for u32 {
        fn from(val: Parerr0ReadVal) -> u32 {
            val.0
        }
    }
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
    pub type Memeccenb = ureg::ReadOnlyReg32<crate::gsram::regs::MemeccenbReadVal>;
    pub type Memeccset = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::MemeccsetReadVal,
        crate::gsram::regs::MemeccsetWriteVal,
    >;
    pub type Memeccclr = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::MemeccclrReadVal,
        crate::gsram::regs::MemeccclrWriteVal,
    >;
    pub type Meminit = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::MeminitReadVal,
        crate::gsram::regs::MeminitWriteVal,
    >;
    pub type Memintstt = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::MemintsttReadVal,
        crate::gsram::regs::MemintsttWriteVal,
    >;
    pub type Memintenb = ureg::ReadOnlyReg32<crate::gsram::regs::MemintenbReadVal>;
    pub type Memintset = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::MemintsetReadVal,
        crate::gsram::regs::MemintsetWriteVal,
    >;
    pub type Memintclr = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::MemintclrReadVal,
        crate::gsram::regs::MemintclrWriteVal,
    >;
    pub type Errinjblo = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Errinjbhi = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Errinjadr = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::ErrinjadrReadVal,
        crate::gsram::regs::ErrinjadrWriteVal,
    >;
    pub type Errinjcts = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::ErrinjctsReadVal,
        crate::gsram::regs::ErrinjctsWriteVal,
    >;
    pub type Errslog0 = ureg::ReadOnlyReg32<crate::gsram::regs::Errslog0ReadVal>;
    pub type Errslog1 = ureg::ReadOnlyReg32<crate::gsram::regs::Errslog1ReadVal>;
    pub type Errssts = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::ErrsstsReadVal,
        crate::gsram::regs::ErrsstsWriteVal,
    >;
    pub type Errsthr = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::ErrsthrReadVal,
        crate::gsram::regs::ErrsthrWriteVal,
    >;
    pub type Errdlog0 = ureg::ReadOnlyReg32<crate::gsram::regs::Errdlog0ReadVal>;
    pub type Errdsts = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::ErrdstsReadVal,
        crate::gsram::regs::ErrdstsWriteVal,
    >;
    pub type Errdthr = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::ErrdthrReadVal,
        crate::gsram::regs::ErrdthrWriteVal,
    >;
    pub type Memarbctl0 = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::Memarbctl0ReadVal,
        crate::gsram::regs::Memarbctl0WriteVal,
    >;
    pub type Parctrl = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::ParctrlReadVal,
        crate::gsram::regs::ParctrlWriteVal,
    >;
    pub type Parerr0 = ureg::ReadOnlyReg32<crate::gsram::regs::Parerr0ReadVal>;
    pub type Memmap0 = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::Memmap0ReadVal,
        crate::gsram::regs::Memmap0WriteVal,
    >;
    pub type Mst0wei = ureg::ReadWriteReg32<
        0,
        crate::gsram::regs::Mst0weiReadVal,
        crate::gsram::regs::Mst0weiWriteVal,
    >;
}
