// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from mcr-cp-reg.xml

#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
#[derive(Clone, Copy)]
pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio> = ureg::RealMmio> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl RegisterBlock<ureg::RealMmio> {
    pub fn block() -> Self {
        unsafe { Self::new(0xb0002000 as *mut u32) }
    }
}
impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new(ptr: *mut u32) -> Self {
        Self {
            ptr,
            mmio: core::default::Default::default(),
        }
    }
}
impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
        Self { ptr, mmio }
    }
    /// ID eFuse Control
    ///
    /// Read value: [`idefuse::regs::IdefuseCtrlReadVal`]; Write value: [`idefuse::regs::IdefuseCtrlWriteVal`]
    #[inline(always)]
    pub fn idefuse_ctrl(&self) -> ureg::RegRef<crate::idefuse::meta::IdefuseCtrl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// ID eFuse Interrupt
    ///
    /// Read value: [`idefuse::regs::IdefuseIntReadVal`]; Write value: [`idefuse::regs::IdefuseIntWriteVal`]
    #[inline(always)]
    pub fn idefuse_int(&self) -> ureg::RegRef<crate::idefuse::meta::IdefuseInt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// ID eFuse Interrupt Mask
    ///
    /// Read value: [`idefuse::regs::IdefuseIntMskReadVal`]; Write value: [`idefuse::regs::IdefuseIntMskWriteVal`]
    #[inline(always)]
    pub fn idefuse_int_msk(&self) -> ureg::RegRef<crate::idefuse::meta::IdefuseIntMsk, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(8 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// ID eFuse Row Address
    ///
    /// Read value: [`idefuse::regs::IdefuseRowAddrReadVal`]; Write value: [`idefuse::regs::IdefuseRowAddrWriteVal`]
    #[inline(always)]
    pub fn idefuse_row_addr(&self) -> ureg::RegRef<crate::idefuse::meta::IdefuseRowAddr, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x10 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// ID eFuse Data
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn idefuse_data(&self) -> ureg::RegRef<crate::idefuse::meta::IdefuseData, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x14 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// ID eFuse SCLK Control
    ///
    /// Read value: [`idefuse::regs::IdefuseSclkCtrlReadVal`]; Write value: [`idefuse::regs::IdefuseSclkCtrlWriteVal`]
    #[inline(always)]
    pub fn idefuse_sclk_ctrl(&self) -> ureg::RegRef<crate::idefuse::meta::IdefuseSclkCtrl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x38 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// ID eFuse CPU Direct Control
    ///
    /// Read value: [`idefuse::regs::IdefuseCpuDirCtrlReadVal`]; Write value: [`idefuse::regs::IdefuseCpuDirCtrlWriteVal`]
    #[inline(always)]
    pub fn idefuse_cpu_dir_ctrl(
        &self,
    ) -> ureg::RegRef<crate::idefuse::meta::IdefuseCpuDirCtrl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x40 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// ID eFuse CPU Direct Control Data
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn idefuse_cpu_dir_ctrl_data(
        &self,
    ) -> ureg::RegRef<crate::idefuse::meta::IdefuseCpuDirCtrlData, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x44 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Chip Unique ID 0
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn chip_uid_0(&self) -> ureg::RegRef<crate::idefuse::meta::ChipUid0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x100 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Chip Unique ID 1
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn chip_uid_1(&self) -> ureg::RegRef<crate::idefuse::meta::ChipUid1, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x104 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Chip Unique ID 2
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn chip_uid_2(&self) -> ureg::RegRef<crate::idefuse::meta::ChipUid2, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x108 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Chip SVC 0
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn chip_svc_0(&self) -> ureg::RegRef<crate::idefuse::meta::ChipSvc0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x10c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Chip SVC 1
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn chip_svc_1(&self) -> ureg::RegRef<crate::idefuse::meta::ChipSvc1, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x110 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Chip Revision ID
    ///
    /// Read value: [`idefuse::regs::ChipRevIdReadVal`]; Write value: [`idefuse::regs::ChipRevIdWriteVal`]
    #[inline(always)]
    pub fn chip_rev_id(&self) -> ureg::RegRef<crate::idefuse::meta::ChipRevId, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x114 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Temperature Sensor Trip Temperature
    ///
    /// Read value: [`idefuse::regs::TsenTripTempReadVal`]; Write value: [`idefuse::regs::TsenTripTempWriteVal`]
    #[inline(always)]
    pub fn tsen_trip_temp(&self) -> ureg::RegRef<crate::idefuse::meta::TsenTripTemp, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x118 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// eFuse Status
    ///
    /// Read value: [`idefuse::regs::EfuseStatusReadVal`]; Write value: [`idefuse::regs::EfuseStatusWriteVal`]
    #[inline(always)]
    pub fn efuse_status(&self) -> ureg::RegRef<crate::idefuse::meta::EfuseStatus, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x11c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
}
pub mod regs {
    //! Types that represent the values held by registers.
    #[derive(Clone, Copy)]
    pub struct ChipRevIdReadVal(u32);
    impl ChipRevIdReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 4) & 0xfffffff
        }
        /// Revision ID
        ///
        /// This field provides the revision ID of the chip - read from Row 5, Bits [3:0] of the eFuse.
        #[inline(always)]
        pub fn revid(&self) -> u32 {
            (self.0 >> 0) & 0xf
        }
    }
    impl From<u32> for ChipRevIdReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ChipRevIdReadVal> for u32 {
        fn from(val: ChipRevIdReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct EfuseStatusReadVal(u32);
    impl EfuseStatusReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 1) & 0x7fffffff
        }
        /// eFuse Lock
        ///
        /// This field provides the eFuse Lock status - read from Row 7, Bit [0] of the eFuse.
        /// Locks the UID (Rows 0 to 2), TSEN_TRIP_THR_VLD and TSEN_TRIP_THR (Row 6) from being programmed.
        /// - 0h: UID, TSEN_TRIP_THR_VLD and TSEN_TRIP_THR can be programmed.
        /// - 1h: UID, TSEN_TRIP_THR_VLD and TSEN_TRIP_THR are locked from being programmed.
        #[inline(always)]
        pub fn efuse_lock(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
    }
    impl From<u32> for EfuseStatusReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<EfuseStatusReadVal> for u32 {
        fn from(val: EfuseStatusReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseCpuDirCtrlReadVal(u32);
    impl IdefuseCpuDirCtrlReadVal {
        /// CPU Direct Control Enable
        ///
        /// Enables the CPU to directly control the eFuse signals.
        /// - 0h: Direct control of eFuse signals disabled.
        /// - 1h: Direct control of eFuse signals enabled.
        #[inline(always)]
        pub fn cpu_dir_ctrl_en(&self) -> bool {
            ((self.0 >> 31) & 1) != 0
        }
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 26) & 0x1f
        }
        /// eFuse A
        ///
        /// CPU directly controls the A9 - A0 signals of the eFuse.
        #[inline(always)]
        pub fn efuse_a(&self) -> u32 {
            (self.0 >> 16) & 0x3ff
        }
        /// Reserved
        #[inline(always)]
        pub fn rsvd_1(&self) -> u32 {
            (self.0 >> 10) & 0x3f
        }
        /// eFuse AT
        ///
        /// CPU directly controls the AT1, AT0 signals of the eFuse.
        #[inline(always)]
        pub fn efuse_at(&self) -> u32 {
            (self.0 >> 8) & 3
        }
        /// eFuse TRCS
        ///
        /// CPU directly controls the TRCS signal of the eFuse.
        #[inline(always)]
        pub fn efuse_trcs(&self) -> bool {
            ((self.0 >> 7) & 1) != 0
        }
        /// eFuse MR
        ///
        /// CPU directly controls the MR signal of the eFuse.
        #[inline(always)]
        pub fn efuse_mr(&self) -> bool {
            ((self.0 >> 6) & 1) != 0
        }
        /// eFuse PD
        ///
        /// CPU directly controls the PD signal of the eFuse.
        #[inline(always)]
        pub fn efuse_pd(&self) -> bool {
            ((self.0 >> 5) & 1) != 0
        }
        /// eFuse PS
        ///
        /// CPU directly controls the PS signal of the eFuse.
        #[inline(always)]
        pub fn efuse_ps(&self) -> bool {
            ((self.0 >> 4) & 1) != 0
        }
        /// eFuse PGENB
        ///
        /// CPU directly controls the PGENB signal of the eFuse.
        #[inline(always)]
        pub fn efuse_pgenb(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// eFuse LOAD
        ///
        /// CPU directly controls the LOAD signal fo the eFuse.
        #[inline(always)]
        pub fn efuse_load(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// eFuse STROBE
        ///
        /// CPU directly controls the STROBE signal of the eFuse.
        #[inline(always)]
        pub fn efuse_strobe(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// eFuse CSB
        ///
        /// CPU directly controls the CSB signal of the eFuse.
        #[inline(always)]
        pub fn efuse_csb(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> IdefuseCpuDirCtrlWriteVal {
            IdefuseCpuDirCtrlWriteVal(self.0)
        }
    }
    impl From<u32> for IdefuseCpuDirCtrlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseCpuDirCtrlReadVal> for u32 {
        fn from(val: IdefuseCpuDirCtrlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseCpuDirCtrlWriteVal(u32);
    impl IdefuseCpuDirCtrlWriteVal {
        /// CPU Direct Control Enable
        ///
        /// Enables the CPU to directly control the eFuse signals.
        /// - 0h: Direct control of eFuse signals disabled.
        /// - 1h: Direct control of eFuse signals enabled.
        #[inline(always)]
        pub fn cpu_dir_ctrl_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 31)) | (u32::from(val) << 31))
        }
        /// eFuse A
        ///
        /// CPU directly controls the A9 - A0 signals of the eFuse.
        #[inline(always)]
        pub fn efuse_a(self, val: u32) -> Self {
            Self((self.0 & !(0x3ff << 16)) | ((val & 0x3ff) << 16))
        }
        /// eFuse AT
        ///
        /// CPU directly controls the AT1, AT0 signals of the eFuse.
        #[inline(always)]
        pub fn efuse_at(self, val: u32) -> Self {
            Self((self.0 & !(3 << 8)) | ((val & 3) << 8))
        }
        /// eFuse TRCS
        ///
        /// CPU directly controls the TRCS signal of the eFuse.
        #[inline(always)]
        pub fn efuse_trcs(self, val: bool) -> Self {
            Self((self.0 & !(1 << 7)) | (u32::from(val) << 7))
        }
        /// eFuse MR
        ///
        /// CPU directly controls the MR signal of the eFuse.
        #[inline(always)]
        pub fn efuse_mr(self, val: bool) -> Self {
            Self((self.0 & !(1 << 6)) | (u32::from(val) << 6))
        }
        /// eFuse PD
        ///
        /// CPU directly controls the PD signal of the eFuse.
        #[inline(always)]
        pub fn efuse_pd(self, val: bool) -> Self {
            Self((self.0 & !(1 << 5)) | (u32::from(val) << 5))
        }
        /// eFuse PS
        ///
        /// CPU directly controls the PS signal of the eFuse.
        #[inline(always)]
        pub fn efuse_ps(self, val: bool) -> Self {
            Self((self.0 & !(1 << 4)) | (u32::from(val) << 4))
        }
        /// eFuse PGENB
        ///
        /// CPU directly controls the PGENB signal of the eFuse.
        #[inline(always)]
        pub fn efuse_pgenb(self, val: bool) -> Self {
            Self((self.0 & !(1 << 3)) | (u32::from(val) << 3))
        }
        /// eFuse LOAD
        ///
        /// CPU directly controls the LOAD signal fo the eFuse.
        #[inline(always)]
        pub fn efuse_load(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// eFuse STROBE
        ///
        /// CPU directly controls the STROBE signal of the eFuse.
        #[inline(always)]
        pub fn efuse_strobe(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// eFuse CSB
        ///
        /// CPU directly controls the CSB signal of the eFuse.
        #[inline(always)]
        pub fn efuse_csb(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for IdefuseCpuDirCtrlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseCpuDirCtrlWriteVal> for u32 {
        fn from(val: IdefuseCpuDirCtrlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseCtrlReadVal(u32);
    impl IdefuseCtrlReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 11) & 0x1fffff
        }
        /// eFuse Test Mode
        ///
        /// This field determines if the test read or write goes to the test row or one of the two test columns.
        /// - 0h: Access is to test row
        /// - 1h: Not used
        /// - 2h: Access is to test column 1
        /// - 3h: Access is to test column 2
        /// When test row is selected, ROW_ADDR[4] (IDEFUSE_ROW_ADDR [4]) determines which 32-bit word is read out to DATA[31:0] (IDFUSE_ROW_ADDR [31:0]).
        /// When one of the test columns is selected, ROW_ADDR[3:0] (IDEFUSE_ROW_ADDR [3:0]) determines which bit of the column is accessed. If test column 1 is selected, the data read is in DATA[0] (IDEFUSE_DATA [0]). If test column 2 is selected, the data read is in DATA[31] (IDEFUSE_DATA [31]).
        /// Note: This bit is used for testing purposes.
        #[inline(always)]
        pub fn test_mode(&self) -> u32 {
            (self.0 >> 9) & 3
        }
        /// eFuse Test Mode Enable
        ///
        /// Set this bit to 1h to access the test bits (test row/column) in the eFuse.
        /// Note: This bit is used for testing purposes. It must be set to 0h in normal operations.
        #[inline(always)]
        pub fn test_en(&self) -> bool {
            ((self.0 >> 8) & 1) != 0
        }
        /// eFuse Margin Read
        ///
        /// Set this bit to 1h to perform an eFuse Margin Read operation, which starts when START (IDEFUSE_CTRL [0]) is set.
        /// Note: The trip point for Margin Read is higher than that of a normal Read (IDEFUSE_CTRL [2]).
        #[inline(always)]
        pub fn margin_read(&self) -> bool {
            ((self.0 >> 7) & 1) != 0
        }
        /// eFuse Power Down
        ///
        /// Set this bit to 1h to put the eFuse in power-down mode.
        #[inline(always)]
        pub fn pdwn(&self) -> bool {
            ((self.0 >> 6) & 1) != 0
        }
        /// Reserved
        #[inline(always)]
        pub fn rsvd_1(&self) -> bool {
            ((self.0 >> 5) & 1) != 0
        }
        /// eFuse Read Back
        ///
        /// Set this bit to 1h to perform an eFuse read back operation, which starts when START (IDEFUSE_CTRL [0]) is set.  The purpose of this operation is to update the following registers with the values read from the eFuse.
        /// - CHIP_UID_0
        /// - CHIP_UID_1
        /// - CHIP_UID_2
        /// - CHIP_SVC_0
        /// - CHIP_SVC_1
        /// - CHIP_REV_ID
        /// - TSEN_TRIP_TEMP
        /// - EFUSE_STATUS
        #[inline(always)]
        pub fn read_back(&self) -> bool {
            ((self.0 >> 4) & 1) != 0
        }
        /// Reserved
        #[inline(always)]
        pub fn rsvd_2(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// eFuse READ
        ///
        /// Set this bit to 1h to perform an eFuse read operation, which starts when START (IDEFUSE_CTRL [0]) is set.
        #[inline(always)]
        pub fn read(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// eFuse WRITE
        ///
        /// Set this bit to 1h to perform an eFuse write operation, which starts when START (IDEFUSE_CTRL [0]) is set.
        /// Note: It is important that an eFuse bit, which has already been burned, is not burned again. Before programming, the eFuse data should be read out and compared against the data intended to be burned to ensure a bit is not burned again.
        #[inline(always)]
        pub fn write(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// eFuse START
        ///
        /// Operation start.
        /// - 0h: Operation not started.
        /// - 1h: Starts the READ, WRITE or READ_BACK operation.
        /// When this bit is set to 1h, the WRITE (IDEFUSE_CTRL [1]), READ (IDEFUSE_CTRL [2]) or READ_BACK (IDEFUSE_CTRL [4]) operation begins.
        /// Note: When this bit is set, only one of the WRITE, READ or READ_BACK operations can be set. This bit automatically resets to 0h after the operation is completed.
        #[inline(always)]
        pub fn start(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> IdefuseCtrlWriteVal {
            IdefuseCtrlWriteVal(self.0)
        }
    }
    impl From<u32> for IdefuseCtrlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseCtrlReadVal> for u32 {
        fn from(val: IdefuseCtrlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseCtrlWriteVal(u32);
    impl IdefuseCtrlWriteVal {
        /// eFuse Test Mode
        ///
        /// This field determines if the test read or write goes to the test row or one of the two test columns.
        /// - 0h: Access is to test row
        /// - 1h: Not used
        /// - 2h: Access is to test column 1
        /// - 3h: Access is to test column 2
        /// When test row is selected, ROW_ADDR[4] (IDEFUSE_ROW_ADDR [4]) determines which 32-bit word is read out to DATA[31:0] (IDFUSE_ROW_ADDR [31:0]).
        /// When one of the test columns is selected, ROW_ADDR[3:0] (IDEFUSE_ROW_ADDR [3:0]) determines which bit of the column is accessed. If test column 1 is selected, the data read is in DATA[0] (IDEFUSE_DATA [0]). If test column 2 is selected, the data read is in DATA[31] (IDEFUSE_DATA [31]).
        /// Note: This bit is used for testing purposes.
        #[inline(always)]
        pub fn test_mode(self, val: u32) -> Self {
            Self((self.0 & !(3 << 9)) | ((val & 3) << 9))
        }
        /// eFuse Test Mode Enable
        ///
        /// Set this bit to 1h to access the test bits (test row/column) in the eFuse.
        /// Note: This bit is used for testing purposes. It must be set to 0h in normal operations.
        #[inline(always)]
        pub fn test_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 8)) | (u32::from(val) << 8))
        }
        /// eFuse Margin Read
        ///
        /// Set this bit to 1h to perform an eFuse Margin Read operation, which starts when START (IDEFUSE_CTRL [0]) is set.
        /// Note: The trip point for Margin Read is higher than that of a normal Read (IDEFUSE_CTRL [2]).
        #[inline(always)]
        pub fn margin_read(self, val: bool) -> Self {
            Self((self.0 & !(1 << 7)) | (u32::from(val) << 7))
        }
        /// eFuse Power Down
        ///
        /// Set this bit to 1h to put the eFuse in power-down mode.
        #[inline(always)]
        pub fn pdwn(self, val: bool) -> Self {
            Self((self.0 & !(1 << 6)) | (u32::from(val) << 6))
        }
        /// eFuse Read Back
        ///
        /// Set this bit to 1h to perform an eFuse read back operation, which starts when START (IDEFUSE_CTRL [0]) is set.  The purpose of this operation is to update the following registers with the values read from the eFuse.
        /// - CHIP_UID_0
        /// - CHIP_UID_1
        /// - CHIP_UID_2
        /// - CHIP_SVC_0
        /// - CHIP_SVC_1
        /// - CHIP_REV_ID
        /// - TSEN_TRIP_TEMP
        /// - EFUSE_STATUS
        #[inline(always)]
        pub fn read_back(self, val: bool) -> Self {
            Self((self.0 & !(1 << 4)) | (u32::from(val) << 4))
        }
        /// eFuse READ
        ///
        /// Set this bit to 1h to perform an eFuse read operation, which starts when START (IDEFUSE_CTRL [0]) is set.
        #[inline(always)]
        pub fn read(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// eFuse WRITE
        ///
        /// Set this bit to 1h to perform an eFuse write operation, which starts when START (IDEFUSE_CTRL [0]) is set.
        /// Note: It is important that an eFuse bit, which has already been burned, is not burned again. Before programming, the eFuse data should be read out and compared against the data intended to be burned to ensure a bit is not burned again.
        #[inline(always)]
        pub fn write(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// eFuse START
        ///
        /// Operation start.
        /// - 0h: Operation not started.
        /// - 1h: Starts the READ, WRITE or READ_BACK operation.
        /// When this bit is set to 1h, the WRITE (IDEFUSE_CTRL [1]), READ (IDEFUSE_CTRL [2]) or READ_BACK (IDEFUSE_CTRL [4]) operation begins.
        /// Note: When this bit is set, only one of the WRITE, READ or READ_BACK operations can be set. This bit automatically resets to 0h after the operation is completed.
        #[inline(always)]
        pub fn start(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for IdefuseCtrlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseCtrlWriteVal> for u32 {
        fn from(val: IdefuseCtrlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseIntReadVal(u32);
    impl IdefuseIntReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 1) & 0x7fffffff
        }
        /// Operation Done
        ///
        /// This field indicates whether the current eFuse operation has completed.
        /// - 0h: Operation not completed.
        /// - 1h: Operation completed.
        /// Note: This bit is reset by writing a 1h to this field.
        #[inline(always)]
        pub fn done(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> IdefuseIntWriteVal {
            IdefuseIntWriteVal(self.0)
        }
    }
    impl From<u32> for IdefuseIntReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseIntReadVal> for u32 {
        fn from(val: IdefuseIntReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseIntWriteVal(u32);
    impl IdefuseIntWriteVal {
        /// Operation Done
        ///
        /// This field indicates whether the current eFuse operation has completed.
        /// - 0h: Operation not completed.
        /// - 1h: Operation completed.
        /// Note: This bit is reset by writing a 1h to this field.
        #[inline(always)]
        pub fn done(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for IdefuseIntWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseIntWriteVal> for u32 {
        fn from(val: IdefuseIntWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseIntMskReadVal(u32);
    impl IdefuseIntMskReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 1) & 0x7fffffff
        }
        /// Operation Done Mask
        ///
        /// This bit masks the DONE (IDEFUSE_INT [0]) interrupt.
        /// - 0h: Interrupt not masked.
        /// - 1h: Interrupt masked.
        #[inline(always)]
        pub fn done_mask(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> IdefuseIntMskWriteVal {
            IdefuseIntMskWriteVal(self.0)
        }
    }
    impl From<u32> for IdefuseIntMskReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseIntMskReadVal> for u32 {
        fn from(val: IdefuseIntMskReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseIntMskWriteVal(u32);
    impl IdefuseIntMskWriteVal {
        /// Operation Done Mask
        ///
        /// This bit masks the DONE (IDEFUSE_INT [0]) interrupt.
        /// - 0h: Interrupt not masked.
        /// - 1h: Interrupt masked.
        #[inline(always)]
        pub fn done_mask(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for IdefuseIntMskWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseIntMskWriteVal> for u32 {
        fn from(val: IdefuseIntMskWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseRowAddrReadVal(u32);
    impl IdefuseRowAddrReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 10) & 0x3fffff
        }
        /// Row Address
        ///
        /// Bits [4:0] of this field indicates which row of the eFuse is being addressed.
        #[inline(always)]
        pub fn row_addr(&self) -> u32 {
            (self.0 >> 0) & 0x3ff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> IdefuseRowAddrWriteVal {
            IdefuseRowAddrWriteVal(self.0)
        }
    }
    impl From<u32> for IdefuseRowAddrReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseRowAddrReadVal> for u32 {
        fn from(val: IdefuseRowAddrReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseRowAddrWriteVal(u32);
    impl IdefuseRowAddrWriteVal {
        /// Row Address
        ///
        /// Bits [4:0] of this field indicates which row of the eFuse is being addressed.
        #[inline(always)]
        pub fn row_addr(self, val: u32) -> Self {
            Self((self.0 & !(0x3ff << 0)) | ((val & 0x3ff) << 0))
        }
    }
    impl From<u32> for IdefuseRowAddrWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseRowAddrWriteVal> for u32 {
        fn from(val: IdefuseRowAddrWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseSclkCtrlReadVal(u32);
    impl IdefuseSclkCtrlReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 16) & 0xffff
        }
        /// Write Time
        ///
        /// This field is used to control the amount of time that the programming voltage is applied to the eFuses. The value is dependent upon the frequency at which the APB clock is running and the programming time requirement for the eFuse technology used in the SoC.
        /// This value must be calculated correctly since incorrectly burned eFuses can lead to incomplete burning, and early life failure of the eFuses.
        /// For eFuses that require a burn time of 5 us, the equation to calculate the field is as follows:
        /// WRITE_TIME = 5 (in us) * APB Clock Frequency (in MHz)
        #[inline(always)]
        pub fn write_time(&self) -> u32 {
            (self.0 >> 1) & 0x7fff
        }
        /// Enable
        ///
        /// Enables the value in WRITE_TIME (IDEFUSE_SCLK_CTRL [15:1]) to be used when programming the eFuses.
        /// - 0h: The default value (which are technology and frequency dependent and have a fixed value) is used.
        /// - 1h: The WRITE_TIME field is used when programming the eFuses.
        #[inline(always)]
        pub fn enable(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> IdefuseSclkCtrlWriteVal {
            IdefuseSclkCtrlWriteVal(self.0)
        }
    }
    impl From<u32> for IdefuseSclkCtrlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseSclkCtrlReadVal> for u32 {
        fn from(val: IdefuseSclkCtrlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IdefuseSclkCtrlWriteVal(u32);
    impl IdefuseSclkCtrlWriteVal {
        /// Write Time
        ///
        /// This field is used to control the amount of time that the programming voltage is applied to the eFuses. The value is dependent upon the frequency at which the APB clock is running and the programming time requirement for the eFuse technology used in the SoC.
        /// This value must be calculated correctly since incorrectly burned eFuses can lead to incomplete burning, and early life failure of the eFuses.
        /// For eFuses that require a burn time of 5 us, the equation to calculate the field is as follows:
        /// WRITE_TIME = 5 (in us) * APB Clock Frequency (in MHz)
        #[inline(always)]
        pub fn write_time(self, val: u32) -> Self {
            Self((self.0 & !(0x7fff << 1)) | ((val & 0x7fff) << 1))
        }
        /// Enable
        ///
        /// Enables the value in WRITE_TIME (IDEFUSE_SCLK_CTRL [15:1]) to be used when programming the eFuses.
        /// - 0h: The default value (which are technology and frequency dependent and have a fixed value) is used.
        /// - 1h: The WRITE_TIME field is used when programming the eFuses.
        #[inline(always)]
        pub fn enable(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for IdefuseSclkCtrlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IdefuseSclkCtrlWriteVal> for u32 {
        fn from(val: IdefuseSclkCtrlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct TsenTripTempReadVal(u32);
    impl TsenTripTempReadVal {
        /// Reserved
        #[inline(always)]
        pub fn rsvd_0(&self) -> u32 {
            (self.0 >> 17) & 0x7fff
        }
        /// Temperature Sensor Trip Threshold Valid
        ///
        /// This field provides the Temperature Sensor Trip Threshold Valid value - read from Row 6, Bit 16 of the eFuse.
        /// The value in this field indicates whether the TSEN_TRIP_THR field has a valid value.
        /// - 0h: Value in TSEN_TRIP_THR is not valid.
        /// - 1h: Value in TSEN_TRIP_THR is valid.
        #[inline(always)]
        pub fn tsen_trip_thr_vld(&self) -> bool {
            ((self.0 >> 16) & 1) != 0
        }
        /// Reserved
        #[inline(always)]
        pub fn rsvd_1(&self) -> u32 {
            (self.0 >> 10) & 0x3f
        }
        /// Temperature Sensor Trip Threshold
        ///
        /// This field provides the Temperature Sensor Trip Threshold value read from Row 6, Bits [9:0] of the eFuse.
        #[inline(always)]
        pub fn tsen_trip_thr(&self) -> u32 {
            (self.0 >> 0) & 0x3ff
        }
    }
    impl From<u32> for TsenTripTempReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<TsenTripTempReadVal> for u32 {
        fn from(val: TsenTripTempReadVal) -> u32 {
            val.0
        }
    }
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
    pub type IdefuseCtrl = ureg::ReadWriteReg32<
        0,
        crate::idefuse::regs::IdefuseCtrlReadVal,
        crate::idefuse::regs::IdefuseCtrlWriteVal,
    >;
    pub type IdefuseInt = ureg::ReadWriteReg32<
        0,
        crate::idefuse::regs::IdefuseIntReadVal,
        crate::idefuse::regs::IdefuseIntWriteVal,
    >;
    pub type IdefuseIntMsk = ureg::ReadWriteReg32<
        0,
        crate::idefuse::regs::IdefuseIntMskReadVal,
        crate::idefuse::regs::IdefuseIntMskWriteVal,
    >;
    pub type IdefuseRowAddr = ureg::ReadWriteReg32<
        0,
        crate::idefuse::regs::IdefuseRowAddrReadVal,
        crate::idefuse::regs::IdefuseRowAddrWriteVal,
    >;
    pub type IdefuseData = ureg::ReadWriteReg32<0, u32, u32>;
    pub type IdefuseSclkCtrl = ureg::ReadWriteReg32<
        0,
        crate::idefuse::regs::IdefuseSclkCtrlReadVal,
        crate::idefuse::regs::IdefuseSclkCtrlWriteVal,
    >;
    pub type IdefuseCpuDirCtrl = ureg::ReadWriteReg32<
        0,
        crate::idefuse::regs::IdefuseCpuDirCtrlReadVal,
        crate::idefuse::regs::IdefuseCpuDirCtrlWriteVal,
    >;
    pub type IdefuseCpuDirCtrlData = ureg::ReadOnlyReg32<u32>;
    pub type ChipUid0 = ureg::ReadOnlyReg32<u32>;
    pub type ChipUid1 = ureg::ReadOnlyReg32<u32>;
    pub type ChipUid2 = ureg::ReadOnlyReg32<u32>;
    pub type ChipSvc0 = ureg::ReadOnlyReg32<u32>;
    pub type ChipSvc1 = ureg::ReadOnlyReg32<u32>;
    pub type ChipRevId = ureg::ReadOnlyReg32<crate::idefuse::regs::ChipRevIdReadVal>;
    pub type TsenTripTemp = ureg::ReadOnlyReg32<crate::idefuse::regs::TsenTripTempReadVal>;
    pub type EfuseStatus = ureg::ReadOnlyReg32<crate::idefuse::regs::EfuseStatusReadVal>;
}
