// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from mcr-cp-reg.xml

#![no_std]
#![allow(clippy::doc_nested_refdefs)]
pub mod aes_regs;
pub mod cdma;
pub mod comphy0_soc;
pub mod comphy1_soc;
pub mod cortexm7;
pub mod dual_cp_m7;
pub mod gdma;
pub mod gsram;
pub mod idefuse;
pub mod ipc_intc;
pub mod msix;
pub mod pcie_assist;
pub mod pcie_doe;
pub mod pcie_ep;
pub mod pcie_ide;
pub mod pcie_ide_aes;
pub mod pcie_tdisp_cfg;
pub mod pcie_top_reg;
pub mod por;
pub mod rng_regs;
pub mod sha_regs;
pub mod sys_mbx;
pub mod tcon;
pub mod uart;
pub mod ucd;
pub mod upka_regs;
