// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from mcr-cp-reg.xml

#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
#[derive(Clone, Copy)]
pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio> = ureg::RealMmio> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl RegisterBlock<ureg::RealMmio> {
    pub fn block() -> Self {
        unsafe { Self::new(0xb0004000 as *mut u32) }
    }
}
impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new(ptr: *mut u32) -> Self {
        Self {
            ptr,
            mmio: core::default::Default::default(),
        }
    }
}
impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
        Self { ptr, mmio }
    }
    /// Reset Control
    ///
    /// Read value: [`por::regs::ResetControlReadVal`]; Write value: [`por::regs::ResetControlWriteVal`]
    #[inline(always)]
    pub fn reset_control(&self) -> ureg::RegRef<crate::por::meta::ResetControl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// FP Runstall
    ///
    /// Read value: [`por::regs::FpRunstallReadVal`]; Write value: [`por::regs::FpRunstallWriteVal`]
    #[inline(always)]
    pub fn fp_runstall(&self) -> ureg::RegRef<crate::por::meta::FpRunstall, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Debug ETM Reset Control
    ///
    /// Read value: [`por::regs::DbgetmResetControlReadVal`]; Write value: [`por::regs::DbgetmResetControlWriteVal`]
    #[inline(always)]
    pub fn dbgetm_reset_control(
        &self,
    ) -> ureg::RegRef<crate::por::meta::DbgetmResetControl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(8 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Reset Control1
    ///
    /// Read value: [`por::regs::ResetControl1ReadVal`]; Write value: [`por::regs::ResetControl1WriteVal`]
    #[inline(always)]
    pub fn reset_control1(&self) -> ureg::RegRef<crate::por::meta::ResetControl1, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xc / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
}
pub mod regs {
    //! Types that represent the values held by registers.
    #[derive(Clone, Copy)]
    pub struct DbgetmResetControlReadVal(u32);
    impl DbgetmResetControlReadVal {
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved1(&self) -> u32 {
            (self.0 >> 5) & 0x7ffffff
        }
        /// FP2 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn fp2_dbgetm_rst(&self) -> bool {
            ((self.0 >> 4) & 1) != 0
        }
        /// FP1 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn fp1_dbgetm_rst(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// FP0 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn fp0_dbgetm_rst(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// CP1 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn cp1_dbgetm_rst(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// CP0 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn cp0_dbgetm_rst(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> DbgetmResetControlWriteVal {
            DbgetmResetControlWriteVal(self.0)
        }
    }
    impl From<u32> for DbgetmResetControlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<DbgetmResetControlReadVal> for u32 {
        fn from(val: DbgetmResetControlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct DbgetmResetControlWriteVal(u32);
    impl DbgetmResetControlWriteVal {
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved1(self, val: u32) -> Self {
            Self((self.0 & !(0x7ffffff << 5)) | ((val & 0x7ffffff) << 5))
        }
        /// FP2 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn fp2_dbgetm_rst(self, val: bool) -> Self {
            Self((self.0 & !(1 << 4)) | (u32::from(val) << 4))
        }
        /// FP1 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn fp1_dbgetm_rst(self, val: bool) -> Self {
            Self((self.0 & !(1 << 3)) | (u32::from(val) << 3))
        }
        /// FP0 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn fp0_dbgetm_rst(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// CP1 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn cp1_dbgetm_rst(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// CP0 DBG ETM Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn cp0_dbgetm_rst(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for DbgetmResetControlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<DbgetmResetControlWriteVal> for u32 {
        fn from(val: DbgetmResetControlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct FpRunstallReadVal(u32);
    impl FpRunstallReadVal {
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved(&self) -> u32 {
            (self.0 >> 3) & 0x1fffffff
        }
        /// FP2 CPU WAIT
        #[inline(always)]
        pub fn fp2_cpuwait(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// FP1 CPU WAIT
        #[inline(always)]
        pub fn fp1_cpuwait(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// FP0 CPU WAIT
        #[inline(always)]
        pub fn fp0_cpuwait(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> FpRunstallWriteVal {
            FpRunstallWriteVal(self.0)
        }
    }
    impl From<u32> for FpRunstallReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<FpRunstallReadVal> for u32 {
        fn from(val: FpRunstallReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct FpRunstallWriteVal(u32);
    impl FpRunstallWriteVal {
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved(self, val: u32) -> Self {
            Self((self.0 & !(0x1fffffff << 3)) | ((val & 0x1fffffff) << 3))
        }
        /// FP2 CPU WAIT
        #[inline(always)]
        pub fn fp2_cpuwait(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// FP1 CPU WAIT
        #[inline(always)]
        pub fn fp1_cpuwait(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// FP0 CPU WAIT
        #[inline(always)]
        pub fn fp0_cpuwait(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for FpRunstallWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<FpRunstallWriteVal> for u32 {
        fn from(val: FpRunstallWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ResetControlReadVal(u32);
    impl ResetControlReadVal {
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved4(&self) -> u32 {
            (self.0 >> 27) & 0x1f
        }
        /// SPI TPM1 Soft Reset
        #[inline(always)]
        pub fn rst_spi_tpm1(&self) -> bool {
            ((self.0 >> 26) & 1) != 0
        }
        /// SPI TPM0 Soft Reset
        #[inline(always)]
        pub fn rst_spi_tpm0(&self) -> bool {
            ((self.0 >> 25) & 1) != 0
        }
        /// FP2 Soft Reset
        #[inline(always)]
        pub fn rst_fp2(&self) -> bool {
            ((self.0 >> 24) & 1) != 0
        }
        /// FP1 Soft Reset
        #[inline(always)]
        pub fn rst_fp1(&self) -> bool {
            ((self.0 >> 23) & 1) != 0
        }
        /// FP0 Soft Reset
        #[inline(always)]
        pub fn rst_fp0(&self) -> bool {
            ((self.0 >> 22) & 1) != 0
        }
        /// CP_2X Soft Reset
        #[inline(always)]
        pub fn rst_cp_2_x(&self) -> bool {
            ((self.0 >> 21) & 1) != 0
        }
        /// CP1 Soft Reset
        #[inline(always)]
        pub fn rst_cp1(&self) -> bool {
            ((self.0 >> 20) & 1) != 0
        }
        /// CP0 Soft Reset
        #[inline(always)]
        pub fn rst_cp0(&self) -> bool {
            ((self.0 >> 19) & 1) != 0
        }
        /// PCIE Matrix Soft Reset
        #[inline(always)]
        pub fn rst_pcie_mtx(&self) -> bool {
            ((self.0 >> 18) & 1) != 0
        }
        /// MCU Soft Reset
        #[inline(always)]
        pub fn rst_mcu(&self) -> bool {
            ((self.0 >> 17) & 1) != 0
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved3(&self) -> bool {
            ((self.0 >> 16) & 1) != 0
        }
        /// TCON Soft Reset
        #[inline(always)]
        pub fn rst_tcon(&self) -> bool {
            ((self.0 >> 15) & 1) != 0
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved2(&self) -> bool {
            ((self.0 >> 14) & 1) != 0
        }
        /// UART Soft Reset
        #[inline(always)]
        pub fn rst_uart(&self) -> bool {
            ((self.0 >> 13) & 1) != 0
        }
        /// MINIAXI Soft Reset
        #[inline(always)]
        pub fn rst_miniaxi(&self) -> bool {
            ((self.0 >> 12) & 1) != 0
        }
        /// TRACE Soft Reset
        #[inline(always)]
        pub fn rst_trace(&self) -> bool {
            ((self.0 >> 11) & 1) != 0
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved1(&self) -> u32 {
            (self.0 >> 9) & 3
        }
        /// GSRAM Soft Reset
        #[inline(always)]
        pub fn rst_gsram(&self) -> bool {
            ((self.0 >> 8) & 1) != 0
        }
        /// NQM Soft Reset
        #[inline(always)]
        pub fn rst_nqm(&self) -> bool {
            ((self.0 >> 7) & 1) != 0
        }
        /// APB Soft Reset
        #[inline(always)]
        pub fn rst_apb(&self) -> bool {
            ((self.0 >> 6) & 1) != 0
        }
        /// BCP Soft Reset
        #[inline(always)]
        pub fn rst_bcp(&self) -> bool {
            ((self.0 >> 5) & 1) != 0
        }
        /// GDMA Soft Reset
        #[inline(always)]
        pub fn rst_gdma(&self) -> bool {
            ((self.0 >> 4) & 1) != 0
        }
        /// CPU_JT Soft Reset
        #[inline(always)]
        pub fn rst_cpu_jt(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// CPUCP Soft Reset
        #[inline(always)]
        pub fn rst_cpucp(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved0(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// OSC Soft Reset
        #[inline(always)]
        pub fn rst_osc(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ResetControlWriteVal {
            ResetControlWriteVal(self.0)
        }
    }
    impl From<u32> for ResetControlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ResetControlReadVal> for u32 {
        fn from(val: ResetControlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ResetControlWriteVal(u32);
    impl ResetControlWriteVal {
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved4(self, val: u32) -> Self {
            Self((self.0 & !(0x1f << 27)) | ((val & 0x1f) << 27))
        }
        /// SPI TPM1 Soft Reset
        #[inline(always)]
        pub fn rst_spi_tpm1(self, val: bool) -> Self {
            Self((self.0 & !(1 << 26)) | (u32::from(val) << 26))
        }
        /// SPI TPM0 Soft Reset
        #[inline(always)]
        pub fn rst_spi_tpm0(self, val: bool) -> Self {
            Self((self.0 & !(1 << 25)) | (u32::from(val) << 25))
        }
        /// FP2 Soft Reset
        #[inline(always)]
        pub fn rst_fp2(self, val: bool) -> Self {
            Self((self.0 & !(1 << 24)) | (u32::from(val) << 24))
        }
        /// FP1 Soft Reset
        #[inline(always)]
        pub fn rst_fp1(self, val: bool) -> Self {
            Self((self.0 & !(1 << 23)) | (u32::from(val) << 23))
        }
        /// FP0 Soft Reset
        #[inline(always)]
        pub fn rst_fp0(self, val: bool) -> Self {
            Self((self.0 & !(1 << 22)) | (u32::from(val) << 22))
        }
        /// CP_2X Soft Reset
        #[inline(always)]
        pub fn rst_cp_2_x(self, val: bool) -> Self {
            Self((self.0 & !(1 << 21)) | (u32::from(val) << 21))
        }
        /// CP1 Soft Reset
        #[inline(always)]
        pub fn rst_cp1(self, val: bool) -> Self {
            Self((self.0 & !(1 << 20)) | (u32::from(val) << 20))
        }
        /// CP0 Soft Reset
        #[inline(always)]
        pub fn rst_cp0(self, val: bool) -> Self {
            Self((self.0 & !(1 << 19)) | (u32::from(val) << 19))
        }
        /// PCIE Matrix Soft Reset
        #[inline(always)]
        pub fn rst_pcie_mtx(self, val: bool) -> Self {
            Self((self.0 & !(1 << 18)) | (u32::from(val) << 18))
        }
        /// MCU Soft Reset
        #[inline(always)]
        pub fn rst_mcu(self, val: bool) -> Self {
            Self((self.0 & !(1 << 17)) | (u32::from(val) << 17))
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved3(self, val: bool) -> Self {
            Self((self.0 & !(1 << 16)) | (u32::from(val) << 16))
        }
        /// TCON Soft Reset
        #[inline(always)]
        pub fn rst_tcon(self, val: bool) -> Self {
            Self((self.0 & !(1 << 15)) | (u32::from(val) << 15))
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved2(self, val: bool) -> Self {
            Self((self.0 & !(1 << 14)) | (u32::from(val) << 14))
        }
        /// UART Soft Reset
        #[inline(always)]
        pub fn rst_uart(self, val: bool) -> Self {
            Self((self.0 & !(1 << 13)) | (u32::from(val) << 13))
        }
        /// MINIAXI Soft Reset
        #[inline(always)]
        pub fn rst_miniaxi(self, val: bool) -> Self {
            Self((self.0 & !(1 << 12)) | (u32::from(val) << 12))
        }
        /// TRACE Soft Reset
        #[inline(always)]
        pub fn rst_trace(self, val: bool) -> Self {
            Self((self.0 & !(1 << 11)) | (u32::from(val) << 11))
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved1(self, val: u32) -> Self {
            Self((self.0 & !(3 << 9)) | ((val & 3) << 9))
        }
        /// GSRAM Soft Reset
        #[inline(always)]
        pub fn rst_gsram(self, val: bool) -> Self {
            Self((self.0 & !(1 << 8)) | (u32::from(val) << 8))
        }
        /// NQM Soft Reset
        #[inline(always)]
        pub fn rst_nqm(self, val: bool) -> Self {
            Self((self.0 & !(1 << 7)) | (u32::from(val) << 7))
        }
        /// APB Soft Reset
        #[inline(always)]
        pub fn rst_apb(self, val: bool) -> Self {
            Self((self.0 & !(1 << 6)) | (u32::from(val) << 6))
        }
        /// BCP Soft Reset
        #[inline(always)]
        pub fn rst_bcp(self, val: bool) -> Self {
            Self((self.0 & !(1 << 5)) | (u32::from(val) << 5))
        }
        /// GDMA Soft Reset
        #[inline(always)]
        pub fn rst_gdma(self, val: bool) -> Self {
            Self((self.0 & !(1 << 4)) | (u32::from(val) << 4))
        }
        /// CPU_JT Soft Reset
        #[inline(always)]
        pub fn rst_cpu_jt(self, val: bool) -> Self {
            Self((self.0 & !(1 << 3)) | (u32::from(val) << 3))
        }
        /// CPUCP Soft Reset
        #[inline(always)]
        pub fn rst_cpucp(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved0(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// OSC Soft Reset
        #[inline(always)]
        pub fn rst_osc(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for ResetControlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ResetControlWriteVal> for u32 {
        fn from(val: ResetControlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ResetControl1ReadVal(u32);
    impl ResetControl1ReadVal {
        /// UPKA Soft Resets, one soft reset bit for each standalone UPKA module
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_upka(&self) -> u32 {
            (self.0 >> 16) & 0xffff
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved1(&self) -> u32 {
            (self.0 >> 3) & 0x1fff
        }
        /// CRYPTO2 Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_crypto2(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// CRYPTO1 Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_crypto1(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// CRYPTO0 Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_crypto0(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ResetControl1WriteVal {
            ResetControl1WriteVal(self.0)
        }
    }
    impl From<u32> for ResetControl1ReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ResetControl1ReadVal> for u32 {
        fn from(val: ResetControl1ReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ResetControl1WriteVal(u32);
    impl ResetControl1WriteVal {
        /// UPKA Soft Resets, one soft reset bit for each standalone UPKA module
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_upka(self, val: u32) -> Self {
            Self((self.0 & !(0xffff << 16)) | ((val & 0xffff) << 16))
        }
        /// Reserved
        ///
        /// Reserved
        #[inline(always)]
        pub fn reserved1(self, val: u32) -> Self {
            Self((self.0 & !(0x1fff << 3)) | ((val & 0x1fff) << 3))
        }
        /// CRYPTO2 Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_crypto2(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// CRYPTO1 Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_crypto1(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// CRYPTO0 Soft Reset
        ///
        /// Write 1 to assert reset and write 0 to clear reset
        #[inline(always)]
        pub fn rst_crypto0(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for ResetControl1WriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ResetControl1WriteVal> for u32 {
        fn from(val: ResetControl1WriteVal) -> u32 {
            val.0
        }
    }
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
    pub type ResetControl = ureg::ReadWriteReg32<
        0,
        crate::por::regs::ResetControlReadVal,
        crate::por::regs::ResetControlWriteVal,
    >;
    pub type FpRunstall = ureg::ReadWriteReg32<
        0,
        crate::por::regs::FpRunstallReadVal,
        crate::por::regs::FpRunstallWriteVal,
    >;
    pub type DbgetmResetControl = ureg::ReadWriteReg32<
        0,
        crate::por::regs::DbgetmResetControlReadVal,
        crate::por::regs::DbgetmResetControlWriteVal,
    >;
    pub type ResetControl1 = ureg::ReadWriteReg32<
        0,
        crate::por::regs::ResetControl1ReadVal,
        crate::por::regs::ResetControl1WriteVal,
    >;
}
