// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from rng.xml

#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
#[derive(Clone, Copy)]
pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio> = ureg::RealMmio> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl RegisterBlock<ureg::RealMmio> {
    pub fn block() -> Self {
        unsafe { Self::new(0xa0300000 as *mut u32) }
    }
}
impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new(ptr: *mut u32) -> Self {
        Self {
            ptr,
            mmio: core::default::Default::default(),
        }
    }
}
impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
        Self { ptr, mmio }
    }
    /// Read value: [`rng_regs::regs::CtrlReadVal`]; Write value: [`rng_regs::regs::CtrlWriteVal`]
    #[inline(always)]
    pub fn ctrl(&self) -> ureg::RegRef<crate::rng_regs::meta::Ctrl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::DasEnReadVal`]; Write value: [`rng_regs::regs::DasEnWriteVal`]
    #[inline(always)]
    pub fn das_en(&self) -> ureg::RegRef<crate::rng_regs::meta::DasEn, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn das_data(&self) -> ureg::RegRef<crate::rng_regs::meta::DasData, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(8 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::StatusReadVal`]; Write value: [`rng_regs::regs::StatusWriteVal`]
    #[inline(always)]
    pub fn status(&self) -> ureg::RegRef<crate::rng_regs::meta::Status, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xc / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn reseed_interval(&self) -> ureg::RegRef<crate::rng_regs::meta::ReseedInterval, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x10 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::GenerateIntervalReadVal`]; Write value: [`rng_regs::regs::GenerateIntervalWriteVal`]
    #[inline(always)]
    pub fn generate_interval(
        &self,
    ) -> ureg::RegRef<crate::rng_regs::meta::GenerateInterval, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x14 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn reseed_cnt(&self) -> ureg::RegRef<crate::rng_regs::meta::ReseedCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x18 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::GenerateCntReadVal`]; Write value: [`rng_regs::regs::GenerateCntWriteVal`]
    #[inline(always)]
    pub fn generate_cnt(&self) -> ureg::RegRef<crate::rng_regs::meta::GenerateCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x1c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::DrbgStatusReadVal`]; Write value: [`rng_regs::regs::DrbgStatusWriteVal`]
    #[inline(always)]
    pub fn drbg_status(&self) -> ureg::RegRef<crate::rng_regs::meta::DrbgStatus, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x20 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::ClkDivMsbReadVal`]; Write value: [`rng_regs::regs::ClkDivMsbWriteVal`]
    #[inline(always)]
    pub fn clk_div_msb(&self) -> ureg::RegRef<crate::rng_regs::meta::ClkDivMsb, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x24 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::RepcntCutoffReadVal`]; Write value: [`rng_regs::regs::RepcntCutoffWriteVal`]
    #[inline(always)]
    pub fn repcnt_cutoff(&self) -> ureg::RegRef<crate::rng_regs::meta::RepcntCutoff, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x30 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::AptCutoffReadVal`]; Write value: [`rng_regs::regs::AptCutoffWriteVal`]
    #[inline(always)]
    pub fn apt_cutoff(&self) -> ureg::RegRef<crate::rng_regs::meta::AptCutoff, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x34 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`rng_regs::regs::ChisqCutoffReadVal`]; Write value: [`rng_regs::regs::ChisqCutoffWriteVal`]
    #[inline(always)]
    pub fn chisq_cutoff(&self) -> ureg::RegRef<crate::rng_regs::meta::ChisqCutoff, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x38 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_0(&self) -> ureg::RegRef<crate::rng_regs::meta::K0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x100 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_1(&self) -> ureg::RegRef<crate::rng_regs::meta::K1, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x104 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_2(&self) -> ureg::RegRef<crate::rng_regs::meta::K2, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x108 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_3(&self) -> ureg::RegRef<crate::rng_regs::meta::K3, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x10c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_4(&self) -> ureg::RegRef<crate::rng_regs::meta::K4, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x110 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_5(&self) -> ureg::RegRef<crate::rng_regs::meta::K5, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x114 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_6(&self) -> ureg::RegRef<crate::rng_regs::meta::K6, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x118 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_7(&self) -> ureg::RegRef<crate::rng_regs::meta::K7, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x11c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_8(&self) -> ureg::RegRef<crate::rng_regs::meta::K8, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x120 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_9(&self) -> ureg::RegRef<crate::rng_regs::meta::K9, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x124 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_10(&self) -> ureg::RegRef<crate::rng_regs::meta::K10, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x128 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_11(&self) -> ureg::RegRef<crate::rng_regs::meta::K11, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x12c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_12(&self) -> ureg::RegRef<crate::rng_regs::meta::K12, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x130 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_13(&self) -> ureg::RegRef<crate::rng_regs::meta::K13, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x134 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_14(&self) -> ureg::RegRef<crate::rng_regs::meta::K14, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x138 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn k_15(&self) -> ureg::RegRef<crate::rng_regs::meta::K15, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x13c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_0(&self) -> ureg::RegRef<crate::rng_regs::meta::V0, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x140 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_1(&self) -> ureg::RegRef<crate::rng_regs::meta::V1, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x144 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_2(&self) -> ureg::RegRef<crate::rng_regs::meta::V2, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x148 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_3(&self) -> ureg::RegRef<crate::rng_regs::meta::V3, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x14c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_4(&self) -> ureg::RegRef<crate::rng_regs::meta::V4, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x150 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_5(&self) -> ureg::RegRef<crate::rng_regs::meta::V5, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x154 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_6(&self) -> ureg::RegRef<crate::rng_regs::meta::V6, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x158 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_7(&self) -> ureg::RegRef<crate::rng_regs::meta::V7, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x15c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_8(&self) -> ureg::RegRef<crate::rng_regs::meta::V8, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x160 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_9(&self) -> ureg::RegRef<crate::rng_regs::meta::V9, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x164 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_10(&self) -> ureg::RegRef<crate::rng_regs::meta::V10, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x168 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_11(&self) -> ureg::RegRef<crate::rng_regs::meta::V11, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x16c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_12(&self) -> ureg::RegRef<crate::rng_regs::meta::V12, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x170 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_13(&self) -> ureg::RegRef<crate::rng_regs::meta::V13, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x174 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_14(&self) -> ureg::RegRef<crate::rng_regs::meta::V14, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x178 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn v_15(&self) -> ureg::RegRef<crate::rng_regs::meta::V15, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x17c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn rn_data(&self) -> ureg::RegRef<crate::rng_regs::meta::RnData, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x200 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn fwin_data(&self) -> ureg::RegRef<crate::rng_regs::meta::FwinData, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x400 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn fwout_data(&self) -> ureg::RegRef<crate::rng_regs::meta::FwoutData, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x600 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
}
pub mod regs {
    //! Types that represent the values held by registers.
    #[derive(Clone, Copy)]
    pub struct AptCutoffReadVal(u32);
    impl AptCutoffReadVal {
        /// apt_cutoff
        ///
        /// Programmable cut off value for the adaptive proportion test.
        #[inline(always)]
        pub fn reg(&self) -> u32 {
            (self.0 >> 0) & 0x3ff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> AptCutoffWriteVal {
            AptCutoffWriteVal(self.0)
        }
    }
    impl From<u32> for AptCutoffReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<AptCutoffReadVal> for u32 {
        fn from(val: AptCutoffReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct AptCutoffWriteVal(u32);
    impl AptCutoffWriteVal {
        /// apt_cutoff
        ///
        /// Programmable cut off value for the adaptive proportion test.
        #[inline(always)]
        pub fn reg(self, val: u32) -> Self {
            Self((self.0 & !(0x3ff << 0)) | ((val & 0x3ff) << 0))
        }
    }
    impl From<u32> for AptCutoffWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<AptCutoffWriteVal> for u32 {
        fn from(val: AptCutoffWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ChisqCutoffReadVal(u32);
    impl ChisqCutoffReadVal {
        /// chisq_cutoff
        ///
        /// Programmable cut off value for the chi square entropy health test.
        #[inline(always)]
        pub fn reg(&self) -> u32 {
            (self.0 >> 0) & 0x3ff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ChisqCutoffWriteVal {
            ChisqCutoffWriteVal(self.0)
        }
    }
    impl From<u32> for ChisqCutoffReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ChisqCutoffReadVal> for u32 {
        fn from(val: ChisqCutoffReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ChisqCutoffWriteVal(u32);
    impl ChisqCutoffWriteVal {
        /// chisq_cutoff
        ///
        /// Programmable cut off value for the chi square entropy health test.
        #[inline(always)]
        pub fn reg(self, val: u32) -> Self {
            Self((self.0 & !(0x3ff << 0)) | ((val & 0x3ff) << 0))
        }
    }
    impl From<u32> for ChisqCutoffWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ChisqCutoffWriteVal> for u32 {
        fn from(val: ChisqCutoffWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ClkDivMsbReadVal(u32);
    impl ClkDivMsbReadVal {
        /// clk_div_msb
        ///
        /// This field specifies the 2 most significant bits for the clock divider ratio for the TRBG and appends it to the 8 bits from the ctrl.clk_div field. The TRBG generates a new bit every time its internal counter reaches the {clk_div_msb[1:0], ctrl.clk_div[7:0], 8'b00} value.
        #[inline(always)]
        pub fn clk_div_msb(&self) -> u32 {
            (self.0 >> 0) & 3
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> ClkDivMsbWriteVal {
            ClkDivMsbWriteVal(self.0)
        }
    }
    impl From<u32> for ClkDivMsbReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ClkDivMsbReadVal> for u32 {
        fn from(val: ClkDivMsbReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ClkDivMsbWriteVal(u32);
    impl ClkDivMsbWriteVal {
        /// clk_div_msb
        ///
        /// This field specifies the 2 most significant bits for the clock divider ratio for the TRBG and appends it to the 8 bits from the ctrl.clk_div field. The TRBG generates a new bit every time its internal counter reaches the {clk_div_msb[1:0], ctrl.clk_div[7:0], 8'b00} value.
        #[inline(always)]
        pub fn clk_div_msb(self, val: u32) -> Self {
            Self((self.0 & !(3 << 0)) | ((val & 3) << 0))
        }
    }
    impl From<u32> for ClkDivMsbWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ClkDivMsbWriteVal> for u32 {
        fn from(val: ClkDivMsbWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct CtrlReadVal(u32);
    impl CtrlReadVal {
        /// clk_div
        ///
        /// This field specifies the lower 8 bits for the clock divider ratio for the TRBG. The TRBG generates a new bit every time its internal counter reaches the {clk_div_msb[1:0], ctrl.clk_div[7:0], 8'b00} value. The clk_div_msb value is appended to this register.
        #[inline(always)]
        pub fn clk_div(&self) -> u32 {
            (self.0 >> 0) & 0xff
        }
        /// enable
        ///
        /// This field enables the RNG block. It must be written to a 1 early on during boot to enable the rng.
        #[inline(always)]
        pub fn enable(&self) -> bool {
            ((self.0 >> 8) & 1) != 0
        }
        /// FW_mode
        ///
        /// Asserting this bit puts the DRBG in FW mode, where the inputs and outputs are to/from the FW FIFOs. When this bit toggles, the FW FIFOs and DRBG states are cleared. Switch to FW mode to perform DRBG tests and for CCS ECC key generation.
        #[inline(always)]
        pub fn fw_mode(&self) -> bool {
            ((self.0 >> 9) & 1) != 0
        }
        /// DRBG_instantiate
        ///
        /// When asserted with DRBG in FW mode, and FWIN_FIFO is full, perform an instantiate function.
        #[inline(always)]
        pub fn drbg_instantiate(&self) -> bool {
            ((self.0 >> 10) & 1) != 0
        }
        /// DRBG_generate
        ///
        /// When asserted with DRBG in FW mode, and DRBG is instantiated, perform generate functions to fill FWOUT_FIFO.
        #[inline(always)]
        pub fn drbg_generate(&self) -> bool {
            ((self.0 >> 11) & 1) != 0
        }
        /// DRBG_uninstantiate
        ///
        /// When asserted with DRBG in FW mode, clear DRBG states. This bit takes precedence over the DRBG_instantiate and DRBG_generate bits.
        #[inline(always)]
        pub fn drbg_uninstantiate(&self) -> bool {
            ((self.0 >> 12) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> CtrlWriteVal {
            CtrlWriteVal(self.0)
        }
    }
    impl From<u32> for CtrlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<CtrlReadVal> for u32 {
        fn from(val: CtrlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct CtrlWriteVal(u32);
    impl CtrlWriteVal {
        /// clk_div
        ///
        /// This field specifies the lower 8 bits for the clock divider ratio for the TRBG. The TRBG generates a new bit every time its internal counter reaches the {clk_div_msb[1:0], ctrl.clk_div[7:0], 8'b00} value. The clk_div_msb value is appended to this register.
        #[inline(always)]
        pub fn clk_div(self, val: u32) -> Self {
            Self((self.0 & !(0xff << 0)) | ((val & 0xff) << 0))
        }
        /// enable
        ///
        /// This field enables the RNG block. It must be written to a 1 early on during boot to enable the rng.
        #[inline(always)]
        pub fn enable(self, val: bool) -> Self {
            Self((self.0 & !(1 << 8)) | (u32::from(val) << 8))
        }
        /// FW_mode
        ///
        /// Asserting this bit puts the DRBG in FW mode, where the inputs and outputs are to/from the FW FIFOs. When this bit toggles, the FW FIFOs and DRBG states are cleared. Switch to FW mode to perform DRBG tests and for CCS ECC key generation.
        #[inline(always)]
        pub fn fw_mode(self, val: bool) -> Self {
            Self((self.0 & !(1 << 9)) | (u32::from(val) << 9))
        }
        /// DRBG_instantiate
        ///
        /// When asserted with DRBG in FW mode, and FWIN_FIFO is full, perform an instantiate function.
        #[inline(always)]
        pub fn drbg_instantiate(self, val: bool) -> Self {
            Self((self.0 & !(1 << 10)) | (u32::from(val) << 10))
        }
        /// DRBG_generate
        ///
        /// When asserted with DRBG in FW mode, and DRBG is instantiated, perform generate functions to fill FWOUT_FIFO.
        #[inline(always)]
        pub fn drbg_generate(self, val: bool) -> Self {
            Self((self.0 & !(1 << 11)) | (u32::from(val) << 11))
        }
        /// DRBG_uninstantiate
        ///
        /// When asserted with DRBG in FW mode, clear DRBG states. This bit takes precedence over the DRBG_instantiate and DRBG_generate bits.
        #[inline(always)]
        pub fn drbg_uninstantiate(self, val: bool) -> Self {
            Self((self.0 & !(1 << 12)) | (u32::from(val) << 12))
        }
    }
    impl From<u32> for CtrlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<CtrlWriteVal> for u32 {
        fn from(val: CtrlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct DasEnReadVal(u32);
    impl DasEnReadVal {
        /// das_en
        ///
        /// This field enables the DAS interface for accessing the the TRBG directly. DAS is enabled if das_en==8'hda.
        #[inline(always)]
        pub fn reg(&self) -> u32 {
            (self.0 >> 0) & 0xff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> DasEnWriteVal {
            DasEnWriteVal(self.0)
        }
    }
    impl From<u32> for DasEnReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<DasEnReadVal> for u32 {
        fn from(val: DasEnReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct DasEnWriteVal(u32);
    impl DasEnWriteVal {
        /// das_en
        ///
        /// This field enables the DAS interface for accessing the the TRBG directly. DAS is enabled if das_en==8'hda.
        #[inline(always)]
        pub fn reg(self, val: u32) -> Self {
            Self((self.0 & !(0xff << 0)) | ((val & 0xff) << 0))
        }
    }
    impl From<u32> for DasEnWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<DasEnWriteVal> for u32 {
        fn from(val: DasEnWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct DrbgStatusReadVal(u32);
    impl DrbgStatusReadVal {
        /// state
        ///
        /// 0: Idle
        /// 1: Instantiate
        /// 2: Generate HMAC Operation
        /// 3: Generate Fill FIFO
        /// 3: Generate HMAC Update
        /// 5: Reseed Wait
        /// 6: Reseed
        /// 7: DRBG Error
        #[inline(always)]
        pub fn reg(&self) -> u32 {
            (self.0 >> 0) & 7
        }
    }
    impl From<u32> for DrbgStatusReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<DrbgStatusReadVal> for u32 {
        fn from(val: DrbgStatusReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct GenerateCntReadVal(u32);
    impl GenerateCntReadVal {
        /// generate_cnt
        ///
        /// Current generate counter value.
        #[inline(always)]
        pub fn reg(&self) -> u32 {
            (self.0 >> 0) & 0x3ff
        }
    }
    impl From<u32> for GenerateCntReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<GenerateCntReadVal> for u32 {
        fn from(val: GenerateCntReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct GenerateIntervalReadVal(u32);
    impl GenerateIntervalReadVal {
        /// generate_interval
        ///
        /// Programmable generate interval, determines how many generate cycles before the DRBG is updated with a new K value
        #[inline(always)]
        pub fn reg(&self) -> u32 {
            (self.0 >> 0) & 0x3ff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> GenerateIntervalWriteVal {
            GenerateIntervalWriteVal(self.0)
        }
    }
    impl From<u32> for GenerateIntervalReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<GenerateIntervalReadVal> for u32 {
        fn from(val: GenerateIntervalReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct GenerateIntervalWriteVal(u32);
    impl GenerateIntervalWriteVal {
        /// generate_interval
        ///
        /// Programmable generate interval, determines how many generate cycles before the DRBG is updated with a new K value
        #[inline(always)]
        pub fn reg(self, val: u32) -> Self {
            Self((self.0 & !(0x3ff << 0)) | ((val & 0x3ff) << 0))
        }
    }
    impl From<u32> for GenerateIntervalWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<GenerateIntervalWriteVal> for u32 {
        fn from(val: GenerateIntervalWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct RepcntCutoffReadVal(u32);
    impl RepcntCutoffReadVal {
        /// repcnt_cutoff
        ///
        /// Programmable cut off value for the repetition count health test.
        #[inline(always)]
        pub fn reg(&self) -> u32 {
            (self.0 >> 0) & 0x3ff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> RepcntCutoffWriteVal {
            RepcntCutoffWriteVal(self.0)
        }
    }
    impl From<u32> for RepcntCutoffReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<RepcntCutoffReadVal> for u32 {
        fn from(val: RepcntCutoffReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct RepcntCutoffWriteVal(u32);
    impl RepcntCutoffWriteVal {
        /// repcnt_cutoff
        ///
        /// Programmable cut off value for the repetition count health test.
        #[inline(always)]
        pub fn reg(self, val: u32) -> Self {
            Self((self.0 & !(0x3ff << 0)) | ((val & 0x3ff) << 0))
        }
    }
    impl From<u32> for RepcntCutoffWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<RepcntCutoffWriteVal> for u32 {
        fn from(val: RepcntCutoffWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct StatusReadVal(u32);
    impl StatusReadVal {
        /// busy
        ///
        /// Indicating that the RNG does not have valid data in RN_DATA register. Must make sure this bit is '0' before reading from the RN_DATA while in FW mode or else will receive a SLVERR response. While not in FW mode, the rn_data read transaction will be extended until data is available
        #[inline(always)]
        pub fn busy(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// repcnt_fault_error
        ///
        /// Indicating that the TRBG repitition count test has failed.
        #[inline(always)]
        pub fn repcnt_fault_error(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// apt_fault_error
        ///
        /// Indicating that the TRBG adaptive proportion test has failed.
        #[inline(always)]
        pub fn apt_fault_error(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// chisq_fault_error
        ///
        /// Indicating that the TRBG chi square test has failed.
        #[inline(always)]
        pub fn chisq_fault_error(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// rbg_fault_error
        ///
        /// Indicating that the TRBG has detected an internal trbg state machine fault.
        #[inline(always)]
        pub fn rbg_fault_error(&self) -> bool {
            ((self.0 >> 4) & 1) != 0
        }
        /// drbg_fault_error
        ///
        /// Indicating that the DRBG has detected some anomoly,
        /// it is either an hssha fault or an internal drbg state machine fault.
        #[inline(always)]
        pub fn drbg_fault_error(&self) -> bool {
            ((self.0 >> 5) & 1) != 0
        }
        /// drbg_inst_busy
        ///
        /// 1 indicates that the DRBG is currently performing an instantiate operation.
        #[inline(always)]
        pub fn drbg_inst_busy(&self) -> bool {
            ((self.0 >> 6) & 1) != 0
        }
        /// drbg_reseed_busy
        ///
        /// 1 indicates that the DRBG is currently performing a reseed operation.
        #[inline(always)]
        pub fn drbg_reseed_busy(&self) -> bool {
            ((self.0 >> 7) & 1) != 0
        }
        /// entropy_fifo_full
        ///
        /// 1 indicates that both entropy fifos (FIFO1 and the EXT_FIFO) are full
        #[inline(always)]
        pub fn entropy_fifo_full(&self) -> bool {
            ((self.0 >> 8) & 1) != 0
        }
        /// entropy_fifo_read
        ///
        /// 1 indicates that data from the entropy FIFOs are being read. The RNG cannot switch to FW mode during this stage.
        #[inline(always)]
        pub fn entropy_fifo_read(&self) -> bool {
            ((self.0 >> 9) & 1) != 0
        }
    }
    impl From<u32> for StatusReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<StatusReadVal> for u32 {
        fn from(val: StatusReadVal) -> u32 {
            val.0
        }
    }
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
    pub type Ctrl = ureg::ReadWriteReg32<
        0,
        crate::rng_regs::regs::CtrlReadVal,
        crate::rng_regs::regs::CtrlWriteVal,
    >;
    pub type DasEn = ureg::ReadWriteReg32<
        0,
        crate::rng_regs::regs::DasEnReadVal,
        crate::rng_regs::regs::DasEnWriteVal,
    >;
    pub type DasData = ureg::ReadOnlyReg32<u32>;
    pub type Status = ureg::ReadOnlyReg32<crate::rng_regs::regs::StatusReadVal>;
    pub type ReseedInterval = ureg::ReadWriteReg32<0, u32, u32>;
    pub type GenerateInterval = ureg::ReadWriteReg32<
        0,
        crate::rng_regs::regs::GenerateIntervalReadVal,
        crate::rng_regs::regs::GenerateIntervalWriteVal,
    >;
    pub type ReseedCnt = ureg::ReadOnlyReg32<u32>;
    pub type GenerateCnt = ureg::ReadOnlyReg32<crate::rng_regs::regs::GenerateCntReadVal>;
    pub type DrbgStatus = ureg::ReadOnlyReg32<crate::rng_regs::regs::DrbgStatusReadVal>;
    pub type ClkDivMsb = ureg::ReadWriteReg32<
        0,
        crate::rng_regs::regs::ClkDivMsbReadVal,
        crate::rng_regs::regs::ClkDivMsbWriteVal,
    >;
    pub type RepcntCutoff = ureg::ReadWriteReg32<
        0,
        crate::rng_regs::regs::RepcntCutoffReadVal,
        crate::rng_regs::regs::RepcntCutoffWriteVal,
    >;
    pub type AptCutoff = ureg::ReadWriteReg32<
        0,
        crate::rng_regs::regs::AptCutoffReadVal,
        crate::rng_regs::regs::AptCutoffWriteVal,
    >;
    pub type ChisqCutoff = ureg::ReadWriteReg32<
        0,
        crate::rng_regs::regs::ChisqCutoffReadVal,
        crate::rng_regs::regs::ChisqCutoffWriteVal,
    >;
    pub type K0 = ureg::ReadOnlyReg32<u32>;
    pub type K1 = ureg::ReadOnlyReg32<u32>;
    pub type K2 = ureg::ReadOnlyReg32<u32>;
    pub type K3 = ureg::ReadOnlyReg32<u32>;
    pub type K4 = ureg::ReadOnlyReg32<u32>;
    pub type K5 = ureg::ReadOnlyReg32<u32>;
    pub type K6 = ureg::ReadOnlyReg32<u32>;
    pub type K7 = ureg::ReadOnlyReg32<u32>;
    pub type K8 = ureg::ReadOnlyReg32<u32>;
    pub type K9 = ureg::ReadOnlyReg32<u32>;
    pub type K10 = ureg::ReadOnlyReg32<u32>;
    pub type K11 = ureg::ReadOnlyReg32<u32>;
    pub type K12 = ureg::ReadOnlyReg32<u32>;
    pub type K13 = ureg::ReadOnlyReg32<u32>;
    pub type K14 = ureg::ReadOnlyReg32<u32>;
    pub type K15 = ureg::ReadOnlyReg32<u32>;
    pub type V0 = ureg::ReadOnlyReg32<u32>;
    pub type V1 = ureg::ReadOnlyReg32<u32>;
    pub type V2 = ureg::ReadOnlyReg32<u32>;
    pub type V3 = ureg::ReadOnlyReg32<u32>;
    pub type V4 = ureg::ReadOnlyReg32<u32>;
    pub type V5 = ureg::ReadOnlyReg32<u32>;
    pub type V6 = ureg::ReadOnlyReg32<u32>;
    pub type V7 = ureg::ReadOnlyReg32<u32>;
    pub type V8 = ureg::ReadOnlyReg32<u32>;
    pub type V9 = ureg::ReadOnlyReg32<u32>;
    pub type V10 = ureg::ReadOnlyReg32<u32>;
    pub type V11 = ureg::ReadOnlyReg32<u32>;
    pub type V12 = ureg::ReadOnlyReg32<u32>;
    pub type V13 = ureg::ReadOnlyReg32<u32>;
    pub type V14 = ureg::ReadOnlyReg32<u32>;
    pub type V15 = ureg::ReadOnlyReg32<u32>;
    pub type RnData = ureg::ReadOnlyReg32<u32>;
    pub type FwinData = ureg::WriteOnlyReg32<0, u32>;
    pub type FwoutData = ureg::ReadOnlyReg32<u32>;
}
