// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from hssha.xml

#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
#[derive(Clone, Copy)]
pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio> = ureg::RealMmio> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl RegisterBlock<ureg::RealMmio> {
    pub fn block() -> Self {
        unsafe { Self::new(0xa0400000 as *mut u32) }
    }
}
impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new(ptr: *mut u32) -> Self {
        Self {
            ptr,
            mmio: core::default::Default::default(),
        }
    }
}
impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
        Self { ptr, mmio }
    }
    /// SHA Command
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn sha_cmd(&self) -> ureg::RegRef<crate::sha_regs::meta::ShaCmd, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// SHA Status
    ///
    /// Read value: [`sha_regs::regs::ShaStatusReadVal`]; Write value: [`sha_regs::regs::ShaStatusWriteVal`]
    #[inline(always)]
    pub fn sha_status(&self) -> ureg::RegRef<crate::sha_regs::meta::ShaStatus, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
}
pub mod regs {
    //! Types that represent the values held by registers.
    #[derive(Clone, Copy)]
    pub struct ShaStatusReadVal(u32);
    impl ShaStatusReadVal {
        /// Busy
        ///
        /// Indicates the engine is currently executing a command.
        #[inline(always)]
        pub fn busy(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Complete
        ///
        /// Indicates the engine has successfully finished the last command. This bit is mutually exclusive from the ERROR_* bits. This bit must be cleared by a read to cause engine=IDLE.
        #[inline(always)]
        pub fn complete(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Command Error
        ///
        /// Indicates the engine is unable to decode the command structure pointed to by the SHA_CMD.CMD_PTR value. This may be due to an illegal command or a malformed argument.
        #[inline(always)]
        pub fn error_cmd(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Bus Error
        ///
        /// Indicates the engine encountered a bus error during execution of the last command.
        #[inline(always)]
        pub fn error_bus(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// Fault Error
        ///
        /// Indicates the engine detected an internal fault during execution of the last command.
        #[inline(always)]
        pub fn error_fault(&self) -> bool {
            ((self.0 >> 4) & 1) != 0
        }
        /// Not Owner
        ///
        /// Indicates the read requestor is not the owner of the currently executing command. Will never be set if the engine is idle.
        #[inline(always)]
        pub fn not_owner(&self) -> bool {
            ((self.0 >> 5) & 1) != 0
        }
        /// Digest Match
        ///
        /// Indicates the reference digest matched the computed digest for last command.
        #[inline(always)]
        pub fn digest_match(&self) -> bool {
            ((self.0 >> 6) & 1) != 0
        }
        /// Reserved
        ///
        /// Reserved - unused bits.
        #[inline(always)]
        pub fn reserved(&self) -> u32 {
            (self.0 >> 7) & 0x1ffffff
        }
    }
    impl From<u32> for ShaStatusReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ShaStatusReadVal> for u32 {
        fn from(val: ShaStatusReadVal) -> u32 {
            val.0
        }
    }
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
    pub type ShaCmd = ureg::ReadWriteReg32<0, u32, u32>;
    pub type ShaStatus = ureg::ReadOnlyReg32<crate::sha_regs::regs::ShaStatusReadVal>;
}
