// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from mcr-cp-reg.xml

#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
#[derive(Clone, Copy)]
pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio> = ureg::RealMmio> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl RegisterBlock<ureg::RealMmio> {
    pub fn block() -> Self {
        unsafe { Self::new(0xb0005000 as *mut u32) }
    }
}
impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new(ptr: *mut u32) -> Self {
        Self {
            ptr,
            mmio: core::default::Default::default(),
        }
    }
}
impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
        Self { ptr, mmio }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timer_lo(&self) -> ureg::RegRef<crate::tcon::meta::TimerLo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timer_hi(&self) -> ureg::RegRef<crate::tcon::meta::TimerHi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`tcon::regs::WatchdogCtrlReadVal`]; Write value: [`tcon::regs::WatchdogCtrlWriteVal`]
    #[inline(always)]
    pub fn watchdog_ctrl(&self) -> ureg::RegRef<crate::tcon::meta::WatchdogCtrl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(8 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn watchdog_cnt(&self) -> ureg::RegRef<crate::tcon::meta::WatchdogCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xc / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`tcon::regs::WakeupCtrlReadVal`]; Write value: [`tcon::regs::WakeupCtrlWriteVal`]
    #[inline(always)]
    pub fn wakeup_ctrl(&self) -> ureg::RegRef<crate::tcon::meta::WakeupCtrl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x10 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn wakeup0_cnt(&self) -> ureg::RegRef<crate::tcon::meta::Wakeup0Cnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x14 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn wakeup1_cnt(&self) -> ureg::RegRef<crate::tcon::meta::Wakeup1Cnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x18 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`tcon::regs::TimestampCtlReadVal`]; Write value: [`tcon::regs::TimestampCtlWriteVal`]
    #[inline(always)]
    pub fn timestamp_ctl(&self) -> ureg::RegRef<crate::tcon::meta::TimestampCtl, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x3c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp0_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp0CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x40 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp0_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp0Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x44 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp0_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp0Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x48 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp1_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp1CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x4c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp1_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp1Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x50 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp1_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp1Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x54 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp2_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp2CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x58 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp2_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp2Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x5c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp2_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp2Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x60 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp3_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp3CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x64 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp3_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp3Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x68 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp3_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp3Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x6c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp4_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp4CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x70 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp4_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp4Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x74 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp4_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp4Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x78 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp5_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp5CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x7c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp5_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp5Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x80 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp5_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp5Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x84 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp6_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp6CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x88 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp6_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp6Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x8c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp6_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp6Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x90 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp7_cycle_cnt(
        &self,
    ) -> ureg::RegRef<crate::tcon::meta::Timestamp7CycleCnt, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x94 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp7_lo(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp7Lo, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x98 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn timestamp7_hi(&self) -> ureg::RegRef<crate::tcon::meta::Timestamp7Hi, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x9c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`tcon::regs::DebugReadVal`]; Write value: [`tcon::regs::DebugWriteVal`]
    #[inline(always)]
    pub fn debug(&self) -> ureg::RegRef<crate::tcon::meta::Debug, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xa0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
}
pub mod regs {
    //! Types that represent the values held by registers.
    #[derive(Clone, Copy)]
    pub struct DebugReadVal(u32);
    impl DebugReadVal {
        /// debug bus sel for [27:0]
        #[inline(always)]
        pub fn debug_bus_sel(&self) -> u32 {
            (self.0 >> 30) & 3
        }
        /// Reserved.
        #[inline(always)]
        pub fn rsvd(&self) -> u32 {
            (self.0 >> 28) & 3
        }
        /// [31:30] = 2'h0, debug_bus = 0x0
        /// [31:30] = 2'h1, debug_bus = 0x555_aaaa
        /// [31:30] = 2'h2, debug_bus = 0xaaa_5555
        /// [31:30] = 2'h3, debug_bus =
        /// tcon_timer[11:0], event_do[7:0], 3'h0, tcon_wakeup2_intr_o[1:0], tcon_watchdog2_intr_o, access_wrd1, access_rdd1
        #[inline(always)]
        pub fn debug_bus(&self) -> u32 {
            (self.0 >> 0) & 0xfffffff
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> DebugWriteVal {
            DebugWriteVal(self.0)
        }
    }
    impl From<u32> for DebugReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<DebugReadVal> for u32 {
        fn from(val: DebugReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct DebugWriteVal(u32);
    impl DebugWriteVal {
        /// debug bus sel for [27:0]
        #[inline(always)]
        pub fn debug_bus_sel(self, val: u32) -> Self {
            Self((self.0 & !(3 << 30)) | ((val & 3) << 30))
        }
        /// Reserved.
        #[inline(always)]
        pub fn rsvd(self, val: u32) -> Self {
            Self((self.0 & !(3 << 28)) | ((val & 3) << 28))
        }
    }
    impl From<u32> for DebugWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<DebugWriteVal> for u32 {
        fn from(val: DebugWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct TimestampCtlReadVal(u32);
    impl TimestampCtlReadVal {
        /// Please don't overwrite the default value.
        #[inline(always)]
        pub fn rsvd(&self) -> u32 {
            (self.0 >> 8) & 0x3fffff
        }
        /// To clear the Time stamp. They are all r/w1c (write 1 and clear by itseft in next cycle).
        /// [7] ---- clear timestamp7
        /// [6] ---- clear timestamp6
        /// [5] ---- clear timestamp5
        /// [4] ---- clear timestamp4
        /// [3] ---- clear timestamp3
        /// [2] ---- clear timestamp2
        /// [1] ---- clear timestamp1
        /// [0] ---- clear timestamp0
        #[inline(always)]
        pub fn timestamp_clear(&self) -> u32 {
            (self.0 >> 0) & 0xff
        }
        /// TCON Soft reset
        /// 1'b0: no soft reset
        /// 1'b1: tcon soft reset exclude tcon_timer[62:0] and watchdog related registers. It is r/w1c (write 1 and clear by itseft in next cycle). Hw will reset tcon block after finish current APB write command.
        #[inline(always)]
        pub fn tcon_sreset(&self) -> bool {
            ((self.0 >> 30) & 1) != 0
        }
        /// Mask bit for APB interface perr.
        /// 1'b0: perr = 1'b1 for access an undefined address, or access is not 32 bits.
        /// 1'b1: perr = 1'b0 always.
        #[inline(always)]
        pub fn perr_mask(&self) -> bool {
            ((self.0 >> 31) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> TimestampCtlWriteVal {
            TimestampCtlWriteVal(self.0)
        }
    }
    impl From<u32> for TimestampCtlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<TimestampCtlReadVal> for u32 {
        fn from(val: TimestampCtlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct TimestampCtlWriteVal(u32);
    impl TimestampCtlWriteVal {
        /// Please don't overwrite the default value.
        #[inline(always)]
        pub fn rsvd(self, val: u32) -> Self {
            Self((self.0 & !(0x3fffff << 8)) | ((val & 0x3fffff) << 8))
        }
        /// To clear the Time stamp. They are all r/w1c (write 1 and clear by itseft in next cycle).
        /// [7] ---- clear timestamp7
        /// [6] ---- clear timestamp6
        /// [5] ---- clear timestamp5
        /// [4] ---- clear timestamp4
        /// [3] ---- clear timestamp3
        /// [2] ---- clear timestamp2
        /// [1] ---- clear timestamp1
        /// [0] ---- clear timestamp0
        #[inline(always)]
        pub fn timestamp_clear(self, val: u32) -> Self {
            Self((self.0 & !(0xff << 0)) | ((val & 0xff) << 0))
        }
        /// TCON Soft reset
        /// 1'b0: no soft reset
        /// 1'b1: tcon soft reset exclude tcon_timer[62:0] and watchdog related registers. It is r/w1c (write 1 and clear by itseft in next cycle). Hw will reset tcon block after finish current APB write command.
        #[inline(always)]
        pub fn tcon_sreset(self, val: bool) -> Self {
            Self((self.0 & !(1 << 30)) | (u32::from(val) << 30))
        }
        /// Mask bit for APB interface perr.
        /// 1'b0: perr = 1'b1 for access an undefined address, or access is not 32 bits.
        /// 1'b1: perr = 1'b0 always.
        #[inline(always)]
        pub fn perr_mask(self, val: bool) -> Self {
            Self((self.0 & !(1 << 31)) | (u32::from(val) << 31))
        }
    }
    impl From<u32> for TimestampCtlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<TimestampCtlWriteVal> for u32 {
        fn from(val: TimestampCtlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct WakeupCtrlReadVal(u32);
    impl WakeupCtrlReadVal {
        /// Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd0(&self) -> u32 {
            (self.0 >> 18) & 0x3fff
        }
        /// Enable periodic interrupt for wakeup1 and wakeup0.
        /// [17] = 1'b1 & [9] = 1'b0 ------ wakeup1 interrupt is periodic
        /// [16] = 1'b1 & [8] = 1'b0 ------ wakeup0 interrupt is periodic
        #[inline(always)]
        pub fn wkintr_rpt_en(&self) -> u32 {
            (self.0 >> 16) & 3
        }
        /// Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd1(&self) -> u32 {
            (self.0 >> 10) & 0x3f
        }
        /// Enable level interrupt for wakeup1 and wakeup0.
        /// 1'b0 ---- pulse output (1 cycle of 62.5Mhz)
        /// 1'b1 ---- level output
        /// [9] ------ for wakeup1 interrupt
        /// [8] ------ for wakeup0 interrupt
        #[inline(always)]
        pub fn wkintr_level_en(&self) -> u32 {
            (self.0 >> 8) & 3
        }
        /// Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd2(&self) -> u32 {
            (self.0 >> 2) & 0x3f
        }
        /// To enable the 2 wakeup counters
        /// [1] ---- enable wakeup1
        /// [0] ---- enable wakeup0
        #[inline(always)]
        pub fn wakeup_enable(&self) -> u32 {
            (self.0 >> 0) & 3
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> WakeupCtrlWriteVal {
            WakeupCtrlWriteVal(self.0)
        }
    }
    impl From<u32> for WakeupCtrlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<WakeupCtrlReadVal> for u32 {
        fn from(val: WakeupCtrlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct WakeupCtrlWriteVal(u32);
    impl WakeupCtrlWriteVal {
        /// Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd0(self, val: u32) -> Self {
            Self((self.0 & !(0x3fff << 18)) | ((val & 0x3fff) << 18))
        }
        /// Enable periodic interrupt for wakeup1 and wakeup0.
        /// [17] = 1'b1 & [9] = 1'b0 ------ wakeup1 interrupt is periodic
        /// [16] = 1'b1 & [8] = 1'b0 ------ wakeup0 interrupt is periodic
        #[inline(always)]
        pub fn wkintr_rpt_en(self, val: u32) -> Self {
            Self((self.0 & !(3 << 16)) | ((val & 3) << 16))
        }
        /// Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd1(self, val: u32) -> Self {
            Self((self.0 & !(0x3f << 10)) | ((val & 0x3f) << 10))
        }
        /// Enable level interrupt for wakeup1 and wakeup0.
        /// 1'b0 ---- pulse output (1 cycle of 62.5Mhz)
        /// 1'b1 ---- level output
        /// [9] ------ for wakeup1 interrupt
        /// [8] ------ for wakeup0 interrupt
        #[inline(always)]
        pub fn wkintr_level_en(self, val: u32) -> Self {
            Self((self.0 & !(3 << 8)) | ((val & 3) << 8))
        }
        /// Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd2(self, val: u32) -> Self {
            Self((self.0 & !(0x3f << 2)) | ((val & 0x3f) << 2))
        }
        /// To enable the 2 wakeup counters
        /// [1] ---- enable wakeup1
        /// [0] ---- enable wakeup0
        #[inline(always)]
        pub fn wakeup_enable(self, val: u32) -> Self {
            Self((self.0 & !(3 << 0)) | ((val & 3) << 0))
        }
    }
    impl From<u32> for WakeupCtrlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<WakeupCtrlWriteVal> for u32 {
        fn from(val: WakeupCtrlWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct WatchdogCtrlReadVal(u32);
    impl WatchdogCtrlReadVal {
        /// Reserved. Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd(&self) -> u32 {
            (self.0 >> 1) & 0x7fffffff
        }
        /// Enable watchdog,
        /// 1'b0 ---- disable the watchdog
        /// 1'b1 ---- enable the watchdog
        #[inline(always)]
        pub fn watchdog_enable(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        pub fn modify(self) -> WatchdogCtrlWriteVal {
            WatchdogCtrlWriteVal(self.0)
        }
    }
    impl From<u32> for WatchdogCtrlReadVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<WatchdogCtrlReadVal> for u32 {
        fn from(val: WatchdogCtrlReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct WatchdogCtrlWriteVal(u32);
    impl WatchdogCtrlWriteVal {
        /// Reserved. Please don't overwrite the default value
        #[inline(always)]
        pub fn rsvd(self, val: u32) -> Self {
            Self((self.0 & !(0x7fffffff << 1)) | ((val & 0x7fffffff) << 1))
        }
        /// Enable watchdog,
        /// 1'b0 ---- disable the watchdog
        /// 1'b1 ---- enable the watchdog
        #[inline(always)]
        pub fn watchdog_enable(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for WatchdogCtrlWriteVal {
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<WatchdogCtrlWriteVal> for u32 {
        fn from(val: WatchdogCtrlWriteVal) -> u32 {
            val.0
        }
    }
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
    pub type TimerLo = ureg::ReadOnlyReg32<u32>;
    pub type TimerHi = ureg::ReadOnlyReg32<u32>;
    pub type WatchdogCtrl = ureg::ReadWriteReg32<
        0,
        crate::tcon::regs::WatchdogCtrlReadVal,
        crate::tcon::regs::WatchdogCtrlWriteVal,
    >;
    pub type WatchdogCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type WakeupCtrl = ureg::ReadWriteReg32<
        0,
        crate::tcon::regs::WakeupCtrlReadVal,
        crate::tcon::regs::WakeupCtrlWriteVal,
    >;
    pub type Wakeup0Cnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Wakeup1Cnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type TimestampCtl = ureg::ReadWriteReg32<
        0,
        crate::tcon::regs::TimestampCtlReadVal,
        crate::tcon::regs::TimestampCtlWriteVal,
    >;
    pub type Timestamp0CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp0Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp0Hi = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp1CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp1Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp1Hi = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp2CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp2Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp2Hi = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp3CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp3Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp3Hi = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp4CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp4Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp4Hi = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp5CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp5Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp5Hi = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp6CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp6Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp6Hi = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp7CycleCnt = ureg::ReadWriteReg32<0, u32, u32>;
    pub type Timestamp7Lo = ureg::ReadOnlyReg32<u32>;
    pub type Timestamp7Hi = ureg::ReadOnlyReg32<u32>;
    pub type Debug =
        ureg::ReadWriteReg32<0, crate::tcon::regs::DebugReadVal, crate::tcon::regs::DebugWriteVal>;
}
