// Copyright (c) Microsoft Corporation. All rights reserved.
//
// generated by mcr-reg-gen from upka.xml

#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
pub mod regs {
    //! Types that represent the values held by registers.
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
}
pub mod upka_instance {
    #[derive(Clone, Copy)]
    pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio> = ureg::RealMmio> {
        ptr: *mut u32,
        mmio: TMmio,
    }
    impl RegisterBlock<ureg::RealMmio> {
        pub fn block() -> Self {
            unsafe { Self::new(0xc0000000 as *mut u32) }
        }
    }
    impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
        /// # Safety
        ///
        /// The caller is responsible for ensuring that ptr is valid for
        /// volatile reads and writes at any of the offsets in this register
        /// block.
        pub unsafe fn new(ptr: *mut u32) -> Self {
            Self {
                ptr,
                mmio: core::default::Default::default(),
            }
        }
    }
    impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
        /// # Safety
        ///
        /// The caller is responsible for ensuring that ptr is valid for
        /// volatile reads and writes at any of the offsets in this register
        /// block.
        pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
            Self { ptr, mmio }
        }
        pub fn at(&self, index: usize) -> UpkaInstanceBlock<&TMmio> {
            assert!(index < 16usize);
            UpkaInstanceBlock {
                ptr: unsafe {
                    self.ptr
                        .add((0 + index * 0x1000) / core::mem::size_of::<u32>())
                },
                mmio: core::borrow::Borrow::borrow(&self.mmio),
            }
        }
    }
    #[derive(Clone, Copy)]
    pub struct UpkaInstanceBlock<TMmio: ureg::Mmio> {
        ptr: *mut u32,
        mmio: TMmio,
    }
    impl<TMmio: ureg::Mmio> UpkaInstanceBlock<TMmio> {
        /// Command
        ///
        /// Read value: [`u32`]; Write value: [`u32`]
        #[inline(always)]
        pub fn command(
            &self,
        ) -> ureg::RegRef<crate::upka_regs::upka_instance::meta::UpkaInstanceCommand, &TMmio>
        {
            unsafe {
                ureg::RegRef::new_with_mmio(
                    self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                    core::borrow::Borrow::borrow(&self.mmio),
                )
            }
        }
        /// Status
        ///
        /// Read value: [`upka_regs::upka_instance::regs::StatusReadVal`]; Write value: [`upka_regs::upka_instance::regs::StatusWriteVal`]
        #[inline(always)]
        pub fn status(
            &self,
        ) -> ureg::RegRef<crate::upka_regs::upka_instance::meta::UpkaInstanceStatus, &TMmio>
        {
            unsafe {
                ureg::RegRef::new_with_mmio(
                    self.ptr.wrapping_add(4 / core::mem::size_of::<u32>()),
                    core::borrow::Borrow::borrow(&self.mmio),
                )
            }
        }
        /// ECC Count
        ///
        /// Read value: [`u32`]; Write value: [`u32`]
        #[inline(always)]
        pub fn ecc_count(
            &self,
        ) -> ureg::RegRef<crate::upka_regs::upka_instance::meta::UpkaInstanceEccCount, &TMmio>
        {
            unsafe {
                ureg::RegRef::new_with_mmio(
                    self.ptr.wrapping_add(8 / core::mem::size_of::<u32>()),
                    core::borrow::Borrow::borrow(&self.mmio),
                )
            }
        }
    }
    pub mod regs {
        //! Types that represent the values held by registers.
        #[derive(Clone, Copy)]
        pub struct StatusReadVal(u32);
        impl StatusReadVal {
            /// Busy
            ///
            /// Indicates the engine is in the middle of something
            #[inline(always)]
            pub fn busy(&self) -> bool {
                ((self.0 >> 0) & 1) != 0
            }
            /// Complete
            ///
            /// Indicates the engine has successfully finished the last command it accepted
            #[inline(always)]
            pub fn complete(&self) -> bool {
                ((self.0 >> 1) & 1) != 0
            }
            /// Error_cmd
            ///
            /// Indicates the engine is unable to decode the command structure successfully
            #[inline(always)]
            pub fn error_cmd(&self) -> bool {
                ((self.0 >> 2) & 1) != 0
            }
            /// Error_bus
            ///
            /// Indicates the engine has encountered an error when the engine tries to initiate a transaction on the AXI bus
            #[inline(always)]
            pub fn error_bus(&self) -> bool {
                ((self.0 >> 3) & 1) != 0
            }
            /// Error_fault
            ///
            /// Indicates the engine detected a fault in itself while it's working on the operation
            #[inline(always)]
            pub fn error_fault(&self) -> bool {
                ((self.0 >> 4) & 1) != 0
            }
            /// Not_owner
            ///
            /// Indicates the engine is/was working on a command initiated a different master than the one who is reading the status register
            #[inline(always)]
            pub fn not_owner(&self) -> bool {
                ((self.0 >> 5) & 1) != 0
            }
        }
        impl From<u32> for StatusReadVal {
            fn from(val: u32) -> Self {
                Self(val)
            }
        }
        impl From<StatusReadVal> for u32 {
            fn from(val: StatusReadVal) -> u32 {
                val.0
            }
        }
    }
    pub mod enums {
        //! Enumerations used by some register fields.
        pub mod selector {}
    }
    pub mod meta {
        //! Additional metadata needed by ureg.
        pub type UpkaInstanceCommand = ureg::ReadWriteReg32<0, u32, u32>;
        pub type UpkaInstanceStatus =
            ureg::ReadOnlyReg32<crate::upka_regs::upka_instance::regs::StatusReadVal>;
        pub type UpkaInstanceEccCount = ureg::ReadOnlyReg32<u32>;
    }
}
