// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef SELF_TEST_MANTICORE_H_
#define SELF_TEST_MANTICORE_H_

#include "crypto/aes_gcm.h"
#include "crypto/aes_key_wrap_interface.h"
#include "crypto/ecc.h"
#include "crypto/ecc_hw.h"
#include "crypto/hash.h"
#include "crypto/hkdf_interface.h"
#include "drivers/ccs_ksu_interface.h"
#include "fips/self_test_interface.h"
#include "status/manticore_module_id.h"


/**
 * Handler for running periodic self-tests against all Manticore cryptographic algorithms, except
 * for the hardware DRBG.
 *
 * The set of self-tests is broken into two separate groups to enable CMVP error injection for all
 * tests.
 */
struct self_test_manticore {
	struct self_test_interface base_first;			/**< Base API for running the first group of self-tests. */
	struct self_test_interface base_second;			/**< Base API for running the second group of self-tests. */
	const struct aes_gcm_engine *gcm;				/**< AES-GCM implementation to test. */
	const struct aes_key_wrap_interface *aes_kwp;	/**< AES key wrap with padding implementation to test. */
	const struct ccs_ksu_interface *ccs;			/**< CCS driver for testing HW implementations. */
	uint8_t key_slot;								/**< CCS key slot to use for self-tests. */
	const struct hkdf_interface *hkdf;				/**< HKDF implementation to test. */
	const struct ecc_hw *pka;						/**< PKA interface for ROM ECDSA testing. */
	const struct ecc_engine *ecc;					/**< ECDSA/ECDH implementation to test. */
	const struct hash_engine *hash;					/**< Hash implementation to use for ECDSA. */
};


int self_test_manticore_init (struct self_test_manticore *self_test,
	const struct aes_gcm_engine *gcm, const struct aes_key_wrap_interface *aes_kwp,
	const struct ccs_ksu_interface *ccs, uint8_t key_slot, const struct hkdf_interface *hkdf,
	const struct ecc_hw *pka, const struct ecc_engine *ecc, const struct hash_engine *hash);
void self_test_manticore_release (const struct self_test_manticore *self_test);


#define	SELF_TEST_MANTICORE_ERROR(code)			ROT_ERROR (MANTICORE_MODULE_SELF_TEST, code)

/**
 * Error codes that can be generated by the Manticore self-test execution.
 */
enum {
	SELF_TEST_MANTICORE_INVALID_ARGUMENT = SELF_TEST_MANTICORE_ERROR (0x00),	/**< Input parameter is null or not valid. */
	SELF_TEST_MANTICORE_NO_MEMORY = SELF_TEST_MANTICORE_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* SELF_TEST_MANTICORE_H_ */
