// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef IRQ_ERROR_H_
#define IRQ_ERROR_H_

#include "status/msft_module_id.h"


#define	IRQ_ERROR(code)		ROT_ERROR (MSFT_MODULE_IRQ, code)

/**
 * Error codes that can be generated by the interrupt driver.
 */
enum {
	IRQ_INVALID_ARGUMENT = IRQ_ERROR (0x00),	/**< Input parameter is null or not valid. */
	IRQ_NO_MEMORY = IRQ_ERROR (0x01),			/**< Memory allocation failed. */
	IRQ_ENTRY_NOT_ALIGNED = IRQ_ERROR (0x02),	/**< Trap entry point is not properly aligned. */
	IRQ_VECTOR_NOT_ALIGNED = IRQ_ERROR (0x03),	/**< Vector table is not properly aligned. */
	IRQ_ALREADY_REGISTERED = IRQ_ERROR (0x04),	/**< A handler is already registered for the interrupt. */
	IRQ_NOT_REGISTERED = IRQ_ERROR (0x05),		/**< Tried to unregister a handler that doesn't exist. */
	IRQ_MODE_UNSUPPORTED = IRQ_ERROR (0x06),	/**< The configured IRQ mode is incompatible with the feature API. */
	IRQ_STACK_NOT_ALIGNED = IRQ_ERROR (0x07),	/**< The target ISR stack is not properly aligned. */
	IRQ_STACK_ALREADY_SET = IRQ_ERROR (0x08),	/**< A stack has already been set for the trap handler. */
};


#endif	/* IRQ_ERROR_H_ */
