// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef CHECKPOINT_H_
#define CHECKPOINT_H_

#include <stdint.h>
#include "splibs/inc/spchkptdefs.h"
#include "status/msft_module_id.h"
#include "status/rot_status.h"


struct Creg_regs_chkpt_regs;	/* Defined in HSP register definition. */

/**
 * Driver interface for updating the hardware checkpoint block to ensure proper code execution.
 */
struct checkpoint {
	/**
	 * Apply the next configuration to the checkpoint hardware.
	 *
	 * If either argument is null, the request will be ignored.
	 *
	 * @param chkpt Driver to the checkpoint instance to update.
	 * @param config The configuration to write to the hardware.
	 */
	void (*set_config) (const struct checkpoint *chkpt, const HSP_CHKPT_CONFIG *config);

	/**
	 * Determine if a checkpoint configuration was successfully applied.  A failure to apply the
	 * configuration would indicate that the checkpoint conditions have not been met.
	 *
	 * @param chkpt Driver to the checkpoint instance to query.
	 * @param config The configuration to check the hardware against.
	 *
	 * @return 0 if the configuration was applied or an error code.
	 */
	int (*check_config) (const struct checkpoint *chkpt, const HSP_CHKPT_CONFIG *config);

	/**
	 * Lock the checkpoint hardware.  It will be unlocked based on the loaded configuration and FW
	 * execution.
	 *
	 * @param chkpt Driver to the checkpoint instance to update.  If this is null, the request will
	 * be ignored.
	 */
	void (*lock_hw) (const struct checkpoint *chkpt);

	/**
	 * Write a message to the checkpoint hardware.
	 *
	 * @param chkpt Driver to the checkpoint instance to update.  If this in null, the request will
	 * be ignored.
	 * @param message The message to write to the hardware.
	 */
	void (*write_message) (const struct checkpoint *chkpt, uint32_t message);

	struct Creg_regs_chkpt_regs *regs;	/**< Base address for the checkpoint registers. */
};


int checkpoint_init (struct checkpoint *chkpt, struct Creg_regs_chkpt_regs *regs);
void checkpoint_release (const struct checkpoint *chkpt);


#define	CHECKPOINT_ERROR(code)		ROT_ERROR (MSFT_MODULE_CHECKPOINT, code)

/**
 * Error codes that can be generated by the checkpoint hardware.
 */
enum {
	CHECKPOINT_INVALID_ARGUMENT = CHECKPOINT_ERROR (0x00),	/**< Input parameter is null or not valid. */
	CHECKPOINT_NO_MEMORY = CHECKPOINT_ERROR (0x01),			/**< Memory allocation failed. */
	CHECKPOINT_CHECK_CFG_FAIL = CHECKPOINT_ERROR (0x02),	/**< Error verifying the checkpoint configuration. */
	CHECKPOINT_DIGEST_MISMATCH = CHECKPOINT_ERROR (0x03),	/**< The digest at a checkpoint was not zero. */
	CHECKPOINT_FENCE_NOT_APPLIED = CHECKPOINT_ERROR (0x04),	/**< The required fencing was not applied. */
	CHECKPOINT_CTRL_NOT_APPLIED = CHECKPOINT_ERROR (0x05),	/**< The specified control was not applied. */

	/* Error codes >0x80 are reserved for reporting bits from the HW status register. */
};

/**
 * An error state is reported by the hardware.  The error code represents the status register
 * output.
 */
#define	CHECKPOINT_HW_ERROR(reg)	CHECKPOINT_ERROR (0x80 | (reg & 0x7f))


#endif	/* CHECKPOINT_H_ */
