// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef EXT_POWER_INTERFACE_H_
#define EXT_POWER_INTERFACE_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "status/msft_module_id.h"


/**
 * Driver to access external power of HSP fuse controller.
 */
struct ext_power_interface {
	/**
	 * external power up for fuse controller.
	 *
	 * @param power External power instance.
	 *
	 * @return 0 for success or an error code
	 */
	int (*power_up) (const struct ext_power_interface *power);

	/**
	 * external power down for fuse controller.
	 *
	 * @param power External power instance.
	 *
	 * @return 0 for success or an error code
	 */
	int (*power_down) (const struct ext_power_interface *power);
};


#define	EXT_POWER_ERROR(code) ROT_ERROR (MSFT_MODULE_EXT_POWER, code)

/**
 * Error codes that can be generated by a ext power.
 */
enum {
	EXT_POWER_INVALID_ARGUMENT = EXT_POWER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	EXT_POWER_NO_MEMORY = EXT_POWER_ERROR (0x01),			/**< Memory allocation failed. */
	EXT_POWER_UP_FAILED = EXT_POWER_ERROR (0x02),			/**< Power Up Failed. */
	EXT_POWER_DOWN_FAILED = EXT_POWER_ERROR (0x03),			/**< Power Down Failed. */
};


#endif	/* EXT_POWER_INTERFACE_H_ */
