// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_AES_H_
#define HSP_AES_H_

#include <stddef.h>
#include <stdint.h>
#include "platform_api.h"
#include "drivers/ccs_ksu_interface.h"
#include "splibs/inc/spcryptotypes.h"
#include "status/msft_module_id.h"
#include "trap/hsp_interrupt_handler.h"


/**
 * AES modes supported by the HSP AES engine.
 */
enum hsp_aes_mode {
	HSP_AES_MODE_ECB = 1,	/**< Electronic Code Book mode */
	HSP_AES_MODE_CBC = 2,	/**< Cipher Block Chaining mode */
	HSP_AES_MODE_CTR = 3,	/**< Counter mode */
	HSP_AES_MODE_CFB = 4,	/**< Cipher Feedback mode */
	HSP_AES_MODE_OFB = 5,	/**< Output FeedBack mode */
	HSP_AES_MODE_XTS = 6,	/**< XOR-Encrypt-XOR Tweakable Block Cipher with Ciphertext Stealing mode */
};

/**
 * Align a length to the AES block size (16 bytes).
 */
#define	HSP_AES_BLOCK_ALIGN(len)		((len) & ~(16 - 1))


/* Defined in HSP register definition. */
struct Aes_regs;
struct Creg_regs_creg_crypto_group;

/**
 * The command structure to use for issuing AES commands.  This structure must be stored in HSP
 * shared RAM for AES HW to be able to access it and must be allocated at a 32-bit aligned address.
 */
struct hsp_aes_command {
	uint32_t command_code;	/**< The command that should be executed. */
	uint32_t result;		/**< Pointer to the result generated by the command. */
	uint32_t byte_count;	/**< Number of bytes to process in this command. */
	uint32_t message;		/**< Address of the data for the operation. */
	uint32_t key;			/**< Address to the encryption key to use. */
	uint32_t init_vector;	/**< Address of the IV for the operation. */
};

/**
 * Memory structure in HSP shared SRAM that is required to be able to execute AES commands.  This
 * must be 32-bit aligned.
 */
struct hsp_aes_cmd_buffer {
	struct hsp_aes_command cmd;	/**< The command and arguments passed to the AES HW. */
	SP_MSG_128 iv;				/**< Input/output buffer for the encryption IV. */
};

/**
 * Variable context for an AES driver.
 */
struct hsp_aes_state {
	platform_mutex lock;		/**< Lock for synchronization. */
	platform_semaphore done;	/**< Semaphore indicating when a HW operation has completed. */
};

/**
 * Driver interface to the hardware AES engine within the HSP.
 */
struct hsp_aes {
	struct hsp_interrupt_handler base;	/**< Base interface for handling HW interrupts. */

	/**
	 * Encrypt data using the specified AES mode.
	 *
	 * @param aes The AES engine to use for the operation.
	 * @param mode Cipher mode to use for encryption.
	 * @param key KSU key slot that contains the encryption key.
	 * @param iv Initial vector for the encryption operation.  This will be ignored for ECB
	 * operations and can be null in that case.
	 * @param plaintext Buffer containing the data to encrypt.
	 * @param length Length of the data.  This must be aligned to the AES block size (16 bytes).
	 * @param ciphertext Output buffer for the encrypted data.  It can be the same as the plaintext
	 * buffer.
	 * @param out_length Length of the output buffer.  It must be at least the same size as the
	 * plaintext data.
	 * @param next_iv Optional output buffer for the IV that would be used to continue the
	 * encryption operation with additional data.  This allows encryption to be executed without
	 * having all the data available in memory at the same time.  This will always be ignored for
	 * ECB operations.
	 *
	 * @param 0 if the encryption completed successfully or an error code.
	 */
	int (*encrypt) (const struct hsp_aes *aes, enum hsp_aes_mode mode, uint8_t key,
		const SP_MSG_128 *iv, const uint8_t *plaintext, size_t length, uint8_t *ciphertext,
		size_t out_length, SP_MSG_128 *next_iv);

	/**
	 * Decrypt data using the specified AES mode.
	 *
	 * @param aes The AES engine to use for the operation.
	 * @param mode Cipher mode to use for decryption.
	 * @param key KSU key slot that contains the encryption key.
	 * @param iv Initial vector for the decryption operation.  This will be ignored for ECB
	 * operations and can be null in that case.
	 * @param ciphertext Buffer containing the data to decrypt.
	 * @param length Length of the data.  This must be aligned to the AES block size (16 bytes).
	 * @param plaintext Output buffer for the decrypted data.  It can be the same as the ciphertext
	 * buffer.
	 * @param out_length Length of the output buffer.  It must be at least the same size as the
	 * ciphertext data.
	 * @param next_iv Optional output buffer for the IV that would be used to continue the
	 * decryption operation with additional data.  This allows decryption to be executed without
	 * having all the data available in memory at the same time.  This will always be ignored for
	 * ECB operations.
	 *
	 * @param 0 if the decryption completed successfully or an error code.
	 */
	int (*decrypt) (const struct hsp_aes *aes, enum hsp_aes_mode mode, uint8_t key,
		const SP_MSG_128 *iv, const uint8_t *ciphertext, size_t length, uint8_t *plaintext,
		size_t out_length, SP_MSG_128 *next_iv);

	struct hsp_aes_state *state;				/**< Variable context for the driver instance. */
	struct Aes_regs *regs;						/**< Register interface to the AES HW. */
	struct Creg_regs_creg_crypto_group *irq;	/**< Register interface to AES interrupts. */
	struct hsp_aes_cmd_buffer *buffer;			/**< Memory location for the AES command structure. */
	uint8_t *msg_buffer;						/**< Input buffer for message data not in shared memory. */
	size_t max_msg;								/**< Size of the shared message buffer. */
	const struct ksu_key_slot *keys;			/**< Memory location where KSU keys are stored. */
	size_t key_slots;							/**< The number of key slots supported by the KSU. */

	/**
	 * Submit a command to the hardware for execution and block until the hardware has completed the
	 * request.
	 *
	 * @param aes The AES engine to use for command execution.
	 * @param error_code Error to return when the the command failure bit is set.
	 *
	 * @return 0 if the command was successfully executed or an error code.
	 */
	int (*execute_command) (const struct hsp_aes *aes, int error_code);
};


int hsp_aes_init_polling (struct hsp_aes *aes, struct hsp_aes_state *state, struct Aes_regs *regs,
	struct hsp_aes_cmd_buffer *cmd_buffer, uint8_t *msg_buffer, size_t buffer_length,
	const struct ksu_key_slot *key_buffer, size_t num_keys);
int hsp_aes_init_interrupt (struct hsp_aes *aes, struct hsp_aes_state *state, struct Aes_regs *regs,
	struct Creg_regs_creg_crypto_group *irq_regs, struct hsp_aes_cmd_buffer *cmd_buffer,
	uint8_t *msg_buffer, size_t buffer_length, const struct ksu_key_slot *key_buffer,
	size_t num_keys);
int hsp_aes_init_state (const struct hsp_aes *aes);
void hsp_aes_release (const struct hsp_aes *aes);

void hsp_aes_mark_as_in_use (const struct hsp_aes *aes);
void hsp_aes_mark_as_available (const struct hsp_aes *aes);

/* TODO:  This should be removed and replaced with common self-tests that operation on the AES
 * APIs.*/
int hsp_aes_run_self_test_aes256_cbc (const struct hsp_aes *aes,
	const struct ccs_ksu_interface *ccs, uint8_t key_slot);


#define	HSP_AES_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_AES, code)

/**
 * Error codes that can be generated by the HSP AES engine.
 */
enum {
	HSP_AES_INVALID_ARGUMENT = HSP_AES_ERROR (0x00),			/**< Input parameter is null or not valid. */
	HSP_AES_NO_MEMORY = HSP_AES_ERROR (0x01),					/**< Memory allocation failed. */
	HSP_AES_ENCRYPT_FAILED = HSP_AES_ERROR (0x02),				/**< Failed to encrypt data. */
	HSP_AES_DECRYPT_FAILED = HSP_AES_ERROR (0x03),				/**< Failed to decrypt data. */
	HSP_AES_INVALID_ADDRESS = HSP_AES_ERROR (0x04),				/**< A buffer is not in HSP shared SRAM. */
	HSP_AES_CMD_NOT_STARTED = HSP_AES_ERROR (0x05),				/**< The HS-SHA did not accept a submitted command. */
	HSP_AES_ADDRESS_NOT_ALIGNED = HSP_AES_ERROR (0x06),			/**< A buffer address is not word aligned. */
	HSP_AES_UNSUPPORTED_AES_MODE = HSP_AES_ERROR (0x07),		/**< The AES mode is not supported. */
	HSP_AES_OUTPUT_BUFFER_TOO_SMALL = HSP_AES_ERROR (0x08),		/**< The output buffer is not large enough for the data. */
	HSP_AES_NOT_BLOCK_ALIGNED = HSP_AES_ERROR (0x09),			/**< Data input is not aligned to the AES block size. */
	HSP_AES_UNSUPPORTED_KEY_SLOT = HSP_AES_ERROR (0x0a),		/**< The requested key slot is not available. */
	HSP_AES_SELF_TEST_FAILED = HSP_AES_ERROR (0x0b),			/**< A self-test of the AES HW failed. */
	HSP_AES_INPUT_BUFFER_TOO_LARGE = HSP_AES_ERROR (0x0c),		/**< The input buffer is too large to be handled. */
	HSP_AES_UNSUPPORTED_XTS_DATA_LENGTH = HSP_AES_ERROR (0x0d),	/**< The data unit length is not supported for AES-XTS. */
	HSP_AES_INVALID_XTS_DATA_LENGTH = HSP_AES_ERROR (0x0e),		/**< The data unit length is not valid for AES-XTS. */
	HSP_AES_CMD_EXE_TIMEOUT = HSP_AES_ERROR (0x0f),				/**< AES command execution timeout. */

	/* Error codes >0x80 are reserved for reporting bits from the HW status register. */
};

/**
 * An error has occurred with the hardware block.  The error code represents the status register
 * output.
 */
#define	HSP_AES_HW_ERROR(reg)	HSP_AES_ERROR (0x80 | ((reg & 0x38) >> 3))


#endif	/* HSP_AES_H_ */
