// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_DMB_H_
#define HSP_DMB_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "platform_api.h"
#include "status/msft_module_id.h"


/* Configurable RoT parameters.  Defaults can be overridden in platform_config.h. */
#include "platform_config.h"
#ifndef HSP_DMB_SEGMENTS
/**
 * Total number of segments available to the DMB hardware.  This is not actually used by the DMB
 * driver, but is available for application use.
 */
#define	HSP_DMB_SEGMENTS				14
#endif

#ifndef HSP_DMB_BASE_MAPPING_ADDRESS
/**
 * The base address for HSP addresses that are mapped by the DMB.  This is not actually used by the
 * DMB driver, but is available for application use.
 */
#define	HSP_DMB_BASE_MAPPING_ADDRESS	0x90000000
#endif


struct Dmb_reg;	/* Defined in HSP register definition. */


/**
 * DMB access indicator bits.
 */
enum {
	HSP_DMB_ACCESS_READ = (0),					/**< Read access always allowed, provided for clarity */
	HSP_DMB_ACCESS_WRITE = (1U << 0),			/**< Allow write + read access to the mapped region. */
	HSP_DMB_ACCESS_NO_PRIVILEGED = (1U << 1),	/**< Disallow privileged access to the mapped region. */
	HSP_DMB_ACCESS_USER = (1U << 2),			/**< Allow user access to the mapped region. */
	HSP_DMB_ACCESS_CRYPTO = (1U << 3),			/**< Allow crypto hardware access to the mapped region. */
	HSP_DMB_ACCESS_AXUSER0 = (1U << 4),			/**< Set AxUser[0] = 1 */
	HSP_DMB_ACCESS_SECURE = (1U << 5),			/**< Set seg_reg secure bit 28 = 1 */
};

/**
 * Information regarding each segment
 */
struct hsp_dmb_segment {
	bool in_use;	/**< Flag indicating the segment is being used. */
};

/**
 * Variable context for the HSP DMB driver
 */
struct hsp_dmb_state {
	platform_mutex lock;	/**< Synchronization for DMB operations. */
};

/**
 * Driver for a single DMB hardware instance.
 */
struct hsp_dmb {
	/**
	 * Map an external SoC address into HSP address space.
	 *
	 * @param dmb The DMB that should be used to perform the mapping.
	 * @param soc_address The SoC address that should be mapped.
	 * @param length The amount of the SoC address space that should be mapped.
	 * @param access_flags Bitmask of HSP DMB access flags to specify the permissions required for
	 * the region.  If no bits are set, the region will be given privileged read-only access.
	 * Setting only the flag to disable privileged access without granting other access is an
	 * invalid configuration.
	 * @param hsp_address Output for the HSP address to use for accessing the SoC address.
	 *
	 * @return 0 if the SoC address was mapped successfully or an error code.
	 */
	int (*map_soc_address) (const struct hsp_dmb *dmb, uint64_t soc_address, size_t length,
		uint8_t access_flags, void **hsp_address);

	/**
	 * Remove an HSP mapping for an external SoC address.
	 *
	 * @param dmb The DMB that create the mapping.
	 * @param hsp_address The HSP address for the SoC address mapping to remove.
	 */
	void (*unmap_soc_address) (const struct hsp_dmb *dmb, void *hsp_address);

	struct hsp_dmb_state *state;		/**< Variable context for DMB management. */
	struct hsp_dmb_segment *segments;	/**< List of DMB segments available to use. */
	size_t segment_count;				/**< Total number of segments available. */
	uint32_t hsp_dmb_base;				/**< Base HSP address for DMB mapping. */
	struct Dmb_reg *regs;				/**< Register interface to the DMB. */
};


int hsp_dmb_init (struct hsp_dmb *dmb, struct hsp_dmb_state *state,
	struct hsp_dmb_segment *segments, size_t total_segments, uint32_t base_map_addr,
	struct Dmb_reg *regs);
int hsp_dmb_init_state (const struct hsp_dmb *dmb);
void hsp_dmb_release (const struct hsp_dmb *dmb);


#define	HSP_DMB_ERROR(code)		ROT_ERROR (MSFT_MODULE_HSP_DMB, code)

/**
 * Error codes that can be generated by the HSP DMB.
 */
enum {
	HSP_DMB_INVALID_ARGUMENT = HSP_DMB_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_DMB_NO_MEMORY = HSP_DMB_ERROR (0x01),			/**< Memory allocation failed. */
	HSP_DMB_MAP_FAILED = HSP_DMB_ERROR (0x02),			/**< Address mapping failed. */
	HSP_DMB_BAD_BASE_ADDR = HSP_DMB_ERROR (0x3),		/**< The base mapping address is invalid. */
	HSP_DMB_MAP_TOO_LARGE = HSP_DMB_ERROR (0x04),		/**< The region being mapped is larger than the HW supports. */
	HSP_DMB_SEGMENT_OVERFLOW = HSP_DMB_ERROR (0x05),	/**< A region small enough to be mapped crosses over a segment boundary. */
	HSP_DMB_NOT_AVAILABLE = HSP_DMB_ERROR (0x06),		/**< There is no DMB segment available for use. */
	HSP_DMB_INVALID_PERMISSIONS = HSP_DMB_ERROR (0x07),	/**< The access flags for a segment are not valid. */
};


#endif	/* HSP_DMB_H_ */
