// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef JTAG_MAILBOX_H_
#define JTAG_MAILBOX_H_

#include "status/msft_module_id.h"


/* Forward declare some dependent types. */
union jtag_handler_msg;		/* Defined as part JTAG handling. */
struct Creg_regs_misc_regs;	/* Defined in HSP register definition. */

/**
 * Interface to the hardware mailbox for JTAG messages.
 */
struct jtag_mailbox {
	/**
	 * Read the current data from the JTAG mailbox.
	 *
	 * @param mailbox The mailbox to read.
	 * @param msg Output for the mailbox contents.
	 */
	void (*read) (const struct jtag_mailbox *mailbox, union jtag_handler_msg *msg);

	/**
	 * Update the contents of the JTAG mailbox.
	 *
	 * @param mailbox The mailbox to update.
	 * @param msg Message contents to use
	 */
	void (*write) (const struct jtag_mailbox *mailbox, const union jtag_handler_msg *msg);

	struct Creg_regs_misc_regs *regs;	/**< Register interface for the JTAG mailbox. */
};


int jtag_mailbox_init (struct jtag_mailbox *mailbox, struct Creg_regs_misc_regs *regs);
void jtag_mailbox_release (const struct jtag_mailbox *mailbox);


#define	JTAG_MAILBOX_ERROR(code)		ROT_ERROR (MSFT_MODULE_JTAG_MAILBOX, code)

/**
 * Error codes that can be generated by a JTAG mailbox driver.
 */
enum {
	JTAG_MAILBOX_INVALID_ARGUMENT = JTAG_MAILBOX_ERROR (0x00),	/**< Input parameter is null or not valid. */
	JTAG_MAILBOX_NO_MEMORY = JTAG_MAILBOX_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* JTAG_MAILBOX_H_ */
