// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef CMD_INTERFACE_IPC_ADMIN_H_
#define CMD_INTERFACE_IPC_ADMIN_H_

#include <stdint.h>
#include <string.h>
#include "cmd_interface/cmd_interface.h"
#include "drivers/hsp_dmb.h"
#include "ipc/ipc_message_handler.h"
#include "pcisig/doe/doe_interface.h"


/**
 * Handles IPC messages sent from Admin core to HSP core
*/
struct cmd_interface_ipc_admin {
	struct cmd_interface base;						/**< Command Interface Object */
	const struct hsp_dmb *dmb;						/**< HSP DMB object used to map and unmap memory regions outside of HSP domain */
	const struct doe_interface *doe;				/**< DOE interface to handle DOE message from Admin core */
	const struct cmd_interface *tdisp_event_policy;	/**< Command interface to handle TDISP-related IPC messages. */
};


int cmd_interface_ipc_admin_init (struct cmd_interface_ipc_admin *cmd_interface_ipc_admin,
	const struct hsp_dmb *dmb, const struct doe_interface *doe,
	const struct cmd_interface *tdisp_event_policy);
void cmd_interface_ipc_admin_release (
	const struct cmd_interface_ipc_admin *cmd_interface_ipc_admin);


/**
 * CMD interface admin Error code.
 */
#define	CMD_INTERFACE_IPC_ADMIN_ERROR(\
	code) ROT_ERROR (MANTICORE_MODULE_CMD_INTERFACE_IPC_ADMIN, code)

/**
 * Error codes that can be generated by the CMD interface admin Module.
 */
enum {
	CMD_INTERFACE_IPC_ADMIN_INVALID_ARGUMENT = CMD_INTERFACE_IPC_ADMIN_ERROR (0x00),	/**< Input parameter is null or not valid. */
	CMD_INTERFACE_IPC_ADMIN_NO_MEMORY = CMD_INTERFACE_IPC_ADMIN_ERROR (0x01),			/**< Memory allocation failure. */
	CMD_INTERFACE_IPC_ADMIN_INVALID_IPC_OPCODE = CMD_INTERFACE_IPC_ADMIN_ERROR (0x02),	/**< Invalid IPC Message Opcode */
};


#endif	/* CMD_INTERFACE_IPC_ADMIN_H_ */
