// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef CMD_INTERFACE_IPC_HSM_H_
#define CMD_INTERFACE_IPC_HSM_H_

#include <stdint.h>
#include <string.h>
#include "attestation/attestation_responder.h"
#include "cmd_interface/cmd_interface.h"
#include "drivers/hsp_dmb.h"
#include "ipc/ipc_message_handler.h"
#include "keystore/ephemeral_key_manager.h"


/**
 * Handles IPC messages sent from HSM core to HSP core
 */
struct cmd_interface_ipc_hsm {
	struct cmd_interface base;							/**< Command Interface Object */
	const struct hsp_dmb *dmb;							/**< HSP DMB object used to map and unmap memory regions outside of HSP domain */
	const struct ephemeral_key_manager *key_manager;	/**< Ephemeral Key Manager instance */
	uint8_t *key;										/**< Temporary buffer for storing keys read from key manager. */
	size_t key_size;									/**< Length of the temporary key buffer. */
	struct attestation_responder *attestation;			/**< Attestation responder instance */
	const struct hash_engine *hash;						/**< Hash engine for cert management. */
};


int cmd_interface_ipc_hsm_init (struct cmd_interface_ipc_hsm *cmd_interface_hsm,
	const struct hsp_dmb *dmb, const struct ephemeral_key_manager *key_manager, uint8_t *key,
	size_t key_size, struct attestation_responder *attestation, const struct hash_engine *hash);
void cmd_interface_ipc_hsm_release (const struct cmd_interface_ipc_hsm *cmd_hsm);


/**
 * CMD interface HSM Error code.
 */
#define	CMD_INTERFACE_IPC_HSM_ERROR(code)	ROT_ERROR (MANTICORE_MODULE_CMD_INTERFACE_IPC_HSM, code)

/**
 * Error codes that can be generated by the CMD interface HSM Module.
 */
enum {
	CMD_INTERFACE_IPC_HSM_INVALID_ARGUMENT = CMD_INTERFACE_IPC_HSM_ERROR (0x00),				/**< Input parameter is null or not valid. */
	CMD_INTERFACE_IPC_HSM_NO_MEMORY = CMD_INTERFACE_IPC_HSM_ERROR (0x01),						/**< Memory allocation failure. */
	CMD_INTERFACE_IPC_HSM_PROCESS_REQUEST_FAILED = CMD_INTERFACE_IPC_HSM_ERROR (0x03),			/**< IPC HSM Process request Failed  */
	CMD_INTERFACE_IPC_HSM_INVALID_IPC_OPCODE = CMD_INTERFACE_IPC_HSM_ERROR (0x04),				/**< Invalid IPC Message Opcode */
	CMD_INTERFACE_IPC_HSM_INVALID_KEY_TYPE = CMD_INTERFACE_IPC_HSM_ERROR (0x05),				/**< Invalid RSA key type  */
	CMD_INTERFACE_IPC_HSM_FAILED_TO_CONVERT_RSA_CONTEXT = CMD_INTERFACE_IPC_HSM_ERROR (0x06),	/**< Failed to convert RSA context from stored der buffer */
	CMD_INTERFACE_IPC_HSM_KEY_NOT_RSA_TYPE = CMD_INTERFACE_IPC_HSM_ERROR (0x07),				/**< Failed to convert RSA context from stored der buffer */
	CMD_INTERFACE_IPC_HSM_GET_CERT_CHAIN_LEN_TOO_MANY = CMD_INTERFACE_IPC_HSM_ERROR (0x08),		/**< Number of cert chain lengths more than number of payload buffer entries */
	CMD_INTERFACE_IPC_HSM_GET_CERT_LEN_BUF_TOO_SMALL = CMD_INTERFACE_IPC_HSM_ERROR (0x09),		/**< Size of provided buffer is smaller than certificate length */
	CMD_INTERFACE_IPC_HSM_CERT_CHAIN_TOO_SMALL = CMD_INTERFACE_IPC_HSM_ERROR (0x0a),			/**< There are fewer than the minimum required certs available. */
};


#endif	/* CMD_INTERFACE_IPC_HSM_H_ */
