// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef IPC_MESSAGE_HANDLER_H_
#define IPC_MESSAGE_HANDLER_H_

#include <stdint.h>
#include <string.h>
#include "platform_api.h"
#include "cmd_interface/cmd_interface.h"
#include "ipc/ipc_channel.h"
#include "system/periodic_task.h"


/**
 * Maximum IPC Message Queue length in bytes.
 */
#define IPC_MESSAGE_BUFFER_SIZE		(sizeof(struct ipc_message))
/**
 * Maximum IPC Message header size in bytes.
 */
#define IPC_MESSAGE_HEADER_SIZE		(sizeof(struct ipc_message_header))
/**
 * Maximum IPC Message payload size in bytes.
 */
#define IPC_MESSAGE_PAYLOAD_SIZE	(IPC_MESSAGE_BUFFER_SIZE - IPC_MESSAGE_HEADER_SIZE)


/**
 * Handles the IPC receive requests and send response
*/
struct ipc_message_handler {
	struct periodic_task_handler base;	/**< Periodic Task Handler Object implemented for IPC Message handler */
	const struct cmd_interface *cmd;	/**< Command Interface to handle the messages receive over IPC Channel */
	const struct ipc_channel *channel;	/**< IPC channel to send and receive message */
};


int ipc_message_handler_init (struct ipc_message_handler *message_handler,
	const struct cmd_interface *ipc_cmd_interface, const struct ipc_channel *ipc_channel);
int ipc_message_handler_release (const struct ipc_message_handler *message_handler);


/**
 * IPC Message Handler Error code.
 */
#define	IPC_MESSAGE_HANDLER_ERROR(code)		ROT_ERROR (MANTICORE_MODULE_IPC_MESSAGE_HANDLER, code)

/**
 * Error codes that can be generated by the IPC Message Handler Module.
 */
enum {
	IPC_MESSAGE_HANDLER_INVALID_ARGUMENT = IPC_MESSAGE_HANDLER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	IPC_MESSAGE_HANDLER_NO_MEMORY = IPC_MESSAGE_HANDLER_ERROR (0x01),			/**< Memory allocation failure. */
};


#endif	/* IPC_MESSAGE_HANDLER_H_ */
