// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef DEVICE_KEYS_H_
#define DEVICE_KEYS_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "crypto/hash.h"
#include "drivers/ccs_ksu_interface.h"
#include "drivers/hsp_security_state.h"
#include "firmware/hw_rot.h"
#include "firmware/identity_renewal.h"
#include "splibs/inc/spcryptotypes.h"
#include "status/msft_module_id.h"


/**
 * Size of the SOC ID array in words
 */
#define DEVICE_KEYS_SOCID_WORDS 4

/**
 * Key Storage Unit slot numbers for device keys.
 */
enum device_keys {
	DEVICE_KEYS_DICE_SEED = 0,								/**< Device-unique seed for DICE identity. */
	DEVICE_KEYS_DICE_UDS = 0,								/**< UDS for DICE CDI and key derivations. */
	DEVICE_KEYS_DICE_CDI = 0,								/**< DICE CDI based on current firmware and security state. */
	DEVICE_KEYS_DME_SEED = 1,								/**< Device-unique seed for the DME key. */
	DEVICE_KEYS_DME_UDS = 1,								/**< UDS for deriving the DME key. */
	DEVICE_KEYS_DEVICE_ID_KEY = 1,							/**< DICE Device ID key pair. */
	DEVICE_KEYS_DEVICE_SEED = 2,							/**< Device-unique seed for application keys. */
	DEVICE_KEYS_FW_IMAGE_AES_KEY = 2,						/**< Device-unique key for encrypting firmware images. */
	DEVICE_KEYS_GLOBAL_SEED = 3,							/**< Global seed shared by all devices of the same type. */
	DEVICE_KEYS_GLOBAL_UNWRAP_KEY = 3,						/**< Unwrapping key used to provision the global seed. */
	DEVICE_KEYS_GLOBAL_KEY = 3,								/**< Base global key used to derive additional keys. */
	DEVICE_KEYS_OWNER_GLOBAL_KEY = 3,						/**< Global key for a specific device owner. */
	DEVICE_KEYS_HASH_STICK_KEY = 4,							/**< Device-unique hash stick key, which depends on device state. */
	DEVICE_KEYS_DEVICE_KEY = 5,								/**< Device-unique key that is independent of device state. */
	DEVICE_KEYS_TENANCY_KEY = 6,							/**< Device-unique key for tenancy transfers. */
	DEVICE_KEYS_DME_KEY = 7,								/**< The DME private ECC key. */
	DEVICE_KEYS_DME_SIGNING_KEY = 8,						/**< Global signing key used to endorse DME public keys. */
	DEVICE_KEYS_ROM_KSU_SLOTS,								/**< The number of KSU key slots used for keys generated by ROM. */
	DEVICE_KEYS_FUSE_SYNC_KEY = DEVICE_KEYS_ROM_KSU_SLOTS,	/**< Fuse sync signing and verifying key used by dies. */
	DEVICE_KEYS_ROM_KSU_SLOTS_EXTENDED,						/**< The number of KSU key slots used for keys generated by ROM. */
};


#pragma pack(push, 1)
/**
 * Container for the DME public key of the device.  This key will be signed by the global DME
 * signing key.
 */
struct device_keys_dme_public_key {
	uint32_t socid[DEVICE_KEYS_SOCID_WORDS];	/**< SOC ID */
	uint32_t renew_counter;						/**< Current value of the DME renewal counter. */
	SP_ECDSA_P384_PUBLIC key;					/**< DME ECC-384 public key. */

	/**
	 * Signature for the DME public key.  This is not a signature over this structure.  Rather, it
	 * is a CCS certification for the DME ECC key.
	 */
	SP_ECDSA_P384_SIGNATURE signature;
};

/**
 * DME endorsement structure for the DICE Device ID public key.
 */
struct device_keys_dice_endorsement {
	struct {
		SP_MSG_384 device_id_hash;		/**< Hash of the DICE device ID public key. */
		SP_MSG_384 measurement;			/**< Measurement of the device execution state. */
	} signed_data;						/**< DME structure signed with the DME key. */
	SP_ECDSA_P384_SIGNATURE signature;	/**< Signature of the structure using the DME key. */
};

#pragma pack(pop)


int device_keys_initialize_rom_keys (enum hsp_security_state state,
	const struct ccs_ksu_interface *ccs, int ksu_slots);

int device_keys_initialize_rom_keys_extended (enum hsp_security_state state,
	const struct ccs_ksu_interface *ccs);

int device_keys_derive_keys (enum hsp_security_state state, const struct ccs_ksu_interface *ccs,
	const struct ecc_hw *ecc, const struct hash_engine *hash,
	const struct identity_renewal *identity, const uint32_t *socid, size_t socid_words,
	uint8_t dme_pcr, struct device_keys_dme_public_key *dme, SP_ECDSA_P384_PUBLIC *dme_signer);

int device_keys_dice (enum hsp_security_state state, const struct ccs_ksu_interface *ccs,
	const struct ecc_hw *ecc, const struct hw_rot *rot, const struct hash_engine *hash,
	uint8_t dice_pcr, const SP_MSG_384 *const *measurements, size_t measurement_count,
	SP_ECDSA_P384_PUBLIC *device_id, struct device_keys_dice_endorsement *dme);


#define	DEVICE_KEYS_ERROR(code)		ROT_ERROR (MSFT_MODULE_DEVICE_KEYS, code)

/**
 * Error codes that can be generated during device key derivation and management.
 */
enum {
	DEVICE_KEYS_INVALID_ARGUMENT = DEVICE_KEYS_ERROR (0x00),	/**< Input parameter is null or not valid. */
	DEVICE_KEYS_NO_MEMORY = DEVICE_KEYS_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* DEVICE_KEYS_H_ */
