// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_FUSE_SYNC_DATA_H_
#define HSP_FUSE_SYNC_DATA_H_

#include <stdint.h>
#include <string.h>
#include "common/buffer_util.h"
#include "drivers/ccs_ksu_interface.h"
#include "drivers/fuse_controller_interface.h"
#include "drivers/hsp_security_state.h"
#include "splibs/inc/spcryptotypes.h"


int hsp_fuse_sync_data_prepare (enum hsp_security_state state, const struct ccs_ksu_interface *ccs,
	uint8_t key_slot, const struct fuse_controller_interface *fuses, uint8_t *ccs_buffer,
	size_t ccs_buffer_length, uint8_t *tenancy_counter, size_t tenancy_counter_length);

int hsp_fuse_sync_data_update (enum hsp_security_state state, const struct ccs_ksu_interface *ccs,
	uint8_t key_slot, const struct fuse_controller_interface *fuses, uint8_t *ccs_buffer,
	size_t ccs_buffer_length, uint8_t *tenancy_counter, size_t tenancy_counter_length);

#define	FUSE_SYNC_DATA_ERROR(code)		ROT_ERROR (MSFT_MODULE_FUSE_SYNC_DATA, code)

/**
 * Error codes that can be generated by a fuse controller.
 */
enum {
	FUSE_SYNC_DATA_INVALID_ARGUMENT = FUSE_SYNC_DATA_ERROR (0x00),				/**< Input parameter is null or not valid. */
	FUSE_SYNC_DATA_NO_MEMORY = FUSE_SYNC_DATA_ERROR (0x01),						/**< Memory allocation failed. */
	FUSE_SYNC_DATA_BUFFER_SMALL = FUSE_SYNC_DATA_ERROR (0x02),					/**< CCS buffer has not enough memory to store fuse data. */
	FUSE_SYNC_DATA_FUSE_MAP_NULL = FUSE_SYNC_DATA_ERROR (0x03),					/**< Fuse Map not allocated. */
	FUSE_SYNC_DATA_UNSUPPORTED_SECURITY_STATE = FUSE_SYNC_DATA_ERROR (0x04),	/**< fuse sync called in unsupported security state. */
};


#endif	/* HSP_FUSE_SYNC_DATA_H_ */
