// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_H_
#define HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "hsp_crashdump_hw_err_handler.h"
#include "hsp_top.h"
#include "status/msft_module_id.h"


/**
 * Number of memory error registers.
 */
#define HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_NUM_ERR_REGS	7

/**
 * Memory error handler structure.
 */
struct hsp_crashdump_hw_err_handler_mem_err {
	struct hsp_crashdump_hw_err_handler base;	/**< Base handler for a HSP HW error processing. */
	size_t mem_regs;							/**< CREG offset for the hardware memory registers. */
};


void hsp_crashdump_hw_err_handler_mem_err_save_opaque_data (uint32_t *buffer, size_t length);
int hsp_crashdump_hw_err_handler_mem_err_init (
	struct hsp_crashdump_hw_err_handler_mem_err *handler,
	const struct hsp_crashdump_handler *crashdump_handler, const struct mmio_register_block *creg,
	size_t mem_regs);
void hsp_crashdump_hw_err_handler_mem_err_release (
	const struct hsp_crashdump_hw_err_handler_mem_err *handler);


#define	HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_ERROR(code)      \
	ROT_ERROR (MSFT_MODULE_HSP_HANDLER_MEM_ERR, code)

/**
 * Error codes that can be generated by the memory error handler.
 *
 * Note: Commented error codes have been deprecated.
 */
enum {
	HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_INVALID_ARGUMENT =
		HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_NO_MEMORY =
		HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_ERROR (0x01),	/**< Memory allocation failed. */
	HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_INT_STATUS_0 =
		HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_ERROR (0x02),	/**< Interrupt status register value was 0. */
};


#endif	/* HSP_CRASHDUMP_HW_ERR_HANDLER_MEM_ERR_H_ */
