// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_CRASHDUMP_HANDLER_H_
#define HSP_CRASHDUMP_HANDLER_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "status/msft_module_id.h"
#include "trap/hsp_interrupt_handler.h"
#include "trap/hsp_trap_context.h"


/* Reset callback function. Once it is invoked, it would get device into warm reset. */
typedef void (*hsp_crashdump_handler_reset_callback) (void);

/**
 * Crashdump implementation to provide crashdump functions.
 */
struct hsp_crashdump_handler {
	struct hsp_interrupt_handler base;			/**< Base interface for handling HW interrupts. */
	const uint8_t *fw_version;					/**< The build version number for the firmware package. */
	size_t fw_version_len;						/**< The length of build version number for the firmware package. */
	hsp_crashdump_handler_reset_callback reset;	/**< Reset callback. Once it is invoked, it would get device into warm reset. */
	uint32_t *persistent_ram;					/**< Persistent RAM, such as sticky registers, used to store crashdump. */
	size_t persistent_ram_size;					/**< Size of persistent RAM used to store crashdump. */
};


int hsp_crashdump_handler_init (struct hsp_crashdump_handler *handler, const uint8_t *fw_version,
	size_t fw_version_len, hsp_crashdump_handler_reset_callback reset, uint32_t *persistent_ram,
	size_t persistent_ram_size);
void hsp_crashdump_handler_release (const struct hsp_crashdump_handler *handler);

void hsp_crashdump_handler_collect_hsp_crashdump (const struct hsp_crashdump_handler *handler,
	struct hsp_trap_context *context, uint16_t fault_code, uint8_t crash_type);


#define	HSP_CRASHDUMP_HANDLER_ERROR(code)      \
	ROT_ERROR (MSFT_MODULE_HSP_CRASHDUMP_HANDLER, code)

/**
 * Error codes that can be generated by the Crashdump interface.
 *
 * Note: Commented error codes have been deprecated.
 */
enum {
	HSP_CRASHDUMP_HANDLER_INVALID_ARGUMENT = HSP_CRASHDUMP_HANDLER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_CRASHDUMP_HANDLER_NO_MEMORY = HSP_CRASHDUMP_HANDLER_ERROR (0x01),			/**< Memory allocation failed. */
};


#endif	/* HSP_CRASHDUMP_HANDLER_H_ */
