// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_CRASHDUMP_HW_ERR_HANDLER_H_
#define HSP_CRASHDUMP_HW_ERR_HANDLER_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "hsp_crashdump_handler.h"
#include "mmio/mmio_register_block.h"
#include "trap/hsp_interrupt_handler.h"


/**
 * Generic structure for HW error handling.
 */
struct hsp_crashdump_hw_err_handler {
	struct hsp_interrupt_handler base;						/**< HSP interrupt handler. */
	const struct hsp_crashdump_handler *crashdump_handler;	/**< Interface to make crashdump collection. */
	const struct mmio_register_block *creg;					/**< The CREG register interface (struct Creg_regs). */
};

/**
 * Generic opaque data to report HW error.
 */
struct hsp_crashdump_hw_err_handler_crashdump_opaque_data {
	uint16_t int_status;	/**< interrupt status register value. It's packed into two bytes. */
	uint16_t err_tag;		/**< Error tag or index. */
	uint32_t status0;		/**< First error status that contains where or what error occurred. */
	uint32_t status1;		/**< Second error status that contains where or what error occurred. */
};


int hsp_crashdump_hw_err_handler_init (
	struct hsp_crashdump_hw_err_handler *handler,
	const struct hsp_crashdump_handler *crashdump_handler, const struct mmio_register_block *creg,
	hsp_interrupt_handler_func hsp_hw_err_handler);
void hsp_crashdump_hw_err_handler_release (
	const struct hsp_crashdump_hw_err_handler *handler);
bool hsp_crashdump_hw_err_handler_collect_hsp_crashdump (
	const struct hsp_crashdump_handler *handler, uintptr_t param, uint16_t fault_code,
	struct hsp_crashdump_hw_err_handler_crashdump_opaque_data *hw_err_data);


#define	HSP_CRASHDUMP_HW_ERR_HANDLER_ERROR(code)      \
	ROT_ERROR (MSFT_MODULE_HSP_HANDLER, code)

/**
 * Error codes that can be generated by the HW error handler.
 *
 * Note: Commented error codes have been deprecated.
 */
enum {
	HSP_CRASHDUMP_HW_ERR_HANDLER_ERR_INVALID_ARGUMENT =
		HSP_CRASHDUMP_HW_ERR_HANDLER_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_CRASHDUMP_HW_ERR_HANDLER_ERR_NO_MEMORY =
		HSP_CRASHDUMP_HW_ERR_HANDLER_ERROR (0x01),	/**< Memory allocation failed. */
};


#endif	/* HSP_CRASHDUMP_HW_ERR_HANDLER_H_ */
