// Copyright (c) Microsoft Corporation. All rights reserved.

#ifndef HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_H_
#define HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "hsp_crashdump_hw_err_handler.h"
#include "hsp_top.h"
#include "fips/error_state_entry_interface.h"
#include "status/msft_module_id.h"


/**
 * RNG error interrupt mask bits.
 */
#define HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_INT_MASKS \
	(CREG_REGS_CREG_CRYPTO_GROUP_CRYPTO_ERR_EN_RNG_ERR_FIELD_MASK)

/**
 * RNG error handler structure.
 */
struct hsp_crashdump_hw_err_handler_rng_err {
	struct hsp_crashdump_hw_err_handler base;			/**< Base handler for a HSP HW error processing. */
	size_t crypto_regs;									/**< CREG offset for the hardware crypto registers. */
	const struct mmio_register_block *rng_regs;			/**< RNG registers referred for error logging. */
	const struct error_state_entry_interface *error;	/**< Error state management interface */
};


void hsp_crashdump_hw_err_handler_rng_err_save_opaque_data (uint32_t *buffer, size_t length);
int hsp_crashdump_hw_err_handler_rng_err_init (
	struct hsp_crashdump_hw_err_handler_rng_err *handler,
	const struct hsp_crashdump_handler *crashdump_handler, const struct mmio_register_block *creg,
	size_t crypto_regs, const struct mmio_register_block *rng_regs,
	const struct error_state_entry_interface *error);
void hsp_crashdump_hw_err_handler_rng_err_release (
	const struct hsp_crashdump_hw_err_handler_rng_err *handler);


#define	HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_ERROR(code)      \
	ROT_ERROR (MSFT_MODULE_HSP_HANDLER_RNG_ERR, code)

/**
 * Error codes that can be generated by the RNG error handler.
 *
 * Note: Commented error codes have been deprecated.
 */
enum {
	HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_INVALID_ARGUMENT =
		HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_ERROR (0x00),	/**< Input parameter is null or not valid. */
	HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_NO_MEMORY =
		HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_ERROR (0x01),	/**< Memory allocation failed. */
	HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_INT_STATUS_0 =
		HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_ERROR (0x02),	/**< Interrupt status register value was 0. */
};


#endif	/* HSP_CRASHDUMP_HW_ERR_HANDLER_RNG_ERR_H_ */
